import type { LevelId, QuestDef } from './types';

// Main story quests. Each chapter is a chain: every quest unlocks the next, and the last is the guardian fight
// followed by restoring the chapter's light. The person you report to usually hands out the next step.
const m = (def: Omit<QuestDef, 'main'>): QuestDef => ({ ...def, main: true });

const meadow: QuestDef[] = [
  m({ id: 'm1', title: 'A Dark Beacon', giver: 'guide', kind: 'talk', count: 1, to: 'rowan', summary: 'Speak with Elder Rowan in Sunpetal Village.', reward: { xp: 60 },
    text: { offer: ['Mira! Thank the stars you came.', 'The Meadow Beacon went dark the night the star fell. Without it the gloom creeps closer every evening.', 'Elder Rowan in Sunpetal Village knows the old ways. Go to him — follow the road south-east.'], progress: ['Elder Rowan lives in Sunpetal Village, down the road.'], complete: [], after: ['Rowan will know what to do.'], deliver: ['Tamsin sent you? Then it is as bad as I feared.', 'The Beacon can only be woken by three sun-crystals. Long ago they were hidden across the valley.'] } }),
  m({ id: 'm2', title: 'The First Sun-crystal', giver: 'rowan', kind: 'key', count: 1, keys: [0], requires: 'm1', summary: 'Find the sun-crystal in the Old Stone Garden.', reward: { xp: 110 },
    text: { offer: ['The first crystal rests in the Old Stone Garden, north-east of here.', 'It will only shine for someone the Beacon trusts. Let us see if that is you.'], progress: ['The Old Stone Garden lies north-east. Look for a golden light between the stones.'], complete: ['It glows in your hands! The Beacon trusts you.', 'The second crystal was carried into Gloom Hollow. Farmer Bram at Millbrook has seen strange lights there.'], after: ['Two more crystals, Mira.'] } }),
  m({ id: 'm3', title: 'Into Gloom Hollow', giver: 'rowan', kind: 'key', count: 1, keys: [1], requires: 'm2', turnIn: 'bram', summary: 'Take the sun-crystal from Gloom Hollow, then tell Farmer Bram.', reward: { xp: 150 },
    text: { offer: ['Gloom Hollow is south, beyond Millbrook Farm. Gloomlings nest there thickly.', 'Bring the crystal out, then visit Farmer Bram — he will want to know the hollow is quieter.'], progress: ['Gloom Hollow lies south of Millbrook Farm. Be careful.'], complete: ['You went into the Hollow? And came out with a crystal!', 'My old dog howls at Shepherd’s Hill every night. I bet the last crystal is up there.'], after: ['The fields feel safer already.'] } }),
  m({ id: 'm4', title: 'Light on Shepherd’s Hill', giver: 'bram', kind: 'key', count: 1, keys: [2], requires: 'm3', turnIn: 'odo', summary: 'Find the last sun-crystal on Shepherd’s Hill and speak with Old Shepherd Odo.', reward: { xp: 180 },
    text: { offer: ['Shepherd’s Hill is far to the north-east. Old Odo lives up there with his sheep.', 'Find that last crystal, and say hello to Odo for me.'], progress: ['Shepherd’s Hill, north-east. Follow the road past Willowmere.'], complete: ['All three crystals… I never thought I’d see them together.', 'Listen. Something rumbles beneath the Beacon Rise. The guardian is waking.'], after: ['Baa. I mean — good luck.'] } }),
  m({ id: 'm5', title: 'The Guardian of the Rise', giver: 'odo', kind: 'boss', count: 1, requires: 'm4', summary: 'Defeat Mossback at the Beacon Rise and relight the Meadow Beacon.', reward: { xp: 300 },
    text: { offer: ['Mossback has slept beneath the Rise for a hundred years. The crystals have woken it.', 'It is not wicked, only old and angry. Defeat it, then lay the crystals in the Beacon.', 'Watch the ground: when it glows, move. And dodge the boulders it throws.'], progress: ['The Beacon Rise lies far to the south-east.'], complete: [], after: ['The Beacon shines!'] } }),
];

const woods: QuestDef[] = [
  m({ id: 'm1', title: 'Whispers of the Bell', giver: 'guide', kind: 'talk', count: 1, to: 'bellkeeper', summary: 'Speak with the Old Bellkeeper in Bellhollow.', reward: { xp: 90 },
    text: { offer: ['Welcome to Whisperroot, Mira. The woods are sick.', 'The Ancient Root Bell has not rung since the star fell, and without it the shadows never leave.', 'The Old Bellkeeper in Bellhollow cared for it all his life. Start with him.'], progress: ['Bellhollow is north-east of this camp.'], complete: [], after: ['Listen to the Bellkeeper.'], deliver: ['Mosskeeper Oda sent you? Good. My old bones can’t climb to the bell any more.', 'But the paths are thick with gloom. We must clear them first.'] } }),
  m({ id: 'm2', title: 'Clear the Hollow Paths', giver: 'bellkeeper', kind: 'slay', count: 6, enemy: 'gloomling', requires: 'm1', summary: 'Defeat gloomlings around the woods.', reward: { xp: 160 },
    text: { offer: ['Gloomlings have crept into every path around Bellhollow.', 'Chase away six of them so the villagers can travel again.'], progress: ['Gloomlings are everywhere in these woods. Six will do.'], complete: ['The paths are open! Now for the runes.', 'Three root runes wake the Bell’s guardian. The first lies in the Root Ruins in the north.'], after: ['The village breathes easier.'] } }),
  m({ id: 'm3', title: 'The Rune in the Ruins', giver: 'bellkeeper', kind: 'key', count: 1, keys: [0], requires: 'm2', turnIn: 'hale', summary: 'Wake the root rune in the Root Ruins, then find Woodcutter Hale at Glowcap Farm.', reward: { xp: 180 },
    text: { offer: ['The Root Ruins lie far to the north. Touch the rune and it will wake.', 'Woodcutter Hale works near Glowcap Farm on the way back. He knows the roads east.'], progress: ['The Root Ruins are north. Hale is at Glowcap Farm.'], complete: ['A root rune! It hums like a beehive.', 'The glade to the east is where the moon drinks. The runes remember it — go and see.'], after: ['Timber and runes, what a week.'] } }),
  m({ id: 'm4', title: 'Where the Moon Drinks', giver: 'hale', kind: 'visit', count: 1, place: 'glade', requires: 'm3', turnIn: 'fenn', summary: 'Visit the Moonlit Glade, then report to Lamplighter Fenn in Lanternmarket.', reward: { xp: 180 },
    text: { offer: ['Walk to the Moonlit Glade in the middle of the woods. The rune will show you something.', 'Then take the news to Lamplighter Fenn in Lanternmarket.'], progress: ['The Moonlit Glade, then Lanternmarket.'], complete: ['The glade showed you the Thornling Nest? Then that is where the second rune hides.', 'Scout Ivo watches it from the Owl Watchtower. Bring him word when you have it.'], after: ['A lantern for every path.'] } }),
  m({ id: 'm5', title: 'Thorns Around the Rune', giver: 'fenn', kind: 'key', count: 1, keys: [1], requires: 'm4', turnIn: 'ivo', summary: 'Wake the rune in the Thornling Nest, then report to Scout Ivo at the Owl Watchtower.', reward: { xp: 200 },
    text: { offer: ['The Thornling Nest is north of here. Thornlings spit — dash through their gaps.', 'Scout Ivo at the Owl Watchtower will want to hear you made it out.'], progress: ['The Thornling Nest is north. The watchtower is east.'], complete: ['Two runes! The owls are hooting like mad.', 'The third is right here, under the tower. Can you hear it?'], after: ['All clear, for now.'] } }),
  m({ id: 'm6', title: 'The Owl’s Rune', giver: 'ivo', kind: 'key', count: 1, keys: [2], requires: 'm5', summary: 'Wake the root rune at the Owl Watchtower.', reward: { xp: 160 },
    text: { offer: ['The last rune sleeps somewhere around the watchtower.', 'Wake it and come back to me.'], progress: ['Look around the tower. It glows green.'], complete: ['All three runes are singing!', 'And listen… the Bramble Warden is stirring by the bell.'], after: ['The owls are proud.'] } }),
  m({ id: 'm7', title: 'The Bramble Warden', giver: 'ivo', kind: 'boss', count: 1, requires: 'm6', summary: 'Defeat the Bramble Warden and ring the Ancient Root Bell.', reward: { xp: 420 },
    text: { offer: ['The Warden wears the thorns so the bell does not. It guards, and it grieves.', 'It throws rings of thorns and sends roots racing through the soil. Keep moving.', 'Defeat it, then ring the bell in the far north-east.'], progress: ['The Old Bell stands in the far north-east.'], complete: [], after: ['The bell rings!'] } }),
];

const summit: QuestDef[] = [
  m({ id: 'm1', title: 'Up the Silver Heights', giver: 'guide', kind: 'talk', count: 1, to: 'aune', summary: 'Speak with Healer Aune in Frostpine Hamlet.', reward: { xp: 120 },
    text: { offer: ['You climbed all the way up. Good. You will need that strength.', 'The fallen star has gone hollow, and now it hunts the sky.', 'First, get warm. Healer Aune in Frostpine Hamlet helps every traveller who makes it this far.'], progress: ['Frostpine Hamlet is north-east of the lookout.'], complete: [], after: ['Aune will keep you warm.'], deliver: ['Another climber! Come in, come in — your fingers are blue.', 'Nobody reaches the Cradle frozen. Let me help you first.'] } }),
  m({ id: 'm2', title: 'Against the Cold', giver: 'aune', kind: 'collect', count: 4, near: 'hamlet', item: 'Emberroot', icon: 'herb', requires: 'm1', summary: 'Gather emberroot around Frostpine Hamlet.', reward: { xp: 200 },
    text: { offer: ['Emberroot grows under the snow around the hamlet. It keeps a body warm for days.', 'Bring me four and I will brew you a tonic.'], progress: ['Four emberroots, around the hamlet.'], complete: ['There! Drink up — you will not freeze now.', 'Astronomer Vale at the Old Observatory has been watching the star. He needs to see you.'], after: ['Warm hands, warm heart.'] } }),
  m({ id: 'm3', title: 'The Astronomer', giver: 'aune', kind: 'talk', count: 1, to: 'vale', requires: 'm2', summary: 'Visit Astronomer Vale at the Old Observatory.', reward: { xp: 180 },
    text: { offer: ['The Old Observatory is to the south-east.', 'Vale is odd, but he knows the sky better than anyone.'], progress: ['The observatory is south-east of the hamlet.'], complete: [], after: ['Vale knows the stars.'], deliver: ['Ah! The girl with the fox. The stars mentioned you.', 'The Hollow Star can be cracked — but first I must read where its light fell.'] } }),
  m({ id: 'm4', title: 'Read the Sky', giver: 'vale', kind: 'visit', count: 1, place: 'tarn', requires: 'm3', summary: 'Look into Mirrorsky Tarn and report back to Vale.', reward: { xp: 220 },
    text: { offer: ['Mirrorsky Tarn reflects the sky perfectly. Walk to it and look into the water.', 'Then tell me what you saw.'], progress: ['Mirrorsky Tarn lies north of here.'], complete: ['Three lights under the water? Three star shards!', 'One is in Crystal Hollow, one in the Void Rift, one at the Broken Spire.'], after: ['The sky is a map.'] } }),
  m({ id: 'm5', title: 'The Crystal Shard', giver: 'vale', kind: 'key', count: 1, keys: [0], requires: 'm4', turnIn: 'aune', summary: 'Take the star shard from Crystal Hollow, then return to Healer Aune.', reward: { xp: 240 },
    text: { offer: ['Crystal Hollow is far to the north-west. The shard hums the note of the star.', 'Aune’s hamlet is on the way back. Warm up there.'], progress: ['Crystal Hollow is north-west. Then Frostpine Hamlet.'], complete: ['A star shard! It is warm, like a little sun.', 'But the wisps are thicker on the road east. Please be careful.'], after: ['Rest a moment.'] } }),
  m({ id: 'm6', title: 'Wisps on the Road', giver: 'aune', kind: 'slay', count: 6, enemy: 'wisp', requires: 'm5', turnIn: 'brun', summary: 'Defeat void wisps, then find Goatherd Brun at the terrace.', reward: { xp: 260 },
    text: { offer: ['Void wisps follow anyone carrying a shard. Thin them out.', 'Goatherd Brun on the terrace to the east knows the way to the Void Rift.'], progress: ['Six void wisps. Then Goatherd’s Terrace.'], complete: ['You scared off the wisps! My goats are grateful.', 'The Void Rift is south-east of here. Nothing grazes near it.'], after: ['Maaa!'] } }),
  m({ id: 'm7', title: 'The Void Rift', giver: 'brun', kind: 'key', count: 1, keys: [1], requires: 'm6', turnIn: 'sella', summary: 'Take the shard from the Void Rift, then bring it to Monk Sella in Skyhold.', reward: { xp: 280 },
    text: { offer: ['The Rift pulls at your feet. Grab the shard and get out.', 'The monks of Skyhold, east of the Rift, can protect a shard from the dark.'], progress: ['The Void Rift, then Skyhold to the east.'], complete: ['You carried a shard out of the Rift? The star must truly want to come home.', 'Before the last shard, you must be blessed at the Star Altar.'], after: ['Peace be with you.'] } }),
  m({ id: 'm8', title: 'The Star Altar', giver: 'sella', kind: 'visit', count: 1, place: 'altar', requires: 'm7', turnIn: 'dov', summary: 'Visit the Star Altar, then report to Quartermaster Dov at Silver Pass.', reward: { xp: 280 },
    text: { offer: ['The Star Altar is west of Skyhold. Stand before it and let it see you.', 'Then go north to Silver Pass. Quartermaster Dov guards the road to the Spire.'], progress: ['The Star Altar, then Silver Pass Camp.'], complete: ['Sella sent you through the Altar? Then you’re more than a traveller.', 'The last shard is at the Broken Spire. My guards can’t get near it.'], after: ['The pass holds.'] } }),
  m({ id: 'm9', title: 'The Broken Spire', giver: 'dov', kind: 'key', count: 1, keys: [2], requires: 'm8', summary: 'Take the last star shard from the Broken Spire.', reward: { xp: 300 },
    text: { offer: ['The Broken Spire is north-east. It fell with the star and still points to it.', 'Bring the shard back here.'], progress: ['The Broken Spire, north-east of the pass.'], complete: ['All three shards. I can feel them from here.', 'The Hollow Star has noticed. It waits at the Cradle.'], after: ['Go, Mira.'] } }),
  m({ id: 'm10', title: 'The Hollow Star', giver: 'dov', kind: 'boss', count: 1, requires: 'm9', summary: 'Defeat the Hollow Star and return the shards to the Star Cradle.', reward: { xp: 600 },
    text: { offer: ['The Star Cradle is at the top of the world, in the far north-east.', 'The Hollow Star spirals void-light, rains meteors and blinks right next to you. Stay brave.', 'Break it, and lay the shards in the Cradle. Bring the star home.'], progress: ['The Star Cradle, far north-east.'], complete: [], after: ['The sky is whole again.'] } }),
];

export const STORY: Record<LevelId, QuestDef[]> = { meadow, woods, summit };
