import type { Captive, NpcLook, QuestDef, RegionId } from './types';

// The main story: one tale told across the valley's four regions.
//
// The night the star fell, Master Orrin vanished. Mira, his apprentice, follows his trail with her fox Tuft and learns
// that the Beacon, the Bell and the Star were lit long ago to seal away Umbra, the Eclipse. Orrin's lost pupil Sable,
// who has carried a painful shadow since birth, is putting the lights out one by one because Umbra promised her relief.
// The truth comes out on the Summit: Orrin pulled the star down trying to "cure" Sable, and Umbra crept inside it.
// Mira frees Orrin, wins Sable back with the flowers she loved as a child and cracks the Hollow Star, but Umbra slips out
// of the broken shell and flees east into the Ember Wastes. There the Cinder Tyrant guards the cold Dawn Forge, and once
// he falls Umbra rises out of every land at once for the last battle.
//
// Each chapter is a chain: every quest unlocks the next. Quest ids are local to their region (the world builder adds
// the region prefix); a `requires` with a colon points into another region. Quests from `fox` are Tuft nudging Mira
// along: they start on their own.
export type StoryQuest = Omit<QuestDef, 'region' | 'main'>;
const m = (def: StoryQuest): StoryQuest => def;
const person = (name: string, portrait: string, look: Partial<NpcLook>): Captive => ({ name, portrait, look: { skin: '#f0c8a2', robe: '#8a6fb0', hat: 'none', hatColor: '#5b5480', hair: '#6b3f2a', ...look } });

// ═════════════════════════════ Chapter I · The Broken Beacon (10)
const meadow: StoryQuest[] = [
  m({ id: 'm1', title: 'Where the Star Fell', giver: 'guide', kind: 'talk', count: 1, to: 'rowan', summary: 'Find Elder Rowan in Sunpetal Village.', reward: { xp: 60 },
    text: { offer: ['Mira! You’re awake. The whole valley felt it when the star came down.', 'Your teacher, Master Orrin, rode toward Sunpetal that same night. Nobody has seen him since.', 'Elder Rowan will know where he went. Follow the road south-east — and keep Tuft close.'], progress: ['Sunpetal Village is down the road to the south-east.'], complete: [], after: ['Rowan knows more than he says.'],
      deliver: ['Orrin’s apprentice. He said you would come looking.', 'He stood right where you are, pale as milk, and said: “The Beacon must not go dark.” An hour later, it did.'] } }),
  m({ id: 'm2', title: 'Gloom at the Gates', giver: 'rowan', kind: 'slay', count: 6, enemy: 'gloomling', requires: 'm1', summary: 'Drive off gloomlings around the village.', reward: { xp: 90 },
    text: { offer: ['Since the Beacon died, gloomlings creep out of the grass every dusk.', 'Drive off six of them, and I will tell you what your master was looking for.'], progress: ['Gloomlings lurk in the tall grass around the village.'], complete: ['You fight like Orrin’s student. Very well.', 'He carried a lantern into the Old Stone Garden, muttering about sun-crystals — as if someone else was after them too.'], after: ['The lanes are quieter tonight.'] } }),
  m({ id: 'm3', title: 'The First Sun-crystal', giver: 'rowan', kind: 'key', count: 1, keys: [0], requires: 'm2', summary: 'Find the sun-crystal in the Old Stone Garden.', reward: { xp: 120 },
    text: { offer: ['The Old Stone Garden lies to the east. The first beacon-keepers hid a sun-crystal there.', 'If Orrin wanted it, so should we. Bring it to me.'], progress: ['Look for a golden light among the stones, east of here.'], complete: ['It glows for you. The Beacon trusts you.', 'A scrap of paper was wedged beneath it, in Orrin’s hand: “S. — forgive me. I only wanted to help.” Who is S.?'], after: ['Two crystals remain.'] } }),
  m({ id: 'm4', title: 'The Scholar of Goldenhearth', giver: 'rowan', kind: 'talk', count: 1, to: 'ilse', requires: 'm3', summary: 'Ask Scholar Ilse in Goldenhearth about Orrin’s note.', reward: { xp: 90 },
    text: { offer: ['Scholar Ilse studied with Orrin when they were young. She lives in Goldenhearth, the great city to the south-east.', 'If anyone can read his riddles, it is her.'], progress: ['Goldenhearth is the city south-east of here.'], complete: [], after: ['Ilse will help.'],
      deliver: ['Orrin’s apprentice! Oh, that stubborn old man. What has he done now?', '“S.” is Sable — his pupil before you. She vanished years ago after a terrible quarrel with him. He never forgave himself.'] } }),
  m({ id: 'm5', title: 'Pages in the Reeds', giver: 'ilse', kind: 'collect', count: 4, near: 'mirror', item: 'Orrin’s journal page', icon: 'letter', requires: 'm4', summary: 'Gather Orrin’s journal pages around Mirror Lake.', reward: { xp: 130 },
    text: { offer: ['Orrin writes everything down. Fishers at Mirror Lake have been finding loose pages in the reeds.', 'Gather four of them. They will tell us what he was chasing.'], progress: ['Mirror Lake lies west of the city. Look along the shore.'], complete: ['“The Beacon, the Bell and the Star were lit together long ago, to seal away Umbra — the Eclipse.”', '“If all three lights fail, the seal breaks.” Stars above… Mira, the Beacon is already dark.'], after: ['Read every page twice.'] } }),
  m({ id: 'm6', title: 'The Keeper’s Daughter', giver: 'ilse', kind: 'rescue', count: 1, place: 'rot', guards: 5, requires: 'm5', turnIn: 'brannoc', summary: 'Free Linnea from Rotwood Den, then report to Captain Brannoc.',
    captive: person('Linnea', '👧', { robe: '#e0a040', hair: '#b8743c', small: true }), reward: { xp: 150, hearts: 1 },
    text: { offer: ['Only a Beacon-keeper knows how to relight the flame. The last one’s daughter, Linnea, was dragged off to Rotwood Den.', 'Please bring her home. Captain Brannoc of the city guard has been trying for days.'], progress: ['Rotwood Den lies far to the east. Defeat her captors, then open the cage.'],
      deliver: ['You came for me! I thought nobody would.', 'A girl in a black cloak told the creatures to take me. She had eyes like an eclipse… she said the Beacon belongs to the dark now.'],
      complete: ['Linnea is safe, thanks to you. The guard owes you.', 'She told us the second crystal was dragged into Gloom Hollow, far to the south-west.'], after: ['The city stands with you, Mira.'] } }),
  m({ id: 'm7', title: 'Crystal in the Gloom', giver: 'brannoc', kind: 'key', count: 1, keys: [1], requires: 'm6', turnIn: 'bram', summary: 'Take the sun-crystal from Gloom Hollow, then tell Farmer Bram.', reward: { xp: 160 },
    text: { offer: ['Gloom Hollow is thick with gloomlings, past Millbrook Farm to the south-west.', 'Farmer Bram lives closest. Let him know when you are out.'], progress: ['Gloom Hollow lies south of Millbrook Farm.'], complete: ['You went into the Hollow and walked back out? With a crystal, no less!', 'Old Odo on Shepherd’s Hill lights signal fires every night. He swears the last crystal is up there.'], after: ['The fields feel safer already.'] } }),
  m({ id: 'm8', title: 'Boars on the Hill Road', giver: 'bram', kind: 'slay', count: 5, enemy: 'bristleboar', requires: 'm7', turnIn: 'odo', summary: 'Defeat bristleboars, then climb to Shepherd’s Hill.', reward: { xp: 170 },
    text: { offer: ['Bristleboars have gone wild on the roads. They charge anything that moves.', 'Clear five of them on your way to Shepherd’s Hill, far to the north-east. When one paws the ground — jump aside!'], progress: ['Bristleboars charge in a straight line. Dash out of the way.'], complete: ['Five boars! My sheep can finally graze.', 'The last crystal is up here among my stones, but it hums strangely. Like it’s afraid.'], after: ['Baa. I mean — good day.'] } }),
  m({ id: 'm9', title: 'The Last Sun-crystal', giver: 'odo', kind: 'key', count: 1, keys: [2], requires: 'm8', summary: 'Find the last sun-crystal on Shepherd’s Hill.', reward: { xp: 180 },
    text: { offer: ['Take it before that cloaked girl does. I saw her last night, watching the Beacon Rise.', '…She looked sad, if you ask me. Sad and angry.'], progress: ['The crystal is somewhere on the hill.'], complete: ['All three crystals, together again. Listen — the ground is rumbling.', 'Mossback, the guardian under the Rise, is waking. It will test whoever carries the crystals.'], after: ['Go on, now.'] } }),
  m({ id: 'm10', title: 'The Guardian of the Rise', giver: 'odo', kind: 'boss', count: 1, boss: 'boss', finale: true, requires: 'm9', summary: 'Defeat Mossback at the Beacon Rise and relight the Meadow Beacon.', reward: { xp: 320, hearts: 1 },
    text: { offer: ['Mossback has slept under the Rise for a hundred years. The dark has made it angry.', 'When the ground glows, move! Dodge the boulders, and never stand still.', 'Defeat it, then lay the crystals in the Meadow Beacon, far to the south-east.'], progress: ['The Beacon Rise lies far to the south-east.'], complete: [], after: ['The Beacon shines!'] } }),
];

// ═════════════════════════════ Chapter II · The Bell Beneath the Roots (15)
const woods: StoryQuest[] = [
  m({ id: 'm1', title: 'Into Whisperroot', giver: 'fox', kind: 'talk', count: 1, to: 'guide', requires: 'meadow:m10', summary: 'Go through the Eastern Gate and find Mosskeeper Oda.', reward: { xp: 60 },
    text: { offer: ['(Tuft tugs at your sleeve and points east, where the road dives under dark trees.)', 'The Beacon’s light showed the way: past the Eastern Gate lies Whisperroot Woods. Sable went there. Find the Mosskeeper.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
      deliver: ['You came through the gate? Then the Beacon is lit — I felt it in the roots.', 'Here the Ancient Bell has gone silent, and a girl in a black cloak walks the paths at night. The woods are afraid of her.'] } }),
  m({ id: 'm2', title: 'Wolves in the Mist', giver: 'guide', kind: 'slay', count: 6, enemy: 'shadewolf', requires: 'm1', summary: 'Defeat shadewolves on the forest roads.', reward: { xp: 80 },
    text: { offer: ['Shadewolves came with her. They hunt in packs and bite out of the fog.', 'Thin them out — six — so the road to Bellhollow is safe.'], progress: ['Shadewolves circle before they lunge. Keep moving.'], complete: ['Well fought. The pack will think twice.'], after: ['Mind the fog.'] } }),
  m({ id: 'm3', title: 'The Silent Bell', giver: 'guide', kind: 'talk', count: 1, to: 'bellkeeper', requires: 'm2', summary: 'Speak with the Old Bellkeeper in Bellhollow.', reward: { xp: 70 },
    text: { offer: ['The Old Bellkeeper in Bellhollow rang the Ancient Bell every dawn for sixty years.', 'If anyone knows why it stopped, it is him. Bellhollow is south-east of here.'], progress: ['Bellhollow lies to the south-east.'], complete: [], after: [],
      deliver: ['The Bell did not stop. It was silenced — strangled in roots by the Bramble Warden, the very guardian that once protected it.', 'Something poisoned the Warden. Shadow, black as ink, running through its thorns.'] } }),
  m({ id: 'm4', title: 'Moonpetal Salve', giver: 'bellkeeper', kind: 'collect', count: 5, near: 'glade', item: 'Moonpetal', icon: 'flower', requires: 'm3', turnIn: 'juna', summary: 'Pick moonpetals in the Moonlit Glade and bring them to Herbalist Juna.', reward: { xp: 90 },
    text: { offer: ['To cleanse the Warden we need moonpetals from the Moonlit Glade — five of them.', 'Herbalist Juna in Lanternmarket can brew them into a salve that eats shadow.'], progress: ['The Moonlit Glade lies north. Juna is in Lanternmarket, the city east of it.'], complete: ['Moonpetals, fresh as dew! The salve will take a while to steep.', 'Meanwhile — the lamplighters saw the girl in black near the Root Ruins. Warden Thessaly is gathering scouts.'], after: ['The salve is bubbling.'] } }),
  m({ id: 'm5', title: 'The Lamplighters', giver: 'juna', kind: 'talk', count: 1, to: 'thessaly', requires: 'm4', summary: 'Find Warden Thessaly in Lanternmarket.', reward: { xp: 70 },
    text: { offer: ['Warden Thessaly keeps the city watch. She’s by the great fountain, most days.'], progress: ['Thessaly is in Lanternmarket.'], complete: [], after: [],
      deliver: ['Orrin’s other apprentice? Then you may be the only one who can reason with her.', 'My scouts went to the Root Ruins yesterday. Two came back. The third — Rook — is still there.'] } }),
  m({ id: 'm6', title: 'Scout in the Ruins', giver: 'thessaly', kind: 'rescue', count: 1, place: 'ruins', guards: 6, requires: 'm5', summary: 'Free Scout Rook from the Root Ruins.',
    captive: person('Scout Rook', '💂', { robe: '#6a7a8a', hat: 'helm', hatColor: '#8a8f9a' }), reward: { xp: 110, hearts: 1 },
    text: { offer: ['Rook is caged somewhere in the Root Ruins, far to the north-west. Shadewolves guard him.', 'Bring him home, Mira.'], progress: ['The Root Ruins are north-west. Defeat the guards, then open the cage.'],
      deliver: ['You came for me? Bless you!', 'Sable was carving runes into the roots. She said: “When the Bell is gone, Umbra will finally set me free.”'],
      complete: ['Umbra… the old tales call it the Eclipse. If Sable serves it, the whole valley is in danger.', 'Three root runes can wake the Bell. The first glows under Glowcap Farm, west of the ruins.'], after: ['The watch owes you a debt.'] } }),
  m({ id: 'm7', title: 'The Rune Under the Glowcaps', giver: 'thessaly', kind: 'key', count: 1, keys: [0], requires: 'm6', turnIn: 'forester', summary: 'Wake the root rune at Glowcap Farm and find Forester Birch.', reward: { xp: 110 },
    text: { offer: ['Glowcap Farm lies in the far north-west. Touch the rune and it will wake.', 'Forester Birch works the timber there. He will want to hear the woods are waking.'], progress: ['Glowcap Farm is north-west.'], complete: ['A root rune! It hums like a beehive.', 'But webspinners have taken the timber road. I can’t haul a single log to the city.'], after: ['Timber and runes, what a week.'] } }),
  m({ id: 'm8', title: 'Silk on the Timber Road', giver: 'forester', kind: 'slay', count: 6, enemy: 'webspinner', requires: 'm7', turnIn: 'fenn', summary: 'Defeat webspinners, then report to Lamplighter Fenn in Lanternmarket.', reward: { xp: 120 },
    text: { offer: ['Webspinners spit sticky silk that slows you down. Then they bite.', 'Clear six of them, then tell Lamplighter Fenn in the city the road is open.'], progress: ['If you are webbed, dash free and keep your distance.'], complete: ['The timber road is open? Then my lanterns will get their oil!', 'Listen — the Moonlit Glade has been glowing strangely. The runes remember things there.'], after: ['A lantern for every path.'] } }),
  m({ id: 'm9', title: 'Where the Moon Drinks', giver: 'fenn', kind: 'visit', count: 1, place: 'glade', requires: 'm8', summary: 'Walk into the Moonlit Glade, then return to Fenn.', reward: { xp: 100 },
    text: { offer: ['Walk into the Moonlit Glade and let the rune show you what it remembers.', 'Then come back and tell me.'], progress: ['The glade is west of the city.'], complete: ['The glade showed you a little girl lighting lanterns with Orrin? …Then Sable was not always like this.', 'The second rune lies in the Thornling Nest to the north. Scout Ivo watches it from the Owl Watchtower.'], after: ['Some memories glow.'] } }),
  m({ id: 'm10', title: 'Thorns Around the Rune', giver: 'fenn', kind: 'key', count: 1, keys: [1], requires: 'm9', turnIn: 'ivo', summary: 'Wake the rune in the Thornling Nest, then report to Scout Ivo.', reward: { xp: 140 },
    text: { offer: ['The Thornling Nest is north of the city. Thornlings spit — dash through their gaps.', 'Scout Ivo at the Owl Watchtower, east of the nest, will want to know you made it out.'], progress: ['The nest is north. The watchtower is east of it.'], complete: ['Two runes! The owls are hooting like mad.', 'And there’s more: I saw Sable’s campfire in Silkshadow Hollow, south-east.'], after: ['All clear, for now.'] } }),
  m({ id: 'm11', title: 'Sable’s Camp', giver: 'ivo', kind: 'visit', count: 1, place: 'web', requires: 'm10', summary: 'Search Silkshadow Hollow for Sable’s camp, then report to Ivo.', reward: { xp: 140 },
    text: { offer: ['Silkshadow Hollow is a spider den south-east of the tower. Sable camped there.', 'See what she left behind.'], progress: ['Silkshadow Hollow is south-east.'], complete: ['She left her journal? Read it, Mira.', '“Orrin tried to burn the shadow out of me with starlight. He pulled the whole sky down doing it. Umbra says it can make the pain stop.”'], after: ['Poor girl.'] } }),
  m({ id: 'm12', title: 'The Owl’s Rune', giver: 'ivo', kind: 'key', count: 1, keys: [2], requires: 'm11', summary: 'Wake the root rune at the Owl Watchtower.', reward: { xp: 130 },
    text: { offer: ['The last rune sleeps somewhere around the watchtower. It glows green.', 'Wake it and come back to me.'], progress: ['Look around the tower.'], complete: ['All three runes are singing!', 'But the shadow in these woods is thick. It feeds on fear — and on every creature Sable calls.'], after: ['The owls are proud.'] } }),
  m({ id: 'm13', title: 'Shadowbreak', giver: 'ivo', kind: 'slay', count: 10, enemy: 'any', requires: 'm12', turnIn: 'juna', summary: 'Defeat creatures of the shadow, then collect the salve from Juna.', reward: { xp: 170 },
    text: { offer: ['Break ten of her creatures and the shadow in the Warden will weaken.', 'Then fetch Juna’s salve from Lanternmarket.'], progress: ['Any creature of the woods will do.'], complete: ['Ten! I can feel the woods breathing easier.', 'And the salve is ready. Take it to the Old Bellkeeper — he knows the Warden best.'], after: ['Go gently.'] } }),
  m({ id: 'm14', title: 'Salve for the Warden', giver: 'juna', kind: 'deliver', count: 1, to: 'bellkeeper', item: 'Moonpetal salve', requires: 'm13', summary: 'Bring the moonpetal salve to the Old Bellkeeper in Bellhollow.', reward: { xp: 120 },
    text: { offer: ['Here it is: moonpetal salve, strong enough to eat shadow.', 'Bring it to the Bellkeeper in Bellhollow.'], progress: ['Bellhollow is south-west of the city.'], complete: [], after: ['May it work.'],
      deliver: ['The salve! With this the Warden’s thorns may remember who they were.', 'The runes are singing and the salve is ready. It is time.'] } }),
  m({ id: 'm15', title: 'The Bramble Warden', giver: 'bellkeeper', kind: 'boss', count: 1, boss: 'boss', finale: true, requires: 'm14', summary: 'Defeat the Bramble Warden and ring the Ancient Root Bell.', reward: { xp: 360, hearts: 1 },
    text: { offer: ['The Warden guards the Old Bell in the far north-east. It throws rings of thorns and sends roots racing through the soil.', 'Break the shadow in it, then ring the Bell.', 'And Mira… if you see Sable, try to talk first.'], progress: ['The Old Bell stands in the far north-east.'], complete: [], after: ['The Bell rings!'] } }),
];

// ═════════════════════════════ Chapter III · The Hollow Star (20)
const summit: StoryQuest[] = [
  m({ id: 'm1', title: 'The Silver Heights', giver: 'fox', kind: 'talk', count: 1, to: 'guide', requires: 'woods:m15', summary: 'Go through the Eastern Gate and find Sky-warden Ilsa.', reward: { xp: 60 },
    text: { offer: ['(Tuft sniffs the icy wind blowing through the Eastern Gate and whines.)', 'Beyond the gate the road climbs to Starfall Summit. Sable fled that way. Maybe Orrin did too.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
      deliver: ['Another climber — and Orrin’s apprentice at that. I’ve been waiting for you.', 'The fallen star lies in the Cradle at the top of the world. It is hollow now, Mira. Something lives inside it.'] } }),
  m({ id: 'm2', title: 'Wisps on the Wind', giver: 'guide', kind: 'slay', count: 6, enemy: 'wisp', requires: 'm1', turnIn: 'aune', summary: 'Defeat six void wisps on the road to Frostpine Hamlet (the gold arrow leads to them), then find Healer Aune there.', reward: { xp: 70 },
    text: { offer: ['Void wisps pour down from the star. They swarm anyone on the road to Frostpine Hamlet.', 'Clear six of them and find Healer Aune in the hamlet, south-east of here.', 'Mind you: the pale ghosts are frost wraiths. The wisps are the small violet lights that dart side to side.'], progress: ['Wisps are small violet lights on the road south-east. Follow the gold arrow to the nearest one.'], complete: ['You made it through the wisps? Sit, sit! Your fingers are blue.', 'Nobody reaches the Cradle frozen.'], after: ['Warm hands, warm heart.'] } }),
  m({ id: 'm3', title: 'Against the Cold', giver: 'aune', kind: 'collect', count: 5, near: 'hamlet', item: 'Emberroot', icon: 'herb', requires: 'm2', summary: 'Gather emberroot around Frostpine Hamlet.', reward: { xp: 70 },
    text: { offer: ['Emberroot grows under the snow around the hamlet. It keeps a body warm for days.', 'Bring me five and I will brew you a tonic.'], progress: ['Five emberroots, around the hamlet.'], complete: ['Drink up — you will not freeze now.', 'Astronomer Vale sent word from the Old Observatory: he has seen an old man in the star’s light.'], after: ['Stay warm.'] } }),
  m({ id: 'm4', title: 'The Astronomer', giver: 'aune', kind: 'talk', count: 1, to: 'vale', requires: 'm3', summary: 'Visit Astronomer Vale at the Old Observatory.', reward: { xp: 60 },
    text: { offer: ['The Old Observatory is south-west of the hamlet. Vale is odd, but he knows the sky.'], progress: ['The observatory is south-west.'], complete: [], after: [],
      deliver: ['Ah! The girl with the fox. The stars mentioned you.', 'Orrin? Yes — I saw him through my lens, dragged into the Void Rift by shadows. He is alive, Mira. For now.'] } }),
  m({ id: 'm5', title: 'Read the Sky', giver: 'vale', kind: 'visit', count: 1, place: 'tarn', requires: 'm4', summary: 'Look into Mirrorsky Tarn, then report back to Vale.', reward: { xp: 80 },
    text: { offer: ['Before you charge into the Rift, look into Mirrorsky Tarn. It reflects what the sky remembers.', 'Tell me what you see.'], progress: ['Mirrorsky Tarn lies north of the hamlet.'], complete: ['Three lights under the water? Three star shards! The star cracked when it fell.', 'One in Crystal Hollow, one on Frostfang Crag, one at the Broken Spire. With all three, its shell can be broken.'], after: ['The sky is a map.'] } }),
  m({ id: 'm6', title: 'The Crystal Shard', giver: 'vale', kind: 'key', count: 1, keys: [0], requires: 'm5', turnIn: 'guide', summary: 'Take the star shard from Crystal Hollow, then return to Ilsa.', reward: { xp: 90 },
    text: { offer: ['Crystal Hollow is in the far north-west. The shard hums the note of the star.', 'Sky-warden Ilsa’s lookout is on the way back.'], progress: ['Crystal Hollow is north-west. Then Warden’s Lookout.'], complete: ['A star shard! It is warm, like a little sun.', 'Crag golems have woken on the heights, drawn to its heat. The Abbot of Skyhold is asking for help.'], after: ['Rest a moment.'] } }),
  m({ id: 'm7', title: 'The City in the Clouds', giver: 'guide', kind: 'talk', count: 1, to: 'corvin', requires: 'm6', summary: 'Meet Abbot Corvin in Skyhold.', reward: { xp: 60 },
    text: { offer: ['Skyhold is the great city of the Summit, south-east of the tarn. Abbot Corvin leads it.'], progress: ['Skyhold lies south-east.'], complete: [], after: [],
      deliver: ['Orrin’s apprentice. We have prayed for you.', 'Crag golems stomp down from the heights and smash our supply carts. Help us, and Skyhold will help you.'] } }),
  m({ id: 'm8', title: 'Stone and Frost', giver: 'corvin', kind: 'slay', count: 4, enemy: 'cragGolem', requires: 'm7', summary: 'Break crag golems on the heights.', reward: { xp: 110 },
    text: { offer: ['Crag golems are slow, but they hit like avalanches. When one raises its fists, get away!', 'Break four of them.'], progress: ['Golems roam the crags north of the city.'], complete: ['Four golems! The monks are singing your name.', 'Now: the Void Rift. No one walks into it without the Star Altar’s blessing.'], after: ['Skyhold stands with you.'] } }),
  m({ id: 'm9', title: 'The Star Altar', giver: 'corvin', kind: 'visit', count: 1, place: 'altar', requires: 'm8', turnIn: 'sella', summary: 'Stand before the Star Altar, then speak with Monk Sella in Skyhold.', reward: { xp: 90 },
    text: { offer: ['The Star Altar is east of Skyhold. Stand before it and let it see you.', 'Then speak with Monk Sella.'], progress: ['The Star Altar lies east of the city.'], complete: ['The Altar accepted you. Its light will keep the Rift from swallowing your mind.', 'Now go and bring your teacher home.'], after: ['Peace be with you.'] } }),
  m({ id: 'm10', title: 'The Prisoner of the Rift', giver: 'sella', kind: 'rescue', count: 1, place: 'rift', guards: 6, requires: 'm9', summary: 'Free Master Orrin from the Void Rift.',
    captive: person('Master Orrin', '🧙‍♂️', { robe: '#5b5480', hat: 'wizard', hatColor: '#3f3a70', beard: true, hair: '#e8e2d0' }), reward: { xp: 140, hearts: 1 },
    text: { offer: ['Orrin is chained in the Void Rift, far to the south-east. Frost wraiths and wisps guard him.', 'Free your teacher, Mira.'], progress: ['The Void Rift lies south-east. Break the guards, then open the cage.'],
      deliver: ['Mira…? Oh, my brave girl. You came all this way.', 'I have done a terrible thing. Take me to Skyhold, and I will tell you everything.'],
      complete: ['Orrin is resting in our infirmary. He asked for you.'], after: ['He is safe now.'] } }),
  m({ id: 'm11', title: 'Orrin’s Confession', giver: 'sella', kind: 'talk', count: 1, to: 'orrin', requires: 'm10', summary: 'Speak with Master Orrin in Skyhold.', reward: { xp: 80 },
    text: { offer: ['He is in the city, by the infirmary. Go gently with him.'], progress: ['Orrin is in Skyhold.'], complete: [], after: [],
      deliver: ['Sable was a foundling. Shadow lived in her from birth, and it hurt her. I thought starlight could burn it out.', 'I called the star down to heal her. Instead I tore open the sky, and Umbra — the Eclipse — crept inside the star and hollowed it out.', 'Sable ran. Umbra whispers that if the three lights die, her pain will end. It lies. When the lights die, Umbra is free.'] } }),
  m({ id: 'm12', title: 'The Crag Shard', giver: 'orrin', kind: 'key', count: 1, keys: [1], requires: 'm11', summary: 'Take the star shard from Frostfang Crag.', reward: { xp: 110 },
    text: { offer: ['The second shard fell on Frostfang Crag, north-east of the city. The golems guard it jealously.', 'Bring it here.'], progress: ['Frostfang Crag is north-east of Skyhold.'], complete: ['Two shards. The star is calling to them.', 'Mira, there is something else I need you to do. For her.'], after: ['Thank you.'] } }),
  m({ id: 'm13', title: 'Flowers That Aren’t Afraid', giver: 'orrin', kind: 'collect', count: 5, near: 'bloom', item: 'Starbloom', icon: 'flower', requires: 'm12', turnIn: 'dov', summary: 'Pick starblooms in the Starbloom Grove, then find Quartermaster Dov.', reward: { xp: 110 },
    text: { offer: ['Sable loved starblooms when she was small. She called them “the flowers that aren’t afraid of the dark.”', 'Pick five in the Starbloom Grove, far to the north. Dov at Silver Pass will know where she went.'], progress: ['The Starbloom Grove is north, past the tarn.'], complete: ['Starblooms? For Sable? That is Orrin’s idea, I bet.', 'She walked right past my guards last night — toward the Broken Spire.'], after: ['Pretty things.'] } }),
  m({ id: 'm14', title: 'Hold the Pass', giver: 'dov', kind: 'slay', count: 10, enemy: 'any', requires: 'm13', summary: 'Defeat creatures of the void around Silver Pass.', reward: { xp: 130 },
    text: { offer: ['The void sends creature after creature at my camp. If we fall, the road to the Spire falls with us.', 'Help us hold — ten of them.'], progress: ['Any creature of the Summit will do.'], complete: ['The pass holds! Now go — the Spire is east of here.'], after: ['The pass holds.'] } }),
  m({ id: 'm15', title: 'The Broken Spire', giver: 'dov', kind: 'key', count: 1, keys: [2], requires: 'm14', summary: 'Take the last star shard from the Broken Spire.', reward: { xp: 130 },
    text: { offer: ['The Broken Spire fell with the star, and still points at it. The last shard is there.', 'And so, I think, is Sable.'], progress: ['The Broken Spire lies east of the pass.'], complete: ['All three shards. You can feel them from here.'], after: ['Go carefully.'] } }),
  m({ id: 'm16', title: 'What Orrin Wrote', giver: 'dov', kind: 'deliver', count: 1, to: 'sable', item: 'Starblooms and Orrin’s letter', requires: 'm15', summary: 'Bring the starblooms and Orrin’s letter to Sable at the Broken Spire.', reward: { xp: 140 },
    text: { offer: ['She’s up at the Spire, alone. Orrin gave you a letter for her, didn’t he?', 'Give her the flowers. Talk to her.'], progress: ['Sable waits at the Broken Spire.'], complete: [], after: [],
      deliver: ['…Starblooms. He remembered.', '“Sable — the shadow was never the part of you that needed fixing. I was. Forgive me.” …He wrote that?', 'Umbra lied to me. It isn’t in me — it’s in the star. And it is almost free. I’ll help you, Mira.'] } }),
  m({ id: 'm17', title: 'The Eclipse’s Heralds', giver: 'sable', kind: 'slay', count: 6, enemy: 'frostwraith', requires: 'm16', summary: 'Defeat the frost wraiths that seal the Cradle.', reward: { xp: 140 },
    text: { offer: ['Frost wraiths are Umbra’s heralds. They keep the Cradle sealed and watch for anyone carrying shards.', 'Break six of them. I’ll pull the shadow off the rest.'], progress: ['Wraiths blink close and throw ice. Stay moving.'], complete: ['That’s all of them near the Cradle. The seal is weak.', 'Go to Orrin. Tell him… tell him I’m coming home.'], after: ['I’m ready.'] } }),
  m({ id: 'm18', title: 'Together Again', giver: 'sable', kind: 'talk', count: 1, to: 'orrin', requires: 'm17', summary: 'Bring Sable’s words to Orrin in Skyhold.', reward: { xp: 110 },
    text: { offer: ['Go on. I’ll follow when I’m brave enough.'], progress: ['Orrin is in Skyhold.'], complete: [], after: [],
      deliver: ['She’s… coming home? After everything I did?', 'Then we face the star together — Ilsa, Vale, the monks, Sable and me. You have the shards, Mira. It is time.'] } }),
  m({ id: 'm19', title: 'The Hollow Star', giver: 'orrin', kind: 'boss', count: 1, boss: 'boss', finale: true, requires: 'm18', summary: 'Defeat the Hollow Star and return the shards to the Star Cradle.', reward: { xp: 420, hearts: 1 },
    text: { offer: ['The Star Cradle lies at the top of the world, north-east of the Spire. The Hollow Star spirals void-light, rains meteors and blinks right beside you.', 'Crack its shell, then lay the three shards in the Cradle.', 'But be ready, Mira. When the shell breaks, Umbra will have nowhere left to hide.'], progress: ['The Star Cradle is in the far north-east.'], complete: [], after: ['The star is home.'] } }),
];

// ═════════════════════════════ Chapter IV · The Dawn Forge (13)
const ember: StoryQuest[] = [
  m({ id: 'm1', title: 'Into the Ember Wastes', giver: 'fox', kind: 'talk', count: 1, to: 'guide', requires: 'summit:m19', summary: 'Follow Umbra’s trail through the Eastern Gate and find Captain Ashka.', reward: { xp: 80 },
    text: { offer: ['(Tuft stares east, where a thread of black smoke crawls over the Summit’s last ridge.)', 'Umbra escaped the broken star. It fled through the Eastern Gate, into the Ember Wastes. Captain Ashka keeps the outpost there.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
      deliver: ['A traveller from the Summit? Then the sky-fire we saw was real.', 'Something black fell out of the east wind two nights ago. Since then the imps have gone mad, and the old Dawn Forge has gone cold.'] } }),
  m({ id: 'm2', title: 'Imps in the Smoke', giver: 'guide', kind: 'slay', count: 6, enemy: 'emberImp', requires: 'm1', summary: 'Drive off six ember imps around the outpost.', reward: { xp: 90 },
    text: { offer: ['Ember imps hover out of range and lob fire. Close in fast, or keep moving.', 'Six of them, and the road to Kilnhollow is safe again.'], progress: ['Imps hang back and throw fireballs. Keep moving.'], complete: ['Six imps! The lads can breathe without swallowing sparks.', 'Kiln-mother Hessa in Kilnhollow knows these wastes better than anyone. Go and see her.'], after: ['Watch the sky for sparks.'] } }),
  m({ id: 'm3', title: 'The Kiln-mother', giver: 'guide', kind: 'talk', count: 1, to: 'hessa', requires: 'm2', summary: 'Find Kiln-mother Hessa in Kilnhollow.', reward: { xp: 80 },
    text: { offer: ['Kilnhollow lies south-east of the outpost, where the glass-kilns never go out.'], progress: ['Kilnhollow is south-east.'], complete: [], after: [],
      deliver: ['The Dawn Forge lit the sunrise over these wastes for a thousand years. Now it sleeps, and the dark walks in its shadow.', 'Its fire lived in three ember cores. Pyrrhus — the Cinder Tyrant — tore them out and hid them.'] } }),
  m({ id: 'm4', title: 'Cooling Salts', giver: 'hessa', kind: 'collect', count: 5, near: 'farm', item: 'Cooling salt', icon: 'gem', requires: 'm3', summary: 'Gather cooling salts around Saltglass Farm.', reward: { xp: 100 },
    text: { offer: ['An ember core burns the hand that holds it. You’ll need cooling salts to carry one.', 'Five crystals, from around Saltglass Farm to the south.'], progress: ['Saltglass Farm lies south-west of here.'], complete: ['Good, clean salt. Wrap a core in this and it won’t scorch you.', 'Forgemaster Tovan in Brasshaven can tell you where Pyrrhus hid the cores.'], after: ['Salt and fire, fire and salt.'] } }),
  m({ id: 'm5', title: 'The Brass City', giver: 'hessa', kind: 'talk', count: 1, to: 'tovan', requires: 'm4', summary: 'Meet Forgemaster Tovan in Brasshaven.', reward: { xp: 80 },
    text: { offer: ['Brasshaven is the great city of the wastes, east of here. Tovan works the biggest anvil.'], progress: ['Brasshaven lies to the east.'], complete: [], after: [],
      deliver: ['Hessa sent you? Then you’re serious.', 'One core glows in the Obsidian Maze to the north-west. The other two… the Tyrant’s creatures carried them off.'] } }),
  m({ id: 'm6', title: 'The Obsidian Maze', giver: 'tovan', kind: 'key', count: 1, keys: [0], requires: 'm5', summary: 'Recover the first ember core from the Obsidian Maze.', reward: { xp: 130 },
    text: { offer: ['The Obsidian Maze is far to the north-west. Its walls are sharp as knives.', 'Bring the core back to me.'], progress: ['The Obsidian Maze lies north-west.'], complete: ['The first core! Feel that heat — the forge remembers it already.', 'A salt caravan came in screaming last night. Its master was taken at the camp in the south-east.'], after: ['One of three.'] } }),
  m({ id: 'm7', title: 'The Salt Caravan', giver: 'tovan', kind: 'rescue', count: 1, place: 'caravan', guards: 6, requires: 'm6', summary: 'Free Caravan-master Oona at the Salt Caravan Camp.',
    captive: person('Caravan-master Oona', '👳‍♀️', { robe: '#c9a24c', hat: 'scarf', hatColor: '#8a3b2f', hair: '#2e2420' }), reward: { xp: 150, hearts: 1 },
    text: { offer: ['Oona’s caravan carries the salt the whole city lives on. Scorpions and imps have her caged at the camp.', 'Bring her home.'], progress: ['The Salt Caravan Camp lies south-east of the city. Defeat the guards, then open the cage.'],
      deliver: ['Sand in my teeth and a scorpion on my chest — I thought I was done.', 'The creatures took the second core into the Scorpion Burrows. I watched them drag it underground.'], complete: ['Oona is safe. The salt will flow again.', 'The Scorpion Burrows are south-west of the city. Mind the ground — they swim through the sand.'], after: ['The caravan owes you.'] } }),
  m({ id: 'm8', title: 'Under the Sand', giver: 'tovan', kind: 'key', count: 1, keys: [1], requires: 'm7', summary: 'Take the second ember core from the Scorpion Burrows.', reward: { xp: 150 },
    text: { offer: ['Ash scorpions burrow and come up right under your feet. When the sand bulges, move!', 'The second core is in their burrows, south-west of the city.'], progress: ['The Scorpion Burrows lie south-west.'], complete: ['Two cores! Hotter than the first. The forge is waking.', 'The last one is in the Old Foundry, north-east. Magma hulks guard it.'], after: ['Two of three.'] } }),
  m({ id: 'm9', title: 'Hulks of the Foundry', giver: 'tovan', kind: 'slay', count: 4, enemy: 'magmaHulk', requires: 'm8', summary: 'Break four magma hulks.', reward: { xp: 160 },
    text: { offer: ['Magma hulks are slow, but when they raise their fists, fire bursts out of the ground around them.', 'Break four and the foundry road opens.'], progress: ['Hulks roam the east of the wastes. Stay out of the glowing cracks.'], complete: ['Four hulks! Now the foundry itself.'], after: ['The anvils are ringing.'] } }),
  m({ id: 'm10', title: 'The Last Ember Core', giver: 'tovan', kind: 'key', count: 1, keys: [2], requires: 'm9', turnIn: 'seer', summary: 'Take the last ember core from the Old Foundry, then find Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 170 },
    text: { offer: ['The Old Foundry lies north-east. Take the last core.', 'Then climb to Ashfall Watch in the north. Ember-seer Ilyana has been watching the forge for weeks.'], progress: ['The Old Foundry is north-east. Ashfall Watch is north of the city.'], complete: ['Three cores, all together. The forge will listen now.', 'But the Tyrant will not let you near it without a fight — and Umbra waits in his shadow.'], after: ['The flames speak of you.'] } }),
  m({ id: 'm11', title: 'Phoenix Water', giver: 'seer', kind: 'visit', count: 1, place: 'spring', requires: 'm10', summary: 'Stand in the Phoenix Spring, then return to Ilyana.', reward: { xp: 150 },
    text: { offer: ['The Phoenix Spring in the east is where the first dawn was born. Bathe in it, and the Tyrant’s fire will not take you.', 'Then come back to me.'], progress: ['The Phoenix Spring lies east of the city.'], complete: ['You glow like sunrise. Good.', 'Now go to the Dawn Forge in the far north-east and face Pyrrhus.'], after: ['Walk in the light.'] } }),
  m({ id: 'm12', title: 'The Cinder Tyrant', giver: 'seer', kind: 'boss', count: 1, boss: 'boss', requires: 'm11', summary: 'Defeat Pyrrhus, the Cinder Tyrant, at the Dawn Forge.', reward: { xp: 480, hearts: 1 },
    text: { offer: ['Pyrrhus slams the earth, rains fire and charges like a landslide. Never stand still.', 'Break him, and the forge is yours.', 'And Mira — when he falls, Umbra will come. It has nowhere else to go.'], progress: ['The Dawn Forge is in the far north-east.'], complete: [], after: ['Be brave.'] } }),
  m({ id: 'm13', title: 'Umbra, the Eclipse', giver: 'fox', kind: 'boss', count: 1, boss: 'final', finale: true, requires: 'm12', summary: 'Defeat Umbra and light the Dawn Forge.', reward: { xp: 900, hearts: 2 },
    text: { offer: ['(Pyrrhus crumbles to cinders — and the ash around the forge turns black and begins to crawl.)', '(Far to the west, dark light rises from the Beacon Rise. From the Old Bell. From the Star Cradle. The shadows of every guardian gather into one.)', '(Tuft’s fur stands on end. Umbra, the Eclipse, is here.)'], progress: ['Defeat Umbra at the Dawn Forge.'], complete: [], after: [] } }),
];

export const STORY: Record<RegionId, StoryQuest[]> = { meadow, woods, summit, ember };
