import { buildValley, type RegionSpec } from './worldgen';
import { STORY, type StoryQuest } from './story';
import type { Captive, NpcLook, Region, RegionId, WorldDefinition } from './types';

export const LEVEL_ORDER: RegionId[] = ['meadow', 'woods', 'summit', 'ember'];

const look = (robe: string, hat: NpcLook['hat'], extra: Partial<NpcLook> = {}): Partial<NpcLook> => ({ robe, hat, hatColor: extra.hatColor || '#4a5b3e', skin: '#f0c8a2', hair: '#6b3f2a', ...extra });
const q = (def: StoryQuest) => def;
const person = (name: string, portrait: string, l: Partial<NpcLook>): Captive => ({ name, portrait, look: { skin: '#f0c8a2', robe: '#8a6fb0', hat: 'none', hatColor: '#5b5480', hair: '#6b3f2a', ...l } });
const shopLines = {
  merchant: ['Potions, tonics and brews — gold on the counter, please.'],
  smith: ['Bring gold and I’ll make that staff sing.'],
  inn: ['A warm bed and a hot meal. Rest as long as you like.'],
  armorer: ['Fine gear is never cheap. Come back when you have grown — my shelf grows with you.'],
};

// ═════════════════════════════ Chapter I · Sunpetal Meadow · levels 1–6
const meadow: RegionSpec = {
  id: 'meadow', chapter: 1, title: 'Sunpetal Meadow', subtitle: 'The Broken Beacon', name: 'Sunpetal Valley', seed: 17,
  palette: { ground: '#7fa05a', alternate: '#8fb065', path: '#d8c48e', pathEdge: '#a8915f', accent: '#f5cd5c', water: '#58a7b4', waterDeep: '#3d7f8f', foliage: ['#35593f', '#5d8a4c', '#a3c46a'], trunk: '#6f5337', rock: '#8c8f80', pod: '#f2b84b', roof: ['#b85a44', '#c9803d', '#8a5a44', '#a8644e'], wall: '#efe0bf' },
  darkness: 0, ambient: 'petals', ground: 'grass', levels: [1, 6], xpScale: .5,
  pois: [
    { id: 'rest', name: 'Bridgekeeper’s Rest', kind: 'start', x: 900, y: 900, r: 380 },
    { id: 'sunpetal', name: 'Sunpetal Village', kind: 'village', x: 2400, y: 1900, r: 520 },
    { id: 'millbrook', name: 'Millbrook Farm', kind: 'farm', x: 1100, y: 3500, r: 440 },
    { id: 'stones', name: 'Old Stone Garden', kind: 'ruins', x: 4200, y: 1000, r: 380 },
    { id: 'city', name: 'Goldenhearth', kind: 'city', x: 4700, y: 3300, r: 900 },
    { id: 'mirror', name: 'Mirror Lake', kind: 'lake', x: 2600, y: 4700, r: 560 },
    { id: 'hollow', name: 'Gloom Hollow', kind: 'lair', x: 1300, y: 5750, r: 430, pack: ['gloomling', 'gloomling', 'sporecap'] },
    { id: 'faerie', name: 'Faerie Ring', kind: 'grove', x: 4300, y: 5900, r: 380 },
    { id: 'willow', name: 'Willowmere', kind: 'village', x: 6900, y: 2000, r: 500 },
    { id: 'shepherd', name: 'Shepherd’s Hill', kind: 'lookout', x: 8300, y: 800, r: 360 },
    { id: 'camp', name: 'Hunter’s Camp', kind: 'camp', x: 6700, y: 5000, r: 340 },
    { id: 'rot', name: 'Rotwood Den', kind: 'lair', x: 7800, y: 3700, r: 420, pack: ['bristleboar', 'gloomling', 'sporecap'] },
    { id: 'shrine', name: 'Sun Shrine', kind: 'shrine', x: 8900, y: 2400, r: 280 },
    { id: 'rise', name: 'The Beacon Rise', kind: 'finale', x: 8500, y: 5900, r: 440 },
    { id: 'gateE', name: 'Eastern Gate', kind: 'gate', x: 9480, y: 3300, r: 240 },
  ],
  lakeSize: { mirror: 360 },
  links: [['sunpetal', 'city'], ['mirror', 'faerie'], ['camp', 'rise'], ['willow', 'shrine'], ['millbrook', 'hollow'], ['city', 'willow'], ['city', 'camp']],
  keyAt: ['stones', 'hollow', 'shepherd'], keyName: 'Sun-crystal', shrineName: 'Sun Shrine', finaleName: 'Meadow Beacon',
  trees: [['tree', 7], ['bush', 3], ['rock', 2]], decorKinds: [['grass', 10], ['flower', 4], ['pebble', 1], ['clover', 2]], decorColors: ['#f7d774', '#f2a1b8', '#ffffff', '#c7a6f2', '#ff9b73'],
  enemyKinds: [['gloomling', 6], ['thornling', 3], ['bristleboar', 3], ['sporecap', 2]], boss: 'mossback', bossLevel: 7,
  critters: [['rabbit', 5], ['bird', 6], ['deer', 2], ['duck', 3], ['frog', 2], ['squirrel', 2]],
  villagerNames: ['Hollis', 'Marigold', 'Fen', 'Bertie', 'Clover', 'Aldo', 'Posy', 'Jem', 'Nell', 'Tobin', 'Wynn', 'Ada', 'Cress', 'Bramwell', 'Lark', 'Maddox', 'Primrose', 'Hugo', 'Elsie', 'Barnaby', 'Dot', 'Gideon', 'Juniper', 'Ottar', 'Rue'],
  chatter: ['Ever since the star fell, the nights feel colder.', 'Goldenhearth’s bakery makes the best honey buns in the valley.', 'Watch the tall grass — gloomlings love to hide there.', 'My grandmother says the Beacon was lit by a fox and a girl, long ago.', 'The roads all meet in the city. Follow them and you won’t get lost.', 'I found a chest in the woods once. Empty. Still proud of it.', 'If you see a stone with glowing runes, read it! They remember old stories.', 'The smith in Goldenhearth can make a staff hit twice as hard. For a price.', 'Boars used to be shy. Now they charge carts on the road.', 'I saw a girl in a black cloak by the Rise. She didn’t leave footprints.'],
  barks: ['Lovely day!', 'Mind the gloomlings.', 'Hello, traveller!', 'Busy, busy…', 'Have you tried the honey buns?', 'The Beacon is dark…', 'Good winds today.'],
  npcs: [
    { id: 'guide', name: 'Bridgekeeper Tamsin', portrait: '🧑‍🌾', at: 'rest', dx: -40, dy: -60, activity: 'idle', role: 'guide', look: look('#d99857', 'straw', { hatColor: '#d9b45a' }), lines: [], barks: ['Over here, Mira!', 'The Beacon needs you.'] },
    { id: 'pip', name: 'Pip the Courier', portrait: '🐿️', at: 'rest', dx: 170, dy: 40, activity: 'wander', look: look('#c16d59', 'ears', { hatColor: '#a0522d', small: true }), lines: ['Letters, parcels, gossip — Pip delivers!'], barks: ['Where did I put it…', 'Busy courier coming through!'] },
    { id: 'rowan', name: 'Elder Rowan', portrait: '🧙🏼', at: 'sunpetal', dx: -60, dy: 90, activity: 'idle', look: look('#818ca8', 'wizard', { hatColor: '#5b5480', beard: true, hair: '#e8e2d0' }), lines: ['The valley has seen darker days. Not many.'], barks: ['Hmm, the stars are restless.'] },
    { id: 'maren', name: 'Healer Maren', portrait: '👩‍⚕️', at: 'sunpetal', dx: 150, dy: -40, activity: 'sweep', look: look('#7a9a5a', 'bonnet', { hatColor: '#e8e2d0' }), lines: ['Herbs, bandages, kind words. That’s the whole trade.'], barks: ['Stay healthy, dear!'] },
    { id: 'wren', name: 'Postmistress Wren', portrait: '📮', at: 'sunpetal', dx: 60, dy: 190, activity: 'idle', look: look('#6f8fb8', 'cap', { hatColor: '#3f5a8a' }), lines: ['Mail goes out at dawn. Well — it used to.'], barks: ['Letters for everyone!'] },
    { id: 'hale', name: 'Woodcutter Hale', portrait: '🪓', at: 'sunpetal', dx: -330, dy: -260, activity: 'chop', look: look('#8a5a3a', 'cap', { hatColor: '#6b3f2a', beard: true }), lines: ['Only fallen and old trees. The forest gives, I take a little.'], barks: ['Timber!', 'One more log…'] },
    { id: 'bram', name: 'Farmer Bram', portrait: '👨‍🌾', at: 'millbrook', dx: 60, dy: 60, activity: 'farm', look: look('#a0785a', 'straw', { hatColor: '#d9b45a', beard: true }), lines: ['Turnips don’t grow themselves. Well, mine don’t.'], barks: ['Good soil this year.', 'Shoo, gloomlings!'] },
    { id: 'lou', name: 'Fisher Lou', portrait: '🎣', at: 'mirror', dx: -60, activity: 'fish', look: look('#5a8a8a', 'cap', { hatColor: '#3a5a5a', beard: true }), lines: ['Shh. The big one is listening.'], barks: ['Nibble…', 'Quiet, please!'] },
    { id: 'ilse', name: 'Scholar Ilse', portrait: '📚', at: 'city', dx: -170, dy: 120, activity: 'idle', look: look('#6a5a8a', 'bonnet', { hatColor: '#3f3560', hair: '#8a8a8a' }), lines: ['Books remember what people forget.'], barks: ['Where did I leave my spectacles?'] },
    { id: 'brannoc', name: 'Captain Brannoc', portrait: '💂', at: 'city', dx: 200, dy: -140, activity: 'idle', look: look('#8a4a3a', 'helm', { hatColor: '#9aa0aa', beard: true }), lines: ['The walls hold. The roads don’t.'], barks: ['Stay sharp.'] },
    { id: 'tom', name: 'Baker Tom', portrait: '🧑‍🍳', at: 'city', dx: 90, dy: 260, activity: 'sweep', look: look('#e8e2d0', 'cap', { hatColor: '#ffffff' }), lines: ['Honey buns! Still warm!'], barks: ['Fresh bread!'] },
    { id: 'merchant', name: 'Merchant Pell', portrait: '🧪', at: 'city', dx: -120, dy: -130, activity: 'idle', role: 'merchant', look: look('#3f7a6a', 'scarf', { hatColor: '#c9a24c' }), lines: shopLines.merchant, barks: ['Potions! Get your potions!'] },
    { id: 'smith', name: 'Smith Hilda', portrait: '⚒️', at: 'city', dx: 330, dy: 80, activity: 'hammer', role: 'smith', look: look('#6a4a3a', 'cap', { hatColor: '#3a2a24' }), lines: shopLines.smith, barks: ['Clang!'] },
    { id: 'armorer', name: 'Armourer Brisk', portrait: '🛡️', at: 'city', dx: 150, dy: 120, activity: 'idle', role: 'armorer', look: look('#5a4a6a', 'helm', { hatColor: '#b8bcc6' }), lines: shopLines.armorer, barks: ['Only the finest!'] },
    { id: 'inn', name: 'Innkeeper Rosa', portrait: '🛏️', at: 'city', dx: -320, dy: 20, activity: 'idle', role: 'inn', look: look('#b07a5a', 'bonnet', { hatColor: '#e0525c' }), lines: shopLines.inn, barks: ['Rooms free for heroes!'] },
    { id: 'ottilie', name: 'Mayor Ottilie', portrait: '👵', at: 'willow', dx: -90, dy: -30, activity: 'idle', look: look('#b07a9a', 'bonnet', { hatColor: '#8a4f6a', hair: '#e8e2d0' }), lines: ['Welcome to Willowmere. Please wipe your boots.'], barks: ['Order, order!'] },
    { id: 'tilly', name: 'Little Tilly', portrait: '👧', at: 'willow', dx: 120, dy: 120, activity: 'play', look: look('#f2a1b8', 'none', { small: true, hair: '#b8743c' }), lines: ['Wanna play tag? You’re it!'], barks: ['Tag!', 'Hee hee!'] },
    { id: 'garrick', name: 'Hunter Garrick', portrait: '🏹', at: 'camp', dx: 80, dy: 60, activity: 'idle', look: look('#556b3a', 'hood', { hatColor: '#3f4f2a', beard: true }), lines: ['Tracks everywhere. The creatures are bold this season.'], barks: ['Keep your eyes open.'] },
    { id: 'odo', name: 'Old Shepherd Odo', portrait: '🧓', at: 'shepherd', dx: -60, dy: 60, activity: 'wander', look: look('#c9a24c', 'straw', { hatColor: '#a8844a', beard: true, hair: '#e8e2d0' }), lines: ['From this hill you can see the whole valley. Mostly clouds today.'], barks: ['Baa… I mean, hello.'] },
    { id: 'cart', name: 'Trader Bex', portrait: '🧳', at: 'sunpetal', to: 'city', activity: 'travel', look: look('#c07850', 'scarf', { hatColor: '#8a3b2f' }), lines: ['Sunpetal to Goldenhearth and back, every day. Good for the legs.'], barks: ['On the road again!', 'Fine wares, fine prices!'] },
    { id: 'peddler', name: 'Peddler Moss', portrait: '🎒', at: 'city', to: 'willow', activity: 'travel', look: look('#7a8a5a', 'hood', { hatColor: '#4a5a3a', beard: true }), lines: ['Buttons, spoons, and a very small kettle.'], barks: ['Buttons for sale!'] },
  ],
  quests: [
    ...STORY.meadow,
    q({ id: 'glowbugs', title: 'Lanterns for the Night', giver: 'rowan', kind: 'collect', count: 5, near: 'mirror', item: 'Glowbug', icon: 'bug', summary: 'Catch glowbugs around Mirror Lake.', reward: { xp: 110, hearts: 1 },
      text: { offer: ['The night paths are hard to see since the star fell.', 'Could you catch five glowbugs by Mirror Lake? They’ll light our lanterns.'], progress: ['The glowbugs gather by Mirror Lake, south of here.'], complete: ['Five little lights! The lanterns will glow again.', 'Take this heartwood charm. You feel sturdier already.'], after: ['The lanterns hum with glowbugs.'] } }),
    q({ id: 'bell', title: 'Pip’s Silver Bell', giver: 'pip', kind: 'collect', count: 1, near: 'faerie', item: 'Silver bell', icon: 'toy', summary: 'Find Pip’s bell near the Faerie Ring.', reward: { xp: 90, regen: .8 },
      text: { offer: ['I dropped my silver bell while running from a gloomling!', 'Somewhere near the Faerie Ring, far to the south. Please?'], progress: ['The Faerie Ring is far to the south.'], complete: ['My bell! Ding-ding!', 'Have a star biscuit. Your magic will flow faster.'], after: ['Ding! Everyone knows Pip is coming now.'] } }),
    q({ id: 'wheat', title: 'Gloom in the Wheat', giver: 'bram', kind: 'slay', count: 8, enemy: 'gloomling', summary: 'Defeat gloomlings anywhere in the valley.', reward: { xp: 140, mana: 10 },
      text: { offer: ['Gloomlings trample my fields every night!', 'Chase off eight of them and I’ll owe you a turnip pie.'], progress: ['Still counting gloomlings? Keep at it!'], complete: ['The fields are quiet. Here — the pie, and a bit of farm magic.'], after: ['My turnips salute you.'] } }),
    q({ id: 'herbs', title: 'Sunpetal Remedy', giver: 'maren', kind: 'collect', count: 6, near: 'stones', item: 'Sunpetal herb', icon: 'herb', summary: 'Gather sunpetal herbs around the Old Stone Garden.', reward: { xp: 120 },
      text: { offer: ['Half the village has the sniffles.', 'Sunpetal herbs grow around the Old Stone Garden, to the east. Bring me six?'], progress: ['Six herbs, dear. They glow a little in the sun.'], complete: ['Wonderful! I’ll brew the remedy at once.'], after: ['Achoo! …That was the last sneeze, I promise.'] } }),
    q({ id: 'letter', title: 'A Letter to Willowmere', giver: 'wren', kind: 'deliver', count: 1, to: 'ottilie', item: 'Sealed letter', summary: 'Bring Wren’s letter to Mayor Ottilie in Willowmere.', reward: { xp: 100 },
      text: { offer: ['The couriers are too scared to travel since the gloom came.', 'Would you carry this letter to Mayor Ottilie in Willowmere, east of the city?'], progress: ['Willowmere is east of Goldenhearth.'], complete: [], after: ['Letters are moving again.'], deliver: ['A letter from Wren? Finally!', 'Tell her Willowmere still stands. And thank you, Mira.'] } }),
    q({ id: 'toy', title: 'Tilly’s Wooden Fox', giver: 'tilly', kind: 'collect', count: 1, near: 'camp', item: 'Wooden fox', icon: 'toy', summary: 'Find Tilly’s toy near the Hunter’s Camp.', reward: { xp: 80 },
      text: { offer: ['I lost my wooden fox! A big gloomling took it!', 'It ran toward the Hunter’s Camp. South!'], progress: ['My fox has a red painted tail!'], complete: ['FOXY! You found him!', 'You can be the fox in our next game.'], after: ['Foxy says hi to your fox!'] } }),
    q({ id: 'finn', title: 'Tilly’s Brother', giver: 'tilly', kind: 'rescue', count: 1, place: 'faerie', guards: 4, summary: 'Free Finn from the gloomlings at the Faerie Ring.', captive: person('Finn', '👦', { robe: '#6f8fb8', small: true, hair: '#b8743c' }), reward: { xp: 150, hearts: 1 },
      text: { offer: ['My big brother Finn went to the Faerie Ring to find faeries…', 'The gloomlings put him in a cage! Please help him!'], progress: ['Finn is caged at the Faerie Ring, far to the south-west.'], deliver: ['You beat them all?! That was AMAZING.', 'I’m going straight home. Tilly’s going to be so mad at me.'], complete: ['FINN! You’re home!', 'Mira, you’re the best hero ever. That’s official.'], after: ['Finn says faeries are real. He’s wrong. Probably.'] } }),
    q({ id: 'thorns', title: 'Thorns on the Trail', giver: 'garrick', kind: 'slay', count: 6, enemy: 'thornling', summary: 'Defeat thornlings.', reward: { xp: 150, hearts: 1 },
      text: { offer: ['Thornlings are shooting at travellers on the roads.', 'Take down six and the roads will be safe again.'], progress: ['Thornlings stay put and spit thorns. Dash through the gaps.'], complete: ['Six! You hunt like a fox.', 'Wear my old leather vest — it’s turned more thorns than I can count.'], after: ['The trail is quiet.'] } }),
    q({ id: 'view', title: 'Light on the Hill', giver: 'odo', kind: 'visit', count: 1, place: 'shrine', summary: 'Visit the Sun Shrine.', reward: { xp: 100 },
      text: { offer: ['On a clear night I used to see the Sun Shrine glowing from here.', 'Will you walk there and see if it still stands? It’s south, past Willowmere.'], progress: ['The Sun Shrine is south of the hill.'], complete: ['It still stands? Then there is hope for the Beacon too.'], after: ['I can almost see its glow again.'] } }),
    q({ id: 'bait', title: 'Bait for the Big One', giver: 'lou', kind: 'collect', count: 4, near: 'faerie', item: 'Fat mushroom', icon: 'mushroom', summary: 'Pick fat mushrooms around the Faerie Ring.', reward: { xp: 100, mana: 10 },
      text: { offer: ['The big one only bites on faerie mushrooms.', 'Four of them grow near the Faerie Ring, south-east of the lake.'], progress: ['Four mushrooms. Fat ones.'], complete: ['Perfect bait! Here, a lucky fishing charm.'], after: ['Any day now. Any day.'] } }),
    q({ id: 'spores', title: 'Spores in the Flour', giver: 'tom', kind: 'slay', count: 5, enemy: 'sporecap', summary: 'Defeat sporecaps.', reward: { xp: 130 },
      text: { offer: ['Sporecaps! Walking mushrooms! They puff poison into my flour sacks.', 'Knock over five of them. When one swells up — step back!'], progress: ['Sporecaps puff a poison cloud. Don’t stand in it.'], complete: ['My flour is saved! Take a honey bun. Take two.'], after: ['Honey buns for the hero!'] } }),
    q({ id: 'caravan', title: 'The Lost Caravan', giver: 'brannoc', kind: 'rescue', count: 1, place: 'hollow', guards: 5, summary: 'Free Trader Jory from Gloom Hollow.', captive: person('Trader Jory', '🧔', { robe: '#c07850', hat: 'scarf', hatColor: '#8a3b2f', beard: true }), reward: { xp: 160, gold: 80 },
      text: { offer: ['A merchant caravan was ambushed near Gloom Hollow. The trader, Jory, is still missing.', 'Find him, free him, and the city will pay you well.'], progress: ['Gloom Hollow is far to the south-west.'], deliver: ['Oh thank the stars! They took my wagon, my ponies, my good hat…', 'But not my life. I owe you that.'], complete: ['Jory is home. Here’s the reward the merchants promised.'], after: ['The roads need more like you.'] } }),
  ],
  lore: [
    { at: 'stones', name: 'Runestone', text: ['“Here the first beacon-keepers planted their garden of stones, one for every star that watched over them.”'] },
    { at: 'hollow', name: 'Cracked runestone', text: ['“Where light forgets, the gloom remembers. It is not evil — only hungry for warmth.”'] },
    { at: 'faerie', name: 'Mossy runestone', text: ['“Dance in the ring at midnight and the faeries will guide your feet home.”'] },
    { at: 'rise', name: 'Beacon runestone', text: ['“Three lights we lit — the Beacon, the Bell and the Star — and in their glow the Eclipse sleeps.”'] },
    { at: 'shepherd', name: 'Weathered stone', text: ['“From the hill, a shepherd counted sheep and stars. The stars were easier. They did not wander off.”'] },
    { at: 'city', name: 'Founding stone', text: ['“Goldenhearth, raised where every road meets, so that no traveller need ever be alone.”'] },
  ],
  script: {
    keyLabel: 'Sun-crystals', bossName: 'Mossback', bossTitle: 'Ancient Guardian of the Rise', finaleName: 'Meadow Beacon',
    guide: { done: ['The valley is bright again, thanks to you.'] },
    shrine: { bless: ['Warm light pours from the shrine and fills you.', 'The Sun blesses you. (+Experience, full health and magic)'], again: ['The shrine glows warmly. Rest here a while.'] },
    finale: { locked: ['The Beacon is dim. Three sun-crystals are needed before its guardian stirs.'], guarded: ['Mossback is here. Defeat the guardian to restore the Beacon.'], done: ['The crystals blaze in the Beacon and gold light sweeps across the valley.', 'Far to the east, above the dark trees of Whisperroot, an answering light flickers… and dies.', 'On the Rise, a black feather drifts down. Sable was here.'] },
    pickupKey: 'Sun-crystal found! {n}/3',
    sealed: 'Mossback is sealed in stone. Find the three sun-crystals first.', tip: 'If the ground glows, move! Dash makes you untouchable for a heartbeat. Spend gold at the smith in Goldenhearth to grow stronger.',
    victory: { title: 'The Beacon shines again.', text: 'The meadow is safe, but Orrin’s trail leads east. In Whisperroot Woods the Ancient Bell has gone silent — and Sable is already there.' },
  },
};

// ═════════════════════════════ Chapter II · Whisperroot Woods · levels 7–12
const woods: RegionSpec = {
  id: 'woods', chapter: 2, title: 'Whisperroot Woods', subtitle: 'The Bell Beneath the Roots', name: 'Whisperroot Wilds', seed: 72,
  palette: { ground: '#4d6a50', alternate: '#587757', path: '#ad9c72', pathEdge: '#7a7153', accent: '#b6df91', water: '#3f7580', waterDeep: '#2b5560', foliage: ['#1f3a2c', '#355c3e', '#6f9a5c'], trunk: '#553f2d', rock: '#6f7568', pod: '#9fe3c9', roof: ['#5a6e4a', '#7a5a3f', '#4a5a6a', '#6e4a4a'], wall: '#cbb892' },
  darkness: .42, ambient: 'leaves', ground: 'grass', levels: [7, 12], xpScale: 1.25,
  pois: [
    { id: 'gateW', name: 'Western Gate', kind: 'gate', x: 250, y: 3300, r: 240 },
    { id: 'camp', name: 'Mosskeeper’s Camp', kind: 'start', x: 1000, y: 3900, r: 380 },
    { id: 'bellhollow', name: 'Bellhollow', kind: 'village', x: 2300, y: 5300, r: 500 },
    { id: 'shroomfarm', name: 'Glowcap Farm', kind: 'farm', x: 1200, y: 1700, r: 440 },
    { id: 'ruins', name: 'Root Ruins', kind: 'ruins', x: 2900, y: 800, r: 400 },
    { id: 'glade', name: 'Moonlit Glade', kind: 'grove', x: 3300, y: 3200, r: 400 },
    { id: 'city', name: 'Lanternmarket', kind: 'city', x: 5400, y: 3600, r: 900 },
    { id: 'pool', name: 'Blackwater Pool', kind: 'lake', x: 4000, y: 5900, r: 520 },
    { id: 'nest', name: 'Thornling Nest', kind: 'lair', x: 5300, y: 1000, r: 420, pack: ['thornling', 'thornling', 'shadewolf'] },
    { id: 'lodge', name: 'Trapper’s Lodge', kind: 'camp', x: 7200, y: 5700, r: 340 },
    { id: 'watch', name: 'Owl Watchtower', kind: 'lookout', x: 7400, y: 2300, r: 360 },
    { id: 'spring', name: 'Moss Shrine', kind: 'shrine', x: 6600, y: 700, r: 280 },
    { id: 'web', name: 'Silkshadow Hollow', kind: 'lair', x: 8500, y: 4400, r: 420, pack: ['webspinner', 'webspinner', 'shadewolf'] },
    { id: 'bell', name: 'The Old Bell', kind: 'finale', x: 8800, y: 1300, r: 440 },
    { id: 'gateE', name: 'Eastern Gate', kind: 'gate', x: 9480, y: 3300, r: 240 },
  ],
  lakeSize: { pool: 360 },
  links: [['bellhollow', 'city'], ['glade', 'city'], ['watch', 'bell'], ['lodge', 'web'], ['shroomfarm', 'ruins'], ['city', 'gateE'], ['city', 'watch']],
  keyAt: ['shroomfarm', 'nest', 'watch'], keyName: 'Root rune', shrineName: 'Moss Shrine', finaleName: 'Ancient Root Bell',
  trees: [['tree', 7], ['mushroom', 2], ['bush', 2], ['rock', 1]], decorKinds: [['grass', 6], ['fern', 5], ['shroom', 3], ['pebble', 1]], decorColors: ['#9fe3c9', '#f0c47a', '#d6a3f0', '#86d4ff'],
  enemyKinds: [['shadewolf', 4], ['webspinner', 3], ['gloomling', 3], ['thornling', 3], ['sporecap', 2], ['wisp', 1]], boss: 'brambleWarden', bossLevel: 13,
  critters: [['deer', 4], ['rabbit', 3], ['bird', 3], ['frog', 4], ['squirrel', 4], ['duck', 1]],
  villagerNames: ['Moss', 'Tansy', 'Fennick', 'Briar', 'Hazel', 'Oakley', 'Sorrel', 'Wick', 'Ivy', 'Thistle', 'Burr', 'Nettle', 'Rowe', 'Linden', 'Alder', 'Sedge', 'Fern', 'Aspen', 'Bracken', 'Holly', 'Yarrow', 'Wren', 'Clove', 'Mallow'],
  chatter: ['The trees whisper at night. Mostly complaints about the damp.', 'Lanternmarket never sleeps — the lanterns keep it awake.', 'Don’t follow the blue lights into the dark. Trust me.', 'The Old Bell used to ring every dawn. The birds miss it.', 'Glowcaps taste like starlight and socks.', 'The owls at the watchtower see everything. Terrible gossips.', 'Shadewolves never hunt alone. If you see one, there are three.', 'A girl in black walked past my door last night. The lantern went out.', 'Webspinner silk is lovely for scarves. Getting it is less lovely.'],
  barks: ['Mind the roots.', 'Evening… or is it morning?', 'Lantern oil, anyone?', 'Hush, the trees listen.', 'Mossy day, isn’t it?'],
  npcs: [
    { id: 'guide', name: 'Mosskeeper Oda', portrait: '🧝', at: 'camp', dx: -40, dy: -60, activity: 'idle', role: 'guide', look: look('#728f5a', 'hood', { hatColor: '#4a5b3e' }), lines: [], barks: ['The Bell, Mira. The Bell.'] },
    { id: 'nutkin', name: 'Courier Nutkin', portrait: '🐿️', at: 'camp', dx: 170, dy: 40, activity: 'wander', look: look('#a86d49', 'ears', { hatColor: '#80522d', small: true }), lines: ['Pip’s my cousin! We both deliver. I’m faster.'], barks: ['So many roots to trip on!'] },
    { id: 'bellkeeper', name: 'Old Bellkeeper', portrait: '🧓', at: 'bellhollow', dx: -60, dy: 90, activity: 'idle', look: look('#9c7860', 'cap', { hatColor: '#6b4a3a', beard: true, hair: '#e8e2d0' }), lines: ['I polished that bell for sixty years.'], barks: ['Ding… dong…'] },
    { id: 'nana', name: 'Nana Bristle', portrait: '👵', at: 'bellhollow', dx: 150, dy: -40, activity: 'sweep', look: look('#8a6fb0', 'bonnet', { hatColor: '#5b5480', hair: '#e8e2d0' }), lines: ['Sit, eat, you’re too thin for a hero.'], barks: ['Soup’s on!'] },
    { id: 'forester', name: 'Forester Birch', portrait: '🪓', at: 'shroomfarm', dx: 120, dy: -120, activity: 'chop', look: look('#6a5a3a', 'hood', { hatColor: '#4a3a2a', beard: true }), lines: ['Old trees for firewood, young ones left to grow.'], barks: ['Timber!'] },
    { id: 'fenn', name: 'Lamplighter Fenn', portrait: '🏮', at: 'city', dx: -190, dy: -120, activity: 'wander', look: look('#c9a24c', 'hood', { hatColor: '#8a6a30' }), lines: ['A lantern for every path, that’s the rule.'], barks: ['Light the way!'] },
    { id: 'juna', name: 'Herbalist Juna', portrait: '🌿', at: 'city', dx: 170, dy: 150, activity: 'idle', look: look('#5a8a5a', 'scarf', { hatColor: '#3f6a3f' }), lines: ['Every leaf here is medicine. Or poison. Mostly medicine.'], barks: ['Fresh herbs!'] },
    { id: 'thessaly', name: 'Warden Thessaly', portrait: '🛡️', at: 'city', dx: 60, dy: -180, activity: 'idle', look: look('#4a5a6a', 'helm', { hatColor: '#8a8f9a' }), lines: ['The watch never sleeps. I rarely do.'], barks: ['Eyes on the trees.'] },
    { id: 'pim', name: 'Little Pim', portrait: '👦', at: 'city', dx: 120, dy: 300, activity: 'play', look: look('#6f8fb8', 'none', { small: true, hair: '#2e2420' }), lines: ['I’m not scared of the dark! Mostly.'], barks: ['Catch me!'] },
    { id: 'merchant', name: 'Merchant Quill', portrait: '🧪', at: 'city', dx: -120, dy: 140, activity: 'idle', role: 'merchant', look: look('#3f6a7a', 'scarf', { hatColor: '#c9a24c' }), lines: shopLines.merchant, barks: ['Potions and tonics!'] },
    { id: 'smith', name: 'Smith Garron', portrait: '⚒️', at: 'city', dx: 330, dy: -60, activity: 'hammer', role: 'smith', look: look('#5a3a2a', 'cap', { hatColor: '#2a1a14', beard: true }), lines: shopLines.smith, barks: ['Clang! Clang!'] },
    { id: 'armorer', name: 'Armourer Vale', portrait: '🛡️', at: 'city', dx: 200, dy: 40, activity: 'idle', role: 'armorer', look: look('#3f5a4a', 'helm', { hatColor: '#8a9a7a', beard: true }), lines: shopLines.armorer, barks: ['Rootsteel, fresh from the forge!'] },
    { id: 'inn', name: 'Innkeeper Bree', portrait: '🛏️', at: 'city', dx: -330, dy: 40, activity: 'idle', role: 'inn', look: look('#8a6a4a', 'bonnet', { hatColor: '#6f9a5c' }), lines: shopLines.inn, barks: ['Warm soup inside!'] },
    { id: 'ysolde', name: 'Trapper Ysolde', portrait: '🏹', at: 'lodge', dx: 80, dy: 60, activity: 'idle', look: look('#556b3a', 'hood', { hatColor: '#3f4f2a' }), lines: ['Quiet feet catch more than loud ones.'], barks: ['Shh.'] },
    { id: 'ivo', name: 'Scout Ivo', portrait: '💂', at: 'watch', dx: -60, dy: 60, activity: 'patrol', look: look('#6a7a8a', 'helm', { hatColor: '#8a8f9a' }), lines: ['From the tower I see every lantern in the woods.'], barks: ['All clear… for now.'] },
    { id: 'maeve', name: 'Fisher Maeve', portrait: '🎣', at: 'pool', dx: -40, activity: 'fish', look: look('#5a7a8a', 'cap', { hatColor: '#3a4a5a' }), lines: ['Blackwater fish glow. Tasty, too.'], barks: ['Nibble…'] },
    { id: 'trader', name: 'Peddler Gus', portrait: '🧳', at: 'bellhollow', to: 'city', activity: 'travel', look: look('#c07850', 'scarf', { hatColor: '#8a3b2f', beard: true }), lines: ['Pots, pans, and a very small lute.'], barks: ['Wares for sale!'] },
  ],
  quests: [
    ...STORY.woods,
    q({ id: 'moths', title: 'Moths for the Lantern Tree', giver: 'bellkeeper', kind: 'collect', count: 5, near: 'glade', item: 'Moon moth', icon: 'bug', summary: 'Catch moon moths in the Moonlit Glade.', reward: { xp: 120, hearts: 1 },
      text: { offer: ['My moon moths fled to the Moonlit Glade. Without them the lantern tree won’t catch.', 'Five of them, please.'], progress: ['The Moonlit Glade lies north of here.'], complete: ['They’re home! Listen to them hum.', 'Take this bark-woven vest.'], after: ['The lantern tree glows again.'] } }),
    q({ id: 'satchel', title: 'Nutkin’s Satchel', giver: 'nutkin', kind: 'collect', count: 1, near: 'pool', item: 'Courier satchel', icon: 'bundle', summary: 'Find Nutkin’s satchel near Blackwater Pool.', reward: { xp: 100, regen: .8 },
      text: { offer: ['I lost my satchel near Blackwater Pool! Don’t tell Pip.', 'Red strap, very loud buckle.'], progress: ['Blackwater Pool is south-east of here.'], complete: ['My satchel! The acorn cakes survived!', 'Have one — your magic flows faster.'], after: ['Nutkin delivers, always.'] } }),
    q({ id: 'timber', title: 'Clear the Timber Road', giver: 'forester', kind: 'slay', count: 6, enemy: 'thornling', summary: 'Defeat thornlings.', reward: { xp: 130 },
      text: { offer: ['Thornlings shoot at my cart every time I haul logs.', 'Six fewer thornlings would make my week.'], progress: ['Thornlings hide in thick brush.'], complete: ['The road’s clear! My cart thanks you.'], after: ['Timber flows again.'] } }),
    q({ id: 'oil', title: 'Lantern Oil for the Lodge', giver: 'fenn', kind: 'deliver', count: 1, to: 'ysolde', item: 'Lantern oil', summary: 'Bring lantern oil to Trapper Ysolde at the lodge.', reward: { xp: 110 },
      text: { offer: ['Trapper Ysolde’s lodge has gone dark.', 'Carry this oil to her — south-east of the city.'], progress: ['Trapper’s Lodge is south-east.'], complete: [], after: ['Every lantern lit.'], deliver: ['Oil! Fenn remembered me.', 'The lodge will shine tonight. Thank you.'] } }),
    q({ id: 'glowcaps', title: 'Glowcap Stew', giver: 'nana', kind: 'collect', count: 6, near: 'shroomfarm', item: 'Glowcap', icon: 'mushroom', summary: 'Pick glowcaps around Glowcap Farm.', reward: { xp: 130, mana: 12 },
      text: { offer: ['I’m making glowcap stew for the whole village.', 'Six glowcaps from around the farm up north.'], progress: ['Six, dear. The shiny ones.'], complete: ['Now that’s a stew! Have the first bowl.'], after: ['More stew? Always.'] } }),
    q({ id: 'tobbin', title: 'Lost by the Water', giver: 'nana', kind: 'rescue', count: 1, place: 'pool', guards: 5, summary: 'Free Nana’s grandson Tobbin at Blackwater Pool.', captive: person('Tobbin', '🧒', { robe: '#7a9a5a', small: true, hair: '#6b3f2a' }), reward: { xp: 160, hearts: 1 },
      text: { offer: ['My grandson Tobbin went fishing at Blackwater Pool and never came back.', 'Maeve says webspinners wrapped him up! Oh, please hurry!'], progress: ['Blackwater Pool is east of Bellhollow.'], deliver: ['I’m all sticky! Is Nana angry?', 'Tell her I caught a fish first. A big one. Before the spiders.'], complete: ['My Tobbin! Come here, you silly boy.', 'Mira, you’ll eat at my table every night you’re in the woods.'], after: ['Soup’s always warm for you.'] } }),
    q({ id: 'gloomhunt', title: 'Push Back the Gloom', giver: 'ivo', kind: 'slay', count: 10, enemy: 'any', summary: 'Defeat any creatures of the gloom.', reward: { xp: 170, hearts: 1 },
      text: { offer: ['The gloom creeps closer to the watchtower every night.', 'Defeat ten of its creatures and we can breathe again.'], progress: ['Any creature will do. They all serve the gloom.'], complete: ['Ten! The owls are cheering. Probably.', 'Wear this ranger’s cloak.'], after: ['The tower stands strong.'] } }),
    q({ id: 'spring', title: 'The Mossy Spring', giver: 'juna', kind: 'visit', count: 1, place: 'spring', summary: 'Visit the Moss Shrine in the north.', reward: { xp: 120 },
      text: { offer: ['The Moss Shrine’s spring gave the best herbs. Nobody has been there in years.', 'Could you see if it still flows? North of the city, past the nest.'], progress: ['The Moss Shrine is north.'], complete: ['It flows! Then the herbs will return.'], after: ['I can smell spring moss already.'] } }),
    q({ id: 'ball', title: 'Pim’s Lucky Ball', giver: 'pim', kind: 'collect', count: 1, near: 'glade', item: 'Lucky ball', icon: 'toy', summary: 'Find Pim’s ball near the Moonlit Glade.', reward: { xp: 90 },
      text: { offer: ['I kicked my lucky ball really far. Like, glade far.', 'Please find it? I’ll let you kick it once.'], progress: ['It’s blue with a star!'], complete: ['MY BALL! Okay, one kick. Just one.'], after: ['Best. Ball. Ever.'] } }),
    q({ id: 'tess', title: 'The Missing Lamplighter', giver: 'fenn', kind: 'rescue', count: 1, place: 'web', guards: 6, summary: 'Free Lamplighter Tess from Silkshadow Hollow.', captive: person('Lamplighter Tess', '🏮', { robe: '#c9a24c', hat: 'hood', hatColor: '#8a6a30' }), reward: { xp: 180, gold: 90 },
      text: { offer: ['Tess went to light the lanterns near Silkshadow Hollow. Her lantern went out an hour later.', 'Webspinners, Mira. Please bring her back.'], progress: ['Silkshadow Hollow is in the south-east.'], deliver: ['I knew someone would see my lantern flicker!', 'Tell Fenn every lantern on that road is lit. I made sure. Before the spiders.'], complete: ['Tess! Oh, thank the light.', 'The Lamplighters took up a collection for you. Here.'], after: ['A lantern for every path.'] } }),
    q({ id: 'feathers', title: 'Owl Feathers', giver: 'ysolde', kind: 'collect', count: 5, near: 'watch', item: 'Owl feather', icon: 'feather', summary: 'Collect owl feathers around the watchtower.', reward: { xp: 130, mana: 10 },
      text: { offer: ['I fletch arrows with owl feathers — shed ones, of course.', 'Five lie around the Owl Watchtower to the north.'], progress: ['Soft grey feathers. Owls drop them everywhere.'], complete: ['Beautiful. Take an arrow charm.'], after: ['Swift and silent.'] } }),
    q({ id: 'nets', title: 'Silk in the Nets', giver: 'maeve', kind: 'slay', count: 6, enemy: 'webspinner', summary: 'Defeat webspinners.', reward: { xp: 150 },
      text: { offer: ['Webspinners keep stringing silk across my nets. I catch more spiders than fish!', 'Six of them, and I’ll give you my best catch.'], progress: ['Webspinners lurk in the deep woods.'], complete: ['My nets are clean! Here — a glowing fish. Don’t eat it raw.'], after: ['Fish are biting again.'] } }),
    q({ id: 'heartwood', title: 'Heartwood for the Bell', giver: 'forester', kind: 'collect', count: 5, near: 'ruins', item: 'Heartwood', icon: 'bundle', summary: 'Gather heartwood around the Root Ruins.', reward: { xp: 140, gold: 60 },
      text: { offer: ['The Bell’s frame is rotten. Only heartwood from the Root Ruins is strong enough.', 'Five pieces. The roots there shed them like old skin.'], progress: ['Heartwood lies around the Root Ruins.'], complete: ['Good, strong wood. The Bell will hang straight when it rings again.'], after: ['Timber!'] } }),
  ],
  lore: [
    { at: 'ruins', name: 'Root-carved stone', text: ['“The roots were here before the woods. They will be here after. Speak kindly to them.”'] },
    { at: 'glade', name: 'Moonstone', text: ['“Once a year the moon comes down to drink from this glade. Leave it a little water.”'] },
    { at: 'nest', name: 'Scratched stone', text: ['“Thornlings are born from brambles that were never loved. Sing to a bramble, and it may flower instead.”'] },
    { at: 'bell', name: 'Bell-stone', text: ['“The Bramble Warden wears the thorns so the Bell will not. It guards, and it grieves.”'] },
    { at: 'watch', name: 'Tower stone', text: ['“Built by owls, finished by people. The owls still claim credit.”'] },
    { at: 'web', name: 'Charred page', text: ['A torn page in Sable’s hand: “Every night the shadow burns. Umbra whispers that it can stop it. I just have to put the lights out.”'] },
  ],
  script: {
    keyLabel: 'Root runes', bossName: 'Bramble Warden', bossTitle: 'Thorn-Crowned Keeper of Roots', finaleName: 'Ancient Root Bell',
    guide: { done: ['The woods breathe easy again.'] },
    shrine: { bless: ['Moss curls around your arms, cool and bright.', 'The woods bless you. (+Experience, full health and magic)'], again: ['The shrine hums softly.'] },
    finale: { locked: ['Three root runes are needed to wake the guardian.'], guarded: ['The Bramble Warden blocks the Bell.'], done: ['You ring the Ancient Bell. Its voice rolls through every root, and the shadows drift away like petals.', 'At the edge of the clearing stands Sable. “You don’t understand,” she whispers. “Only Umbra can stop the pain.”', 'Then she is gone — east, toward the Summit.'] },
    pickupKey: 'Root rune awakened. {n}/3',
    sealed: 'The Warden is wrapped in sleeping roots. Wake the three runes first.', tip: 'Moss Shield (learned at level 7) reflects thorns. Raise it just as a ring of thorns flies at you!',
    victory: { title: 'The Bell rings through the valley.', text: 'Whisperroot breathes again. But Sable has fled to Starfall Summit, where the hollow star waits — and something inside it is waking.' },
  },
};

// ═════════════════════════════ Chapter III · Starfall Summit · levels 13–18
const summit: RegionSpec = {
  id: 'summit', chapter: 3, title: 'Starfall Summit', subtitle: 'The Hollow Star', name: 'The Silver Heights', seed: 131,
  palette: { ground: '#3e4a6b', alternate: '#46527a', path: '#8f93b8', pathEdge: '#62678c', accent: '#c9b6ff', water: '#5a6fc0', waterDeep: '#34408a', foliage: ['#1c2b45', '#2e4a63', '#6a93a8'], trunk: '#3c3346', rock: '#6f7493', pod: '#c9b6ff', roof: ['#5a5f8a', '#6e5a8a', '#4a6a8a', '#7a6a9a'], wall: '#c8cce0' },
  darkness: .6, ambient: 'stars', ground: 'snow', levels: [13, 18], xpScale: 2.4,
  pois: [
    { id: 'gateW', name: 'Western Gate', kind: 'gate', x: 250, y: 3300, r: 240 },
    { id: 'lookout', name: 'Warden’s Lookout', kind: 'start', x: 1000, y: 3000, r: 380 },
    { id: 'hamlet', name: 'Frostpine Hamlet', kind: 'village', x: 2300, y: 4400, r: 500 },
    { id: 'observatory', name: 'Old Observatory', kind: 'lookout', x: 1300, y: 5900, r: 380 },
    { id: 'crystal', name: 'Crystal Hollow', kind: 'ruins', x: 1300, y: 1200, r: 400 },
    { id: 'tarn', name: 'Mirrorsky Tarn', kind: 'lake', x: 3600, y: 2400, r: 540 },
    { id: 'bloom', name: 'Starbloom Grove', kind: 'grove', x: 3400, y: 600, r: 380 },
    { id: 'city', name: 'Skyhold', kind: 'city', x: 5400, y: 4200, r: 900 },
    { id: 'terrace', name: 'Goatherd’s Terrace', kind: 'farm', x: 3700, y: 6000, r: 440 },
    { id: 'pass', name: 'Silver Pass Camp', kind: 'camp', x: 5800, y: 1600, r: 340 },
    { id: 'frostfang', name: 'Frostfang Crag', kind: 'lair', x: 6700, y: 2700, r: 420, pack: ['cragGolem', 'frostwraith', 'frostwraith'] },
    { id: 'rift', name: 'Void Rift', kind: 'lair', x: 7600, y: 5900, r: 430, pack: ['wisp', 'frostwraith', 'wisp'] },
    { id: 'altar', name: 'Star Altar', kind: 'shrine', x: 7400, y: 4200, r: 280 },
    { id: 'spire', name: 'Broken Spire', kind: 'ruins', x: 7800, y: 1300, r: 400 },
    { id: 'cradle', name: 'The Star Cradle', kind: 'finale', x: 8800, y: 1900, r: 480 },
    { id: 'gateE', name: 'Eastern Gate', kind: 'gate', x: 9480, y: 3300, r: 240 },
  ],
  lakeSize: { tarn: 380 },
  links: [['hamlet', 'tarn'], ['terrace', 'city'], ['pass', 'spire'], ['city', 'altar'], ['crystal', 'bloom'], ['altar', 'cradle'], ['city', 'frostfang'], ['altar', 'gateE']],
  keyAt: ['crystal', 'frostfang', 'spire'], keyName: 'Star shard', shrineName: 'Star Altar', finaleName: 'Star Cradle',
  trees: [['pine', 7], ['crystal', 2], ['rock', 3]], decorKinds: [['grass', 4], ['shard', 3], ['pebble', 2], ['flower', 2]], decorColors: ['#c9b6ff', '#8ee8ff', '#ffffff', '#ffd6f5'],
  enemyKinds: [['wisp', 4], ['frostwraith', 4], ['cragGolem', 2], ['shadewolf', 2], ['thornling', 1]], boss: 'hollowStar', bossLevel: 19,
  critters: [['goat', 6], ['bird', 3], ['rabbit', 3], ['duck', 1]],
  villagerNames: ['Frost', 'Astra', 'Corin', 'Vesper', 'Lumi', 'Soren', 'Nyx', 'Halden', 'Skye', 'Elna', 'Birk', 'Selka', 'Tarn', 'Isolde', 'Rune', 'Kestrel', 'Sölve', 'Brisa', 'Eira', 'Haldor', 'Tove'],
  chatter: ['Up here the stars are close enough to hear.', 'Skyhold’s monks haven’t slept since the star went hollow.', 'Goats are the only ones who like this wind.', 'If the void wisps sing, don’t sing back.', 'The observatory lens once saw a comet sneeze.', 'Crag golems are just rocks that got angry. Very, very angry.', 'The Cradle glows black at night now. Nobody goes near it.', 'I heard the old wizard from the Rift is in the infirmary. Lucky man.'],
  barks: ['Brr!', 'Mind the ice.', 'Clear skies tonight.', 'The star is so dark…', 'Stay warm!'],
  npcs: [
    { id: 'guide', name: 'Sky-warden Ilsa', portrait: '🧝‍♀️', at: 'lookout', dx: -40, dy: -60, activity: 'idle', role: 'guide', look: look('#6c78b8', 'hood', { hatColor: '#3f4a8a' }), lines: [], barks: ['The Cradle waits.'] },
    { id: 'bramble', name: 'Courier Bramble', portrait: '🐿️', at: 'lookout', dx: 170, dy: 40, activity: 'wander', look: look('#8a7a9a', 'ears', { hatColor: '#6a5a7a', small: true }), lines: ['Pip, Nutkin and me — the three fastest couriers in the valley!'], barks: ['Brrr!'] },
    { id: 'vale', name: 'Astronomer Vale', portrait: '🔭', at: 'observatory', dx: -60, dy: 60, activity: 'idle', look: look('#8a6fb0', 'wizard', { hatColor: '#5b5480', beard: true, hair: '#8a8a8a' }), lines: ['The sky is a map, if you know how to read it.'], barks: ['Fascinating…'] },
    { id: 'brun', name: 'Goatherd Brun', portrait: '🐐', at: 'terrace', dx: 60, dy: 60, activity: 'farm', look: look('#a0785a', 'scarf', { hatColor: '#8a3b2f', beard: true }), lines: ['My goats climb higher than any hero.'], barks: ['Come back, Bramble!'] },
    { id: 'aune', name: 'Healer Aune', portrait: '👩‍⚕️', at: 'hamlet', dx: 150, dy: -40, activity: 'idle', look: look('#7a9aba', 'bonnet', { hatColor: '#e8e2d0' }), lines: ['Frostbite, starburn, heartache — I treat them all.'], barks: ['Keep your hands warm!'] },
    { id: 'kiri', name: 'Little Kiri', portrait: '👧', at: 'hamlet', dx: 120, dy: 200, activity: 'play', look: look('#8ee8ff', 'none', { small: true, hair: '#d9c08a' }), lines: ['Snowball fight! You can’t dodge forever!'], barks: ['Snowball!'] },
    { id: 'toma', name: 'Logger Toma', portrait: '🪓', at: 'hamlet', dx: -330, dy: -260, activity: 'chop', look: look('#5a4a6a', 'cap', { hatColor: '#3a2a4a', beard: true }), lines: ['Frostpine burns bright. Worth the climb.'], barks: ['Timber!'] },
    { id: 'ren', name: 'Pilgrim Ren', portrait: '🧳', at: 'hamlet', to: 'observatory', activity: 'travel', look: look('#b07a9a', 'scarf', { hatColor: '#8a4f6a' }), lines: ['I walk to the observatory and back, every day, for luck.'], barks: ['One more step…'] },
    { id: 'corvin', name: 'Abbot Corvin', portrait: '🧙', at: 'city', dx: -60, dy: -200, activity: 'idle', look: look('#e8e2d0', 'hood', { hatColor: '#c9a24c', beard: true, hair: '#e8e2d0' }), lines: ['Skyhold has stood a thousand winters. It will stand one more.'], barks: ['Blessings.'] },
    { id: 'sella', name: 'Monk Sella', portrait: '🧘', at: 'city', dx: 200, dy: 150, activity: 'sweep', look: look('#c9a24c', 'hood', { hatColor: '#a8844a' }), lines: ['We pray for the star every hour.'], barks: ['Peace be with you.'] },
    { id: 'orrin', name: 'Master Orrin', portrait: '🧙‍♂️', at: 'city', dx: -260, dy: 200, activity: 'idle', after: 'm10', look: look('#5b5480', 'wizard', { hatColor: '#3f3a70', beard: true, hair: '#e8e2d0' }), lines: ['I have much to make right, Mira.'], barks: ['My brave girl.'] },
    { id: 'orla', name: 'Tinker Orla', portrait: '🔧', at: 'city', dx: 380, dy: 180, activity: 'hammer', look: look('#6a4a3a', 'cap', { hatColor: '#3a2a24' }), lines: ['Starsilver sings when you strike it.'], barks: ['Tink tink!'] },
    { id: 'merchant', name: 'Merchant Sol', portrait: '🧪', at: 'city', dx: -120, dy: 140, activity: 'idle', role: 'merchant', look: look('#4a4a8a', 'scarf', { hatColor: '#c9a24c' }), lines: shopLines.merchant, barks: ['Warming tonics!'] },
    { id: 'smith', name: 'Master-smith Ingrid', portrait: '⚒️', at: 'city', dx: 340, dy: -80, activity: 'hammer', role: 'smith', look: look('#5a4a5a', 'cap', { hatColor: '#2a2a3a' }), lines: shopLines.smith, barks: ['Starsteel!'] },
    { id: 'armorer', name: 'Armourer Sigrun', portrait: '🛡️', at: 'city', dx: 160, dy: -150, activity: 'idle', role: 'armorer', look: look('#4a4a7a', 'helm', { hatColor: '#c9cfe8' }), lines: shopLines.armorer, barks: ['Starsilver, for those who can pay.'] },
    { id: 'inn', name: 'Innkeeper Mott', portrait: '🛏️', at: 'city', dx: -340, dy: -40, activity: 'idle', role: 'inn', look: look('#7a6a9a', 'hood', { hatColor: '#5a4a7a', beard: true }), lines: shopLines.inn, barks: ['Hot cocoa by the fire!'] },
    { id: 'dov', name: 'Quartermaster Dov', portrait: '💂', at: 'pass', dx: 80, dy: 60, activity: 'patrol', look: look('#6a7a8a', 'helm', { hatColor: '#8a8f9a', beard: true }), lines: ['Nobody crosses the pass without my say-so. Except wisps. They don’t ask.'], barks: ['Halt! Oh, it’s you.'] },
    { id: 'sable', name: 'Sable', portrait: '🌑', at: 'spire', dx: -120, dy: 90, activity: 'idle', after: 'm15', look: look('#2a2438', 'hood', { hatColor: '#1a1428', hair: '#1a1a24' }), lines: ['I remember lighting lanterns with him. Before the shadow hurt.'], barks: ['…'] },
  ],
  quests: [
    ...STORY.summit,
    q({ id: 'wisps', title: 'Wisps for the Telescope', giver: 'vale', kind: 'collect', count: 5, near: 'tarn', item: 'Star wisp', icon: 'bug', summary: 'Catch star wisps around Mirrorsky Tarn.', reward: { xp: 110, hearts: 1 },
      text: { offer: ['Five star wisps escaped my telescope. They drift around Mirrorsky Tarn.', 'Without them I cannot chart the sky.'], progress: ['Glittering little things, by the tarn.'], complete: ['Wonderful! The constellations make sense again.', 'Wear this starsilver cloak.'], after: ['The stars align nicely tonight.'] } }),
    q({ id: 'lens', title: 'Bramble’s Brass Lens', giver: 'bramble', kind: 'collect', count: 1, near: 'crystal', item: 'Brass lens', icon: 'gem', summary: 'Find Bramble’s lens in Crystal Hollow.', reward: { xp: 100, regen: .8 },
      text: { offer: ['I climbed all this way and dropped my brass lens!', 'It rolled toward Crystal Hollow, to the north.'], progress: ['Crystal Hollow is north.'], complete: ['My lens! Now I can see the whole valley!', 'Last biscuit, just for you.'], after: ['Everything looks so tiny from up here.'] } }),
    q({ id: 'herd', title: 'Wisps in the Herd', giver: 'brun', kind: 'slay', count: 8, enemy: 'wisp', summary: 'Defeat void wisps.', reward: { xp: 130 },
      text: { offer: ['Void wisps spook my goats right off the cliffs!', 'Eight of them, and the herd can graze in peace.'], progress: ['Wisps dart side to side. Spark finds them for you.'], complete: ['The goats are grazing again! Have some goat cheese. It’s… strong.'], after: ['Maaa!'] } }),
    q({ id: 'sunniva', title: 'Lost on the Crag', giver: 'brun', kind: 'rescue', count: 1, place: 'frostfang', guards: 5, summary: 'Free herd-girl Sunniva on Frostfang Crag.', captive: person('Sunniva', '👧', { robe: '#a0785a', small: true, hair: '#d9c08a', hat: 'scarf', hatColor: '#8a3b2f' }), reward: { xp: 150, hearts: 1 },
      text: { offer: ['My daughter Sunniva chased a lost kid up Frostfang Crag.', 'The golems have her boxed in! Please, Mira!'], progress: ['Frostfang Crag is north-east of Skyhold.'], deliver: ['I found the baby goat! Then the rocks stood up…', 'Thank you, thank you! I’m never climbing anything ever again. Probably.'], complete: ['Sunniva! My girl!', 'Mira, the whole herd is yours to ride. Well — the nice ones.'], after: ['Maaa!'] } }),
    q({ id: 'scroll', title: 'A Prayer for the Pass', giver: 'sella', kind: 'deliver', count: 1, to: 'dov', item: 'Prayer scroll', summary: 'Bring Sella’s prayer scroll to Quartermaster Dov.', reward: { xp: 110 },
      text: { offer: ['The guards at Silver Pass have lost hope.', 'Please bring this prayer scroll to Quartermaster Dov.'], progress: ['Silver Pass Camp is north of the city.'], complete: [], after: ['May the star return.'], deliver: ['A prayer from Skyhold? Hm. It does help, actually.', 'Thank you, Mira.'] } }),
    q({ id: 'frostbloom', title: 'Frostbloom Tonic', giver: 'aune', kind: 'collect', count: 6, near: 'bloom', item: 'Frostbloom', icon: 'flower', summary: 'Pick frostbloom in the Starbloom Grove.', reward: { xp: 130, mana: 14 },
      text: { offer: ['Frostblooms make the best tonic against the cold.', 'Six from the Starbloom Grove, far north.'], progress: ['They sparkle like frost on petals.'], complete: ['A tonic fit for a hero.'], after: ['Warm hands, warm heart.'] } }),
    q({ id: 'wall', title: 'Wraiths at the Wall', giver: 'dov', kind: 'slay', count: 6, enemy: 'frostwraith', summary: 'Defeat frost wraiths.', reward: { xp: 160, hearts: 1 },
      text: { offer: ['Frost wraiths drift over the wall every night and freeze my guards solid.', 'Six of them, please.'], progress: ['Wraiths blink close, then throw ice. Keep moving.'], complete: ['Six! You fight like a whole squad.', 'Take my old starsilver guard.'], after: ['The wall holds.'] } }),
    q({ id: 'altar', title: 'The Pilgrim’s Path', giver: 'ren', kind: 'visit', count: 1, place: 'altar', summary: 'Visit the Star Altar in the east.', reward: { xp: 120 },
      text: { offer: ['I’ve walked to the observatory a thousand times, but never to the Star Altar.', 'Would you go for me? Tell me if it still shines.'], progress: ['The Star Altar lies east of Skyhold.'], complete: ['It shines? Then I will walk there tomorrow.'], after: ['One more step, and another.'] } }),
    q({ id: 'kite', title: 'Kiri’s Star Kite', giver: 'kiri', kind: 'collect', count: 1, near: 'terrace', item: 'Star kite', icon: 'toy', summary: 'Find Kiri’s kite near the Goatherd’s Terrace.', reward: { xp: 100 },
      text: { offer: ['The wind stole my star kite!', 'It flew toward the goats. They might be eating it!'], progress: ['It has a long sparkly tail!'], complete: ['My kite! Only a little goat-nibbled!'], after: ['Wheee!'] } }),
    q({ id: 'astrid', title: 'Kiri’s Big Sister', giver: 'kiri', kind: 'rescue', count: 1, place: 'crystal', guards: 5, summary: 'Free Astrid in Crystal Hollow.', captive: person('Astrid', '👩', { robe: '#8ee8ff', hair: '#d9c08a', hat: 'bonnet', hatColor: '#6c78b8' }), reward: { xp: 160, gold: 100 },
      text: { offer: ['My sister Astrid went crystal hunting in Crystal Hollow.', 'Now the wisps have her in a cage made of ice! Help!'], progress: ['Crystal Hollow is far to the north-west.'], deliver: ['The wisps sang to me all night. Horrible songs. No rhythm at all.', 'Tell Kiri I’m coming. And that I’m bringing crystals.'], complete: ['ASTRID! You’re back!', 'She says you can have her crystal money. I say you can have mine too!'], after: ['Snowball fight later?'] } }),
    q({ id: 'chips', title: 'Starsilver Chips', giver: 'orla', kind: 'collect', count: 5, near: 'spire', item: 'Crystal chip', icon: 'gem', summary: 'Gather crystal chips around the Broken Spire.', reward: { xp: 140, mana: 12 },
      text: { offer: ['Starsilver needs crystal chips from the Broken Spire.', 'Five should do. Watch for wisps up there.'], progress: ['They glow violet. Hard to miss.'], complete: ['Perfect chips! I forged you a charm.'], after: ['Tink! That’s the sound of progress.'] } }),
    q({ id: 'rockslide', title: 'Rockslide Road', giver: 'toma', kind: 'slay', count: 4, enemy: 'cragGolem', summary: 'Break crag golems blocking the roads.', reward: { xp: 170, gold: 80 },
      text: { offer: ['Crag golems keep sitting down in the middle of my logging road. Then they don’t get up.', 'Break four. I’ll pay in good silver.'], progress: ['Golems roam the heights around Skyhold.'], complete: ['The road’s open! Here’s your silver, as promised.'], after: ['Timber rolls again.'] } }),
    q({ id: 'polish', title: 'Lens Polish', giver: 'vale', kind: 'collect', count: 4, near: 'frostfang', item: 'Frost crystal', icon: 'gem', summary: 'Gather frost crystals on Frostfang Crag.', reward: { xp: 140, mana: 10 },
      text: { offer: ['Frost crystals make the finest lens polish in the world.', 'Four from Frostfang Crag. Mind the golems.'], progress: ['Frostfang Crag is north-east of Skyhold.'], complete: ['Oh, look how the lens gleams! I can see the rings of the moon.'], after: ['Clear skies.'] } }),
  ],
  lore: [
    { at: 'crystal', name: 'Crystal tablet', text: ['“The crystals grow where starlight pools. Each hums the note of the star that made it.”'] },
    { at: 'bloom', name: 'Frosted stone', text: ['“Starblooms open only when someone is watching the sky. Nobody knows who watches the flowers.”'] },
    { at: 'spire', name: 'Spire fragment', text: ['“The spire once reached the star. It fell with it, and still points the way.”'] },
    { at: 'cradle', name: 'Cradle-stone', text: ['“Every star is a heart. A hollow heart can be filled again — with light, with shards, with courage.”'] },
    { at: 'observatory', name: 'Brass plaque', text: ['“Observatory of the Silver Heights. Please do not feed the comets.”'] },
    { at: 'rift', name: 'Scorched slate', text: ['Scratched into the stone in Orrin’s hand: “Umbra is not in her. It never was. It is in the star. Forgive me, Sable.”'] },
  ],
  script: {
    keyLabel: 'Star shards', bossName: 'The Hollow Star', bossTitle: 'Heart of the Fallen Light', finaleName: 'Star Cradle',
    guide: { done: ['The sky is whole again.'] },
    shrine: { bless: ['The altar opens to the sky. A star answers your call.', 'The stars bless you. (+Experience, full health and magic)'], again: ['The altar glitters like a tiny night sky.'] },
    finale: { locked: ['The Cradle is cold. Three star shards are needed.'], guarded: ['A shadow circles the Cradle. Defeat it!'], done: ['You lay the three shards into the Cradle. The star remembers its light and rises, whole, into the sky.', 'Beside you, Sable’s shadow is gone — or maybe it was never the enemy. Orrin holds her like he is afraid to let go.', 'But as the star climbs, a thread of black smoke tears loose from the broken shell and streaks east, over the last ridge, toward the Ember Wastes. Umbra is not finished.'] },
    pickupKey: 'Star shard gathered. {n}/3',
    sealed: 'The Hollow Star hides behind a void shell. Gather three star shards first.', tip: 'When stars fall on you, dash out of their circles. Starfall turns the sky on your enemies.',
    victory: { title: 'The star rises home.', text: 'The star is whole again. Sable is free and Orrin is forgiven — but Umbra slipped out of the broken shell and fled east, into the Ember Wastes.' },
  },
};

// ═════════════════════════════ Chapter IV · The Ember Wastes · levels 19–24
const ember: RegionSpec = {
  id: 'ember', chapter: 4, title: 'The Ember Wastes', subtitle: 'The Dawn Forge', name: 'The Ember Wastes', seed: 211,
  palette: { ground: '#6e4a3a', alternate: '#7c5442', path: '#c9a26e', pathEdge: '#8a6a48', accent: '#ff9a3d', water: '#e2592a', waterDeep: '#a3301a', foliage: ['#2e2220', '#4f3428', '#8f5a34'], trunk: '#2a1e1a', rock: '#5e4c4a', pod: '#ffb347', roof: ['#9a4a2a', '#6a4a3a', '#b0642a', '#5a3a3a'], wall: '#dcc4a2' },
  darkness: .38, ambient: 'embers', ground: 'ash', levels: [19, 24], xpScale: 4,
  pois: [
    { id: 'gateW', name: 'Western Gate', kind: 'gate', x: 250, y: 3300, r: 240 },
    { id: 'camp', name: 'Emberwatch Outpost', kind: 'start', x: 1000, y: 2700, r: 380 },
    { id: 'kiln', name: 'Kilnhollow', kind: 'village', x: 2400, y: 4300, r: 500 },
    { id: 'farm', name: 'Saltglass Farm', kind: 'farm', x: 1200, y: 5600, r: 440 },
    { id: 'obsidian', name: 'Obsidian Maze', kind: 'ruins', x: 1500, y: 1100, r: 400 },
    { id: 'mere', name: 'The Molten Mere', kind: 'lake', x: 3500, y: 2100, r: 540 },
    { id: 'city', name: 'Brasshaven', kind: 'city', x: 5100, y: 3900, r: 900 },
    { id: 'nest', name: 'Scorpion Burrows', kind: 'lair', x: 3700, y: 6000, r: 430, pack: ['ashScorpion', 'ashScorpion', 'emberImp'] },
    { id: 'watch', name: 'Ashfall Watch', kind: 'lookout', x: 5300, y: 900, r: 360 },
    { id: 'green', name: 'The Last Green', kind: 'grove', x: 7000, y: 700, r: 380 },
    { id: 'caravan', name: 'Salt Caravan Camp', kind: 'camp', x: 7000, y: 5900, r: 340 },
    { id: 'foundry', name: 'Old Foundry', kind: 'lair', x: 7300, y: 2800, r: 430, pack: ['magmaHulk', 'emberImp', 'emberImp'] },
    { id: 'spring', name: 'Phoenix Spring', kind: 'shrine', x: 8200, y: 4500, r: 280 },
    { id: 'forge', name: 'The Dawn Forge', kind: 'finale', x: 8800, y: 1700, r: 480 },
  ],
  lakeSize: { mere: 380 },
  links: [['kiln', 'city'], ['city', 'caravan'], ['city', 'foundry'], ['mere', 'watch'], ['obsidian', 'mere'], ['foundry', 'forge'], ['spring', 'caravan'], ['city', 'spring']],
  keyAt: ['obsidian', 'nest', 'foundry'], keyName: 'Ember core', shrineName: 'Phoenix Spring', finaleName: 'Dawn Forge',
  trees: [['deadtree', 5], ['rock', 4], ['crystal', 1]], decorKinds: [['pebble', 5], ['grass', 3], ['shard', 2], ['flower', 1]], decorColors: ['#ff9a3d', '#ffd27a', '#ff5f3d', '#c9a26e'],
  enemyKinds: [['emberImp', 4], ['ashScorpion', 4], ['magmaHulk', 2], ['shadewolf', 1], ['wisp', 1]], boss: 'cinderTyrant', bossLevel: 25,
  critters: [['bird', 4], ['rabbit', 3], ['goat', 2], ['frog', 1]],
  villagerNames: ['Ash', 'Brenna', 'Cinder', 'Dax', 'Emberly', 'Faro', 'Garnet', 'Hale', 'Ione', 'Jasper', 'Kilna', 'Loam', 'Marl', 'Nell', 'Onyx', 'Pyra', 'Quill', 'Rust', 'Sienna', 'Tinder', 'Umber', 'Vesta', 'Wren'],
  chatter: ['The wind here tastes of salt and smoke.', 'Brasshaven’s bells are made from melted-down swords. Peace, they say, sounds better.', 'When the sand bulges, run. That’s all anyone needs to know about scorpions.', 'The Dawn Forge lit the sunrise for a thousand years. Now the mornings come up grey.', 'Glass from Kilnhollow sells for gold in every city of the valley.', 'I once saw a phoenix drink from the spring. Or a very orange chicken.', 'Magma hulks are just rocks that got too hot to be calm.', 'The Tyrant used to be the Forge’s keeper. Then he fell in love with the fire.'],
  barks: ['Hot one today.', 'Mind the lava.', 'Water, anyone?', 'Salt for sale!', 'The dawn is late again…'],
  npcs: [
    { id: 'guide', name: 'Captain Ashka', portrait: '💂‍♀️', at: 'camp', dx: -40, dy: -60, activity: 'idle', role: 'guide', look: look('#8a4a3a', 'helm', { hatColor: '#6a6a70', hair: '#2e2420' }), lines: [], barks: ['Over here, traveller!', 'The forge is cold.'] },
    { id: 'soot', name: 'Courier Soot', portrait: '🐿️', at: 'camp', dx: 170, dy: 40, activity: 'wander', look: look('#5a4a48', 'ears', { hatColor: '#3a2a26', small: true }), lines: ['Pip, Nutkin, Bramble and me. I’m the one who doesn’t burn.'], barks: ['Hot paws, hot paws!'] },
    { id: 'hessa', name: 'Kiln-mother Hessa', portrait: '👵', at: 'kiln', dx: -60, dy: 90, activity: 'idle', look: look('#b0643a', 'bonnet', { hatColor: '#6a3a2a', hair: '#e8e2d0' }), lines: ['Glass is only sand that was brave enough to walk through fire.'], barks: ['The kilns never sleep.'] },
    { id: 'tam', name: 'Little Tam', portrait: '👦', at: 'kiln', dx: 140, dy: 160, activity: 'play', look: look('#c9a24c', 'none', { small: true, hair: '#4a2f24' }), lines: ['I’m going to be a glassblower. Or a dragon.'], barks: ['Roar!'] },
    { id: 'fenwick', name: 'Saltfarmer Fenwick', portrait: '👨‍🌾', at: 'farm', dx: 60, dy: 60, activity: 'farm', look: look('#d8c8a8', 'straw', { hatColor: '#e8d8a8', beard: true }), lines: ['Salt doesn’t grow, it just waits for you.'], barks: ['Shoo, scorpions!'] },
    { id: 'tovan', name: 'Forgemaster Tovan', portrait: '🧔', at: 'city', dx: 300, dy: 120, activity: 'hammer', look: look('#5a3a2a', 'cap', { hatColor: '#2a1a14', beard: true }), lines: ['Iron remembers every blow. So do I.'], barks: ['Clang! Clang!'] },
    { id: 'rusk', name: 'Captain Rusk', portrait: '💂', at: 'city', dx: 200, dy: -160, activity: 'idle', look: look('#8a5a3a', 'helm', { hatColor: '#b0643a', beard: true }), lines: ['Brasshaven has never fallen. I don’t plan to start.'], barks: ['Eyes on the dunes.'] },
    { id: 'merchant', name: 'Merchant Zafir', portrait: '🧪', at: 'city', dx: -120, dy: 140, activity: 'idle', role: 'merchant', look: look('#3f6a7a', 'scarf', { hatColor: '#c9a24c' }), lines: shopLines.merchant, barks: ['Cooling tonics!'] },
    { id: 'smith', name: 'Smith Brona', portrait: '⚒️', at: 'city', dx: 340, dy: -60, activity: 'hammer', role: 'smith', look: look('#6a4a3a', 'cap', { hatColor: '#3a2a24' }), lines: shopLines.smith, barks: ['Firesteel!'] },
    { id: 'armorer', name: 'Armourer Kess', portrait: '🛡️', at: 'city', dx: 160, dy: -250, activity: 'idle', role: 'armorer', look: look('#4a3a3a', 'helm', { hatColor: '#8a5a3a' }), lines: shopLines.armorer, barks: ['Obsidian plate, fresh from the forge!'] },
    { id: 'inn', name: 'Innkeeper Dusk', portrait: '🛏️', at: 'city', dx: -330, dy: -40, activity: 'idle', role: 'inn', look: look('#7a5a4a', 'hood', { hatColor: '#5a3a2a' }), lines: shopLines.inn, barks: ['Cool rooms, cold drinks!'] },
    { id: 'seer', name: 'Ember-seer Ilyana', portrait: '🔮', at: 'watch', dx: -60, dy: 60, activity: 'idle', look: look('#8a3a5a', 'hood', { hatColor: '#5a2a3a', hair: '#e8e2d0' }), lines: ['The flames show me the future. Mostly they show me more flames.'], barks: ['I saw you coming.'] },
    { id: 'zara', name: 'Hunter Zara', portrait: '🏹', at: 'caravan', dx: 80, dy: 60, activity: 'idle', look: look('#8a6a4a', 'hood', { hatColor: '#5a4a2a' }), lines: ['In the wastes, the hunter who drinks most wins.'], barks: ['Quiet feet.'] },
    { id: 'omar', name: 'Salt-trader Omar', portrait: '🧳', at: 'kiln', to: 'city', activity: 'travel', look: look('#c07850', 'scarf', { hatColor: '#8a3b2f', beard: true }), lines: ['Salt to the city, glass to the kiln, gossip everywhere.'], barks: ['Salt! Fine salt!'] },
  ],
  quests: [
    ...STORY.ember,
    q({ id: 'stingers', title: 'Stingers in the Kiln', giver: 'hessa', kind: 'slay', count: 8, enemy: 'ashScorpion', summary: 'Defeat ash scorpions.', reward: { xp: 160, hearts: 1 },
      text: { offer: ['Scorpions dig into my kilns at night for the warmth. Then they sting my glassblowers.', 'Eight of them, please.'], progress: ['Scorpions burrow. Watch the sand for moving mounds.'], complete: ['Eight! My glassblowers can work in peace.', 'Take this — kiln-hardened leather.'], after: ['The kilns hum happily.'] } }),
    q({ id: 'marble', title: 'Tam’s Glass Marble', giver: 'tam', kind: 'collect', count: 1, near: 'mere', item: 'Glass marble', icon: 'gem', summary: 'Find Tam’s marble near the Molten Mere.', reward: { xp: 120 },
      text: { offer: ['I made my first marble and it rolled all the way to the Molten Mere!', 'It’s blue inside. Like water. Please?'], progress: ['It’s near the lava lake, north of here!'], complete: ['My marble! It didn’t even melt!'], after: ['Want to see it catch the light?'] } }),
    q({ id: 'bellows', title: 'Imps in the Bellows', giver: 'tovan', kind: 'slay', count: 8, enemy: 'emberImp', summary: 'Defeat ember imps.', reward: { xp: 170 },
      text: { offer: ['Imps nest in the city bellows and blow my forge fires every which way.', 'Eight fewer imps, and I’ll owe you.'], progress: ['Imps hover out of reach. Close in fast.'], complete: ['My fires burn straight again. Well done.'], after: ['Clang!'] } }),
    q({ id: 'water', title: 'Water for the Watch', giver: 'guide', kind: 'deliver', count: 1, to: 'seer', item: 'Waterskins', summary: 'Bring waterskins to Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 140 },
      text: { offer: ['Ilyana at Ashfall Watch hasn’t had fresh water in days. She won’t leave her flames.', 'Carry these waterskins to her — north, past the Molten Mere.'], progress: ['Ashfall Watch is far to the north-east.'], complete: [], after: ['Water is worth more than gold out here.'], deliver: ['Water! You are kinder than the flames told me.', 'Sit, sit. The fire is friendlier when you are not thirsty.'] } }),
    q({ id: 'lastgreen', title: 'The Last Green', giver: 'seer', kind: 'visit', count: 1, place: 'green', summary: 'Find The Last Green in the far north.', reward: { xp: 150 },
      text: { offer: ['Somewhere in the north, one grove still grows. The Last Green, the old songs call it.', 'Go and see if it lives.'], progress: ['The Last Green is north-east of the watch.'], complete: ['It lives? Then the wastes can bloom again, once the dawn returns.'], after: ['Green and gold, green and gold.'] } }),
    q({ id: 'shards', title: 'Obsidian for the Anvil', giver: 'tovan', kind: 'collect', count: 5, near: 'obsidian', item: 'Obsidian shard', icon: 'gem', summary: 'Gather obsidian shards in the Obsidian Maze.', reward: { xp: 170, gold: 120 },
      text: { offer: ['Obsidian makes the sharpest edge a smith can forge.', 'Five shards from the Maze, and I’ll pay well.'], progress: ['The Obsidian Maze is far to the north-west.'], complete: ['Beautiful black glass. Here’s your gold, as promised.'], after: ['Sharp as the day it cooled.'] } }),
    q({ id: 'ria', title: 'The Kiln-girl', giver: 'hessa', kind: 'rescue', count: 1, place: 'mere', guards: 5, summary: 'Free Ria at the Molten Mere.', captive: person('Ria', '👧', { robe: '#b0643a', small: true, hair: '#4a2f24' }), reward: { xp: 190, gold: 110 },
      text: { offer: ['Ria went to the Molten Mere for glass-sand. The imps have her caged on the shore.', 'Please bring her back.'], progress: ['The Molten Mere lies north of Kilnhollow.'], deliver: ['It was SO hot in there. The imps kept singing.', 'I’m going home. Hessa is going to be so cross.'], complete: ['Ria! Come here, child.', 'Take this, hero. Every kiln in the hollow chipped in.'], after: ['Glass and fire, fire and glass.'] } }),
    q({ id: 'hulkhunt', title: 'Hulk Hunt', giver: 'zara', kind: 'slay', count: 4, enemy: 'magmaHulk', summary: 'Break magma hulks.', reward: { xp: 190, hearts: 1 },
      text: { offer: ['Magma hulks stomp through the caravan routes and melt the wagon wheels.', 'Break four, and the caravans roll again.'], progress: ['Hulks roam the east. Stay out of the glowing cracks.'], complete: ['Four hulks! You hunt like a sandstorm.', 'Wear this — it has turned more fire than I can count.'], after: ['The caravans roll again.'] } }),
    q({ id: 'plumes', title: 'Phoenix Plumes', giver: 'seer', kind: 'collect', count: 4, near: 'spring', item: 'Phoenix plume', icon: 'feather', summary: 'Collect phoenix plumes around the Phoenix Spring.', reward: { xp: 170, mana: 14 },
      text: { offer: ['Phoenixes shed their plumes at the spring. Each one holds a little dawn.', 'Four, please. My flames need them.'], progress: ['The Phoenix Spring lies east of the city.'], complete: ['Four little dawns. Here — they’ll warm your magic.'], after: ['The flames grow brighter.'] } }),
  ],
  lore: [
    { at: 'obsidian', name: 'Obsidian tablet', text: ['“The maze was the Forge’s first mould. Every wall is a sword that was never finished.”'] },
    { at: 'mere', name: 'Scorched stone', text: ['“The Mere was a lake of water once. Then the Tyrant wept fire into it.”'] },
    { at: 'nest', name: 'Buried marker', text: ['“Scorpions guard what is hot. Whatever they drag below is worth digging for.”'] },
    { at: 'forge', name: 'Forge-stone', text: ['“Beacon, Bell, Star and Forge — four lights, and the dark between them has nowhere to sleep.”'] },
    { at: 'watch', name: 'Seer’s stone', text: ['“From the Watch you see the sunrise before anyone else. Lately, you see it first — and alone.”'] },
    { at: 'city', name: 'Brass plaque', text: ['“Brasshaven, forged where the caravan roads cross. Its gates open to anyone who brings water.”'] },
  ],
  script: {
    keyLabel: 'Ember cores', bossName: 'Pyrrhus', bossTitle: 'The Cinder Tyrant', finaleName: 'Dawn Forge',
    guide: { done: ['The wastes are cooling. The dawn is coming back.'] },
    shrine: { bless: ['Warm water bubbles up around you, bright as a sunrise.', 'The phoenix blesses you. (+Experience, full health and magic)'], again: ['The spring steams gently.'] },
    finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['A shadow broods over the forge. Defeat it!'], done: ['You set the three ember cores into the Dawn Forge. Its fire roars up, white and gold, and a new dawn spills across the wastes.', 'Umbra’s last shadow burns away like morning mist. Far to the west, the Star, the Bell and the Beacon shine back.', 'Every land, every light. The valley is whole again.'] },
    pickupKey: 'Ember core recovered. {n}/3',
    sealed: 'Pyrrhus sleeps in a shell of cooling stone. Recover the three ember cores first.', tip: 'Magma hulks crack the ground around them: step out of the glowing circles. Ash scorpions burrow, so watch for moving mounds of sand.',
    victory: { title: 'The dawn returns.', text: 'Umbra is gone for good. The Dawn Forge burns again, and Mira and Tuft have become the valley’s newest legend.' },
    final: { name: 'Umbra', title: 'The Eclipse Sovereign' },
  },
};

const SPECS: RegionSpec[] = [meadow, woods, summit, ember];
let valley: WorldDefinition | null = null;
/**
 * "Wisps on the Wind" sends the player down the road from Warden's Lookout to Frostpine Hamlet, but the random packs
 * rarely put wisps there. Three fixed swarms make sure the hunt can be done where the quest says.
 */
function addRoadWisps(world: WorldDefinition) {
  const find = (id: string) => world.pois.find(p => p.id === id);
  const from = find('summit:lookout'), to = find('summit:hamlet'), lv = WORLDS.summit.levels[0];
  if (!from || !to) return;
  const dx = to.x - from.x, dy = to.y - from.y, len = Math.hypot(dx, dy), nx = -dy / len, ny = dx / len;
  [.3, .55, .8].forEach((t, pack) => {
    const cx = from.x + dx * t + nx * (pack % 2 ? 160 : -160), cy = from.y + dy * t + ny * (pack % 2 ? 160 : -160);
    for (let i = 0; i < 3; i++) {
      const a = i / 3 * Math.PI * 2 + pack;
      world.enemies.push({ id: `summit:e-windwisp-${pack * 3 + i}`, kind: 'wisp', x: cx + Math.cos(a) * 70, y: cy + Math.sin(a) * 55, level: lv + Math.min(1, pack), region: 'summit', elite: pack === 2 && i === 0 });
    }
  });
}
/** The whole valley is generated on first use (a fraction of a second) and then cached. */
/** Each lair's pack leader is a heroic creature: a named little boss with far more health and much better loot. */
const HEROIC: Record<string, string> = {
  'meadow:hollow': 'Murkmaw the Gloom King', 'meadow:rot': 'Old Tusker',
  'woods:nest': 'Mother Briar', 'woods:web': 'Silkshade the Weaver',
  'summit:frostfang': 'Frostfang the Unbroken', 'summit:rift': 'Nulleye',
  'ember:nest': 'Sandreaper', 'ember:foundry': 'Slagjaw',
};
function addHeroics(world: WorldDefinition) {
  for (const p of world.pois) {
    const name = HEROIC[`${p.region}:${p.id.split(':').pop()}`] || HEROIC[p.id]; if (!name || p.kind !== 'lair') continue;
    const leader = world.enemies.filter(e => e.region === p.region && !e.boss && Math.hypot(e.x - p.x, e.y - p.y) < p.r)
      .sort((a, b) => Number(!!b.elite) - Number(!!a.elite) || Math.hypot(a.x - p.x, a.y - p.y) - Math.hypot(b.x - p.x, b.y - p.y))[0];
    if (leader) { leader.heroic = name; leader.elite = true; leader.level += 1; }
  }
}
export function getWorld(): WorldDefinition { if (!valley) { valley = buildValley(SPECS); addRoadWisps(valley); addHeroics(valley); } return valley; }
/** Region metadata for menus, without generating the map. */
export const WORLDS: Record<RegionId, Pick<Region, 'id' | 'chapter' | 'title' | 'subtitle' | 'levels' | 'script'>> = { meadow, woods, summit, ember };
