import { LOOKS, type Shot } from '../cutscenes';
import { look, own, person, type HeroStory } from './kit';

// Kael, the Oathsworn: squire to Ser Aldric of the Wardens. On the night the star fell the shadow rose out of the Beacon
// Rise; Aldric threw Kael onto his own horse and shouted “Hold the line where I can’t!”, and the shadow took him.
//
// I · Sunpetal Meadow: Kael reports to the city guard, holds Sunpetal, follows Aldric’s horse home and finds his split
//     shield and his Warden book. He calls the farms to muster with the old hill fires, frees Warden Brin and learns the
//     Wardens were the Beacon’s keepers. The shadow has stitched the armour of the nine fallen Wardens into the Hollow
//     Bulwark; Kael fears Aldric’s armour is in it. It isn’t.
// II · Whisperroot Woods: the old Warden road leads to Thornhold, the Wardens’ lost hall, where the oath-stones show
//     Captain Briarthorn swearing in two squires, Tobb and Aldric. The black knight who spares children is Aldric; Old
//     Tobb tells how Briarthorn ran from the Silver Pass. Ser Briarthorn, the Oathbreaker, strangles the Bell; Kael
//     breaks him and decides what to do with the old man the roots let go.
// III · Starfall Summit: at the Silver Pass the wraith host marches under the Frost Marshal, a wraith wearing the helm
//     Briarthorn threw down. Kael holds the pass, lights the Warden fires, is knighted by Brin, forgives a boy who ran,
//     wins Skyhold’s banner and re-founds the order. The new Wardens melt Umbra’s black ice with the Star-lamp.
// IV · The Ember Wastes: Pyrrhus, the forge-keeper the Wardens forgot, built the Iron Colossus from their melted swords
//     and wanted Aldric for its heart. Kael follows the black knight’s smoking prints, finds Aldric at Ashfall Watch,
//     holds the line for him, walks him to the Phoenix Spring, breaks the engine, and keeps his oath when Umbra offers
//     him Aldric’s safety for stepping aside.
const q = own('kael');
const title = (t: string, sub: string, dur = 3.4): Shot => ({ title: t, sub, dur });

const BRIN = person('Warden Brin', '🛡️', { robe: '#3f5a8a', hat: 'helm', hatColor: '#b8bcc6', hair: '#b8743c' });
const TOBB = person('Old Tobb', '🧓', { robe: '#3f5a8a', hat: 'helm', hatColor: '#9aa0aa', beard: true, hair: '#e8e2d0' });
const BLACK_KNIGHT = person('The Black Knight', '🖤', { robe: '#1a1624', hat: 'helm', hatColor: '#2a2438', skin: '#3a3048', hair: '#1a1624' });
const ALDRIC = person('Ser Aldric', '🛡️', { robe: '#3f5a8a', hat: 'helm', hatColor: '#b8bcc6', beard: true, hair: '#8a8a8a' });
const BRIAR = look('#3f4a2e', 'helm', { hatColor: '#b08a3a', beard: true, hair: '#6b3f2a' });
const OLD_BRIAR = look('#3f4a2e', 'helm', { hatColor: '#8a6a3a', beard: true, hair: '#d8d0c0' });
const DOV = look('#6a7a8a', 'helm', { hatColor: '#8a8f9a', beard: true });
const ILSA = look('#6c78b8', 'hood', { hatColor: '#3f4a8a' });
const PYRRHUS = look('#3a2e2c', 'hood', { hatColor: '#ff7a3d', skin: '#9a8a80', hair: '#1a1210', beard: true });

export const KAEL: HeroStory = {
  hero: 'kael',
  chains: {
    meadow: ['m1', 'm2', 'kael1', 'kael0', 'm8', 'kael11', 'm9', 'kael12', 'kael6', 'kael2', 'm4', 'm3', 'kael10', 'kael13', 'm10', 'm12'],
    woods: ['m1', 'kael14', 'kael15', 'm7', 'm5', 'kael3', 'kael18', 'kael7', 'm10', 'm11', 'm12', 'm3', 'kael19', 'm15', 'kael20', 'm17'],
    summit: ['m1', 'kael24', 'm6', 'm5', 'm14', 'kael4', 'kael23', 'kael27', 'm12', 'kael30', 'm10', 'kael28', 'm15', 'kael29', 'm19', 'm20'],
    ember: ['m1', 'kael31', 'm5', 'm6', 'm7', 'kael33', 'kael38', 'm14', 'm10', 'kael5', 'kael37', 'kael35', 'kael36', 'm15', 'm12', 'm13'],
  },
  quests: {
    // ═════════════════════════════ Chapter I · the muster of the meadow
    meadow: [
    q({ id: 'kael1', title: 'The Warden’s Trail', giver: 'fox', kind: 'trail', count: 4, near: 'sunpetal', place: 'millbrook', auto: true, summary: 'Follow the tracks of Aldric’s riderless warhorse south to Millbrook Farm.', reward: { xp: 110, hearts: 1 },
      clues: ['Hoofprints, deep and fast. A warhorse at full gallop. That’s Cinder. Aldric’s horse.', 'A torn blue pennant on a fence post. The Wardens’ colours. It was tied to his saddle.', 'Snapped saddle straps in the ditch. Cinder carried me off the Rise. Aldric must have thrown me onto his own horse.', 'Aldric’s shield, lying in the wheat at Millbrook, split right down the middle. It fell off the saddle when I did.'],
      text: { offer: ['A grey warhorse with an empty saddle and a blue pennant. That can only be Cinder.', 'The Wardens’ horses always run home when they lose their rider. If I follow his tracks, I’ll know what happened that night.'], progress: ['Follow Cinder’s hoofprints south from Sunpetal.'],
        complete: ['I don’t remember running. I remember Aldric lifting me into the saddle, and then the hay.', 'He sent me away on his own horse. He kept nothing for himself. Not even his shield.', 'I’ll carry it. Someone has to, until he can again. Farmer Bram will know where Cinder went.'], after: [] } }),
    q({ id: 'kael0', title: 'A Wall for Millbrook', giver: 'bram', kind: 'build', count: 4, near: 'millbrook', item: 'Fence stake', icon: 'bundle', place: 'millbrook', site: 'barricade', siteName: 'Millbrook barricade', turnIn: 'bram', cine: { done: 'barricade-kael' }, summary: 'Cut four fence stakes around Millbrook and build Farmer Bram a barricade.', reward: { xp: 150, hearts: 1 },
      text: { offer: ['Cinder? Big grey brute? He’s in my barn eating my oats, lad. Won’t let anybody near him but me.', 'Is that the Warden’s shield? Stars. I’m sorry.', 'Listen. The gloomlings come right up to my door every night now. You Wardens used to build walls for the farms. Show me how?', 'Four good stakes from the woods around the farm, and we’ll put up a fence they won’t cross.'],
        progress: ['Four fence stakes around Millbrook, then build the barricade.'],
        complete: ['That’ll hold. That’ll hold for years.', 'Oh, and this was in Cinder’s saddlebag. A little book with a shield on it. Can’t read it myself. Too many long words.', '(Aldric’s Warden book. On the first page, in his square hand: “If the Beacon falls, the Wardens carry the sun-crystals home.”)'],
        after: ['Not one gloomling since. Not one!'] } }),
    q({ id: 'kael11', title: 'The Hill Fires', giver: 'odo', kind: 'activate', count: 3, near: 'shepherd', switches: 'brazier', order: ['North signal fire', 'East signal fire', 'Old Odo’s fire'], summary: 'Light the three old signal fires on Shepherd’s Hill to call the farms to muster.', reward: { xp: 140, mana: 10 },
      text: { offer: ['Three signal fires ring this hill. Light them all, and every farmer from Millbrook to Willowmere will see them.', 'The old signal meant “The Wardens call. Bring what you’ve got.” Mostly they brought soup. Soup counts.'],
        progress: ['Three signal fires around Shepherd’s Hill.'],
        complete: ['Look at that! Lights in every window down the valley. They’re answering!', 'Bram’s bringing Millbrook. Ottilie’s bringing Willowmere, probably with a list. You’ve got yourself a muster, Warden.', 'Now, about that crystal of yours. It’s been humming among my stones since the night the Beacon died.'],
        after: ['The fires burn every night now. The gloomlings hate it.'] } }),
    q({ id: 'kael12', title: 'The Rise-Picker', giver: 'odo', kind: 'chase', count: 1, place: 'city', turnIn: 'brannoc', who: person('Fitch the Picker', '🧒', { robe: '#6a5a3a', hat: 'cap', hatColor: '#3a2e22', small: true }), summary: 'Catch the boy selling fallen Wardens’ armour in Goldenhearth, then tell Captain Brannoc.', reward: { xp: 150, gold: 40 },
      text: { offer: ['Fitch, they call him. Quick as a hare and twice as shameless. He sells Warden helms by the pound on the market square in Goldenhearth.', 'That’s not how we treat the fallen. Catch him, and ask him what else he saw up there. Then tell that captain of yours.'],
        progress: ['Fitch hangs around Goldenhearth. He’s fast, but he runs out of breath.'],
        deliver: ['Ow! Alright, alright! I only took the little bits!', 'I stopped going up. The armour up there… it moves, Warden. At night it crawls together, piece by piece, like it’s looking for itself.', 'And the swords are gone. Every one. Somebody took them before me.'],
        complete: ['Armour that walks, and every Warden sword missing. I’ve heard worse this week, but not much.', 'The lad can sweep my barracks until he’s paid for what he sold. Stay close, squire. I have work for you.'],
        after: ['Fitch sweeps the barracks now. He complains in a very small voice.'] } }),
    q({ id: 'kael6', title: 'The Last Wardens', giver: 'brannoc', kind: 'rescue', count: 1, place: 'faerie', guards: 4, escort: true, turnIn: 'brannoc', cine: { done: 'wardens-oath' }, summary: 'Free Warden Brin at the Faerie Ring and walk her to Captain Brannoc.', captive: BRIN, reward: { xp: 190, item: 'barkskin' },
      text: { offer: ['Here’s a real order, then. One of my scouts saw a Warden at the Faerie Ring, south of the city. Alive, in a cage of thorns, with gloomlings all round her.', 'Brin, I think. She rode with Aldric. Bring her back to me, squire. The valley can’t spare a single Warden.'],
        progress: ['The Faerie Ring lies south of the city. Break the guards, open the cage, and bring Brin to Brannoc.'], arrive: ['Goldenhearth. I never thought I’d see those walls again.'],
        deliver: ['A squire? Aldric’s squire! Then he got you clear. Good.', 'Get me out of here and I’ll tell you everything I saw on the Rise.'],
        complete: ['Brin says the shadow took Aldric whole. It didn’t kill him, lad. It took him.', 'Nine Wardens fell on the Rise that night. Aldric wasn’t one of them. Hold on to that.'], after: ['Two Wardens in my city again.'] } }),
    q({ id: 'kael2', title: 'Mend the Shield', giver: 'brannoc', kind: 'deliver', count: 1, to: 'smith', item: 'Aldric’s split shield', summary: 'Bring Ser Aldric’s shield to Smith Hilda in Goldenhearth.', reward: { xp: 140, item: 'healthPotion' },
      text: { offer: ['Is that… Aldric’s shield? I served under him, twenty years back. Best Warden the Rise ever had.', 'Hilda at the forge made it for him. Take it to her. If anyone can mend it, she can.'], progress: ['Hilda’s forge is here in the city, on the east side.'], complete: [], after: ['A Warden’s shield, mended. Good.'],
        deliver: ['Rootsteel rivets, oak core… I made this for Aldric when he was younger than you.', 'Something hit it that was not a sword. The wood is cold as a grave.', 'There. It will hold. Carry it until you find him, lad, and give it back to him yourself.', 'Now go on. Warden Brin has been pacing outside my door for an hour.'] } }),
    q({ id: 'kael10', title: 'Into Gloom Hollow', giver: 'ilse', kind: 'key', count: 1, keys: [1], turnIn: 'bram', summary: 'Take the sun-crystal the Wardens hid in Gloom Hollow, then report to Farmer Bram.', reward: { xp: 160 },
      text: { offer: ['The roll says the second crystal lies in Gloom Hollow, south of Millbrook Farm. Aldric took new recruits there, to learn to be afraid properly.', 'Farmer Bram lives closest. Tell him when you’re out, so someone knows you are.'],
        progress: ['Gloom Hollow lies south of Millbrook Farm.'],
        complete: ['You went into the Hollow and walked back out? With a crystal!', 'Listen, lad. Hunter Garrick sent a boy from his camp in the south-east. There’s something standing on the Rise. Something big, made of Warden armour.', 'And the whole muster’s here. Forty farmers with pitchforks, and they’re all looking at you.'],
        after: ['Stakes still standing. Muster still mustered.'] } }),
    q({ id: 'kael13', title: 'Pennants on the Wind', giver: 'bram', kind: 'collect', count: 4, near: 'camp', item: 'Torn Warden pennant', icon: 'bundle', turnIn: 'garrick', cine: { done: 'kael-bulwark' }, summary: 'Gather the torn Warden pennants around the Hunter’s Camp, then find Hunter Garrick.', reward: { xp: 140, regen: .5 },
      text: { offer: ['Garrick says the Wardens’ pennants have been blowing down off the Rise for days. Blue rags in every bush around his camp.', 'Gather them up, lad. You don’t leave your colours in a hedge. His camp is far to the south-east. We’ll follow with the muster.'],
        progress: ['Four torn pennants around the Hunter’s Camp, south-east of the city.'],
        complete: ['Nine pennants flew on that hill. You’ve four. I buried nobody, Warden. There was nobody to bury.', 'Just armour, walking. Last night it stood up in one piece, as tall as a barn, and it hasn’t moved since.', 'It’s waiting at the Beacon. For you, I think.'],
        after: ['I keep watch toward the Rise now. It never blinks. Neither do I.'] } }),
    ],
    // ═════════════════════════════ Chapter II · the Wardens’ past
    woods: [
    q({ id: 'kael14', title: 'Marks on the Warden Road', giver: 'fox', kind: 'trail', count: 4, near: 'camp', place: 'ruins', auto: true, summary: 'Follow the old Warden waymarks from the Mosskeeper’s Camp north to the Root Ruins.', reward: { xp: 150 },
      clues: ['A shield cut into a birch trunk, green with moss. A Warden waymark.', 'A milestone, split by roots. Under the moss: “Thornhold, two leagues. Stand fast.”', 'Scratched over the next waymark, deep and old: a sword, and the word RUN. Somebody hated this road.', 'The gate of the Root Ruins. Over it, worn almost smooth, the Warden shield. Thornhold, the Wardens’ hall of the woods.'],
      text: { offer: ['A Warden hall in the woods. Aldric never told me. Why not?', 'If the waymarks still stand, they’ll lead me there.'], progress: ['Follow the Warden waymarks north from the camp.'],
        complete: ['(Thornhold is empty. Roots have broken its floors, and owls nest where the banners hung.)', 'In the middle of the hall stand three oath-stones. I know the words carved on them. Every squire does.'], after: [] } }),
    q({ id: 'kael15', title: 'The Oath-stones', giver: 'fox', kind: 'activate', count: 3, near: 'ruins', switches: 'rune', ordered: true, order: ['I stand', 'I shield', 'I stay'], auto: true, cine: { done: 'kael-oathstones' }, summary: 'Wake the three oath-stones of Thornhold in the order of the Warden oath.', reward: { xp: 170, mana: 10 },
      text: { offer: ['Three oath-stones, three words. Every squire learns them before they learn to hold a sword.', 'I stand. I shield. I stay. In that order, or not at all.'], progress: ['Wake the oath-stones around the Root Ruins in the order of the oath: I stand, I shield, I stay.'],
        complete: ['(The stones fade. You are alone in the hall again.)', 'Captain Briarthorn. Aldric was one of his squires, here, and he never once said the name.', 'The stones say the Wardens cut the woods’ root runes to wake the Bell. The first sleeps under Glowcap Farm, to the west.'], after: [] } }),
    q({ id: 'kael3', title: 'The Black Knight', giver: 'thessaly', kind: 'chase', count: 1, place: 'glade', escapes: true, cine: { caught: 'knight-vanish' }, who: BLACK_KNIGHT, turnIn: 'thessaly', summary: 'Run down the knight in black armour seen near the Moonlit Glade, then report to Thessaly.', reward: { xp: 200 },
      text: { offer: ['He walks the Moonlit Glade at dusk, west of the city. My scouts can’t catch him. They can’t even keep up.', 'You wear the same blue he wears under the black. Maybe he’ll stop for you. Find out who he is.'], progress: ['The black knight lurks near the Moonlit Glade, west of Lanternmarket.'],
        deliver: ['(The knight sags, and a voice you know whispers from inside the helm.)'],
        complete: ['An empty suit of armour that knew your name? Stars keep us.', 'If it was Aldric, then some part of him is still fighting. Hold on to that.', 'Little Pim swears the black knight saved him from the wolves. Ask him. He plays by the market stalls.'], after: ['Keep your shield close.'] } }),
    q({ id: 'kael18', title: 'The Knight Who Spared Pim', giver: 'thessaly', kind: 'talk', count: 1, to: 'pim', summary: 'Ask Little Pim in Lanternmarket about the black knight.', reward: { xp: 110, gold: 30 },
      text: { offer: ['Go easy on him. He’s only seven, and he has told the story to every cat in the market.'], progress: ['Little Pim plays by the stalls in Lanternmarket.'], complete: [], after: ['Pim practises “holding the line” on the market geese.'],
        deliver: ['You’re blue like him! Are you a knight too? Can I hold your sword? No? Okay.', 'The wolf fog got me at Blackwater Pool. Then the black knight came and the wolves ran away. His armour was cold like snow.', 'He said, “Hold the line, little one.” And then he said, “Tell the squire: Tobb. The tower.” What’s a Tobb?'] } }),
    q({ id: 'kael7', title: 'Old Tobb', giver: 'pim', kind: 'escort', count: 1, from: 'watch', place: 'city', turnIn: 'thessaly', who: TOBB, ambush: ['shadewolf', 'webspinner', 'thornling'], cine: { done: 'kael-tobb-tale' }, summary: 'Walk Old Tobb, the last Warden of the woods, from the Owl Watchtower to Warden Thessaly in Lanternmarket.', reward: { xp: 230, hearts: 1 },
      text: { offer: ['The tower? The Owl Watchtower! There’s an old man up there who shouts at owls. His name is Tobb! That’s a Tobb!', 'He never comes down, because the woods are full of wolves. Will you go and get him? Bring him to Thessaly!'],
        progress: ['Walk Old Tobb from the Owl Watchtower, far to the north-east, to Lanternmarket. Keep the wolves off him.'], arrive: ['Lanternmarket. Smells like it always did. Burnt sugar and wet dog.'],
        complete: ['He’s talking. The owls say he hasn’t talked in years. Sit with him a while, Kael.'], after: ['Tobb tells the same story twice a night now.'] } }),
    q({ id: 'kael19', title: 'Roots at the Door', giver: 'bellkeeper', kind: 'defend', count: 3, place: 'bellhollow', waves: [4, 5, 5], foes: ['thornling', 'sporecap', 'webspinner'], ward: 'The Bellkeeper’s door', summary: 'Hold the Bellkeeper’s door in Bellhollow against three waves of Briarthorn’s creatures.', reward: { xp: 260, hearts: 1 },
      text: { offer: ['Here they come. Thornlings, sporecaps, spinners, all of them his.', 'Hold my door, Warden. The Bell’s old rope hangs inside. If they cut it, nobody will ever ring the Bell again.'],
        progress: ['Stand by the Bellkeeper’s door and break every wave.'],
        complete: ['You stood like a Thornhold Warden. I saw the last of them do it when I was a boy.', 'Now go to the Old Bell, in the far north-east. Briarthorn sits on it like a crow on a fence.', 'He was a Warden once, lad. Remember that, whatever he does.'],
        after: ['The door is scratched to ribbons. I’m keeping it that way.'] } }),
    q({ id: 'kael20', title: 'What the Roots Kept', giver: 'fox', kind: 'talk', count: 1, to: 'kael-briarthorn', summary: 'Speak with the old knight the roots let go beside the Old Bell.', reward: { xp: 200 },
      text: { offer: ['(The Bell’s voice rolls through the woods. Among the fallen roots, something is breathing.)', 'That’s him. What’s left of him.'], progress: ['Ser Briarthorn lies among the roots by the Old Bell.'], complete: [], after: [],
        deliver: ['A blue cloak. Of course. They always send a blue cloak, in the end.', 'I ran from the Silver Pass forty winters ago. Left two squires and my helm in the snow. The roots were the only thing that would have me.', 'Something whispered to me in the dark: “You broke one oath. Break another, and the shame stops.” I believed it. What will you do with me, boy?'] },
      choice: {
        a: { label: 'Forgive him', lines: ['Forgive…? Tobb never did. Aldric never said my name again. And you forgive me?', '(The old knight bows his head.) Then I will keep this Bell until I die. Here: take its flame, and burn down the wall I grew across the gate.'], reward: { mana: 10 } },
        b: { label: 'Tell him to stand his post', lines: ['A post. At my age. With my shame.', '(He takes up a fallen root like a spear and stands before the Bell.) I stand. I shield. I stay. …I had forgotten how heavy it is.', 'Take the Bell’s flame, Warden. Burn my wall down.'], reward: { regen: .5 } },
      } }),
    ],
    // ═════════════════════════════ Chapter III · the Silver Pass and the new order
    summit: [
    q({ id: 'kael24', title: 'Shields in the Snow', giver: 'guide', kind: 'collect', count: 5, near: 'lookout', item: 'Old Warden shield', icon: 'bundle', summary: 'Dig five old Warden shields out of the snow around the Lookout for Sky-warden Ilsa.', reward: { xp: 130, gold: 50 },
      text: { offer: ['When the star fell, the old armoury behind the Lookout came down. Warden shields, scattered all over the slope.', 'If you’re thinking of fighting that host, you’ll need more shields than yours. Dig out five.'],
        progress: ['Five old Warden shields in the snow around the Lookout.'],
        complete: ['Rootsteel rims and oak hearts. They still ring when you knock on them.', 'Five shields. Now all we need is five people foolish enough to carry them.', 'Before that, though: the host is hunting shards of the fallen star. We saw one drop into Crystal Hollow.'],
        after: ['The shields hang by the door, polished. Just in case.'] } }),
    q({ id: 'kael4', title: 'The Wardens’ Fires', giver: 'dov', kind: 'activate', count: 3, near: 'pass', switches: 'brazier', order: ['Old fire', 'Watch fire', 'Last fire'], auto: true, summary: 'Light the three Warden fires at Silver Pass.', reward: { xp: 200, hearts: 1 },
      text: { offer: ['You fought like a Warden out there. We have three old Warden fires on this pass. Nobody has lit them since the order broke up.', 'Light them. Let whatever is watching from the dark know the Wardens are back.'], progress: ['Three Warden fires around Silver Pass.'],
        complete: ['(The third fire roars up. Every soldier on the pass stands straighter, and somebody starts to hum the old Warden song.)', '“Hold the line where I cannot.” Aldric learned it on this very pass. I’m holding it, Ser.'], after: [] } }),
    q({ id: 'kael23', title: 'The New Oath', giver: 'dov', kind: 'talk', count: 1, to: 'kael-brin', cine: { done: 'kael-knighted' }, summary: 'Find Warden Brin, who climbed the mountain when she saw the Warden fires.', reward: { xp: 150 },
      text: { offer: ['Someone came up the road behind you. A woman in blue, with a broken spear and a very loud voice.', 'Says she saw the fires from the Beacon Rise and walked all night. She’s asking for “the squire”.'], progress: ['Warden Brin waits by the Warden fires at Silver Pass.'], complete: [], after: ['Ser Kael. Has a ring to it.'],
        deliver: ['Three Warden fires on the Silver Pass. I saw them from the meadow and cried like a baby. Don’t tell Brannoc.', 'Kael, a squire lights no fires. A squire follows orders. You’ve been giving them since the Beacon.', 'So kneel. By the oath of the Rise, a Warden can make a Warden. What do you swear?'] },
      choice: {
        a: { label: 'Swear the old oath', lines: ['“I stand. I shield. I stay.” Just like Aldric said it. Just like Tobb.', 'Rise, Ser Kael, Warden of the valley. Now let’s find you an order to lead.'], reward: { mana: 12 } },
        b: { label: 'Add a line of your own', lines: ['“I stand. I shield. I stay. And I go back for those who fall.” …That isn’t in the book.', 'It is now. Rise, Ser Kael, Warden of the valley. Aldric would have liked that line.'], reward: { regen: .5 } },
      } }),
    q({ id: 'kael27', title: 'The One Who Ran', giver: 'kael-brin', kind: 'chase', count: 1, place: 'bloom', turnIn: 'dov', who: person('Private Ferris', '💂', { robe: '#6a7a8a', hat: 'helm', hatColor: '#8a8f9a', hair: '#b8743c' }), summary: 'Catch the young soldier who fled the pass, near the Starbloom Grove, and bring word to Dov.', reward: { xp: 170, gold: 40 },
      text: { offer: ['First order for the new Warden. One of Dov’s lads ran in the night. Ferris. Seventeen, maybe.', 'He was seen near the Starbloom Grove, west of the pass. Dov wants him flogged. What you do with him is your call, Ser Kael.'],
        progress: ['Ferris hides around the Starbloom Grove, west of Silver Pass. He’s fast, but he tires.'],
        deliver: ['Don’t! Please! I saw them marching and my legs just… went.', 'Everyone says Briarthorn ran. I thought, at least I’m in good company. Are you going to tell Dov?', '(You tell him the pass still needs him, and that one night of running doesn’t have to be forty winters.)'],
        complete: ['You told him he can come back? No punishment?', '…Aye. Briarthorn got forty winters of roots for running. A lad deserves one second chance. He’s on the barricade now, standing a little taller.', 'Now: my scouts found the second shard up on Frostfang Crag, south-east of here. Crag golems sit on it like hens.'],
        after: ['Ferris polishes the Warden fires every morning. Nobody asked him to.'] } }),
    q({ id: 'kael30', title: 'The Banner of Skyhold', giver: 'kael-brin', kind: 'talk', count: 1, to: 'corvin', summary: 'Meet Abbot Corvin in Skyhold, the city south of the pass.', reward: { xp: 80 },
      text: { offer: ['Skyhold is the great city south of here. Abbot Corvin leads the monks.', 'When the order broke up, the Wardens left their last banner with Skyhold. Go and hear what the Abbot wants for it.'], progress: ['Skyhold lies south of Silver Pass.'], complete: [], after: [],
        deliver: ['A Warden in my hall. We have kept your banner folded for thirty years, waiting for someone to ask for it.', 'Its keeper, Brother Ansel, was taken by the wraiths three nights ago. They dragged him into the Void Rift, far to the south-east.', 'Bring him home, and the banner is yours.'] } }),
    q({ id: 'kael28', title: 'Goats Before Glory', giver: 'brun', kind: 'herd', count: 5, near: 'terrace', place: 'terrace', animal: 'goat', summary: 'Drive five of Brun’s scattered goats back into their pen on Goatherd’s Terrace.', reward: { xp: 150, mana: 10 },
      text: { offer: ['The goat path to the Spire? Sure, I know it. So do my goats. And my goats are all over the mountain, because the wraiths scared them silly.', 'Walk up behind a goat and it trots the other way. Five back in the pen, and I’ll draw you the path.', 'The Wardens used to pay my granddad in cheese to carry their fire-oil up the pass. Very good cheese. I’m just saying.'],
        progress: ['Walk behind a goat to push it toward the pen. Goats are stubborn. Be more stubborn.'],
        complete: ['Five goats! They’re pretending it was their idea. That’s goats for you.', 'Here: the path. Up the ice road past Silver Pass, east to the Broken Spire. The road’s full of wraiths. The path is only full of goats.', '(Brun presses a wheel of cheese into your hands. It is very good cheese.)'],
        after: ['The goats are fine. I’m fine. Everyone’s fine.'] } }),
    q({ id: 'kael29', title: 'Break the Ranks', giver: 'kael-brin', kind: 'slay', count: 8, enemy: 'frostwraith', summary: 'Break eight of the wraith host’s frost wraiths before the march on the Star Cradle.', reward: { xp: 180 },
      text: { offer: ['The host holds the road to the Cradle in ranks. Break the ranks, and the Marshal has to come out and fight you himself.', 'Eight wraiths, Ser Kael. Dov and I will hold the pass.'],
        progress: ['Frost wraiths blink close and throw ice. Keep moving, and keep your shield up.'],
        complete: ['Eight! The ranks are broken. It’s only the Marshal now, and whatever it has left.', 'Tobb and Aldric held this pass against that thing for a whole night. You get to finish it.'],
        after: ['The host is scattered. I can hear it sulking in the wind.'] } }),
    ],
    // ═════════════════════════════ Chapter IV · finding Aldric
    ember: [
    q({ id: 'kael31', title: 'Footprints in the Ash', giver: 'guide', kind: 'trail', count: 4, near: 'camp', place: 'kiln', turnIn: 'hessa', summary: 'Follow the black knight’s smoking footprints from the outpost to Kilnhollow, then find Kiln-mother Hessa.', reward: { xp: 140 },
      clues: ['A bootprint, burned into the ash. The left heel drags. Aldric always dragged his left heel when he was tired.', 'A black gauntlet, dropped and left. Inside, a strip of blue cloth is tied around the wrist. Warden blue.', 'Here he stopped and drove his sword into the ground, again and again, as if something wanted to walk him the other way.', 'The prints end at the kilns. Someone has left a cup of water on the wall for him.'],
      text: { offer: ['Smoking footprints, going south-east. Follow them, Warden, if you want him.', 'Kiln-mother Hessa runs Kilnhollow. If he passed her kilns, she saw him.'], progress: ['Follow the smoking footprints south-east toward Kilnhollow.'],
        complete: ['The black knight? I left him water. He stood at my wall and didn’t drink it.', 'He asked me one thing, in a voice like an empty kiln: “Is the Dawn Forge still cold?” Then he walked on east.', 'If you want to know what the Forge has to do with your knight, ask Forgemaster Tovan in Brasshaven.'],
        after: ['The cup is still on the wall. Nobody touches it.'] } }),
    q({ id: 'kael33', title: 'The Names on the Hilts', giver: 'kael-pyke', kind: 'collect', count: 5, near: 'mere', item: 'Warden sword hilt', icon: 'gem', turnIn: 'kael-pyke', summary: 'Gather the Warden sword hilts thrown into the Molten Mere and bring them to Old Pyke.', reward: { xp: 170, regen: .5 },
      text: { offer: ['Pyrrhus melted Warden blades for his engine. The imps brought him sacks of them from the west, only a few weeks ago.', 'He threw the hilts in the Molten Mere, north-west of the city. Hilts carry names. Bring me five and we’ll see whose swords he took.'],
        progress: ['Five Warden sword hilts around the Molten Mere, north-west of Brasshaven.'],
        complete: ['Let me see. “Oswin. Harra. Tamsel. Bryce. Wat.” Rise names, all five. The swords of your fallen.', 'So that’s where the swords went that your picker boy couldn’t find. The Colossus is made of them.', '(Aldric’s name is not on any of the hilts. You breathe out for what feels like the first time today.)'],
        after: ['I keep the hilts in a row on the anvil. I say their names in the morning.'] } }),
    q({ id: 'kael38', title: 'The Burrow Core', giver: 'kael-pyke', kind: 'key', count: 1, keys: [1], turnIn: 'fenwick', summary: 'Take the second ember core from the Scorpion Burrows, then find Saltfarmer Fenwick.', reward: { xp: 170 },
      text: { offer: ['Pyrrhus hid the second core in the Scorpion Burrows, south-west of the city.', 'Ash scorpions come up right under your feet. When the sand bulges, move!', 'Saltfarmer Fenwick sent word from his farm, west of the burrows. He says he’s seen your black knight.'],
        progress: ['The Scorpion Burrows lie south-west of Brasshaven. Saltglass Farm is west of them.'],
        complete: ['Two cores? Good. Now, about your knight.', 'He’s been standing in my salt pans every dusk. Just standing, like a scarecrow made of night. The salt hisses where he steps.'],
        after: ['The salt’s coming in white again.'] } }),
    q({ id: 'kael5', title: 'Unbroken', giver: 'fox', kind: 'talk', count: 1, to: 'aldric', summary: 'Face the kneeling knight at Ashfall Watch.', reward: { xp: 280 },
      text: { offer: ['There, at the edge of the Watch. A knight in black armour, kneeling, with his sword driven into the ash.', 'It’s him. I know how he kneels.'], progress: ['The knight kneels at Ashfall Watch.'], complete: [], after: [],
        deliver: ['Kael. You… have my shield.', 'Umbra meant to put me in Pyrrhus’s engine. A Warden’s oath for its heart, it said, so it would never run. I walked away. Every step, it pulled me back.', 'I can’t hold much longer, lad. It’s coming for me.'] },
      choice: {
        a: { label: 'Offer him your hand', lines: ['(Aldric looks at your hand for a long moment. Then he grips it, and the black drains out of his armour like water.)', 'Hold the line where I cannot… you did, didn’t you? Then hold it one more time. Here it comes.'], reward: { regen: .6 } },
        b: { label: 'Raise his shield against the dark', lines: ['(You set the mended shield between Aldric and the shadow. It breaks against the oak like a wave on a rock.)', 'Hilda’s rivets. Ha! But it isn’t done with me, lad. Here it comes.'], reward: { item: 'phoenixFeather' } },
      } }),
    q({ id: 'kael37', title: 'Hold the Line', giver: 'aldric', kind: 'defend', count: 3, place: 'watch', waves: [4, 5, 6], foes: ['emberImp', 'ashScorpion', 'wisp'], ward: 'Ser Aldric', cine: { start: 'kael-shadow-returns' }, summary: 'Hold the line at Ashfall Watch while the shadow tries to take Ser Aldric back.', reward: { xp: 250, hearts: 1 },
      text: { offer: ['The shadow is sending everything it has left. It wants me back inside that armour.', 'I can’t fight it, lad. It’s in my arms, my legs. All I can do is kneel, and not go.', 'So you hold the line. Where I can’t.'],
        progress: ['Stay by Ser Aldric and break every wave before it reaches him.'],
        complete: ['It’s quiet. It’s gone quiet in my head, Kael, for the first time since the Rise.', 'You held. Nine Wardens fell on that hill, and you held for every one of them.', 'There’s one more shadow left in me. The Phoenix Spring could burn it out. Walk with me? My legs are still learning.'],
        after: ['Look at you. A Warden.'] } }),
    q({ id: 'kael35', title: 'The Long Walk', giver: 'aldric', kind: 'escort', count: 1, from: 'watch', place: 'spring', who: ALDRIC, ambush: ['emberImp', 'ashScorpion', 'magmaHulk'], auto: true, cine: { done: 'kael-spring' }, summary: 'Walk Ser Aldric from Ashfall Watch to the Phoenix Spring, far to the south-east.', reward: { xp: 200 },
      text: { offer: ['The Phoenix Spring is far to the south-east. The first dawn was born in it, they say. If anything can burn the last of this out of me, it can.', 'Slow, now. I carried you off the Rise. You can walk me across the Wastes.'],
        progress: ['Walk Ser Aldric to the Phoenix Spring and keep the imps off him.'], arrive: ['The Phoenix Spring. It’s warm, lad. It’s warm.'],
        complete: ['(Aldric wades into the Phoenix Spring, and the water blazes gold around him.)'], after: [] } }),
    q({ id: 'kael36', title: 'Quench the Engine', giver: 'kael-aldric2', kind: 'activate', count: 3, near: 'foundry', switches: 'vent', order: ['West quench-vent', 'North quench-vent', 'East quench-vent'], auto: true, summary: 'Open the three quench-vents of the Old Foundry, so the Iron Colossus wakes cold and brittle.', reward: { xp: 200, mana: 12 },
      text: { offer: ['I saw the engine they meant to put me in. The Iron Colossus, Pyrrhus calls it. It sleeps under the Dawn Forge, waiting for the fire.', 'Pyke says the Old Foundry has quench-vents that run under the Forge. Open all three, and it wakes cold. Cold iron cracks.', 'I’ll follow when my legs remember me. Go on, Warden.'],
        progress: ['Open the three quench-vents around the Old Foundry, north-east of Brasshaven.'],
        complete: ['(Steam roars out of the last vent and races away underground, toward the Dawn Forge.)', 'Now the Forge has to breathe. Its Great Bellows are smashed, but this foundry is full of brass gears.'], after: [] } }),
    ],
  },
  reuse: {
    meadow: {
      m1: { giver: 'bram', to: 'brannoc', title: 'The Squire’s Report', summary: 'Report the fall of the Rise to Captain Brannoc in Goldenhearth.', reward: { xp: 70 },
        text: { offer: ['Easy, lad, easy. I found you face-down in my hay at first light, still in your armour, shouting about the Rise.', 'The Beacon died last night. Half the valley saw it go. If a Warden fell up there, the city guard must hear it.', 'Captain Brannoc keeps the guard in Goldenhearth, east along the river road. Go and make your report.'],
          progress: ['Goldenhearth is the big walled city east of the farm.'], after: ['The captain will know what to do. Captains always do. Mostly.'],
          deliver: ['A Warden’s squire? Stand up straight, lad, and make your report.', '…Aldric. Gone into the shadow. Stars keep him.', 'You want orders? I have none to give. My riders can’t even hold the roads.', 'Elder Rowan in Sunpetal faces the gloom every dusk with farmers and pitchforks. Go north-west and stand with him. That’s the best order I’ve got.'], complete: [] } },
      m2: { title: 'The Line at Sunpetal', summary: 'Stand at Sunpetal’s barricade through three waves of gloomlings.', reward: { xp: 120 },
        text: { offer: ['Brannoc sent you? One squire. Well, it’s one more than yesterday.', 'Every dusk since the Beacon died, the gloom crawls out of the grass. Tonight we hold the barricade or we lose the lanes.', 'Stand where the line is thinnest, lad. Three waves, and then it’s morning.'],
          progress: ['Stay by the barricade. Stop them before they reach it.'],
          complete: ['You didn’t take a single step back. The old Wardens fought just like that.', 'At dawn a great grey warhorse galloped through the village with an empty saddle and a blue pennant. It ran south, toward the farms.'],
          after: ['The lanes are quiet tonight. We sleep in turns, but we sleep.'] } },
      m8: { giver: 'bram', turnIn: 'odo', title: 'Boars on the Muster Road', summary: 'Clear five bristleboars off the hill road, then climb to Old Odo on Shepherd’s Hill.', reward: { xp: 150 },
        text: { offer: ['That book says the Wardens kept a crystal on Shepherd’s Hill? That’s Old Odo’s hill, far to the north-east.', 'Odo lights the signal fires up there. In my grandad’s day, one fire on that hill and every farm in the valley came running with a pitchfork.', 'Bristleboars have gone wild on the hill road, though. Clear five on your way up. When one paws the ground, jump aside!'],
          progress: ['Bristleboars charge in a straight line. Step out of the way, then hit them.'],
          complete: ['Five boars! And a Warden on my hill, with a shield on his back. I thought I’d seen the last of you lot.', 'A muster? You want to call the farms? Ha! Then we need the old hill fires. Nobody’s lit them in twenty years.'],
          after: ['Baa. I mean, good day, Warden.'] } },
      m9: { title: 'The Hill Post', summary: 'Find the sun-crystal the Wardens hid on Shepherd’s Hill.', reward: { xp: 150 },
        text: { offer: ['Your Aldric came up here every spring to check on it. Brought me cheese. I never asked what he was checking.', 'Go on, then. It’s somewhere among the stones.', '(You tell him you’re only a squire. Odo laughs so hard he has to sit down.)'],
          progress: ['The crystal is somewhere on the hill. Listen for the hum.'],
          complete: ['A sun-crystal! Warm as a loaf. The Beacon’s own fire, in your hand.', 'Now, there’s a lad in Goldenhearth selling Warden steel off a cart. Old helms, gauntlets. Says he found it on the Rise. You might want a word with him.'],
          after: ['Go on, now. Mind the boars.'] } },
      m4: { giver: 'kael-brin', to: 'ilse', title: 'The Roll of the Rise', summary: 'Ask Scholar Ilse in Goldenhearth for the roll of the Wardens who stood on the Rise.', reward: { xp: 80 },
        text: { offer: ['Fitch says the armour walks. I say the shadow wants something with it.', 'Before we climb that hill, I want the names. Scholar Ilse keeps the city’s rolls, the Wardens’ too. She’s on the west side of the city.'],
          progress: ['Scholar Ilse is here in Goldenhearth, on the west side.'], after: ['Names matter, squire. Remember that.'],
          deliver: ['The Rise roll? Here. I’ve kept it since the order broke up. Nobody else wanted it.', 'Eleven Wardens for the Rise: Ser Aldric, Warden Brin and nine more. And one squire, added last spring in Aldric’s hand.', 'Beside every name, a post. The Wardens were the Beacon’s keepers, Kael. They kept its three sun-crystals. Did nobody tell you?'] } },
      m3: { giver: 'ilse', title: 'The Keepers’ Crystal', summary: 'Bring back the sun-crystal the Wardens kept in the Old Stone Garden.', reward: { xp: 130 },
        text: { offer: ['The first post on the roll is the Old Stone Garden, north of the city. The Wardens hid a sun-crystal beneath the tallest stone.', 'Bring it here, and I’ll show you something else in the roll.'],
          progress: ['The Old Stone Garden is north of Goldenhearth. Look for a golden light among the stones.'],
          complete: ['It glows for you. The Beacon still trusts a Warden, even a young one.', 'Here, at the bottom of the roll, one line in Aldric’s hand: “If I fall, the squire keeps the book.” He meant you.'],
          after: ['Two crystals home. Go carefully with the last.'] } },
      m10: { giver: 'garrick', title: 'The Hollow Bulwark', summary: 'Face the Hollow Bulwark on the Beacon Rise and relight the Meadow Beacon.', reward: { xp: 320, hearts: 1 },
        text: { offer: ['The shadow sewed your fallen friends into one great hollow knight, with a tower shield as wide as a door.', 'It slams that shield down and throws knives of black steel. When it lowers its head, it charges. Don’t be where it’s looking.', 'Break it, lad, and lay the three crystals in the Beacon, south-east of here. The muster will hold the foot of the hill.'],
          progress: ['The Beacon Rise lies south-east of the Hunter’s Camp.'], after: ['The Beacon shines, and so do you.'] } },
      m12: { title: 'A Bridge for the Muster', summary: 'Gather bridge timber around Willowmere, then rebuild the Gloomwater Bridge at the Eastern Gate.', reward: { xp: 250, hearts: 1 },
        text: { offer: ['You’re the Warden who lit the Beacon? Your farmers are all over my gate, asking where you’re off to next.', 'The Gloomwater Bridge came down the night the star fell. Nobody gets east to Whisperroot without it.', 'Bring me five good timbers from around Willowmere, north-west of here, and your muster can build it with me. Many hands, Warden.'],
          progress: ['Five bridge timbers from around Willowmere, then build at the Eastern Gate.'],
          complete: ['Forty farmers and a squire, and it only took an afternoon! She’s straighter than the old one.', 'The road east is open. Whisperroot Woods lies beyond. They say a knight in black armour walks the old roads there.'],
          after: ['Mind the third plank. It squeaks.'] } },
    },
    woods: {
      m1: { title: 'The Old Warden Road', summary: 'Cross the bridge into Whisperroot and find Mosskeeper Oda.', reward: { xp: 70 },
        text: { offer: ['(You look east, where the road dives under dark trees.)', 'The muster has gone home to its farms, and Brin keeps watch at the Beacon. The rest of this road is mine.'], progress: ['Take the road east through the gate.'],
          deliver: ['A Warden, in Whisperroot? We haven’t seen a blue cloak on this road since my mother was a girl.', 'The Ancient Bell has gone silent, strangled in black roots. And a knight in black walks our paths at night. He carries a sword like yours.', 'Your order had a hall here once, in the Root Ruins to the north. The old Warden road still runs there, if you can find the marks.'] } },
      m7: { giver: 'fox', turnIn: 'forester', title: 'The Wardens’ Rune', summary: 'Wake the root rune the Wardens cut under Glowcap Farm, then find Forester Birch.', reward: { xp: 120 },
        text: { offer: ['Glowcap Farm lies west of the ruins. If the Wardens cut the rune, a Warden can wake it.', 'Forester Birch works the timber there. Somebody should tell him the woods are waking.'], progress: ['Glowcap Farm is west of the Root Ruins.'],
          complete: ['A root rune! It hums like a beehive. And you woke it with your bare hand?', 'My gran used to feed the Wardens when they came through. Big eaters, all of them.', 'If you’re after that black knight, talk to Warden Thessaly in Lanternmarket. She’s been hunting him for a week.'],
          after: ['Timber and runes, what a week.'] } },
      m5: { giver: 'forester', to: 'thessaly', title: 'The Watch-Warden', summary: 'Find Warden Thessaly of the city watch in Lanternmarket.', reward: { xp: 80 },
        text: { offer: ['Lanternmarket is the city south-east of here, past the Moonlit Glade. Thessaly is by the great fountain, most days.', 'She’s a Warden too, sort of. The watch borrowed the word from your lot, long ago.'], progress: ['Lanternmarket lies south-east.'],
          deliver: ['A real Warden? The watch only borrowed the name. We never swore the oath.', 'The black knight haunts the Moonlit Glade. He fights travellers, but he has never once hurt a child.', 'And he carries a Warden’s sword. Your order’s sword, Kael.'] } },
      m10: { giver: 'kael-tobb', turnIn: 'ivo', title: 'Briarthorn’s Nest', summary: 'Wake the root rune in the Thornling Nest, then report to Scout Ivo at the Owl Watchtower.', reward: { xp: 150 },
        text: { offer: ['The second rune sleeps in the Thornling Nest, north of the city. It was Briarthorn’s post, before he ran. The thorns grew up after.', 'Wake it, lad. Then tell young Ivo at my tower. He worries.'],
          progress: ['The Thornling Nest is north of the city. The Owl Watchtower is east of it.'],
          complete: ['Two runes! The owls are hooting like mad.', 'Your black knight passed the tower last night, going south-east. He left tracks a child could follow. Almost like he wanted them followed.'],
          after: ['All clear, for now.'] } },
      m11: { title: 'The Black Knight’s Trail', summary: 'Follow the black knight’s trail from the watchtower to Silkshadow Hollow, then report to Ivo.', reward: { xp: 170 },
        clues: ['Deep bootprints, frosted at the edges, though the night was warm.', 'A shadewolf, cut clean in two. A Warden’s stroke: low guard, high cut. Aldric’s.', 'Letters scratched into an oak with a sword point: K… A… E… The rest is gouged away, as if the hand fought itself.', 'His camp in Silkshadow Hollow: no fire, no bedroll. Just a circle in the moss where a knight knelt all night.'],
        text: { offer: ['The knight went south-east, toward Silkshadow Hollow. The owls didn’t like him. They wouldn’t say why.', 'Follow his trail and see where he sleeps. Then come back and tell me.'], progress: ['Follow the knight’s trail south-east from the watchtower.'],
          complete: ['He knelt all night? Like he was keeping a vigil. Or holding something in.', 'Well. The last rune is right here around my tower. It glows green when it wants to be found.'],
          after: ['I watch the south-east now. Mostly I see owls.'] } },
      m12: { title: 'The Tower Rune', summary: 'Wake the last root rune around the Owl Watchtower.', reward: { xp: 140 },
        text: { offer: ['The last rune sleeps somewhere around this tower. Old Tobb used to sit on it to eat his lunch.', 'Wake it and come back to me.'], progress: ['Look around the Owl Watchtower.'],
          complete: ['All three runes are singing! You can feel the Bell trying to answer.', 'But the Old Bellkeeper sent word from Bellhollow: the roots under the village are moving. Go to him, far to the south-west.'],
          after: ['The owls are proud. So am I, a bit.'] } },
      m3: { giver: 'ivo', title: 'The Knight in the Roots', summary: 'Speak with the Old Bellkeeper in Bellhollow.', reward: { xp: 90 },
        text: { offer: ['Bellhollow is far to the south-west. The Bellkeeper rang the Bell every dawn for sixty years. If anyone knows what’s strangling it, he does.'], progress: ['Bellhollow lies far to the south-west.'],
          deliver: ['A Warden. At last. I have been praying for a blue cloak.', 'The Bell did not stop. It is being strangled by a knight made of roots and old green armour: Ser Briarthorn, the last of the Thornhold Wardens.', 'He ran from his oath, and the roots of Whisperroot hid him. Now something has woken him and fed him shadow. And tonight his roots are coming for Bellhollow.'] } },
      m15: { title: 'Ser Briarthorn', summary: 'Face Ser Briarthorn, the Oathbreaker Knight, and ring the Ancient Bell.', cine: { done: 'bell-rung' }, reward: { xp: 360, hearts: 1 },
        text: { offer: ['He fights like a Warden still: shield-rush, root-snares, a ring of thorns when you close in.', 'When he digs in his heels, he charges. When the ground rumbles, his roots are coming. Keep moving.', 'Break the shadow in him, then ring the Bell.'],
          progress: ['The Old Bell stands in the far north-east.'], after: ['The Bell rings! Sixty years, and I never heard it ring like that.'] } },
      m17: { giver: 'kael-briarthorn', title: 'The Wall Briarthorn Grew', summary: 'Light the three Bell-lanterns at the Eastern Gate to wither Briarthorn’s thorn wall.', reward: { xp: 260 },
        text: { offer: ['The thorns across the Eastern Gate are mine. I grew them to keep the Wardens out. I am sorry for it.', 'Light the three Bell-lanterns beside the gate with this flame, and the thorns will remember they were only roots.'],
          progress: ['Three Bell-lanterns by the Eastern Gate, far to the east.'],
          complete: ['(The thorn wall shivers. Far behind you the Bell rings once more, and an old knight is ringing it.)'] } },
    },
    summit: {
      m1: { title: 'The Warden’s Lookout', summary: 'Go through the Eastern Gate and find Sky-warden Ilsa at the Warden’s Lookout.', reward: { xp: 60 },
        text: { offer: ['(An icy wind howls through the Eastern Gate.)', 'Tobb said the Wardens built a lookout at the top of the pass road. If any of my order is left, that’s where they’ll be.'], progress: ['Take the road east through the gate.'],
          deliver: ['A blue cloak on my mountain! I thought the Wardens were a story we told the novices.', 'We are Sky-wardens. The Wardens left us this lookout long ago. We swore to watch, not to fight. Lately I wish we had sworn more.', 'A wraith host is gathering on the heights, Kael. It marches in ranks, like soldiers. And its captain wears a Warden’s helm.'] } },
      m6: { title: 'The Shard in the Hollow', turnIn: 'guide', summary: 'Take the star shard from Crystal Hollow, then return to Ilsa.', reward: { xp: 100 },
        text: { offer: ['Wherever the host marches, it hunts for shards of the fallen star. Get to Crystal Hollow, north of here, before the wraiths do.'], progress: ['Crystal Hollow is north of the Lookout.'],
          complete: ['A star shard! Warm as a little sun. The wraiths will want that badly.', 'That captain’s helm… I have a feeling about it. Look into Mirrorsky Tarn. It shows what the mountain remembers.'],
          after: ['Rest a moment. Your ears are blue.'] } },
      m5: { giver: 'guide', turnIn: 'dov', title: 'What the Mountain Remembers', summary: 'Look into Mirrorsky Tarn, then go on to Quartermaster Dov at Silver Pass.', reward: { xp: 100 },
        text: { offer: ['Mirrorsky Tarn lies east of here. Look into it, and ask it about the helm.', 'Then go on to Silver Pass, north-east of the tarn. Quartermaster Dov holds it with a handful of soldiers. He will need you before the week is out.'],
          progress: ['Mirrorsky Tarn lies east of the Lookout. Silver Pass Camp is north-east of it.'],
          complete: ['You saw the pass, forty winters back? Two squires and a runaway captain. Everyone up here knows that story.', 'And that thing wears his helm now. Stars. Well, it’s coming back for the pass, Warden. Tonight.'],
          after: ['The pass holds. It always has, somehow.'] } },
      m14: { title: 'The Second Stand', summary: 'Hold the Silver Pass barricade against three waves of the wraith host.', reward: { xp: 180 },
        text: { offer: ['Here they come. Wisps first, then the wraiths, marching in step. They learned that from somebody.', 'Two squires held this pass once. Let’s see if a squire and my lads can do it again.'], progress: ['Stand by the barricade and break every wave.'],
          complete: ['The pass holds! My lads have never seen anything like it.', 'Hear that? They’re singing the old Warden song. None of them knows the words, so they’re making them up.'],
          after: ['The pass holds.'] } },
      m12: { giver: 'dov', turnIn: 'kael-brin', title: 'Frostfang’s Heart', summary: 'Take the star shard from Frostfang Crag, then bring it to Warden Brin at the pass.', reward: { xp: 150 },
        text: { offer: ['Frostfang Crag is south-east of the pass. The golems are drawn to the shard’s warmth.', 'Bring it to Brin. She’s been sorting your shields and she’s bored.'], progress: ['Frostfang Crag lies south-east of Silver Pass.'],
          complete: ['Two shards! And not a scratch on you. Well, a few scratches.', 'Listen. The monks of Skyhold sent a runner: the host has been taking prisoners. One of them keeps the old Warden banner.'],
          after: ['Two shards and a Warden. Good week.'] } },
      m10: { giver: 'corvin', title: 'The Banner-keeper', summary: 'Free Brother Ansel from the Void Rift and bring him home to Abbot Corvin in Skyhold.', reward: { xp: 170 },
        captive: person('Brother Ansel', '🧘', { robe: '#c9a24c', hat: 'hood', hatColor: '#a8844a', beard: true, hair: '#8a8a8a' }),
        text: { offer: ['Frost wraiths and wisps guard the Rift. Ansel is old, and not very brave. He will be very glad to see you.', 'Bring him home, Warden.'],
          progress: ['The Void Rift lies south-east of Skyhold. Break the guards, open the cage, and bring Ansel home.'], arrive: ['Skyhold! My own cold bed! I will never complain about it again.'],
          deliver: ['A blue cloak… oh, thank the stars. I thought I would die in a cage.', 'Their captain came to look at me. It wore a Warden captain’s helm, and it called out the old muster calls in a dead man’s voice, like a joke.', 'Get me home, please. My knees are made of ice.'],
          complete: ['Ansel is home, and talking the novices’ ears off. The banner is yours, Ser Kael.', 'He says the wraiths guard the last shard at the Broken Spire. Goatherd Brun knows a goat path up there. His terrace is south-west of the city.'],
          after: ['The banner hangs in the hall again, waiting for you.'] } },
      m15: { giver: 'brun', turnIn: 'kael-brin', title: 'The Goat Path', summary: 'Climb the goat path to the Broken Spire, take the last star shard, and bring it to Brin.', reward: { xp: 140 },
        text: { offer: ['Take the goat path, not the road. The Broken Spire is north-east, past Silver Pass. The shard is at the top.', 'And give that Warden at the pass my regards. And some cheese.'], progress: ['The Broken Spire lies east of Silver Pass. Brin waits at the pass.'],
          complete: ['All three shards. You can feel them humming from here.', 'But the host has gathered around the Star Cradle, rank on rank. It knows we have them.'],
          after: ['Three shards. One Warden, and a bit.'] } },
      m19: { giver: 'kael-brin', title: 'The Frost Marshal', summary: 'Defeat the Frost Marshal at the Star Cradle and return the shards to it.', reward: { xp: 420, hearts: 1 },
        text: { offer: ['The Marshal holds the Star Cradle in the far north-east. It throws volleys of ice, calls blizzards down and blinks right beside you.', 'Crack that helm, lay the three shards in the Cradle, and the star goes home.', 'It was a Warden captain’s helm once, Kael. Take it back.'],
          progress: ['The Star Cradle is in the far north-east.'], after: ['The star is home, and so is the helm.'] } },
      m20: { giver: 'corvin', title: 'The Star-lamp', who: BRIN, summary: 'Walk Warden Brin and the Star-lamp of Skyhold to the Eastern Gate to melt the black ice.', reward: { xp: 350, hearts: 1 },
        text: { offer: ['Umbra fled east and sealed the pass behind it with black ice. Our Star-lamp was lit from the star itself, long ago. Nothing else will melt that ice.', 'Brin came down to carry it. You keep the wraiths off her. Your whole order is waiting at the gate.'],
          progress: ['Lead Brin to the Eastern Gate and keep the wraiths off her.'], arrive: ['There they are. Dov, Ilsa, Ferris, the lads… all in blue. Look at them, Kael.'],
          complete: ['(Brin lifts the Star-lamp to the black ice.) Ready, Ser Kael? Shields up, all of you!'] } },
    },
    ember: {
      m1: { title: 'The Knight’s Road East', summary: 'Follow Umbra’s trail through the Eastern Gate and find Captain Ashka.', reward: { xp: 90 },
        text: { offer: ['(You stare east, where a thread of black smoke crawls over the Summit’s last ridge.)', 'Umbra ran east. The black knight went east. Whatever has Aldric, it’s out there in the Ember Wastes.'], progress: ['Take the road east through the gate.'],
          deliver: ['A Warden? In the Wastes? We have a song about you lot. It isn’t very kind.', 'Two nights ago a knight in black armour walked right past my outpost. My sentries froze. He didn’t even draw his sword.', 'He left prints in the ash, south-east toward Kilnhollow. And every one of them was smoking.'] } },
      m5: { title: 'The Blade Ledger', summary: 'Ask Forgemaster Tovan in Brasshaven about the Dawn Forge.', reward: { xp: 90 },
        text: { offer: ['Brasshaven lies east of here. Tovan works the biggest anvil, and he keeps the oldest books.', 'Tell him Hessa sent you, or he’ll make you wait while he finishes a horseshoe.'], progress: ['Brasshaven lies east of Kilnhollow.'],
          deliver: ['A Warden. Look at that sword. Squire’s steel, good Brasshaven iron. But not a Forge blade.', 'Every true Warden blade was forged at the Dawn Forge by its keeper, Pyrrhus. The ledger lists them all, a thousand names.', 'When the Wardens stopped coming, Pyrrhus went sour and strange, and the Forge went cold.', 'Now its three ember cores are scattered, and something big is being built up there.'] } },
      m6: { title: 'The Core in the Maze', summary: 'Recover the first ember core from the Obsidian Maze.', reward: { xp: 150 },
        text: { offer: ['Wake the Forge, and whatever is being built there has to show itself. One core glows in the Obsidian Maze, far to the north-west.', 'Its walls are sharp as knives. Bring the core back to me.'], progress: ['The Obsidian Maze lies north-west.'],
          complete: ['The first core! Feel that heat. The Forge remembers it already.', 'Bad news from the south-east. Imps raided the Salt Caravan Camp and took Old Pyke, the last smith who ever worked under Pyrrhus.'],
          after: ['One of three.'] } },
      m7: { title: 'The Last Forge-hand', summary: 'Free Old Pyke at the Salt Caravan Camp and bring him to Tovan in Brasshaven.', reward: { xp: 180, hearts: 1 },
        captive: person('Old Pyke', '🧓', { robe: '#5a3a2a', hat: 'cap', hatColor: '#2a1a14', beard: true, hair: '#e8e2d0' }),
        text: { offer: ['Pyke carried coal at the Dawn Forge when he was a boy. If anyone knows what Pyrrhus is building, it’s him.', 'Scorpions and imps have him caged at the camp. Bring him home, Warden.'],
          progress: ['The Salt Caravan Camp lies south-east of the city. Defeat the guards, open the cage, and bring Pyke to Brasshaven.'], arrive: ['Brasshaven. Still ugly. Still standing. Lovely.'],
          deliver: ['A Warden! Hah! Pyrrhus said none of you would ever come back.', 'He’s building a war engine, boy. A colossus of iron, fed with the Forge’s fire. And he wanted a Warden for its heart.', 'Get me to Tovan and I’ll tell you the rest. And mind the scorpions. They like old ankles.'],
          complete: ['Pyke is safe, and very rude. That means he’s well.', 'He wants a word with you. He’s by the anvils, eating all my bread.'],
          after: ['The caravan owes you. So do my bread bins.'] } },
      m14: { giver: 'fenwick', turnIn: 'fenwick', title: 'The Knight in the Salt', who: BLACK_KNIGHT, escapes: true, cine: { caught: 'kael-knight-ember' }, summary: 'Run down the black knight around Saltglass Farm.', reward: { xp: 180 },
        text: { offer: ['There he is again, down by the pans. He runs when anyone comes near, but he stops to breathe. Or whatever it is he does.', 'Catch him, Warden. If he’s yours, bring him home.'],
          progress: ['The black knight lurks around Saltglass Farm. Run him down: he has to stop.'],
          deliver: ['(The black knight stops, and turns, and his sword drops into the salt.)'],
          complete: ['He went to smoke in your hands? Stars. That’s a cruel thing to do to a man.', 'Ashfall Watch, he said? It’s up in the high ash, far to the north. The Ember-seer lives there.'],
          after: ['I left a bucket of clean water in the pans. For him. In case.'] } },
      m10: { giver: 'fox', turnIn: 'seer', title: 'The Last Core', summary: 'Take the last ember core from the Old Foundry, then climb to Ashfall Watch.', reward: { xp: 180 },
        text: { offer: ['Pyke said the last core is in the Old Foundry, north-east of the city.', 'Then Ashfall Watch. He asked me to come. He asked.'], progress: ['The Old Foundry is north-east of the city. Ashfall Watch lies north-west of it.'],
          complete: ['Three cores, and a Warden carrying them. The flames told me you would come.', 'He is here, Warden. At the edge of the Watch. He has been kneeling since sunrise, and the ash will not settle on him.'],
          after: ['The flames are quiet today. Almost kind.'] } },
      m15: { giver: 'fox', title: 'Bellows for the Dawn Forge', summary: 'Gather brass gears at the Old Foundry, then rebuild the Great Bellows at the Dawn Forge.', reward: { xp: 300 },
        text: { offer: ['Four brass gears from the Old Foundry, and the Great Bellows can breathe again.', 'When the Forge breathes, the Colossus wakes. Better it wakes cold and facing me than hot and marching on Brasshaven.'],
          progress: ['Four brass gears from the Old Foundry, then build at the Dawn Forge in the far north-east.'] } },
      m12: { title: 'The Iron Colossus', summary: 'Break the Iron Colossus, the war engine of the Dawn Forge.', reward: { xp: 480, hearts: 1 },
        text: { offer: ['(The ground heaves under the Dawn Forge. The Iron Colossus is awake, and my brothers’ swords are in it.)', 'It slams the earth, rains molten iron and charges like a landslide. Never stand still.', 'Break it, and the Wardens’ steel can rest.'],
          progress: ['The Dawn Forge is in the far north-east.'], after: ['The swords are free.'] } },
      m13: { title: 'The Black Oath', cine: { start: 'kael-black-oath' }, summary: 'Hold the line against Umbra and light the Dawn Forge.', reward: { xp: 900, hearts: 2 },
        text: { offer: ['(The Colossus falls apart into a thousand blades, and every one of them sinks into the ash. The ash turns black and begins to crawl.)', '(From the Beacon Rise, the Old Bell and the Star Cradle, dark light rises. The shadows of every guardian gather into one.)', '(The hair on your neck stands on end. Umbra is here, and it has come dressed as a knight.)'],
          progress: ['Hold the line against Umbra at the Dawn Forge.'] } },
    },
  },
  npcs: {
    meadow: [
      { id: 'kael-brin', name: 'Warden Brin', portrait: '🛡️', at: 'city', dx: 280, dy: -60, activity: 'idle', after: 'kael6', look: look('#3f5a8a', 'helm', { hatColor: '#b8bcc6', hair: '#b8743c' }), lines: ['Two Wardens in one city. Brannoc keeps counting us, like we might wander off.', 'Hilda mends everything. Shields, swords, people. Mostly shields.'], barks: ['Stand fast.', 'Shields up.'] },
      { id: 'kael-fitch', name: 'Fitch the Picker', portrait: '🧒', at: 'city', dx: -40, dy: 320, activity: 'sweep', after: 'kael12', look: look('#6a5a3a', 'cap', { hatColor: '#3a2e22', small: true }), lines: ['I’m not a picker any more. I’m a sweeper. It pays worse.', 'The armour on the Rise… I’m glad it’s you going up there and not me.'], barks: ['Sweep, sweep.'] },
    ],
    woods: [
      { id: 'kael-tobb', name: 'Old Tobb', portrait: '🧓', at: 'city', dx: -60, dy: -60, activity: 'idle', after: 'kael7', look: look('#3f5a8a', 'helm', { hatColor: '#9aa0aa', beard: true, hair: '#e8e2d0' }), lines: ['Forty winters I waited for a blue cloak to come up that road. And look: it’s a boy with a split shield.', 'Aldric? A stubborn little squire. Held the pass with a cracked shield and a runny nose.'], barks: ['Hold the line.', 'Back in my day…'] },
      { id: 'kael-briarthorn', name: 'Ser Briarthorn', portrait: '🌿', at: 'bell', dx: -150, dy: 110, activity: 'idle', after: 'm15', look: OLD_BRIAR, lines: ['I stand. I shield. I stay. I say it every morning now. It gets a little lighter.', 'If you see Tobb, tell him… no. I will tell him myself, one day.'], barks: ['The Bell is kept.'] },
    ],
    summit: [
      { id: 'kael-brin', name: 'Warden Brin', portrait: '🛡️', at: 'pass', dx: -120, dy: -40, activity: 'idle', after: 'kael4', until: 'm20', look: look('#3f5a8a', 'helm', { hatColor: '#b8bcc6', hair: '#b8743c' }), lines: ['The Beacon is guarded. Brannoc swore on his moustache.', 'Aldric’s shield looks right on you. Don’t tell him I said so.'], barks: ['Shields up!'] },
      { id: 'kael-ferris', name: 'Private Ferris', portrait: '💂', at: 'pass', dx: 170, dy: -90, activity: 'patrol', after: 'kael27', look: look('#6a7a8a', 'helm', { hatColor: '#8a8f9a', hair: '#b8743c' }), lines: ['I didn’t run this time. The fires helped.', 'Is it true you said the oath with a new line? The lads are learning it.'], barks: ['Standing!', 'Not running.'] },
    ],
    ember: [
      { id: 'aldric', name: 'Ser Aldric', portrait: '🛡️', at: 'watch', dx: 170, dy: 90, activity: 'idle', after: 'm10', until: 'kael35', look: look('#1a1624', 'helm', { hatColor: '#2a2438', beard: true, hair: '#8a8a8a' }), lines: ['It pulls, lad. Every heartbeat, it pulls.', 'Talk to me. It helps, hearing a Warden’s voice.'], barks: ['Hold…', 'Not yet.'] },
      { id: 'kael-aldric2', name: 'Ser Aldric', portrait: '🛡️', at: 'spring', dx: -120, dy: 60, activity: 'idle', after: 'kael35', look: look('#3f5a8a', 'helm', { hatColor: '#b8bcc6', beard: true, hair: '#8a8a8a' }), lines: ['You grew up while I was gone, Warden.', 'Aldric of the Rise, at your side. Where you go, I go.'], barks: ['For the valley.'] },
      { id: 'kael-pyke', name: 'Old Pyke', portrait: '🧓', at: 'city', dx: 220, dy: 240, activity: 'idle', after: 'm7', look: look('#5a3a2a', 'cap', { hatColor: '#2a1a14', beard: true, hair: '#e8e2d0' }), lines: ['Pyrrhus was a great smith and a small man. Bad mix.', 'Your sword wants a better edge. Leave it with me one day.'], barks: ['Hah!'] },
    ],
  },
  npcFor: {
    // Orrin and Sable’s story happens at the edges of Kael’s: Orrin is never freed from the Rift by him, and the ice
    // seal is broken by the Wardens, so the pair at the gate stay out of it.
    'summit:orrin': { hidden: true },
    'summit:sable2': { hidden: true },
    'summit:orrin2': { hidden: true },
    'summit:sable3': { hidden: true },
    'summit:sable': { lines: ['A blue cloak. The knight in black walked past me on the east road. He didn’t even look at me.', 'He looked like he was trying very hard not to turn around.'], barks: ['…'] },
  },
  script: {
    meadow: {
      sealed: 'The Hollow Bulwark stands locked behind its tower shield. Bring the three sun-crystals home first.',
      pickupKey: 'Sun-crystal brought home! {n}/3',
      tip: 'When the Bulwark lowers its head, it charges: step aside. Shield Wall (learned at level 3) bounces its knives straight back.',
      finale: { locked: ['The Beacon is cold. The Wardens’ three sun-crystals must come home before its guard will stir.'], guarded: ['The Hollow Bulwark stands before the Beacon: nine Wardens’ armour, and maybe Aldric’s. Break it to relight the Beacon.'],
        done: ['You lay the three sun-crystals in the Beacon. Gold light roars up and sweeps across the valley.', 'Nine dented helms lie in the grass where the Bulwark fell. You count them twice. None of them is Aldric’s.', 'He wasn’t in there. Wherever the shadow took him, he is still out there.'] },
      victory: { title: 'The Beacon shines again.', text: 'The Wardens’ fire burns on the Rise once more. Aldric was not among the fallen, and the road east leads into Whisperroot Woods, where a black knight walks.' },
      guide: { done: ['The Beacon is lit, and a Warden lit it. The valley is bright again.'] },
    },
    woods: {
      sealed: 'Ser Briarthorn is wrapped in sleeping roots. Wake the three root runes first.',
      pickupKey: 'Root rune awakened. {n}/3',
      tip: 'Briarthorn charges shield-first and leaves thorns behind him. Sidestep the rush, then hit him while he turns. Earthsplitter knocks his roots loose.',
      finale: { locked: ['The Bell hangs in black roots. Three root runes must wake before its keeper stirs.'], guarded: ['Ser Briarthorn stands on the Bell, sword drawn. Defeat the Oathbreaker to ring it.'],
        done: ['You ring the Ancient Bell. Its voice rolls through every root in Whisperroot, and the shadow in the thorns burns away.', 'Where the Oathbreaker fell, the roots let go of an old man in rusted green armour. He is alive, and he is weeping.'] },
      victory: { title: 'The Bell rings for the Wardens.', text: 'Whisperroot breathes again, and an oathbreaker keeps the Bell. Old Tobb has told the story of the Silver Pass, and the road climbs toward it.' },
      guide: { done: ['The Bell rings, and the woods remember the Wardens again.'] },
    },
    summit: {
      sealed: 'The Frost Marshal waits behind a wall of black ice. Gather the three star shards first.',
      pickupKey: 'Star shard gathered. {n}/3',
      tip: 'The Marshal’s blizzards slow you: dash out of the frost circles. Raise Shield Wall when it throws a volley, and the ice flies back at it.',
      finale: { locked: ['The Cradle is cold. Three star shards are needed.'], guarded: ['The Frost Marshal holds the Cradle, in a Warden captain’s helm. Defeat it!'],
        done: ['You lay the three shards in the Cradle. The star remembers its light and rises, whole, into the sky.', 'In the snow lies an old Warden captain’s helm, cracked through. Briarthorn’s. You tie it to your belt. Tobb will want to see it.', 'But a thread of black smoke tears loose from the star and streaks east, toward the Ember Wastes. Umbra is running.'] },
      victory: { title: 'The Wardens hold the pass.', text: 'The star is home, the Wardens have a banner again, and Kael is a Warden in his own right. But Umbra fled east into the Ember Wastes, and so did the black knight.' },
      guide: { done: ['The sky is whole, and the Lookout has Wardens again.'] },
    },
    ember: {
      sealed: 'The Iron Colossus sleeps in a shell of cooling iron. Recover the three ember cores first.',
      pickupKey: 'Ember core recovered. {n}/3',
      tip: 'The Colossus slams the earth: dash out of the glowing circles. When it charges, step aside and let it hit the rocks. Bladestorm halves the harm you take.',
      finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['Umbra stands before the Forge in the shape of a black knight. Hold the line!'],
        done: ['You set the three ember cores into the Dawn Forge. Its fire roars up, white and gold, and a new dawn spills across the wastes.', 'Umbra’s last shadow burns away like morning mist. It asked you to step aside. You didn’t.', 'Beside you, Ser Aldric takes off his helm and laughs. Far to the west, the Star, the Bell and the Beacon shine back.'] },
      victory: { title: 'The line held.', text: 'Umbra is gone for good. The Dawn Forge burns again, Ser Aldric is home, and the Wardens of the valley stand once more, led by the squire who kept his oath.' },
      guide: { done: ['The wastes are cooling. And a Warden walks my outpost. Who’d have thought.'] },
    },
  },
  cines: {
    // ─────────────── Chapter I
    'kael-bulwark': [
      { at: 'meadow:rise', cut: true, dy: -40, night: .65, text: 'That night, on the Beacon Rise, the armour of the fallen Wardens began to move.', fx: [{ kind: 'shadow', dx: -60, dy: 40 }, { kind: 'shadow', dx: 80, dy: 20, delay: .6 }], dur: 4.4 },
      { text: 'Helm to helm, plate to plate, the shadow stitched them together…', fx: [{ kind: 'quake' }, { kind: 'gloom', n: 3, delay: .4 }], dur: 3.8 },
      { text: '…into one hollow knight as tall as a barn, with a tower shield as wide as a door.', fx: [{ kind: 'shadow', dy: -20 }, { kind: 'ring', dy: -20, delay: .6 }], dur: 4.4 },
      { at: 'hero', cut: true, night: 0, speaker: 'Kael', portrait: '⚔️', text: '“If Aldric’s armour is inside that thing… then I’ll bring that home too.”', dur: 4 }],
    'beacon-lit@kael': [
      { at: 'meadow:rise', dy: -90, text: 'The Beacon roars back to life. Gold light spills across the meadow.', fx: [{ kind: 'light', dy: -90 }], dur: 4 },
      { at: 'meadow:rise', dy: 40, text: 'The Hollow Bulwark comes apart. Nine dented helms roll into the grass, and none of them is Aldric’s.', fx: [{ kind: 'collapse', dy: 40 }], dur: 4.6 },
      { at: 'hero', speaker: 'Kael', portrait: '⚔️', text: '“He wasn’t in there. Then he’s still out there. Somewhere.”', dur: 3.6 },
      { at: 'obj:meadow:barrier', cut: true, text: 'The Beacon’s light reaches all the way to the Eastern Gate, where the Gloomwater Bridge lies broken in the river.', fx: [{ kind: 'collapse' }], dur: 4.6 },
      { at: 'npc:meadow:holt', text: 'Bridgewright Holt is already there, staring at the wreck and scratching his head.', dur: 3.6 }],
    'chapter-meadow@kael': [
      { at: 'obj:meadow:barrier', text: 'Plank by plank, forty farmers and a squire raise the Gloomwater Bridge.', fx: [{ kind: 'build' }], actors: [{ id: 'cbram', name: 'Farmer Bram', look: LOOKS.bram, dx: -150, dy: 70 }], dur: 4 },
      { at: 'obj:meadow:barrier', dx: 900, text: 'Beyond it, the old Warden road dives under ancient trees: Whisperroot Woods.', dur: 3.8 },
      { at: 'woods:glade', cut: true, night: .5, text: 'Among the trees, a knight in black armour stops, and turns toward the sound of hammers.', actors: [{ id: 'cbk', name: 'The Black Knight', look: LOOKS.blackKnight, dy: 40 }], fx: [{ kind: 'shadow', dy: 40, delay: 2 }], dur: 4.6 },
      { at: 'woods:bell', cut: true, night: 0, dy: -60, text: 'Deeper still, the Ancient Bell hangs silent, strangled in black roots.', fx: [{ kind: 'shadow', dy: -60 }], dur: 4 },
      title('Chapter II', 'The Bell Beneath the Roots')],
    // ─────────────── Chapter II
    'kael-oathstones': [
      { at: 'woods:ruins', text: 'The last oath-stone flares, and Thornhold remembers.', fx: [{ kind: 'memory' }], dur: 3.4 },
      { night: .4, text: 'Banners, torchlight, and a captain in green armour before two kneeling squires.', actors: [{ id: 'obriar', name: 'Captain Briarthorn', look: BRIAR, dx: -70, dy: 20, face: 1 }, { id: 'oald', name: 'Young Aldric', look: LOOKS.youngAldric, dx: 30, dy: 60, face: -1 }, { id: 'otobb', name: 'Young Tobb', look: LOOKS.youngTobb, dx: 90, dy: 50, face: -1 }], fx: [{ kind: 'embers', dy: 40, delay: .5 }], dur: 5 },
      { speaker: 'Captain Briarthorn', portrait: '🌿', text: '“Say it with me, squires. I stand. I shield. I stay.”', dur: 4 },
      { text: 'Of the three who spoke the oath that night, one would break it.', fx: [{ kind: 'memory', delay: 1 }], dur: 4 },
      { at: 'hero', night: 0, text: 'The hall is empty again. Only the oath-stones hum.', dur: 3.2 }],
    'kael-tobb-tale': [
      { at: 'npc:woods:kael-tobb', night: .35, text: '(Old Tobb sits down by the fountain and, for the first time in forty winters, tells the story.)', fx: [{ kind: 'memory' }], dur: 4 },
      { at: 'summit:pass', cut: true, night: .6, text: 'The Silver Pass. The wraith host came over the ridge, and Captain Briarthorn saw how many there were.', actors: [{ id: 'tbriar', name: 'Captain Briarthorn', look: BRIAR, dx: 40, dy: 40, walk: { dx: -520, dy: 60 } }], fx: [{ kind: 'wisps', n: 4, dx: 300, dy: -120 }, { kind: 'frost', delay: .6 }], dur: 5 },
      { text: 'He threw down his helm and ran. Something pale drifted out of the snow and picked it up.', fx: [{ kind: 'frost', dx: 60 }, { kind: 'wisps', n: 1, dx: 60, delay: .8 }], dur: 4.4 },
      { text: 'Two squires held the pass alone until dawn: Tobb, and a boy called Aldric.', actors: [{ id: 'tald', name: 'Young Aldric', look: LOOKS.youngAldric, dx: -60, dy: 30, face: 1 }, { id: 'ttobb', name: 'Young Tobb', look: LOOKS.youngTobb, dx: 60, dy: 30, face: -1 }], fx: [{ kind: 'embers', dy: 40, delay: .5 }], dur: 4.6 },
      { at: 'npc:woods:kael-tobb', cut: true, night: .35, speaker: 'Old Tobb', portrait: '🧓', text: '“Briarthorn ran into these very woods, lad. The roots took him in. And that pale thing in his helm… it’s still up on that mountain.”', dur: 5 },
      { at: 'hero', night: 0, text: 'Hold the line where I cannot. Aldric learned it on that pass.', dur: 3.6 }],
    'bell-rung@kael': [
      { at: 'woods:bell', dy: -80, text: 'The Ancient Bell rings out, and the black roots fall away from it like old rope.', fx: [{ kind: 'light', dy: -80 }, { kind: 'wither', dy: -20, delay: .6 }], dur: 4.2 },
      { at: 'npc:woods:kael-briarthorn', text: 'Where the Oathbreaker fell lies an old man in rusted green armour. The roots have let him go.', dur: 4.4 },
      { at: 'obj:woods:barrier', cut: true, text: 'But far to the east, the wall of thorns he grew still stands across the Eastern Gate.', fx: [{ kind: 'shadow' }], dur: 4 }],
    'chapter-woods@kael': [
      { at: 'obj:woods:barrier', text: 'The Bell-lanterns blaze, and the Bell’s voice rolls down the road after you…', fx: [{ kind: 'light' }], dur: 3.6 },
      { text: '…and Briarthorn’s thorn wall remembers it was only roots, and withers into dust.', fx: [{ kind: 'wither' }], dur: 4 },
      { at: 'summit:pass', cut: true, night: .5, text: 'High above, on the Silver Pass, a wraith host gathers in ranks under a captain in an old Warden’s helm.', fx: [{ kind: 'wisps', n: 5, dx: 200, dy: -100 }, { kind: 'frost', delay: .5 }], dur: 5 },
      { at: 'hero', cut: true, night: 0, text: 'Kael tightens the straps on Aldric’s shield and starts to climb.', dur: 3.4 },
      title('Chapter III', 'The Hollow Star')],
    // ─────────────── Chapter III
    'tarn-vision@kael': [
      { at: 'summit:tarn', text: 'You look into Mirrorsky Tarn and ask it about the helm. The water goes as still as glass…', fx: [{ kind: 'memory' }], dur: 4 },
      { at: 'summit:pass', cut: true, night: .6, text: '…and shows the Silver Pass, forty winters ago. A Warden captain throws his helm down in the snow, and runs.', actors: [{ id: 'vbriar', name: 'Captain Briarthorn', look: BRIAR, dx: 30, dy: 40, walk: { dx: -480, dy: 40 } }], fx: [{ kind: 'wisps', n: 3, dx: 320, dy: -100 }], dur: 5 },
      { text: 'A frost wraith lifts the helm and sets it on its own pale head. Behind it, the whole host bows.', fx: [{ kind: 'frost', dx: 40 }, { kind: 'shadow', dx: 40, delay: .8 }], dur: 4.6 },
      { at: 'summit:frostfang', cut: true, night: 0, text: 'Then the shard at your belt glows, and the tarn answers with two more lights: one high on Frostfang Crag,', fx: [{ kind: 'ring' }], dur: 4 },
      { at: 'summit:spire', cut: true, text: 'and one at the Broken Spire. The shards of the fallen star, that the host is hunting.', fx: [{ kind: 'ring' }], dur: 3.8 }],
    'pass-siege@kael': [
      { at: '$ward', night: .4, text: 'Over the ridge comes the wraith host: wisps in front, frost wraiths behind, marching in step like soldiers.', fx: [{ kind: 'wisps', n: 5, dx: 420, dy: -200 }, { kind: 'frost', dx: 300, dy: -160, delay: .6 }], dur: 4.6 },
      { at: '$ward', dx: 520, dy: -260, text: 'Far behind them, a tall pale shape in a Warden captain’s helm raises its sword.', fx: [{ kind: 'shadow', delay: .4 }], dur: 4 },
      { at: '$ward', night: 0, speaker: 'Quartermaster Dov', portrait: '💂', text: '“Shields up, lads! Stand by the Warden!”', dur: 3.4 }],
    'kael-knighted': [
      { at: 'npc:summit:kael-brin', night: .5, text: 'On the Silver Pass, by the light of three Warden fires, Kael kneels in the snow.', fx: [{ kind: 'kindle', dx: -120, dy: -20 }, { kind: 'kindle', dx: 140, dy: -10, delay: .3 }, { kind: 'embers', delay: .6 }], dur: 4.4 },
      { speaker: 'Warden Brin', portrait: '🛡️', text: '“By the fires of the Pass and the oath of the Rise: rise, Ser Kael, Warden of the valley.”', dur: 4.6 },
      { night: 0, text: 'Dov’s soldiers bang their shields. The Sky-wardens sing the old song, and nobody knows all the words.', fx: [{ kind: 'ring' }], dur: 4.2 },
      title('Ser Kael', 'Warden of the Valley')],
    'star-rises@kael': [
      { at: 'summit:cradle', dy: -40, text: 'The Frost Marshal bursts like a frozen lake, and an old Warden captain’s helm rolls to Kael’s feet.', fx: [{ kind: 'frost' }, { kind: 'shatter', delay: .5 }], dur: 4.4 },
      { at: 'summit:cradle', dy: -100, text: 'The three shards fly home, and the star rises from its Cradle, whole again.', fx: [{ kind: 'light', dy: -100 }], dur: 4 },
      { text: 'But a thread of black smoke tears loose from the star…', fx: [{ kind: 'smoke', dy: -100, to: { dx: 1600, dy: 900 } }], dur: 3.6 },
      { at: 'obj:summit:barrier', cut: true, text: '…and flees east. Behind it, black ice creeps over the Eastern Gate and seals the pass.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .3 }], dur: 4.6 },
      { at: 'hero', cut: true, speaker: 'Kael', portrait: '⚔️', text: '“East. Where the black knight went. Hold on, Ser. I’m coming.”', dur: 3.8 }],
    'chapter-summit@kael': [
      { at: 'obj:summit:barrier', text: 'At the Eastern Gate the new Wardens raise their shields around Brin, and Brin lifts the Star-lamp of Skyhold.', actors: [{ id: 'sbrin', name: 'Warden Brin', look: LOOKS.brin, dx: -170, dy: 20 }, { id: 'sdov', name: 'Quartermaster Dov', look: DOV, dx: -240, dy: 100 }, { id: 'silsa', name: 'Sky-warden Ilsa', look: ILSA, dx: -240, dy: -60 }], fx: [{ kind: 'light', dx: -170, delay: .6 }], dur: 5 },
      { text: 'Starfire pours into the black ice. It hisses, and groans, and cracks from end to end…', fx: [{ kind: 'kindle' }, { kind: 'quake', delay: .8 }], dur: 4.2 },
      { text: '…and shatters.', fx: [{ kind: 'shatter' }], dur: 3 },
      { at: 'summit:spire', cut: true, text: 'On a far ridge, a girl in a black cloak watches the Wardens for a long moment. Then she turns away.', actors: [{ id: 'ssable', name: 'Sable', look: LOOKS.sable, dy: 40 }], dur: 4.4 },
      { at: 'ember:forge', cut: true, dy: -60, text: 'Beyond lie the Ember Wastes. Under the cold Dawn Forge, something enormous and made of iron is waiting for a heart.', fx: [{ kind: 'quake' }], dur: 5 },
      title('Chapter IV', 'The Dawn Forge')],
    // ─────────────── Chapter IV
    'kael-knight-ember': [
      { at: '$thief', text: 'The black knight stumbles in the salt and falls to one knee. His sword drops from his hand.', dur: 4 },
      { speaker: 'The Black Knight', portrait: '🖤', text: '“Kael… Ashfall. Where the ash falls. Come to me there, before it takes me back—”', dur: 4.4 },
      { text: 'Shadow tears him apart into smoke, and the smoke streams away north, toward the high ash.', fx: [{ kind: 'shadow' }, { kind: 'smoke', to: { dx: 2000, dy: -2400 } }], dur: 4.2 }],
    'kael-shadow-returns': [
      { at: '$ward', night: .5, text: 'The ash stops falling. Every shadow on Ashfall Watch turns toward Ser Aldric.', fx: [{ kind: 'shadow', dx: 60 }, { kind: 'imps', n: 4, dx: 380, dy: -160, delay: .6 }], dur: 4.4 },
      { speaker: 'Ser Aldric', portrait: '🛡️', text: '“It wants me back, lad. I can’t fight it. I can only kneel, and not go.”', dur: 4 },
      { at: 'hero', speaker: 'Kael', portrait: '⚔️', text: '“Then kneel, Ser. I’ll stand. Hold the line where you can’t: that was the order.”', dur: 4.4 }],
    'kael-spring': [
      { at: 'npc:ember:kael-aldric2', text: 'Aldric wades into the Phoenix Spring, and the last of the black burns off his armour like frost in the sun.', fx: [{ kind: 'light', dy: -30 }, { kind: 'embers', delay: .5 }], dur: 4.6 },
      { text: 'For the first time since the Rise, he takes off his helm.', dur: 3.4 },
      { speaker: 'Ser Aldric', portrait: '🛡️', text: '“I heard you, you know. In the dark. Every time you said my words, it let go of me a little.”', dur: 4.6 },
      { speaker: 'Ser Aldric', portrait: '🛡️', text: '“Now. Pyrrhus built an engine out of our swords. Let’s go and take them back.”', dur: 4 }],
    'pyrrhus-wakes@kael': [
      { at: 'ember:forge', dy: -60, text: 'The Great Bellows heave. For the first time in years, the Dawn Forge breathes.', fx: [{ kind: 'build' }], dur: 3.8 },
      { at: 'ember:forge', dy: -20, text: 'Over the anvil flickers a ghost of cinders: Pyrrhus, the last keeper of the Forge.', actors: [{ id: 'gpyr', name: 'Pyrrhus', look: PYRRHUS, dy: 30, spirit: true }], fx: [{ kind: 'embers' }], dur: 4.2 },
      { speaker: 'Pyrrhus', portrait: '🔥', text: '“The Wardens forgot my Forge. So I made them a new Warden, out of their own swords.”', dur: 4.4 },
      { text: 'The ground splits, steam screams out of the quench-vents, and the Iron Colossus rises out of the magma, cold and furious.', fx: [{ kind: 'quake' }, { kind: 'smoke', delay: .3 }, { kind: 'fire', n: 2, t: 30, delay: .5 }], dur: 5 }],
    'kael-black-oath': [
      { at: 'ember:forge', dy: -40, text: 'Out of the Forge’s shadow rises Umbra, in the shape of a knight in black, with a shield as dark as the sky between stars.', fx: [{ kind: 'shadow', dy: -40 }, { kind: 'quake', delay: .4 }], dur: 5 },
      { speaker: 'Umbra', portrait: '🌑', text: '“Little Warden. Step aside, and I give him back to you. Aldric, whole and safe, forever.”', dur: 4.6 },
      { speaker: 'Umbra', portrait: '🌑', text: '“Hold your line, and I take him again. And you with him.”', dur: 4 },
      { at: 'hero', speaker: 'Kael', portrait: '⚔️', text: '“He taught me what a Warden says when the dark asks nicely.”', dur: 4 },
      { speaker: 'Kael', portrait: '⚔️', text: '“I stand. I shield. I stay.”', dur: 3.4 }],
    'chapter-ember@kael': [
      { at: 'ember:forge', dy: -60, text: 'The Dawn Forge burns white and gold, and a new dawn spills across the wastes.', fx: [{ kind: 'light', dy: -60 }], dur: 4.4 },
      { at: 'summit:pass', cut: true, text: 'On the Silver Pass, three Warden fires burn in a row.', fx: [{ kind: 'kindle' }], dur: 3.4 },
      { at: 'woods:bell', cut: true, dy: -60, text: 'In Whisperroot, an old knight rings the Bell for the dawn.', fx: [{ kind: 'light', dy: -60 }], dur: 3.6 },
      { at: 'meadow:rise', cut: true, dy: -80, text: 'And on the Beacon Rise, where it all began, two Wardens plant a new blue banner beside the flame.', actors: [{ id: 'eald', name: 'Ser Aldric', look: LOOKS.aldric, dx: -70, dy: 110 }, { id: 'ekael', name: 'Kael', look: LOOKS.kael, dx: 40, dy: 120, face: -1 }], fx: [{ kind: 'light', dy: -80 }], dur: 5 },
      title('Every light is shining', 'The line held', 4)],
  },
};
