import { LOOKS, type Shot } from '../cutscenes';
import { look, own, person, type HeroStory } from './kit';

// Lyra, the Frostborn. The night the star fell, her little sister Nessa, a courier, vanished on the meadow's lake road.
// Lyra is a Rimeward of the Silver Heights, a family of frost-singers: two sisters in every generation, one voice of
// cold and one of warmth, singing the Rime Song. Long ago two Rimewardens sang a crown of frost around the star to keep
// its light bright. When the star fell, that frost fell with it, and Umbra crowned it: Queen Hoarfrost, frost without
// any warmth, who wants both sisters' voices to seal the mountain in ice forever.
// When Lyra was twelve she sang the song alone, and her cold froze Gran's glasshouse with Nessa inside. Nessa's hair
// has been white ever since, and Lyra has kept her frost, and everyone else, at arm's length. Umbra's shadow takes the
// shape of what she fears: cold that takes and keeps (a lake serpent, a pale rider with her own face, a queen of ice,
// a serpent of fire that hates all frost) and at last an endless winter night. Her story: the lost post and the lake
// (meadow), the wraiths' trail and the Pale Huntress (woods), home, Nessa and the family's secret (summit), and frost
// that is needed in a land of fire (ember), until the sisters sing together.
const q = own('lyra');
const NESSA = person('Nessa', '👧', { robe: '#6f8fb8', hat: 'scarf', hatColor: '#dff6ff', hair: '#e8e2d0', small: true });
const COURIER = look('#c16d59', 'cap', { hatColor: '#6f8fb8', hair: '#b8743c' });
const HUNTRESS = look('#e8f4ff', 'hood', { hatColor: '#bfe8ff', skin: '#e8f4ff', hair: '#ffffff' });
const RIME_COLD = look('#dff6ff', 'hood', { hatColor: '#8ee8ff', hair: '#e8e2d0' });
const RIME_WARM = look('#f0e6d8', 'scarf', { hatColor: '#ffb38a', hair: '#e8e2d0' });

const cines: Record<string, Shot[]> = {
  // ─────────────── Chapter I
  'lyra-lake-memory': [
    { at: 'meadow:mirror', dx: 200, dy: -560, night: .6, text: '(The frost runes ring like bells. Ice races across the water, and the lake remembers.)', fx: [{ kind: 'frost' }, { kind: 'memory', delay: .6 }], dur: 4 },
    { text: 'Nessa, the night the star fell, running along this very shore with her satchel clutched to her chest.', actors: [{ id: 'enessa', name: 'Nessa', look: LOOKS.nessa, dx: -300, dy: 30, walk: { dx: 460, dy: 40 } }], dur: 4.6 },
    { text: 'Pale riders drift out of the reeds behind her, on horses made of mist.', fx: [{ kind: 'wisps', n: 3, dx: -260 }, { kind: 'frost', dx: -200, delay: .5 }], dur: 4 },
    { speaker: 'Nessa', portrait: '👧', text: '“You’re not having the post! Nobody gets the post!”', fx: [{ kind: 'letters', dx: 160, dy: 200, delay: .4 }], dur: 3.6 },
    { at: 'meadow:mirror', text: 'She flings the satchel far out over the water… and something vast and green rises out of the deep to swallow it.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .4 }], dur: 4.6 },
    { at: 'hero', night: 0, speaker: 'Lyra', portrait: '❄️', text: '“Frost wraiths, from the Summit. And a serpent in the lake. Hold on, Nessa. I’m coming.”', dur: 4 }],
  'lyra-last-letter': [
    { at: 'meadow:rise', dy: -90, text: 'The Beacon roars back to life, and gold light spills across the meadow.', fx: [{ kind: 'light', dy: -90 }], dur: 3.8 },
    { at: 'hero', text: 'Lyra breaks the wax seal with cold fingers.', fx: [{ kind: 'letters' }], dur: 3 },
    { speaker: 'Nessa’s letter', portrait: '✉️', text: '“Lyra. It’s been three winters. Come down from the mountain. I’m not afraid of your frost. I never was.”', dur: 5 },
    { speaker: 'Nessa’s letter', portrait: '✉️', text: '“Pale riders keep asking at the post house for ‘the Rimeward girls’. I told them to go and boil their heads. Love, N.”', dur: 5 },
    { at: 'obj:meadow:barrier', cut: true, text: 'Far to the east, the Gloomwater Bridge lies broken in the river. On the far bank, a white mist hangs under the trees.', fx: [{ kind: 'collapse' }, { kind: 'frost', dx: 300, delay: .8 }], dur: 4.8 },
    { at: 'npc:meadow:holt', text: 'Bridgewright Holt is already there, staring at the wreck and scratching his head.', dur: 3.6 }],
  'chapter-meadow@lyra': [
    { at: 'obj:meadow:barrier', text: 'Plank by plank, the Gloomwater Bridge stands again, over the water Nessa crossed.', fx: [{ kind: 'build' }], dur: 3.8 },
    { at: 'obj:meadow:barrier', dx: 900, text: 'Beyond it, the road dives under ancient trees, and a cold white mist lies between the trunks.', fx: [{ kind: 'frost' }], dur: 4 },
    { at: 'woods:bell', cut: true, dy: -60, text: 'Deep in Whisperroot, a pale rider sits wound around the silent Bell, and the mist pours off her like breath.', actors: [{ id: 'chunt', name: '???', look: HUNTRESS, dy: 40, spirit: true }], fx: [{ kind: 'frost', dy: -60 }, { kind: 'shadow', dy: -60, delay: .6 }], dur: 5 },
    { title: 'Chapter II', sub: 'The Bell Beneath the Roots', dur: 3.4 }],
  // ─────────────── Chapter II
  'rider-flees@lyra': [
    { at: '$thief', text: 'The pale rider shrieks, and a gust of snow tears it free of your grip.', fx: [{ kind: 'frost' }], dur: 3.6 },
    { dy: -200, text: 'It streaks away north-east over the treetops, toward the Old Bell, where the mist is thickest.', fx: [{ kind: 'lantern', to: { dx: 1400, dy: -1400 } }, { kind: 'wisps', n: 2, delay: .8 }], dur: 4 },
    { at: 'woods:bell', cut: true, dy: -40, night: .4, text: 'There, wound around the silent Bell, a pale woman on a horse of fog lifts her head, and listens.', actors: [{ id: 'fhunt', name: 'The Pale Huntress', look: HUNTRESS, dy: 40, spirit: true }], fx: [{ kind: 'frost', dy: -40 }], dur: 4.6 },
    { at: 'hero', night: 0, speaker: 'Lyra', portrait: '❄️', text: '“Observatory. So Nessa is on the Summit. But first, you and I are going to have words.”', dur: 3.8 }],
  'lyra-huntress': [
    { at: 'woods:bell', dy: -80, text: 'The Ancient Bell rings out, and the winter mist tears apart like wet paper.', fx: [{ kind: 'light', dy: -80 }, { kind: 'ring', dy: -80, delay: .4 }], dur: 3.8 },
    { at: 'woods:bell', dy: 30, text: 'The Pale Huntress kneels in the melting frost. Her hood slips back.', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], dur: 4 },
    { text: 'Under it is Lyra’s own face: older, colder, and with no one standing beside it.', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], fx: [{ kind: 'frost', dx: 40 }], dur: 4.2 },
    { speaker: 'The Pale Huntress', portrait: '👻', text: '“You froze her once. I only finished what you started. Stay alone, frost-daughter. It is safer for everyone.”', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], dur: 5 },
    { text: 'Then she is mist, and the mist is gone.', fx: [{ kind: 'wither', dx: 40 }], dur: 3 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“That’s what I’d become if I stopped looking for her. …I won’t.”', dur: 4 }],
  'chapter-woods@lyra': [
    { at: 'obj:woods:barrier', text: 'The Bell-lanterns blaze, and the Bell’s last echo rolls down the road…', fx: [{ kind: 'light' }], dur: 3.4 },
    { text: '…and the wall of thorns at the Eastern Gate withers into dust.', fx: [{ kind: 'wither' }], dur: 3.4 },
    { at: 'summit:observatory', cut: true, dy: -60, night: .5, text: 'High on the Silver Heights, in the Old Observatory, a white-haired girl sits in a cage of ice, singing half a song.', actors: [{ id: 'cnessa', name: 'Nessa', look: LOOKS.nessa, dy: 40 }], fx: [{ kind: 'frost', dy: -20 }], dur: 5 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'Above her, in the Star Cradle, a queen of ice listens to every note.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'shadow', dy: -80, delay: .5 }], dur: 4.4 },
    { title: 'Chapter III', sub: 'The Hollow Star', dur: 3.4 }],
  // ─────────────── Chapter III
  'lyra-reunion': [
    { at: 'npc:summit:aune', night: .4, text: 'That night, by Aune’s fire, the Rimeward sisters sit side by side for the first time in three winters.', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], fx: [{ kind: 'embers', dy: 30 }], dur: 4.6 },
    { speaker: 'Nessa', portrait: '👧', text: '“You can hug me, you know. I won’t break. I’m not glass.”', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], dur: 3.6 },
    { text: 'Lyra’s arms are cold. Nessa doesn’t let go anyway.', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], fx: [{ kind: 'frost', dx: -30, dy: 40 }], dur: 3.6 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'High above, in the Star Cradle, a crown of ice turns toward the hamlet… and the wind begins to rise.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'shadow', dy: -60, delay: .5 }], dur: 4.6 }],
  'lyra-blizzard': [
    { at: 'summit:hamlet', night: .6, text: 'The wind howls down from the Cradle, and snow buries Frostpine Hamlet to the windowsills.', fx: [{ kind: 'frost', n: 3 }, { kind: 'snuff', dx: -150, delay: .6 }, { kind: 'snuff', dx: 150, delay: 1 }], dur: 4.4 },
    { text: 'In the storm, a voice like cracking ice: “Come home, daughters. Come home and sing for me.”', fx: [{ kind: 'shadow', delay: .3 }], dur: 4.4 },
    { speaker: 'Nessa', portrait: '👧', text: '“That’s her. The Queen. …I’ve got a flint. You do the ice, I’ll do the fire. Like Gran used to say.”', dur: 4.2 }],
  'tarn-vision@lyra': [
    { at: 'summit:tarn', text: 'The sisters look into Mirrorsky Tarn together. The water goes as still as glass…', fx: [{ kind: 'memory' }], dur: 3.6 },
    { at: 'summit:cradle', cut: true, dy: -60, night: .5, text: '…and shows the Star Cradle, long ago. Two sisters in white stand beneath the star, singing.', actors: [{ id: 'rime1', name: 'Rimeward', look: RIME_COLD, dx: -60, dy: 60, spirit: true }, { id: 'rime2', name: 'Rimeward', look: RIME_WARM, dx: 40, dy: 60, face: -1, spirit: true }], fx: [{ kind: 'frost', dy: -60 }], dur: 5 },
    { text: 'One voice cold, one voice warm. A crown of frost rises around the star and keeps its light bright.', actors: [{ id: 'rime1', name: 'Rimeward', look: RIME_COLD, dx: -60, dy: 60, spirit: true }, { id: 'rime2', name: 'Rimeward', look: RIME_WARM, dx: 40, dy: 60, face: -1, spirit: true }], fx: [{ kind: 'ring', dy: -90 }, { kind: 'light', dy: -90, delay: .6 }], dur: 4.6 },
    { text: 'Then the star falls, and its frost falls with it. Out of the dark, a shadow sets that frost on the throne like a queen.', fx: [{ kind: 'starfall', dy: -90 }, { kind: 'shadow', dy: -60, delay: 1 }], dur: 4.8 },
    { at: 'summit:crystal', cut: true, night: 0, text: 'Then three lights: one in Crystal Hollow,', fx: [{ kind: 'ring' }], dur: 2.6 },
    { at: 'summit:frostfang', cut: true, text: 'one on Frostfang Crag,', fx: [{ kind: 'ring' }], dur: 2.4 },
    { at: 'summit:spire', cut: true, text: 'and one at the Broken Spire: the shards of the fallen star.', fx: [{ kind: 'ring' }], dur: 3.4 }],
  'lyra-two-voices': [
    { at: 'summit:altar', night: .4, text: 'Nessa sings, and Lyra sings with her: one voice cold, one voice warm, for the first time since the glasshouse.', actors: [{ id: 'snessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 60 }], fx: [{ kind: 'ring' }, { kind: 'frost', delay: .6 }], dur: 5 },
    { text: 'Snow begins to fall around the altar, soft and slow. It doesn’t bite. Underneath it, the grass is green.', actors: [{ id: 'snessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 60 }], fx: [{ kind: 'light', delay: .4 }], dur: 4.6 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'In the Star Cradle, Queen Hoarfrost rises from her throne of ice, and the black star shivers behind her.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'quake', delay: .4 }], dur: 4.6 },
    { speaker: 'Queen Hoarfrost', portrait: '👑', text: '“Two voices. At last. Come to me, daughters, and sing the mountain to sleep.”', dur: 4.4 }],
  'star-rises@lyra': [
    { at: 'summit:cradle', dy: -100, text: 'Queen Hoarfrost’s crown cracks, and all her frost comes loose at once, a hundred years of winter falling like snow.', fx: [{ kind: 'shatter', dy: -60 }, { kind: 'frost', dy: -60, delay: .4 }], dur: 4.6 },
    { text: 'The star drinks the shards and rises, whole again. Its crown of frost settles round it, soft and bright, the way the Rimewardens sang it.', fx: [{ kind: 'light', dy: -100 }], dur: 4.6 },
    { text: 'But a thread of black smoke tears loose from where the Queen stood…', fx: [{ kind: 'smoke', dy: -100, to: { dx: 1600, dy: 900 } }], dur: 3.6 },
    { at: 'obj:summit:barrier', cut: true, text: '…and flees east. Behind it, black ice creeps over the Eastern Gate: cold without a spark of warmth in it.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .3 }], dur: 4.6 },
    { at: 'hero', text: 'Lyra touches the frost on her sleeve. It is warm. Somewhere down in Skyhold, Nessa is still singing.', dur: 4 }],
  'chapter-summit@lyra': [
    { at: 'obj:summit:barrier', text: 'The sisters sing, one voice cold and one voice warm, and frost that remembers warmth creeps over the black ice.', actors: [{ id: 'gnessa', name: 'Nessa', look: LOOKS.nessa, dx: -170, dy: 40 }], fx: [{ kind: 'frost', delay: .4 }, { kind: 'light', delay: 1.2 }], dur: 4.8 },
    { text: 'The black ice cracks from end to end, and shatters into snow.', actors: [{ id: 'gnessa', name: 'Nessa', look: LOOKS.nessa, dx: -170, dy: 40 }], fx: [{ kind: 'shatter' }], dur: 3.4 },
    { at: 'ember:forge', cut: true, dy: -60, text: 'Beyond lie the Ember Wastes, where the Dawn Forge has gone cold… and a serpent of fire lies coiled around it, hating everything that is cold.', fx: [{ kind: 'fire', n: 2, t: 60 }, { kind: 'quake', delay: .4 }], dur: 5 },
    { title: 'Chapter IV', sub: 'The Dawn Forge', dur: 3.4 }],
  // ─────────────── Chapter IV
  'lyra-first-snow': [
    { at: 'ember:green', text: 'The Last Green: a handful of thirsty trees, their leaves curled brown at the edges.', dur: 3.6 },
    { at: 'hero', text: 'Lyra lifts her hands. For once she doesn’t hold the cold back. She lets it go.', fx: [{ kind: 'frost' }], dur: 3.8 },
    { at: 'ember:green', text: 'Snow falls on the Ember Wastes for the first time in a thousand years. It melts where it lands, and the roots drink.', fx: [{ kind: 'frost', n: 3 }, { kind: 'douse', delay: .6 }], dur: 5 },
    { text: 'By the time the last flake has melted, every leaf in the grove is green.', fx: [{ kind: 'light', delay: .3 }], dur: 3.8 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“Three winters I was afraid of my own hands. …Look what they can do.”', dur: 4.6 }],
  'pyrrhus-wakes@lyra': [
    { at: 'ember:forge', dy: -60, text: 'The great bellows heave. For the first time in weeks, the Dawn Forge breathes.', fx: [{ kind: 'build' }], dur: 3.6 },
    { text: 'The slag around the anvil bulges, splits… and a serpent of living fire pours out of it, coil after coil.', fx: [{ kind: 'quake' }, { kind: 'fire', n: 3, t: 40, delay: .4 }], dur: 4.4 },
    { text: 'The Cinderwyrm tastes the frost in the air, and screams.', fx: [{ kind: 'embers' }, { kind: 'shadow', delay: .3 }], dur: 3.6 },
    { at: 'hero', speaker: 'Nessa', portrait: '👧', text: '(Nessa skids up the forge steps behind you, out of breath.) “I’m here! Did I miss it? I’m singing!”', actors: [{ id: 'wnessa', name: 'Nessa', look: LOOKS.nessa, dx: -80, dy: 30 }], dur: 4.4 }],
  'chapter-ember@lyra': [
    { at: 'ember:forge', dy: -60, text: 'The Dawn Forge burns white and gold, and a new dawn spills across the wastes, with a little snow in it.', fx: [{ kind: 'light', dy: -60 }, { kind: 'frost', delay: .8 }], dur: 4.4 },
    { at: 'hero', text: 'Nessa sits down beside you on the forge steps to watch it come up. One sister cold, one warm. Neither lets go.', actors: [{ id: 'enessa2', name: 'Nessa', look: LOOKS.nessa, dx: -50, dy: 20 }], dur: 5 },
    { at: 'summit:cradle', cut: true, dy: -90, text: 'On the Summit, the Star shines in its crown of frost.', fx: [{ kind: 'light', dy: -90 }], dur: 3.4 },
    { at: 'woods:bell', cut: true, dy: -60, text: 'In Whisperroot, the Bell rings for the dawn, and no mist answers.', fx: [{ kind: 'light', dy: -60 }], dur: 3.4 },
    { at: 'meadow:rise', cut: true, dy: -80, text: 'And in the meadow, the Beacon blazes over Mirror Lake, where a courier once threw her satchel into the water.', fx: [{ kind: 'light', dy: -80 }], dur: 4.4 },
    { title: 'Every light is shining', sub: 'The post always gets through', dur: 4 }],
};

export const LYRA: HeroStory = {
  hero: 'lyra',
  chains: {
    meadow: ['m1', 'lyra1', 'lyra2', 'lyra6', 'm7', 'm2', 'lyra0', 'lyra12', 'lyra13', 'm3', 'm6', 'lyra9', 'm11', 'm9', 'lyra11', 'm10', 'm12'],
    woods: ['m1', 'lyra3', 'lyra14', 'lyra15', 'lyra19', 'lyra7', 'm2', 'm6', 'm16', 'm14', 'm7', 'lyra17', 'lyra18', 'lyra21', 'm15', 'm17'],
    summit: ['m1', 'lyra22', 'm2', 'lyra4', 'lyra26', 'lyra23', 'lyra24', 'm5', 'm6', 'lyra28', 'lyra29', 'm14', 'm15', 'lyra27', 'm19', 'm20'],
    ember: ['m1', 'm2', 'lyra30', 'lyra37', 'm14', 'lyra5', 'lyra31', 'm7', 'm8', 'lyra38', 'lyra36', 'm10', 'lyra35', 'm15', 'm12', 'm13'],
  },
  quests: {
    // ═════════════ Chapter I · the lost post, the lake and the serpent
    meadow: [
    q({ id: 'lyra1', title: 'Nessa’s Letters', giver: 'fox', kind: 'trail', count: 4, near: 'sunpetal', place: 'millbrook', auto: true, summary: 'Follow the trail of Nessa’s dropped letters south toward Millbrook Farm.', reward: { xp: 90, mana: 10 },
      clues: ['A single blue mitten in the grass. Nessa’s. I knitted it for her, badly, the winter she turned nine.', 'Frost on the leaves, in the middle of summer. Is that hers… or mine? I never can tell where my cold ends.', 'Letters, scattered in the ditch. Every one addressed in her round, careful hand. Some of them have been torn open.', 'Small boot prints by the farm gate, running on toward the lake. And a second set, barefoot, following. Someone picking up what she dropped.'],
      text: { offer: ['Wynne says Nessa’s round ran south from Sunpetal to Millbrook Farm, then along the lake.', 'If she dropped anything on that road, the frost will find it. It always finds her.'], progress: ['Follow the trail of frost and letters south toward Millbrook Farm.'],
        complete: ['She ran on toward the lake. She was still running. Good girl.', 'And someone has been picking up her letters. That farmer over there looks like he knows who.'], after: [] } }),
    q({ id: 'lyra2', title: 'The Letter Thief', giver: 'bram', kind: 'chase', count: 1, place: 'millbrook', who: person('Wick the Magpie-boy', '🧒', { robe: '#5a4a3a', hat: 'cap', hatColor: '#2e2420', small: true }), summary: 'Catch the boy selling Nessa’s letters around Millbrook Farm.', reward: { xp: 130, gold: 40 },
      text: { offer: ['There’s a lad around my farm selling letters. Sealed ones, courier’s post. Says he found them in a ditch.', 'One had frost on the seal, if you can believe it. In summer. That mean anything to you, miss? …You’ve gone pale. Paler.'], progress: ['Wick hangs around Millbrook Farm. He’s quick, but he runs out of breath.'],
        deliver: ['Ow! Alright! I only sold the boring ones, I swear!', 'The courier girl ran past me that night, white as snow. Pale riders on horses made of fog were after her.', 'She ran for the lake and threw her satchel in, far as she could, so they wouldn’t get it. Then something BIG came up out of the water.'],
        complete: ['Something big in Mirror Lake? Lou’s been saying that for thirty years. Nobody listens to Lou.', 'Wick says he threw the letters nobody would buy into Gloom Hollow. Of course he did.'], after: ['Wick’s mending my fences now. Honest work, and he hates it.'] } }),
    q({ id: 'lyra6', title: 'Letters in the Gloom', giver: 'bram', kind: 'collect', count: 4, near: 'hollow', item: 'Nessa’s letter', icon: 'letter', summary: 'Gather the rest of Nessa’s letters in Gloom Hollow and bring them back to Farmer Bram.', reward: { xp: 150, gold: 45 },
      text: { offer: ['Gloom Hollow is south of the farm. The gloomlings sit on those letters like eggs, Wick says.', 'Every one is somebody’s news, and your sister carried them. Fetch them back, and we’ll see they get to Wynne.'], progress: ['Four of Nessa’s letters in Gloom Hollow, south of the farm.'],
        complete: ['Four letters, and hardly chewed. Nessa’s round hand on every one.', 'Now, what’s this about a golden light down there, under the biggest gloomling? A lamp that doesn’t flicker, you say?'], after: ['Wynne will want those letters.'] } }),
    q({ id: 'lyra0', title: 'The Lake Remembers', giver: 'fox', kind: 'activate', count: 3, near: 'mirror', switches: 'rune', order: ['Frost rune', 'Road rune', 'Heart rune'], auto: true, cine: { done: 'lyra-lake-memory' }, summary: 'Wake three old frost runes on the shore of Mirror Lake to see what happened to Nessa’s satchel.', reward: { xp: 130, mana: 10 },
      text: { offer: ['Rowan’s right. The lake is where the post went.', 'There are frost runes on the shore stones of Mirror Lake. Old ones, from when my family still came down to the valley.', 'Frost remembers. If I wake them, the lake might show me the night Nessa ran this road.'], progress: ['Three frost runes around Mirror Lake.'], complete: [], after: [] } }),
    q({ id: 'lyra12', title: 'Scales Like Dinner Plates', giver: 'lou', kind: 'collect', count: 4, near: 'mirror', item: 'Serpent scale', icon: 'gem', summary: 'Gather the great scales washed up around Mirror Lake for Fisher Lou.', reward: { xp: 110, gold: 30 },
      text: { offer: ['Something big, swallowing the satchel? I’ve said for thirty years there’s a big one in this lake. Thirty years!', 'Since the star fell, scales have been washing up on the shore. Big as dinner plates. Fetch me four, and I’ll finally have proof.'], progress: ['Four scales along the shores of Mirror Lake.'],
        complete: ['Look at the size of them. Green as pondweed and cold as your hands. I knew it. I KNEW it.', 'Mind you, the lake’s been dead quiet since that night. Whatever it is, it’s gone somewhere.', 'Scholar Ilse in Goldenhearth knows all the old lake tales. She’ll know its name.'], after: ['Shh. The big one is… well, gone, for now. I still whisper out of habit.'] } }),
    q({ id: 'lyra13', title: 'The Serpent in the Books', giver: 'lou', kind: 'talk', count: 1, to: 'ilse', summary: 'Ask Scholar Ilse in Goldenhearth about the beast of Mirror Lake.', reward: { xp: 90 },
      text: { offer: ['Goldenhearth is the big city north-east of the lake. Ilse will be in her books, same as always.', 'Show her the scales. And tell her Lou was right.'], progress: ['Goldenhearth lies north-east of Mirror Lake.'], complete: [], after: ['Lou was right. Say it slowly.'],
        deliver: ['Lou was right? Oh, he will be unbearable.', 'These are Gloamgill’s scales. The old serpent of Mirror Lake. It sleeps for a hundred years at a time, down in the black water, dreaming of anything that glows.', 'When the Beacon died, the shadow woke it. It followed the dark down the underground streams to the Beacon Rise, and coiled itself around the cold Beacon like a lake around a stone.', 'If it swallowed your sister’s satchel, the satchel is down there with it. And it won’t come up for anything… except the light of the sun-crystals.'] } }),
    q({ id: 'lyra9', title: 'The Post Must Go Through', giver: 'brannoc', kind: 'deliver', count: 1, to: 'odo', item: 'Nessa’s last letter for the Hill', summary: 'Finish Nessa’s round: carry her last letter to Old Shepherd Odo on Shepherd’s Hill.', reward: { xp: 120, gold: 40 },
      text: { offer: ['Tansy found this under her cart seat. One letter from your sister’s round, still sealed. For Old Shepherd Odo, on Shepherd’s Hill.', 'Couriers have a saying: the post always gets through. Your sister would want it delivered. Shepherd’s Hill is far to the north-east.'], progress: ['Shepherd’s Hill is far to the north-east of Goldenhearth.'], complete: [], after: ['The post always gets through.'],
        deliver: ['A letter? For me? Nobody has written to me since my Hettie moved to Willowmere.', '…It’s from Hettie. She’s coming for the harvest. With the grandchildren. All seven of them.', 'You finished your sister’s round for her. That’s a kind thing, frost or no frost. Now, while you’re up here… my sheep.'] } }),
    q({ id: 'lyra11', title: 'Freeze the Serpent’s Road', giver: 'fox', kind: 'activate', count: 3, near: 'faerie', switches: 'rune', order: ['West spring', 'Moss spring', 'East spring'], auto: true, summary: 'Freeze the three springs around the Faerie Ring, so Gloamgill can’t flee back into the deep.', reward: { xp: 140, mana: 12 },
      text: { offer: ['Ilse said Gloamgill swims the underground streams. The springs that feed them rise around the Faerie Ring, south-east of the lake.', 'If I freeze them shut, it can’t slip back into the deep when the light draws it up. It will have to face me.', 'Frost that locks a door. That, at least, I know how to do.'], progress: ['Three springs around the Faerie Ring. Freeze them shut.'],
        complete: ['(The last spring groans and turns to glass. Far underground, something very large bumps against the ice… and turns toward the Beacon Rise.)'], after: [] } }),
    ],
    // ═════════════ Chapter II · the wraiths' trail and the Pale Huntress
    woods: [
    q({ id: 'lyra3', title: 'The Courier’s Word', giver: 'guide', kind: 'talk', count: 1, to: 'nutkin', summary: 'Ask Courier Nutkin at the camp about Nessa.', reward: { xp: 120 },
      text: { offer: ['A courier girl with frost in her hair? Nutkin would know. The couriers look after each other.'], progress: ['Nutkin is here at the camp.'], complete: [], after: [],
        deliver: ['Nessa? She carried the post with me for two whole summers! Fastest feet in the valley, after mine.', 'She came through here a week ago, soaked and shivering, with pale riders in the mist behind her. I hid her in the mailbags till they passed.', 'Then she ran south for Bellhollow, to Nana Bristle. Everyone runs to Nana. She kept saying your name. “Lyra will come.”'] } }),
    q({ id: 'lyra14', title: 'Soup at Nana Bristle’s', giver: 'nutkin', kind: 'talk', count: 1, to: 'nana', summary: 'Visit Nana Bristle in Bellhollow, where Nessa hid.', reward: { xp: 120 },
      text: { offer: ['Bellhollow is south-east of the camp. Follow your nose. Nana’s soup reaches further than the road does.', 'And… Lyra? Nessa said you’d be scary. You’re not that scary. Only a bit.'], progress: ['Bellhollow lies south-east of the camp.'], complete: [], after: ['Nana’s soup mends everything. Mostly.'],
        deliver: ['You’re the sister. Sit. Eat. You’re too thin for a hero and too cold for anything.', 'Nessa slept by my stove for two nights. She talked about you the whole time, until my ears were warm.', 'She told me about a glasshouse, dear. About the winter you froze it with her inside, and cried for a week, and never hugged her again.', 'She wasn’t angry. She just missed her sister. Then one morning she went down to the stream, the mist came, and she was gone.'] },
      choice: {
        a: { label: 'Tell her about the glasshouse', lines: ['(You tell her: Gran’s frost-song sung wrong, the cold getting away from you, Nessa’s hair turning white.)', 'Oh, my dear. You were twelve. A child with a winter inside her.', 'And you’ve carried that glasshouse on your back ever since. Put it down. It’s far too heavy for climbing mountains.'], reward: { regen: .4 } },
        b: { label: 'Change the subject', lines: ['Hmph. Keep your secrets, dear, if they keep you warm. But they don’t, do they?', 'When you find her, hug her. That’s all. It isn’t complicated.'], reward: { mana: 12 } },
      } }),
    q({ id: 'lyra15', title: 'Hoofprints of Frost', giver: 'nana', kind: 'trail', count: 4, near: 'bellhollow', place: 'pool', turnIn: 'maeve', summary: 'Follow the frozen trail from Bellhollow to Blackwater Pool, then ask Fisher Maeve what she saw.', reward: { xp: 170 },
      clues: ['Hoofprints in the moss, rimmed with frost. No horse made these. They’re too light, and they don’t sink.', 'Nessa’s courier badge, trodden into the mud. She dropped it on purpose. She always drops things on purpose.', 'The ferns here are frozen stiff and black at the tips. Cold with nothing living in it. Not like mine. …Is it?', 'The shore of Blackwater Pool, iced over in one long bridge. They rode straight across the water with her.'],
      text: { offer: ['The frost those riders leave behind doesn’t melt, dear. Follow it east from the stream.', 'Fisher Maeve at Blackwater Pool sees everything that crosses her water. Ask her.'], progress: ['Follow the frozen hoofprints east from Bellhollow toward Blackwater Pool.'],
        complete: ['The pale ones? I saw them. Rode right across my pool on a bridge of ice, with a little white-haired girl slung over a saddle.', 'She was kicking. Good for her.', 'One of them didn’t go on with the rest. It rides round and round the Trapper’s Lodge at night, like it’s waiting for someone.'], after: ['Pale riders. Pale fish too, since. Coincidence? I think not.'] } }),
    q({ id: 'lyra19', title: 'A Light on the Water', giver: 'maeve', kind: 'build', count: 4, near: 'pool', item: 'Driftwood', icon: 'bundle', place: 'pool', site: 'lantern', siteName: 'Nessa’s Lantern', summary: 'Gather driftwood around Blackwater Pool and build a lantern post on the shore where Nessa was taken.', reward: { xp: 170, gold: 40 },
      text: { offer: ['Before you go chasing ghosts: couriers use this shore road, and nobody should cross it in the dark again.', 'Bring me four good pieces of driftwood from around the pool, and we’ll build a lantern post right here. So the next one who runs this way can see where she’s going.'], progress: ['Four pieces of driftwood around Blackwater Pool, then build the lantern on the shore.'],
        complete: ['There. A light on the water. Your sister will see it when she comes home this way.', 'You built that with your own cold hands, and it burns warm as anything. Funny, that.', 'Now go and have words with that rider. The Trapper’s Lodge is east of here. Ysolde’s been sleeping with an axe.'], after: ['The lantern burns all night. The fish are delighted.'] } }),
    q({ id: 'lyra7', title: 'The Pale Rider', giver: 'maeve', kind: 'chase', count: 1, place: 'lodge', escapes: true, turnIn: 'ysolde', who: person('The Pale Rider', '👻', { robe: '#dff6ff', hat: 'hood', hatColor: '#bfe8ff', skin: '#e8f4ff', hair: '#ffffff' }), cine: { caught: 'rider-flees' }, summary: 'Catch the frost wraith haunting the Trapper’s Lodge, then tell Trapper Ysolde what it said.', reward: { xp: 220, mana: 12 },
      text: { offer: ['(Maeve points east with her fishing rod.) The rider circles the Trapper’s Lodge every night. It was with the ones that took her.', 'Catch it and make it talk. If those things can talk.'], progress: ['The pale rider haunts the Trapper’s Lodge, east of Blackwater Pool.'],
        deliver: ['(The wraith hisses a single word, cold as the Summit wind: “…Observatory.”)', '(Then, lower, almost like laughter: “The Huntress is waiting for you, frost-daughter.”)'],
        complete: ['That thing has circled my lodge for a week, and you just grabbed it by the mist. Brave or daft, I can’t tell.', 'It flew north-east, to the Old Bell. The mist is thickest there. That’s where its mistress sits, the one they call the Huntress.', 'Observatory, it said? There’s an old one high on the Summit. So that’s where they’ve taken your girl.'], after: ['Quiet feet catch more than loud ones. Cold hands catch pale riders, apparently.'] } }),
    q({ id: 'lyra17', title: 'Thorns in the Mist', giver: 'forester', kind: 'key', count: 1, keys: [1], turnIn: 'ivo', summary: 'Wake the root rune in the Thornling Nest, then report to Scout Ivo at the Owl Watchtower.', reward: { xp: 160 },
      text: { offer: ['The Thornling Nest lies north of Lanternmarket, a long walk east of here. Thornlings spit. Blink through the gaps.', 'Scout Ivo keeps watch from the Owl Watchtower, south-east of the nest. He’ll want to know you made it out.'], progress: ['The nest is north of the city. The watchtower is south-east of it.'],
        complete: ['You came out of the nest with a rune AND all your fingers. The owls are hooting like mad.', 'I watch the Bell from up here. Every night she sits on it, the Huntress, and every night she looks this way. As if she’s waiting for someone.'], after: ['All clear, for now.'] } }),
    q({ id: 'lyra18', title: 'Owl-light', giver: 'ivo', kind: 'key', count: 1, keys: [2], summary: 'Wake the last root rune around the Owl Watchtower.', reward: { xp: 150 },
      text: { offer: ['The last rune sleeps somewhere round the foot of my tower. It glows green when it’s dreaming.', 'Wake it, and the roots around the Bell will start to let go.'], progress: ['Look around the Owl Watchtower.'],
        complete: ['All three runes are singing! Listen to the owls. Proud as anything.', 'But the Huntress heard them too. The mist is thicker tonight, and full of little cold lights.'], after: ['The owls are proud.'] } }),
    q({ id: 'lyra21', title: 'Cold Lights', giver: 'ivo', kind: 'slay', count: 6, enemy: 'wisp', summary: 'Snuff six wisps drifting in the Huntress’s mist.', reward: { xp: 170, mana: 12 },
      text: { offer: ['Those lights in the mist are wisps. She sees through them, the way a spider feels its web.', 'Snuff six, and she’ll be blind when you come for her. Then she’ll have to come down off that Bell and face you.'], progress: ['Wisps are small violet lights. They dart side to side.'],
        complete: ['Six! The mist is thinning. I can see the Bell from here, and her on it, sitting very still.', 'The Bellkeeper told me what he saw under her hood. Whatever she is, Lyra, she isn’t you.'], after: ['Go carefully.'] } }),
    ],
    // ═════════════ Chapter III · home, Nessa and the Rimewardens' secret
    summit: [
    q({ id: 'lyra22', title: 'Bramble’s Report', giver: 'guide', kind: 'talk', count: 1, to: 'bramble', summary: 'Hear what Courier Bramble saw on the road to Frostpine Hamlet.', reward: { xp: 100 },
      text: { offer: ['Bramble is here at the lookout, pretending she isn’t freezing. Couriers.'], progress: ['Bramble is at the lookout.'], complete: [], after: [],
        deliver: ['You’re Lyra? THE Lyra? Nutkin sent word up the courier line: “Frost-sister coming. Be nice to her.” I’m being nice!', 'The riders took Nessa past Frostpine Hamlet, south-west, to the Old Observatory. Poor old Vale has locked himself in the top of it with his telescope.', 'Healer Aune in the hamlet patched up the ones who tried to follow. But the road to her is thick with wisps. Mind yourself.'] } }),
    q({ id: 'lyra4', title: 'Nessa', giver: 'aune', kind: 'rescue', count: 1, place: 'observatory', guards: 5, escort: true, captive: NESSA, cine: { done: 'lyra-reunion' }, summary: 'Free Nessa from the frost wraiths at the Old Observatory and bring her to Healer Aune.', reward: { xp: 260, hearts: 1 },
      text: { offer: ['The Old Observatory lies south-west of the hamlet. Five wraiths stand guard, and Vale has barricaded himself in the dome.', 'Bring her back here to me. She’ll be half frozen, and you’ll be no better.'], progress: ['The Old Observatory lies south-west of the hamlet. Break the wraiths, open the cage, and bring her back to Aune.'],
        deliver: ['Lyra?! LYRA! I knew it, I told them you’d come! I told them every single day!', 'They wanted Gran’s song. The Rime Song. They kept saying their queen needs two voices. I wouldn’t sing. Not without you.'], arrive: ['Is that Aune? Is there soup? Lyra, is there soup?'],
        complete: ['Sit down, both of you. Your sister is frozen to the bone and stubborn as a goat. Must run in the family.', 'She stays by my fire tonight. And so do you, Lyra Rimeward. No arguments.'], after: ['Two frost-girls in one hamlet. Stars help us.'] } }),
    q({ id: 'lyra26', title: 'The Queen’s Blizzard', giver: 'aune', kind: 'activate', count: 4, near: 'hamlet', switches: 'brazier', order: ['Well brazier', 'Mill brazier', 'Chapel brazier', 'Gate brazier'], cine: { start: 'lyra-blizzard' }, summary: 'Clear the ice from Frostpine Hamlet’s four hearth-braziers so Nessa can relight them before the blizzard buries the hamlet.', reward: { xp: 160, regen: .4 },
      text: { offer: ['Listen to that wind. That isn’t weather. Something up at the Cradle is angry that you took her back.', 'The blizzard has put out every hearth-brazier in the hamlet. If they stay dark till morning, Frostpine freezes in its beds.', 'Nessa has a flint and more nerve than sense. You clear the ice off the braziers, and she’ll strike the fire. Four of them, round the hamlet.'], progress: ['Four hearth-braziers around Frostpine Hamlet. Clear the ice so Nessa can light them.'],
        complete: ['Four fires, burning right through a blizzard. Frost to clear the way and a spark to follow. Your gran would have liked that.', 'Nessa’s asking for you. She’s sitting by the well, and she’s gone very quiet. That’s never a good sign with Nessa.'], after: ['The hamlet sleeps warm tonight.'] } }),
    q({ id: 'lyra23', title: 'Frost in Her Hair', giver: 'aune', kind: 'talk', count: 1, to: 'nessa', summary: 'Sit with Nessa by the well in Frostpine Hamlet.', reward: { xp: 120 },
      text: { offer: ['Go on. She’s by the well. Whatever it is, you two can sort it out without me listening. I’ll only listen a little.'], progress: ['Nessa is in Frostpine Hamlet.'], complete: [], after: [],
        deliver: ['Lyra. Can I ask you something, and you won’t go all icy and walk off up a mountain?', 'Is it the glasshouse? Is that why you never came down? Because my hair went white?', 'Because I LIKE my hair. Everyone at the post house thinks I’m very dramatic.'] },
      choice: {
        a: { label: '“I was afraid I’d hurt you again.”', lines: ['So you stayed away, so your frost couldn’t reach me? Lyra, the cold reached me anyway. It was the lonely kind.', 'You didn’t hurt me. You just left.', 'Right. That’s decided. No more leaving. Now: the Queen called us daughters, and I want to know why.'], reward: { regen: .4 } },
        b: { label: '“It isn’t your hair. It’s the frost in it.”', lines: ['The frost in it? …You mean that’s YOURS? Still in me? From that day?', 'Huh. So when I’m cold, that’s you, looking after me. That’s nicer than I thought.', 'Now: the Queen called us daughters, and I want to know why.'], reward: { mana: 12 } },
      } }),
    q({ id: 'lyra24', title: 'The Skyhold Road', giver: 'nessa', kind: 'escort', count: 1, who: NESSA, from: 'hamlet', place: 'city', ambush: ['frostwraith', 'wisp', 'frostwraith'], turnIn: 'corvin', summary: 'Walk Nessa from Frostpine Hamlet to Abbot Corvin in Skyhold, and keep the wraiths off her.', reward: { xp: 200 },
      text: { offer: ['Gran kept a chronicle, the Rime-book. When she died, it went to Abbot Corvin in Skyhold, east of here, over the ridge.', 'Walk me there? My legs are still half ice, and the Queen’s wraiths will want me back.', 'And you have to talk on the way. Three winters of talking. I’ll start. Once, at the post house…'], progress: ['Lead Nessa east to Skyhold and keep the wraiths off her.'],
        arrive: ['Skyhold! Look at the towers, Lyra! I delivered a parcel here once. It was a goat.'],
        complete: ['The Rimeward sisters, together, at my door. I did not think I would live to see that.', 'Your grandmother sat where you are standing, many winters ago, and wrote in this book. It is time you read it.'], after: ['The Rime-book is yours to read, whenever you wish.'] } }),
    q({ id: 'lyra28', title: 'Frostfang Crag', giver: 'lyra-nessa-sky', kind: 'key', count: 1, keys: [1], turnIn: 'dov', summary: 'Take the star shard from Frostfang Crag, then find Quartermaster Dov at Silver Pass Camp.', reward: { xp: 150 },
      text: { offer: ['The next shard is on Frostfang Crag, north-east of the city. Golems AND wraiths. I’d come, but you’d only make that face.', 'Afterwards, go and see Quartermaster Dov at Silver Pass Camp, north-west of the crag. Corvin says his guards have seen the Queen’s heralds gathering.', 'And Lyra? Come back. That’s an order from your little sister, which is the highest kind.'], progress: ['Frostfang Crag is north-east of Skyhold. Silver Pass Camp is north-west of the crag.'],
        complete: ['A Rimeward, on my crag road, with a star shard in her pocket. Well, well. The Abbot sent word you might come.', 'The Queen’s heralds are gathering on the ridge. Frost wraiths with crowns of ice. They’re looking for shards, and for you.'], after: ['Halt! Oh, it’s you.'] } }),
    q({ id: 'lyra29', title: 'The Queen’s Heralds', giver: 'dov', kind: 'slay', count: 5, enemy: 'frostwraith', summary: 'Break five frost wraiths gathering on the heights around Silver Pass.', reward: { xp: 150 },
      text: { offer: ['Her heralds prowl round my camp. They freeze my guards solid and then just… stand there, admiring them.', 'You’re as cold as they are, frostweaver. Colder, maybe. Break five of them.'], progress: ['Wraiths blink close and throw ice. Keep moving.'],
        complete: ['Five heralds, shattered. And you know, when you fight, the snow falls AWAY from my lads. As if it’s keeping them out of it.', 'That’s not their kind of cold. That’s yours.', 'Now look at that ridge. The whole void is coming over it.'], after: ['The wall holds.'] } }),
    q({ id: 'lyra27', title: 'The Rime Song', giver: 'lyra-nessa-sky', kind: 'activate', count: 4, near: 'altar', switches: 'rune', order: ['Cold voice', 'Warm voice', 'Cold voice', 'Warm voice'], ordered: true, auto: true, cine: { done: 'lyra-two-voices' }, summary: 'Wake the four song-stones around the Star Altar in turn, cold then warm, while Nessa sings.', reward: { xp: 180, mana: 14 },
      text: { offer: ['Four song-stones stand around the Star Altar, east of the city. Gran’s book says you wake them in turn: cold, then warm, then cold, then warm.', 'You do the frost. I’ll sing. Loudly. If I get the words wrong, sing louder so nobody notices.'], progress: ['Four song-stones around the Star Altar. Cold, then warm, in turn.'],
        complete: ['(The last song-stone rings. For the first time since the glasshouse, Lyra’s frost doesn’t feel like a door closing. It feels like a blanket.)', 'Now we go and knock that crown off her head. Together.'], after: [] } }),
    ],
    // ═════════════ Chapter IV · frost in a land of fire
    ember: [
    q({ id: 'lyra30', title: 'Soot’s Letters', giver: 'guide', kind: 'talk', count: 1, to: 'soot', summary: 'Collect your post from Courier Soot at the outpost.', reward: { xp: 110 },
      text: { offer: ['Soot’s our courier, the one that doesn’t burn. She’s been hopping about waiting for you all day.'], progress: ['Soot is here at the outpost.'], complete: [], after: [],
        deliver: ['Lyra Rimeward! Pip, Nutkin, Bramble and me: the whole courier line has been passing your news along like a hot potato.', 'Letter for you. From Nessa. It says: “Arrived in Brasshaven. It is VERY hot. Also I miss snow.”', 'And Kiln-mother Hessa wants to meet you. She says a frostweaver in the Wastes is either a miracle or a joke, and she’d like to know which.'] } }),
    q({ id: 'lyra37', title: 'Sand Brave Enough', giver: 'soot', kind: 'talk', count: 1, to: 'hessa', summary: 'Meet Kiln-mother Hessa in Kilnhollow.', reward: { xp: 120 },
      text: { offer: ['Kilnhollow is south-east of the outpost, where the glass-kilns never go out. Don’t touch the glass. Well, you can. You’re probably the only one who can.'], progress: ['Kilnhollow lies south-east of the outpost.'], complete: [], after: ['Glass is only sand that was brave enough to walk through fire.'],
        deliver: ['So you’re the frost-girl. Hm. Smaller than I expected. Colder, too.', 'The Dawn Forge lit the sunrise over these wastes for a thousand years. Its keeper, Pyrrhus, fell in love with the fire and wanted all of it for himself.', 'He bred a serpent out of the slag, the Cinderwyrm, to keep anyone from sharing the forge’s light. It swallowed the three ember cores and spat them across the wastes.', 'Now it lies coiled round the cold forge, and it hates frost more than anything. So tell me, frost-girl. Why are you really here?'] },
      choice: {
        a: { label: '“Because my sister is here.”', lines: ['Ha! Family. The only thing hotter than a kiln.', 'Good answer. Frost that stays for someone is worth more than fire that burns for itself.'], reward: { regen: .5 } },
        b: { label: '“Because everyone says I’ll be useless here.”', lines: ['Ha! Stubborn. I like stubborn. Sand is stubborn, and look what it becomes.', 'Useless? Girl, half this desert is dying of heat. You may be the most useful thing that ever walked into it.'], reward: { mana: 14 } },
      } }),
    q({ id: 'lyra5', title: 'Winter in the Forge', giver: 'tovan', kind: 'activate', count: 3, near: 'city', switches: 'vent', order: ['West vent', 'North vent', 'East vent'], turnIn: 'tovan', summary: 'Freeze Brasshaven’s three overheating forge vents before they burst.', reward: { xp: 260, mana: 14 },
      text: { offer: ['You’re the frost-girl your sister won’t stop talking about? Good. Three of my forge vents are glowing white.', 'Since the serpent coiled round the Dawn Forge, the heat under the city has nowhere to go. If the vents burst, half of Brasshaven burns.', 'Freeze them. Just… not my beard.'], progress: ['Three vents around Brasshaven. Freeze them.'],
        complete: ['Ice! In Brasshaven! My apprentices are having snowball fights in the forge.', 'Forty years I’ve fought fire with fire. Never once thought to fight it with snow.', 'I was wrong about you, frost-girl. So listen: I know where the serpent spat the cores.'], after: ['Cool as a mountain morning.'] } }),
    q({ id: 'lyra31', title: 'A Core Held in Frost', giver: 'tovan', kind: 'key', count: 1, keys: [0], summary: 'Recover the first ember core from the Obsidian Maze. Only frost can hold it.', reward: { xp: 160 },
      text: { offer: ['The first core glows in the Obsidian Maze, far to the north-west. It burns through any glove, any salt, any hand. My best smiths have tried.', 'But frost… wrap it in your cold, and it might just let you carry it. Bring it back here.'], progress: ['The Obsidian Maze lies far to the north-west.'],
        complete: ['You carried it all that way bare-handed? It’s hissing in your ice like a kettle, but it’s whole!', 'Hessa always says the forge was made by two kinds of hands: hot ones to light it and cold ones to temper it. I thought it was a kiln-saying.', 'Now, trouble. A caravan came in screaming last night. The imps have taken the Salt Caravan Camp.'], after: ['One of three.'] } }),
    q({ id: 'lyra38', title: 'The Last Post Run', giver: 'nessa', kind: 'escort', count: 1, who: NESSA, from: 'city', place: 'watch', ambush: ['emberImp', 'ashScorpion', 'emberImp'], turnIn: 'seer', summary: 'Walk Nessa and her letter north to Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 200 },
      text: { offer: ['Ember-seer Ilyana at Ashfall Watch hasn’t had post in weeks. I’ve got a letter for her from Abbot Corvin, and it says URGENT on it in red.', 'Tovan says the dunes are full of imps. So walk with me. Couriers look after each other, and sisters look after each other twice.'], progress: ['Lead Nessa north to Ashfall Watch and keep the imps off her.'],
        arrive: ['Ashfall Watch! Special delivery! …She’s already waving. Seers. You can’t surprise them.'],
        complete: ['A letter from the Summit, carried by a Rimeward and guarded by a Rimeward. I saw it in the flames, and still I hardly believed it.', 'The Abbot writes that the dark that fled his mountain is cold without any warmth: an endless winter night. It wants the dawn never to come again.', 'Only the Dawn Forge can stop it. But first, the wastes have something to ask of you, frost-daughter.'], after: ['The flames speak of two sisters.'] } }),
    q({ id: 'lyra36', title: 'Snow on the Last Green', giver: 'seer', kind: 'visit', count: 1, place: 'green', turnIn: 'seer', cine: { ready: 'lyra-first-snow' }, summary: 'Bring the first snow in a thousand years to the Last Green, then return to Ilyana.', reward: { xp: 170, mana: 12 },
      text: { offer: ['East of here grows the Last Green, the only grove left in the wastes. It is dying of thirst. No rain has fallen on it in a lifetime.', 'The flames showed me snow on its leaves. I did not understand it. Then you walked up my hill.', 'Go there. Let your cold fall on it. Then come back and tell me what you saw.'], progress: ['The Last Green lies east of Ashfall Watch.'],
        complete: ['You made it snow. In the Ember Wastes. The flames are laughing. I have never heard them laugh.', 'Frost that gives water. Frost that keeps a seed safe until spring. That is what your family’s magic was always for, child.', 'Now, the last core. It burns in the Old Foundry, where Pyrrhus kept his hulks.'], after: ['Green and white, green and white.'] } }),
    q({ id: 'lyra35', title: 'Frost Runes on the Molten Mere', giver: 'seer', kind: 'activate', count: 3, near: 'mere', switches: 'rune', order: ['Rime rune', 'Hearth rune', 'Dawn rune'], auto: true, summary: 'Carve three frost runes around the Molten Mere to freeze the slag channels that feed the Cinderwyrm.', reward: { xp: 200, mana: 14 },
      text: { offer: ['Three slag channels run from the Molten Mere, south-west of here, deep under the sand to the Dawn Forge. The serpent drinks fire through them.', 'The couriers say you froze a lake’s springs once, to trap a serpent in the meadow. Do it again. Freeze the channels, and it will go hungry.'], progress: ['Three frost runes around the Molten Mere.'],
        complete: ['(The last rune bites into the slag, and a long hiss runs away under the sand toward the Dawn Forge. Far off, something enormous stirs, hungry and furious.)', 'Mirror Lake at the start, and a lake of fire at the end. Nessa would call that poetic.'], after: [] } }),
    ],
  },
  reuse: {
    // ═════════════ Chapter I
    meadow: {
      m1: { title: 'Frost on the Reeds', giver: 'lou', to: 'wren', summary: 'Ask Postmistress Wynne in Sunpetal Village about Nessa.',
        text: { offer: ['You came down the lake road in the night, trailing frost. The reeds are still white where you walked.', 'A courier girl, you say? Aye… a little one ran past my boat after midnight, satchel bouncing. Something pale was after her.', 'Postmistress Wynne in Sunpetal counts every courier in and out. The village is north of the lake, up the road.'],
          progress: ['Sunpetal Village is north of Mirror Lake.'], complete: [], after: ['Frost on the water, in summer. Hmph. The fish don’t like it either.'],
          deliver: ['Nessa? My Nessa? She never came in that night. Nor did her satchel: half the valley’s post, gone with her.', 'You’re the sister from the mountain, aren’t you. She talks about you. Snow in summer, she says.', 'Her round ran south from here to Millbrook Farm, then along the lake. If she dropped anything, it’ll be on that road.'] } },
      m7: { title: 'The Gloom King’s Lamp', giver: 'bram', turnIn: 'wren', summary: 'Take the golden light from Gloom Hollow, then bring it and Nessa’s letters to Postmistress Wynne in Sunpetal.', reward: { xp: 150 },
        text: { offer: ['A lamp that doesn’t flicker, in a place the sun never reaches? That’ll be one of the Beacon’s sun-crystals, or I’m a turnip.', 'The gloom must have dragged it down there the night the Beacon died. Go back and take it. Then bring it, and those letters, to Wynne in Sunpetal.'],
          progress: ['Gloom Hollow lies south of Millbrook Farm. Then take the crystal and letters north to Sunpetal.'],
          complete: ['A sun-crystal! And Nessa’s letters! Let me count… nearly all of them. Oh, you clever thing.', 'Nearly. Everything bound for the Silver Heights is missing. That was all in her own satchel.', 'There was a letter for you in there, you know. She wrote you one every month for three years, and never sent them. This month she finally posted it.'],
          after: ['Keep that crystal close. Rowan says the Beacon will want it back.'] } },
      m2: { title: 'Frost at the Barricade', giver: 'rowan', summary: 'Hold Sunpetal’s barricade against three waves of gloomlings.', reward: { xp: 110, hearts: 1 },
        text: { offer: ['So you are the frost-girl. Half the village has been whispering about the white footprints in the lane.', 'Whisper away, I say. Every dusk the gloomlings come for Sunpetal, and every dusk there are more of them.', 'Stand at the barricade with us tonight. If your cold frightens them half as much as it frightens old Hollis, we’ll do very well.'],
          progress: ['Stay near the barricade. Stop them before they reach it.'],
          complete: ['You froze them solid! Hollis fainted, but in a proud sort of way.', 'The village saw what you did tonight. They’ll still whisper, mind, but now it will be the nice sort of whispering.', 'Wynne told me about the post. If your sister threw her satchel into the lake, then the lake is where you should look.'],
          after: ['The lanes are quiet tonight. And a little frosty.'] } },
      m3: { title: 'Bait of Sunlight', giver: 'ilse', summary: 'Find the sun-crystal in the Old Stone Garden.', reward: { xp: 110 },
        text: { offer: ['You already carry one crystal? Then you need the other two. The first beacon-keepers hid one in the Old Stone Garden, north of the city.', 'Three sun-crystals, laid in the Beacon, would light it again. And a serpent that dreams of glowing things could never stay down in the dark with that much light above it.'],
          progress: ['Look for a golden light among the old stones, north of Goldenhearth.'],
          complete: ['Two crystals. You carry them as if they might burn you.', 'Frost and sunlight in the same pocket. My old teacher would have written a whole book about you.', 'Now. Captain Brannoc came by this morning, grey as ash. One of his couriers never came back from the east road.'],
          after: ['One more crystal.'] } },
      m6: { title: 'The Courier of the East Road', giver: 'ilse', turnIn: 'brannoc', summary: 'Free Courier Tansy from Rotwood Den and walk her home to Captain Brannoc in Goldenhearth.', captive: person('Courier Tansy', '🧑', COURIER), reward: { xp: 150, hearts: 1 },
        text: { offer: ['Brannoc’s courier is Tansy. She rode the east road the same night your sister ran the lake road.', 'The gloom dragged her into Rotwood Den, far to the east. If anyone saw Nessa after the lake, it was Tansy. Bring her home.'],
          progress: ['Rotwood Den lies far to the east. Defeat her captors, open the cage, and bring her to Captain Brannoc in Goldenhearth.'],
          arrive: ['Goldenhearth! Captain! I’m back, and I’ve still got the post! Mostly.'],
          deliver: ['You’re… the frost-sister! Nessa said you’d come. She said it like it was the weather.', 'She came to me dripping from the lake, and we raced east in my cart. The boars turned us over here. She ran on, right over the Gloomwater Bridge.', 'The bridge came down behind her. Then pale riders came out of the mist on the far bank. That’s all I saw.'],
          complete: ['Tansy, home, and still counting her letters. You have the guard’s thanks, frostweaver.', 'East over the bridge, then. That bridge is in the river now. But one thing at a time.', 'Tansy has something for you. Something your sister left in her cart.'],
          after: ['The east road is watched again.'] } },
      m11: { title: 'Seven Grandchildren and Five Sheep', giver: 'odo', summary: 'Drive five of Odo’s scattered sheep back into their pen.', reward: { xp: 130 },
        text: { offer: ['The boars scattered my flock across the hill, and the grandchildren arrive for the harvest. I can’t have them see me like this.', 'Sheep run from anything that walks at them. Walk up behind one and it trots the other way. Five back in the pen, please.', 'And they’re a bit wary of cold hands. Can’t think why.'],
          progress: ['Walk behind a sheep to push it toward the pen. Slowly does it.'],
          complete: ['Five sheep! One of them has frost on its nose. It seems to like it.', 'Now. You’re wanting the light that sits among my stones, aren’t you? I’ve seen you looking.'],
          after: ['Baa. I mean, good day.'] } },
      m9: { title: 'The Shepherd’s Star', giver: 'odo', summary: 'Find the last sun-crystal on Shepherd’s Hill.', reward: { xp: 160 },
        text: { offer: ['It came rolling up my hill the night the Beacon died, glowing like a lamb with a lantern in it.', 'Take it. It hums all night and the sheep can’t sleep.'], progress: ['The crystal is somewhere on the hill.'],
          complete: ['Three crystals. Look how they shine together. Even your frost glows gold in that light.', 'You’ll be going to the Beacon Rise, then, far to the south. Mind the water down there. Something has been making the springs run cold.'],
          after: ['Go carefully. And wave to Hettie, if you see her.'] } },
      m10: { title: 'Gloamgill', giver: 'fox', cine: { done: 'lyra-last-letter' }, summary: 'Draw Gloamgill up from under the Beacon Rise with the sun-crystals, defeat it, and relight the Meadow Beacon.', reward: { xp: 320, hearts: 1 },
        text: { offer: ['The springs are frozen. Gloamgill has only one way out of the dark now: up, toward the light.', 'It has slept down there a hundred years. It will spit ice, whirl and charge, and the ground will burst wherever it swims. Keep moving.', 'Then I lay the crystals in the Beacon, far to the south-east. And I get my sister’s letter back.'],
          progress: ['The Beacon Rise lies far to the south-east.'], complete: [], after: ['The Beacon shines!'] } },
      m12: { title: 'The Bridge Nessa Crossed', giver: 'holt', summary: 'Gather bridge timber around Willowmere, then rebuild the Gloomwater Bridge at the Eastern Gate.', reward: { xp: 260, hearts: 1 },
        text: { offer: ['That was you, lighting the Beacon? Then you’re the one to help me with this mess.', 'The Gloomwater Bridge came down the night the star fell. A courier girl ran over it just before. I saw her from my window. She never looked back.', 'Bring me five good timbers from around Willowmere, north-west of here. Then we build her together, at the gate.'],
          progress: ['Five bridge timbers from around Willowmere, then build at the Eastern Gate.'],
          complete: ['Look at her! Straighter than the old one, and she only wobbles a little.', 'The road east is open. Your courier girl went that way, into Whisperroot. Go and bring her home.'],
          after: ['Mind the third plank. It squeaks.'] } },
    },
    // ═════════════ Chapter II
    woods: {
      m1: { title: 'Into the Winter Mist', giver: 'fox', to: 'guide', summary: 'Cross the Eastern Gate into Whisperroot and find Mosskeeper Oda.',
        text: { offer: ['(Beyond the new bridge, white mist curls between the trees. Summer mist doesn’t bite like that.)', 'Nessa ran this road. Someone at the camp inside the woods must have seen her.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
          deliver: ['You walked out of the mist and it didn’t touch you. It shrank from you, almost.', 'It rolls off the Old Bell every night now, cold enough to kill the moss. There’s a rider in it, they say. A pale woman.', 'You’re looking for someone? Ask Nutkin. Couriers know every face on every road.'] } },
      m2: { title: 'The Huntress’s Hounds', giver: 'ysolde', summary: 'Defeat six shadewolves running with the mist.', reward: { xp: 110 },
        text: { offer: ['Before you go after her: the wolves run with that mist now. Shadewolves, dozens of them, hunting anything warm.', 'Thin them out. Six. Then I’ll tell you who can help you get to that Bell.'], progress: ['Shadewolves circle before they lunge. Keep moving.'],
          complete: ['Six! You fight cold. I mean that kindly.', 'Warden Thessaly in Lanternmarket sent a scout after the riders days ago. He never came back. She’ll want to hear what you know. The city is north-west of here.'],
          after: ['Mind the fog.'] } },
      m6: { title: 'The Scout Who Followed', giver: 'thessaly', summary: 'Free Scout Rook from the Root Ruins and bring him back to Warden Thessaly.', reward: { xp: 140, hearts: 1 },
        text: { offer: ['A frostweaver asking after pale riders. You’re either their friend or their worst enemy.', 'My scout Rook followed them to the Root Ruins, far to the north-west. The wolves have him caged there. Bring him back, and I’ll trust you.'],
          progress: ['The Root Ruins are far to the north-west. Defeat the guards, open the cage, and bring Rook home.'],
          arrive: ['Lanternmarket! Warm lanterns! I’ll never complain about the smoke again.'],
          deliver: ['Frost? Oh no, not more frost… wait. You’re not one of them. Your eyes are warm.', 'I saw them carry a white-haired girl through the ruins. She was singing to keep warm. An old song, with gaps in it, as if she was waiting for someone to sing the other half.'],
          complete: ['Rook is home, and he says you carried him the last mile. Thank you.', 'A song with two voices… But not now. Look at the trees. The mist is coming, and everything in it.'],
          after: ['The watch owes you a debt.'] } },
      m16: { title: 'Lanterns Against the Mist', giver: 'thessaly', summary: 'Hold Lanternmarket’s lantern gate against three waves of shadow creatures riding the mist.', reward: { xp: 300, hearts: 1 },
        text: { offer: ['The mist is rolling in over the walls, and everything in the woods is riding it. They followed Rook. Or they followed you.', 'My watch holds the walls. You hold the lantern gate. Some of the townsfolk say your frost brought this. Prove them wrong.'],
          progress: ['Stand at the lantern gate and stop them before they reach it.'],
          complete: ['The gate stands! You froze a wolf in mid-leap. Little Pim is already telling everyone you’re a snow queen.', 'Nobody in this market will call you a witch again. Not in my hearing.', 'Herbalist Juna has been asking for you. The Old Bellkeeper was hurt by that mist, and she needs someone with cold hands.'],
          after: ['Every lantern lit.'] } },
      m14: { title: 'Kept Cold', giver: 'juna', to: 'bellkeeper', item: 'Frost-kept salve', summary: 'Carry Juna’s moonpetal salve, frozen fresh, to the Old Bellkeeper in Bellhollow.', reward: { xp: 140 },
        text: { offer: ['The Old Bellkeeper tried to climb to the Bell and ring the mist away. It bit him to the bone. Frostbite, the bad kind.', 'This moonpetal salve spoils in a day in this warm city. But you could keep it cold. Frozen fresh, all the way to Bellhollow, south-west of here.'],
          progress: ['Bellhollow is south-west of the city. Keep the salve cold.'], complete: [], after: ['Cold hands, kind heart. My mother used to say that.'],
          deliver: ['Oh, that’s cold. Cold and good. The moonpetal is working already.', 'I climbed to the Bell to ring it. She was there, wound around it: a pale woman in a hood of mist.', 'She looked down at me, and I saw her face under the hood. Young, and sad. Like yours, frostweaver. Very like yours.', 'Roots have grown round the Bell since. Wake the three root runes and they will let it go. The first one sleeps under Glowcap Farm, far to the north-west.'] } },
      m7: { title: 'Glowcaps and Frost', giver: 'bellkeeper', turnIn: 'forester', summary: 'Wake the root rune at Glowcap Farm and tell Forester Birch.', reward: { xp: 110 },
        text: { offer: ['Glowcap Farm lies far to the north-west. Touch the rune and it will wake.', 'Forester Birch works the timber there. He has watched the Huntress ride past his fields, I think. Ask him.'],
          progress: ['Glowcap Farm is far to the north-west.'],
          complete: ['A root rune, humming like a beehive! Welcome, frostweaver. Mind the mushrooms, they sulk in the cold.', 'The Huntress? Aye. She rides past every night, east toward the Thornling Nest. The second rune is there, and the thornlings love her mist.'],
          after: ['Timber and runes, what a week.'] } },
      m15: { title: 'The Pale Huntress', giver: 'ivo', cine: { done: 'lyra-huntress' }, summary: 'Defeat the Pale Huntress and ring the Ancient Root Bell.', reward: { xp: 360, hearts: 1 },
        text: { offer: ['The Old Bell stands in the far north-east. She throws ice in fans, blinks from mist to mist, and calls down the blizzard.', 'Break her, then ring the Bell. Its voice should drive the mist out of Whisperroot for good.'],
          progress: ['The Old Bell stands in the far north-east.'], complete: [], after: ['The Bell rings!'] } },
      m17: { title: 'The Bell-lanterns', giver: 'fox', summary: 'Light the three Bell-lanterns at the Eastern Gate to wither the thorn wall.', reward: { xp: 260 },
        text: { offer: ['(At the foot of the Bell, the old Bell-candle is burning again. Lyra lights a torch from it.)', 'Thorns grew across the Eastern Gate in the mist. Ivo says the three Bell-lanterns beside it will make them remember what they were.', 'The Summit is past that gate. And the Observatory. And Nessa.'],
          progress: ['Three Bell-lanterns by the Eastern Gate.'], complete: ['(The thorn wall shivers. Far behind you, the Bell rings once more, as if to say: go on.)'], after: [] } },
    },
    // ═════════════ Chapter III
    summit: {
      m1: { title: 'Home, and Not Home', giver: 'fox', to: 'guide', summary: 'Go through the Eastern Gate and find Sky-warden Ilsa.',
        text: { offer: ['(An icy wind comes through the Eastern Gate, and it smells of home: pine, snow and woodsmoke.)', 'The Silver Heights. I left three winters ago and swore I wouldn’t come back. Nessa is up there. So I’m back.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
          deliver: ['A frostweaver, walking up out of the woods? You’re a Rimeward, or I’m a goat. You have the look.', 'Frost wraiths came down from the Cradle a week ago with a girl slung over a saddle. White hair, loud voice. She bit one of them.', 'My courier Bramble followed them as far as she dared. Talk to her. She’s just over there, blowing on her paws.'] } },
      m2: { title: 'The Hamlet Road', giver: 'bramble', turnIn: 'aune', summary: 'Clear six void wisps from the road to Frostpine Hamlet (the gold arrow leads to them), then find Healer Aune there.', reward: { xp: 80 },
        text: { offer: ['Void wisps swarm the road south-east to the hamlet. Six of them are sitting on it like it’s theirs.', 'Clear them, and find Healer Aune. She’ll know you. Everyone in Frostpine knew your gran.', 'Mind you: the pale ghosts are frost wraiths. The wisps are the small violet lights that dart side to side.'],
          progress: ['Wisps are small violet lights on the road south-east. Follow the gold arrow to the nearest one.'],
          complete: ['Lyra Rimeward. You have your gran’s scowl exactly.', 'I know why you’ve come. The wraiths dragged your sister past my door, to the Old Observatory.'],
          after: ['Warm hands, warm heart.'] } },
      m5: { title: 'What the Sky Remembers', giver: 'corvin', summary: 'Look into Mirrorsky Tarn, then return to Abbot Corvin in Skyhold.', reward: { xp: 120 },
        text: { offer: ['The Rime-book says the Rimewardens were a family of frost-singers. Two sisters in every generation: one voice of cold, one of warmth.', 'It says they once sang a crown of frost around the star, to keep its light from burning out. The rest is written in ice-script. I cannot read it.', 'Mirrorsky Tarn remembers what the sky saw. It lies north-west of here, above the hamlet. Look into it. You will understand it better than I.'],
          progress: ['Mirrorsky Tarn lies north-west of Skyhold, above the hamlet.'],
          complete: ['So that is the Queen. Your family’s own frost, fallen with the star and crowned by the dark.', 'She cannot sing the Rime Song herself. She needs two Rimeward voices to seal the mountain in ice forever. That is why she took your sister. That is why she wants you.', 'Then crack her crown. The tarn showed you three shards of the fallen star. The first lies in Crystal Hollow.'],
          after: ['The sky is a map. Your family drew part of it.'] } },
      m6: { title: 'A Shard in Crystal Hollow', giver: 'corvin', turnIn: 'lyra-nessa-sky', summary: 'Take the star shard from Crystal Hollow, then bring it to Nessa in Skyhold.', reward: { xp: 120 },
        text: { offer: ['Crystal Hollow is in the far north-west, beyond the lookout. The shard hums the note of the star.', 'Nessa will wait here with me. She has already reorganised my library. Twice.'],
          progress: ['Crystal Hollow is in the far north-west. Then back to Nessa in Skyhold.'],
          complete: ['A star shard! It’s warm. Why is it warm? It’s a bit of the sky! Shouldn’t it be cold?', 'Corvin and I read more of the Rime-book. Well, he read. I guessed.'],
          after: ['Two more shards. I’m counting.'] } },
      m14: { title: 'The Queen Sends Her Winter', giver: 'dov', summary: 'Hold the Silver Pass barricade against three waves from the void.', reward: { xp: 160 },
        text: { offer: ['She knows you have two shards. She’s throwing everything at my camp to stop you reaching the third.', 'Hold the barricade with us. Three waves, and they’ll give up for tonight.'],
          progress: ['Stand by the barricade and break every wave.'],
          complete: ['The pass holds! And look at my barricade: wrapped in your ice, thick as a wall, and not a scratch on it.', 'The last shard is at the Broken Spire, east of here.'],
          after: ['The pass holds.'] } },
      m15: { title: 'The Last Shard', giver: 'dov', turnIn: 'lyra-nessa-sky', summary: 'Take the last star shard from the Broken Spire, then bring it to Nessa in Skyhold.', reward: { xp: 130 },
        text: { offer: ['The Broken Spire fell with the star, and still points at it. The last shard is up there.', 'Then take it back to your sister in Skyhold, south of here. I hear she has plans. Loud ones.'],
          progress: ['The Broken Spire lies east of the pass. Then back to Skyhold.'],
          complete: ['All three shards! And Lyra, I finished the Rime-book. The ice-script is just Gran’s handwriting, backwards.', 'The Rime Song only works with both voices. Cold alone seals things forever. Warm alone melts everything. Together, frost keeps things safe. Like snow on seeds.', 'That’s why Gran taught us both halves. You got the cold. I got the warm. We have to sing it together at the Star Altar before we face her.'],
          after: ['I’m nervous. Are you nervous? You look nervous. For you.'] } },
      m19: { title: 'Queen Hoarfrost', giver: 'lyra-nessa-sky', summary: 'Defeat Queen Hoarfrost at the Star Cradle and return the shards to the star.', reward: { xp: 420, hearts: 1 },
        text: { offer: ['The Star Cradle is at the top of the world, north-east of the Spire. She rains blizzards, slams the ice, spins frost in spirals and steps through the cold like a door.', 'She’s made of the same frost as you, Lyra, so she knows your tricks. But she doesn’t know mine. I’ll be singing the whole time, from right here. You won’t hear me. You’ll feel it.', 'Crack her crown, then lay the three shards in the Cradle.'],
          progress: ['The Star Cradle is in the far north-east.'], complete: [], after: ['The star is home.'] } },
      m20: { title: 'Two Voices at the Gate', giver: 'lyra-nessa-sky', who: NESSA, summary: 'Walk Nessa to the Eastern Gate, where the Rimeward sisters will sing the black ice apart.', reward: { xp: 380, hearts: 1 },
        text: { offer: ['You did it! I felt it, all the way down here. Like a door opening.', 'Umbra ran east and sealed the pass behind it with black ice. Corvin says only the Rime Song can break frost with no warmth in it.', 'So walk me to the Eastern Gate. It’s a long way, and the last of her wraiths will try to stop us. We sing it together, or not at all.'],
          progress: ['Lead Nessa to the Eastern Gate and keep the wraiths off her.'],
          arrive: ['There it is. It looks like the inside of a nightmare. Right. On three, Lyra. One… two…'],
          complete: ['(Nessa takes a deep breath, and Lyra takes her hand.)'], after: [] } },
    },
    // ═════════════ Chapter IV
    ember: {
      m1: { title: 'Frost in the Wastes', giver: 'fox', to: 'guide', summary: 'Follow Umbra’s trail through the Eastern Gate and find Captain Ashka.',
        text: { offer: ['(Hot wind blows through the broken ice, and the snow on Lyra’s cloak turns to steam.)', 'Umbra fled into the Ember Wastes. Nessa has run on ahead with the post, of course. Nobody catches her twice.', 'A land of fire. I’ll be about as useful as a snowball in a kiln. …Well. Let’s find out.'], progress: ['Take the road east through the gate.'], complete: [], after: [],
          deliver: ['A frostweaver? In the Wastes? Ha! You’ll be a puddle by noon.', 'Something black fell out of the west wind two nights ago. Since then the imps have gone mad, and the Dawn Forge sits cold, with a fire-serpent wrapped round it.', 'And here they come again. Can that cold of yours do anything besides melt?'] } },
      m2: { title: 'A Wall of Ice', giver: 'guide', summary: 'Hold the gate of Emberwatch Outpost against three waves of imps.', reward: { xp: 140, hearts: 1 },
        text: { offer: ['Ember imps hover out of reach and lob fire. They’ve set the outpost gate alight every night since the black thing fell.', 'Here they come! Hold the gate with us, frostweaver, if you don’t melt first.'],
          progress: ['Stand by the outpost gate. Imps keep their distance, so close in fast.'],
          complete: ['You put the gate OUT. Every fire, in one breath. My lads have never seen ice before. One of them licked it.', 'I take back the puddle. Stay as long as you like.', 'There’s a courier here with a letter for you. Small, sooty, very pleased with herself.'],
          after: ['Watch the sky for sparks.'] } },
      m14: { title: 'The Soot-sprite and the Satchel', giver: 'hessa', turnIn: 'nessa', summary: 'Catch the soot-sprite who snatched Nessa’s satchel near Saltglass Farm, and bring the satchel back to her in Brasshaven.', reward: { xp: 180 },
        text: { offer: ['Word just came from Fenwick’s farm. A little soot-sprite snatched a satchel off a courier on the road. A white-haired courier, shouting very rude words.', 'Your sister, I’d guess. The sprite hides around Saltglass Farm, south-west of here. It’s fast, but it tires. Then take the satchel to her in Brasshaven.'],
          progress: ['Cinderfinch hides near Saltglass Farm. Run it down: it has to stop for breath.'],
          deliver: ['Eek! Cold! COLD! Alright, take it, take the bag!', 'The imps said they’d burn my nest if I didn’t steal letters for the fire-serpent. It eats them. It eats everything with a warm word in it.'],
          complete: ['My satchel! Nobody catches me twice, and nobody catches HIM once, apparently. Except you.', 'Poor little thing. Tovan says it can sleep in his forge ash. Tovan says a lot of things, loudly. And right now he needs you.'],
          after: ['Brasshaven is SO hot. I’m building a snowman out of salt.'] } },
      m7: { title: 'The Water Caravan', giver: 'tovan', summary: 'Free Caravan-master Oona at the Salt Caravan Camp and bring her to Tovan in Brasshaven.', reward: { xp: 160, hearts: 1 },
        text: { offer: ['Oona’s caravan carries salt and water to every town in the wastes. The imps have her caged at the camp, south-east of the city.', 'And her water barrels are boiling dry in the sun. Bring her home before the whole caravan turns to steam.'],
          progress: ['The Salt Caravan Camp lies south-east of the city. Defeat the guards, open the cage, and bring her to Brasshaven.'],
          arrive: ['Brasshaven’s brass gates! And my barrels… you froze my barrels? You beautiful icicle.'],
          deliver: ['Sand in my teeth and a scorpion on my chest. I thought I was done.', 'They dragged the second ember core into the Scorpion Burrows. And my water! Freeze it, freeze it, before it boils!'],
          complete: ['Oona is safe, and her water with her, frozen solid and thawing slowly all the way home. Clever.', 'The Scorpion Burrows are south-west of the city. Mind the ground: they swim through the sand.'],
          after: ['The caravan owes you. So does every thirsty town in the wastes.'] } },
      m8: { title: 'Cold Under the Sand', giver: 'tovan', summary: 'Take the second ember core from the Scorpion Burrows.', reward: { xp: 150 },
        text: { offer: ['Ash scorpions burrow and come up right under your feet. When the sand bulges, move!', 'The second core is in their burrows, south-west of the city. Hold it in frost, like the first.'],
          progress: ['The Scorpion Burrows lie south-west.'],
          complete: ['Two cores! The first one sings when the second comes near. The forge is remembering.', 'Your sister came by. She has a letter for Ashfall Watch, and she says the imps won’t stop her. I told her to wait for you. She is waiting. Very loudly.'],
          after: ['Two of three.'] } },
      m10: { title: 'The Foundry Core', giver: 'seer', turnIn: 'seer', summary: 'Take the last ember core from the Old Foundry, then return to Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 180 },
        text: { offer: ['The Old Foundry lies north-east of Brasshaven, where Pyrrhus kept his magma hulks. The last core burns at its heart.', 'Hold it in frost as you held the others, and bring it to me.'],
          progress: ['The Old Foundry is north-east of Brasshaven. Ashfall Watch is north of the city.'],
          complete: ['Three cores, all together. Feel them. The forge is calling them home.', 'But the Cinderwyrm will not let you near while it can still drink. It feeds on the Molten Mere, through channels of slag deep under the sand.'],
          after: ['The flames speak of you.'] } },
      m15: { title: 'Breath for a Cold Forge', giver: 'fox', cine: { done: 'pyrrhus-wakes' }, summary: 'Gather brass gears at the Old Foundry, then rebuild the Great Bellows at the Dawn Forge.', reward: { xp: 300 },
        text: { offer: ['Ilyana says three cores are not enough. A forge must breathe, and its Great Bellows were smashed when the serpent coiled round it.', 'The Old Foundry is full of brass gears. Four of them, to the Dawn Forge in the far north-east, and the forge breathes again.', 'And the Cinderwyrm will rise, starving and furious. Good. I’m tired of it hiding.'],
          progress: ['Four brass gears from the Old Foundry, then build at the Dawn Forge.'], complete: [], after: [] } },
      m12: { title: 'Cinderwyrm', giver: 'fox', summary: 'Defeat the Cinderwyrm, the Serpent in the Slag, at the Dawn Forge.', reward: { xp: 480, hearts: 1 },
        text: { offer: ['(The Cinderwyrm rears over the Dawn Forge, and the air shimmers with heat.)', 'It rains lava, spins fire in spirals and charges like a landslide, and wherever it has been, the ground burns. Never stand still.', 'It hates frost. Good. Let it hate me. Nessa is singing, and I’m not afraid of my cold any more.'],
          progress: ['The Dawn Forge is in the far north-east.'], complete: [], after: ['Be brave.'] } },
      m13: { title: 'The Endless Winter Night', giver: 'fox', summary: 'Defeat Umbra, the Endless Winter Night, and light the Dawn Forge.', reward: { xp: 900, hearts: 2 },
        text: { offer: ['(The Cinderwyrm crumbles into cooling slag, and for one breath the forge is quiet. Then every ember in the wastes goes out at once.)', '(Far to the west, dark light rises from the Beacon Rise, the Old Bell and the Star Cradle. The shadows of the serpent, the Huntress and the Queen gather into one.)', '(Black frost creeps over the Dawn Forge: a winter with no warmth anywhere in it. Nessa takes your hand. Umbra is here.)'],
          progress: ['Defeat Umbra at the Dawn Forge.'], complete: [], after: [] } },
    },
  },
  npcs: {
    meadow: [
      { id: 'lyra-wick', name: 'Wick', portrait: '🧒', at: 'millbrook', dx: -140, dy: 90, activity: 'wander', after: 'lyra2', look: look('#5a4a3a', 'cap', { hatColor: '#2e2420', small: true }), lines: ['I’m mending fences. For free. Bram says it builds character. I had loads of character before.', 'Your sister gave me a biscuit once, you know. I should’ve given her letters back.'], barks: ['Honest work, ugh.', 'Sorry about the letters!'] },
      { id: 'lyra-tansy', name: 'Courier Tansy', portrait: '🧑', at: 'city', dx: -60, dy: 300, activity: 'wander', after: 'm6', look: COURIER, lines: ['Nessa and I raced the whole east road in my cart. She steers like a mad goat. Best courier I ever rode with.', 'The post always gets through. Say it with me.'], barks: ['Post’s moving again!', 'Mind the boars!'] },
    ],
    woods: [],
    summit: [
      { id: 'nessa', name: 'Nessa', portrait: '👧', at: 'hamlet', dx: 60, dy: -120, activity: 'play', after: 'lyra4', until: 'lyra24', look: NESSA.look, lines: ['Aune says I have to stay warm. I’m warm! I’m SO warm.', 'You came all this way for me. You’re the best big sister in the whole valley. Don’t let it go to your head.'], barks: ['Lyra!', 'Snowball!'] },
      { id: 'lyra-nessa-sky', name: 'Nessa', portrait: '👧', at: 'city', dx: -260, dy: 200, activity: 'play', after: 'lyra24', until: 'm20', look: NESSA.look, lines: ['Corvin lets me read the Rime-book if I don’t lick my fingers to turn the pages. I lick them a little.', 'Gran’s handwriting is terrible. It’s like ice-script. It might actually BE ice-script.'], barks: ['Lyra! Over here!', 'I’m practising my half!'] },
    ],
    ember: [
      { id: 'nessa', name: 'Nessa', portrait: '👧', at: 'city', dx: -60, dy: 300, activity: 'play', after: 'summit:m20', until: 'lyra38', look: NESSA.look, lines: ['I carried Tovan’s letters all the way here! Nobody catches me twice.', 'Well. The soot-sprite did, once. That doesn’t count. It was a sprite.'], barks: ['Special delivery!', 'It’s SO hot!'] },
      { id: 'lyra-nessa-watch', name: 'Nessa', portrait: '👧', at: 'watch', dx: 70, dy: -80, activity: 'play', after: 'lyra38', look: NESSA.look, lines: ['Ilyana says the flames like my singing. I think the flames are being polite.', 'When this is over, we’re going home together. Both of us. You promised. Well, I promised for you.'], barks: ['I’m warming up my voice!', 'La-laaa!'] },
    ],
  },
  // Orrin and Sable are Mira's story; Lyra only hears of them. Their places at the Summit stay empty for her.
  npcFor: {
    'summit:orrin': { hidden: true }, 'summit:orrin2': { hidden: true },
    'summit:sable': { hidden: true }, 'summit:sable2': { hidden: true }, 'summit:sable3': { hidden: true },
  },
  script: {
    meadow: {
      pickupKey: 'Sun-crystal found! {n}/3',
      sealed: 'Gloamgill lies coiled deep in the black water under the Rise. Only the light of three sun-crystals will draw it up.',
      tip: 'When the ground bubbles where Gloamgill swims, move! Frostbolt slows even a serpent. Spend gold at the smith in Goldenhearth to grow stronger.',
      guide: { done: ['The meadow is bright again. Your sister would be proud of you.'] },
      finale: { locked: ['The Beacon is dark, and the water under the Rise lies still. Three sun-crystals are needed to draw up what sleeps below.'], guarded: ['Gloamgill is coiled around the Beacon. Defeat the serpent to relight it.'],
        done: ['The crystals blaze in the Beacon, and gold light pours down the Rise into the dark water below.', 'Gloamgill shudders, spits a soaked courier’s satchel onto the stones, and sinks back into the deep to sleep another hundred years.', 'Inside, wrapped in oilcloth and perfectly dry, is a letter in Nessa’s round hand: “For Lyra. Silver Heights. Please deliver.”'] },
      victory: { title: 'The Beacon shines again.', text: 'Nessa’s letter is found and the meadow is safe. But she ran east over the Gloomwater Bridge into Whisperroot Woods, and pale riders were waiting on the other side.' },
    },
    woods: {
      pickupKey: 'Root rune awakened. {n}/3',
      sealed: 'The Pale Huntress is wrapped in sleeping roots and mist. Wake the three root runes first.',
      tip: 'The Huntress blinks from mist to mist and throws ice in fans. When she vanishes, keep moving, and step out of the blizzard’s circles.',
      guide: { done: ['The woods are warm again. Who would have thought a frostweaver would bring the warmth back?'] },
      finale: { locked: ['Three root runes are needed to loosen the roots around the Bell.'], guarded: ['The Pale Huntress is wound around the Bell.'],
        done: ['You ring the Ancient Bell. Its voice rolls through every root, and the winter mist drifts out of Whisperroot like breath on a cold morning.', 'Where the Huntress sat, a scrap of blue wool is caught on the Bell’s rim: the other mitten.', 'Nessa was here. The riders carried her on, east and up, toward the Summit.'] },
      victory: { title: 'The Bell rings through the valley.', text: 'The winter mist is gone from Whisperroot, and the Huntress with it, for now. Nessa is on the Summit, in the Old Observatory, and Lyra is going home.' },
    },
    summit: {
      pickupKey: 'Star shard gathered. {n}/3',
      sealed: 'Queen Hoarfrost is sealed behind a crown of black frost. Gather the three star shards first.',
      tip: 'When the Queen’s blizzard falls, blink out of its circles. When she steps out of the cold beside you, she slams the ice. Never stand still.',
      guide: { done: ['The Heights are yours again, Rimeward. Come home more often.'] },
      finale: { locked: ['The Cradle is cold, and the frost on it is black. Three star shards are needed.'], guarded: ['Queen Hoarfrost sits on the Cradle in her crown of ice. Defeat her!'],
        done: ['You lay the three shards in the Cradle. The star remembers its light and rises, whole, with a soft crown of frost around it.', 'Far below in Skyhold, a small voice is still singing the warm half of an old song. You can feel it in your hands.', 'But a thread of black smoke has torn loose from the Queen’s broken crown and fled east, toward the Ember Wastes. Umbra is not finished.'] },
      victory: { title: 'The star rises home.', text: 'Nessa is free, the Rimeward sisters sing together again, and the star is whole. But Umbra fled east into the Ember Wastes, where frost has never been welcome.' },
    },
    ember: {
      pickupKey: 'Ember core held in frost. {n}/3',
      sealed: 'The Cinderwyrm sleeps curled in the slag, wrapped in a shell of cooling stone. Recover the three ember cores first.',
      tip: 'The Cinderwyrm leaves fire wherever it charges: never follow its trail. Its lava falls in circles you can blink out of.',
      guide: { done: ['The wastes are cooling. Who’d have guessed it would take a frostweaver?'] },
      finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['The Cinderwyrm is coiled around the forge. Defeat it!'],
        done: ['You set the three ember cores in the Dawn Forge. Nessa sings the warm voice, you sing the cold one, and the fire takes, tempered and steady.', 'Its flame roars up white and gold, and a new dawn spills across the wastes, with a little snow in it.', 'Far to the west, the Star, the Bell and the Beacon shine back. The endless winter night is over.'] },
      victory: { title: 'The dawn returns.', text: 'Umbra is gone for good. The Dawn Forge burns again, and the Rimeward sisters, frost and warmth together, have become the valley’s newest legend.' },
    },
  },
  cines,
};
