import { LOOKS, type Shot } from '../cutscenes';
import { look, own, person, type HeroStory } from './kit';

// Lyra, the Frostborn. The night the star fell, her little sister Nessa, a courier, vanished on the meadow's lake road.
// Lyra is a Rimeward of the Silver Heights, a family of frost-singers: two sisters in every generation, one voice of
// cold and one of warmth, singing the Rime Song. Long ago two Rimewardens sang a crown of frost around the star to keep
// its light bright. When the star fell, that frost fell with it, and Umbra crowned it: Queen Hoarfrost, frost without
// any warmth, who wants both sisters' voices to seal the mountain in ice forever.
// When Lyra was twelve she sang the song alone, and her cold froze Gran's glasshouse with Nessa inside. Nessa's hair
// has been white ever since, and Lyra has kept her frost, and everyone else, at arm's length. Umbra's shadow takes the
// shape of what she fears: cold that takes and keeps (a lake serpent, a pale rider with her own face, a queen of ice,
// a serpent of fire that hates all frost) and at last an endless winter night.
//
// Every link of her story is her own; only the guardians and Umbra are the valley's quests, told in her words.
// I · the lost post (meadow): Fisher Lou saw Nessa run the shore, and the frost runes of Mirror Lake show Lyra the night
//   the satchel went into the water. Her frost follows Nessa's scattered letters to Wick, the Gloom Hollow and Wynne's
//   drawer of unsent letters for Lyra. Lou's scales name the serpent; Nessa posted one sun-crystal in Tansy's cart, Odo
//   keeps one among his sheep, and freezing the Faerie Ring's springs traps Gloamgill and pushes the last one up in the
//   ice. After the serpent, Lyra freezes a bridge across the Gloomwater.
// II · the Huntress (woods): the mist shrinks from her. Couriers, Nana's stove, the frozen trail to Blackwater Pool, a
//   lantern built for Nessa and the pale rider. She frees the Bellkeeper from a cage of ice, holds her lantern against
//   the mist, wakes the root runes (the first where the roots began) and faces the Huntress with her own face. Then she
//   freezes the thorn wall to glass so Nutkin can carry the post east.
// III · home (summit): the glasshouse remembered, Gran's marks in the snow, Nessa freed at the Observatory, a blizzard,
//   the sisters' talk by the well, the Rime-book read by frost. Shards under Mirrorsky Tarn, on Frostfang Crag and in the
//   Void Rift, where a herald speaking with the Queen's voice flees. The Rime Song, the Queen, and at the gate Lyra holds
//   off the last wraiths while Nessa sings the black ice apart.
// IV · frost in a land of fire (ember): she freezes the imps out of the sky over Emberwatch, cools Brasshaven's vents,
//   carries cores in frost (from the Obsidian Maze, from Oona's boiling water barrels, from the cooling Molten Mere),
//   walks Nessa to Ashfall Watch, brings snow to the Last Green and cracks the slag shell of the Cinderwyrm.
const q = own('lyra');
const NESSA = person('Nessa', '👧', { robe: '#6f8fb8', hat: 'scarf', hatColor: '#dff6ff', hair: '#e8e2d0', small: true });
const COURIER = look('#c16d59', 'cap', { hatColor: '#6f8fb8', hair: '#b8743c' });
const HUNTRESS = look('#e8f4ff', 'hood', { hatColor: '#bfe8ff', skin: '#e8f4ff', hair: '#ffffff' });
const RIME_COLD = look('#dff6ff', 'hood', { hatColor: '#8ee8ff', hair: '#e8e2d0' });
const RIME_WARM = look('#f0e6d8', 'scarf', { hatColor: '#ffb38a', hair: '#e8e2d0' });
const LITTLE_LYRA = look('#dff6ff', 'hood', { hatColor: '#8ee8ff', hair: '#cfe6f5', small: true });
const LITTLE_NESSA = { ...LOOKS.nessa, hair: '#8a5a3a' };
const NUTKIN = person('Courier Nutkin', '🐿️', look('#a86d49', 'ears', { hatColor: '#80522d', small: true }));
const BELLKEEPER = person('Old Bellkeeper', '🧓', look('#9c7860', 'cap', { hatColor: '#6b4a3a', beard: true, hair: '#e8e2d0' }));
const HERALD = person('The Crowned Herald', '👻', { robe: '#dff6ff', hat: 'hood', hatColor: '#8ee8ff', skin: '#e8f4ff', hair: '#ffffff' });

const cines: Record<string, Shot[]> = {
  // ─────────────── Chapter I
  'lyra-lake-memory': [
    { at: 'meadow:mirror', dx: 200, dy: -560, night: .6, text: '(The frost runes ring like bells. Ice races across the water, and the lake remembers.)', fx: [{ kind: 'frost' }, { kind: 'memory', delay: .6 }], dur: 4 },
    { text: 'Nessa, the night the star fell, running along this very shore with her satchel clutched to her chest.', actors: [{ id: 'enessa', name: 'Nessa', look: LOOKS.nessa, dx: -300, dy: 30, walk: { dx: 460, dy: 40 } }], dur: 4.6 },
    { text: 'Pale riders drift out of the reeds behind her, on horses made of mist.', fx: [{ kind: 'wisps', n: 3, dx: -260 }, { kind: 'frost', dx: -200, delay: .5 }], dur: 4 },
    { speaker: 'Nessa', portrait: '👧', text: '“You’re not having the post! Nobody gets the post!”', fx: [{ kind: 'letters', dx: 160, dy: 200, delay: .4 }], dur: 3.6 },
    { at: 'meadow:mirror', text: 'She flings the satchel far out over the water… and something vast and green rises out of the deep to swallow it.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .4 }], dur: 4.6 },
    { at: 'hero', night: 0, speaker: 'Lyra', portrait: '❄️', text: '“Frost wraiths, from the Summit. And a serpent in the lake. Hold on, Nessa. I’m coming.”', dur: 4 }],
  'lyra-frost-trail': [
    { at: 'hero', text: 'Lyra kneels in the wet grass by the shore and lays her palm flat on the ground.', dur: 3.2 },
    { text: 'Frost runs out from her fingers in a thin white thread, west along the lake road…', fx: [{ kind: 'frost' }, { kind: 'frost', dx: -260, dy: -60, delay: .6 }, { kind: 'frost', dx: -520, dy: -120, delay: 1.2 }], dur: 4 },
    { at: 'meadow:millbrook', cut: true, text: '…and wherever one of Nessa’s letters lies in the grass, the frost stops and glitters, like a finger pointing.', fx: [{ kind: 'letters' }, { kind: 'frost', delay: .5 }], dur: 4.4 },
    { at: 'hero', cut: true, speaker: 'Lyra', portrait: '❄️', text: '“My cold always finds her. For once, I’m glad of it.”', dur: 3.6 }],
  'lyra-unsent-letters': [
    { at: 'npc:meadow:wren', text: 'Postmistress Wynne pulls open a drawer behind her counter. It is stuffed full of envelopes.', dur: 3.8 },
    { text: 'Every one says the same, in Nessa’s round, careful hand: “For Lyra. Silver Heights.” Not one of them has a stamp.', fx: [{ kind: 'letters' }], dur: 4.6 },
    { speaker: 'Postmistress Wynne', portrait: '📮', text: '“One a month, for three winters. She wrote them and never sent them. Said you’d only freeze them.”', dur: 4.4 },
    { speaker: 'Postmistress Wynne', portrait: '📮', text: '“The night the star fell, she finally sent one. She put it in her own satchel, love.”', dur: 4.2 },
    { at: 'meadow:mirror', cut: true, dy: -40, night: .3, text: 'Far to the south, under the black water of Mirror Lake, something vast turns over in its sleep.', fx: [{ kind: 'shadow' }, { kind: 'quake', delay: .4 }], dur: 4.2 },
    { at: 'npc:meadow:wren', cut: true, night: 0, speaker: 'Postmistress Wynne', portrait: '📮', text: '“And Lou’s been banging on my door since dawn, waving a scale as big as a dinner plate. Maybe he isn’t so daft after all.”', dur: 4.6 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“Then I’m going to get that letter back.”', dur: 3 }],
  'lyra-cart': [
    { at: '$ward', dy: -30, text: 'Tansy’s cart lies on its side at the edge of Rotwood Den, wheels in the air. A courier in a red coat is sitting on top of it.', actors: [{ id: 'ctansy', name: 'Courier Tansy', look: COURIER, dy: -20 }], dur: 4.6 },
    { speaker: 'Courier Tansy', portrait: '🧑', text: '“Three days I’ve been up here! Three! I’ve run out of turnips to throw!”', actors: [{ id: 'ctansy', name: 'Courier Tansy', look: COURIER, dy: -20 }], dur: 3.8 },
    { text: 'Out of the dark under the trees come the bristleboars, tusks low, and the gloom creeping after them.', fx: [{ kind: 'gloom', n: 4, dx: 300, dy: 60 }, { kind: 'quake', delay: .6 }], dur: 4 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“Stay up there, Tansy. And cover your ears. This is going to be cold.”', fx: [{ kind: 'frost' }], dur: 3.8 }],
  'lyra-springs-frozen': [
    { at: 'meadow:faerie', text: 'The last spring groans and turns to glass. Frost runs down into the earth after it, along every hidden stream.', fx: [{ kind: 'frost', n: 3 }, { kind: 'quake', delay: .8 }], dur: 4.4 },
    { text: 'Far underground, something very large bumps against the ice. Then again, harder.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .4 }], dur: 3.8 },
    { at: 'meadow:rise', cut: true, dy: -70, night: .4, text: 'Under the Beacon Rise, Gloamgill uncoils in the black water and lifts its great head toward the cold Beacon.', fx: [{ kind: 'shadow', dy: -40 }, { kind: 'quake', delay: .5 }], dur: 4.6 },
    { at: 'meadow:faerie', cut: true, night: 0, text: 'And in the ice of the last spring, pushed up from the deep, something glows gold.', fx: [{ kind: 'light' }], dur: 4 }],
  'lyra-last-letter': [
    { at: 'meadow:rise', dy: -90, text: 'The Beacon roars back to life, and gold light spills across the meadow.', fx: [{ kind: 'light', dy: -90 }], dur: 3.8 },
    { at: 'hero', text: 'Lyra breaks the wax seal with cold fingers.', fx: [{ kind: 'letters' }], dur: 3 },
    { speaker: 'Nessa’s letter', portrait: '✉️', text: '“Lyra. It’s been three winters. Come down from the mountain. I’m not afraid of your frost. I never was.”', dur: 5 },
    { speaker: 'Nessa’s letter', portrait: '✉️', text: '“Pale riders keep asking at the post house for ‘the Rimeward girls’. I told them to go and boil their heads. Love, N.”', dur: 5 },
    { at: 'obj:meadow:barrier', cut: true, text: 'Far to the east, the Gloomwater Bridge lies broken in the river. On the far bank, a white mist hangs under the trees.', fx: [{ kind: 'collapse' }, { kind: 'frost', dx: 300, delay: .8 }], dur: 4.8 },
    { at: 'npc:meadow:holt', text: 'Bridgewright Holt is already there, staring at the wreck and scratching his head.', dur: 3.6 }],
  'chapter-meadow@lyra': [
    { at: 'obj:meadow:barrier', text: 'Ice races across the Gloomwater and locks round every timber. The bridge stands again, blue as glass, over the water Nessa crossed.', fx: [{ kind: 'frost' }, { kind: 'build', delay: .6 }], dur: 4.4 },
    { at: 'obj:meadow:barrier', dx: 900, text: 'Beyond it, the road dives under ancient trees, and a cold white mist lies between the trunks.', fx: [{ kind: 'frost' }], dur: 4 },
    { at: 'woods:bell', cut: true, dy: -60, text: 'Deep in Whisperroot, a pale rider sits wound around the silent Bell, and the mist pours off her like breath.', actors: [{ id: 'chunt', name: '???', look: HUNTRESS, dy: 40, spirit: true }], fx: [{ kind: 'frost', dy: -60 }, { kind: 'shadow', dy: -60, delay: .6 }], dur: 5 },
    { title: 'Chapter II', sub: 'The Bell Beneath the Roots', dur: 3.4 }],
  // ─────────────── Chapter II
  'lyra-mist-parts': [
    { at: 'woods:camp', dx: -300, dy: -100, text: 'White mist lies between the trunks of Whisperroot, thick as wool and cold enough to kill the moss.', fx: [{ kind: 'frost', dx: -200 }, { kind: 'wisps', n: 2, dx: -100 }], dur: 4.2 },
    { at: 'hero', text: 'It curls toward Lyra like a cat… sniffs at her sleeve… and draws back from her, all at once.', fx: [{ kind: 'frost' }, { kind: 'ring', delay: .8 }], dur: 4.2 },
    { at: 'npc:woods:guide', text: 'At the camp, Mosskeeper Oda lowers her lantern and stares.', dur: 3.2 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“It knows what I’m made of. …And it’s afraid of me. Good.”', dur: 3.8 }],
  'rider-flees@lyra': [
    { at: '$thief', text: 'The pale rider shrieks, and a gust of snow tears it free of your grip.', fx: [{ kind: 'frost' }], dur: 3.6 },
    { dy: -200, text: 'It streaks away north-east over the treetops, toward the Old Bell, where the mist is thickest.', fx: [{ kind: 'lantern', to: { dx: 1400, dy: -1400 } }, { kind: 'wisps', n: 2, delay: .8 }], dur: 4 },
    { at: 'woods:bell', cut: true, dy: -40, night: .4, text: 'There, wound around the silent Bell, a pale woman on a horse of fog lifts her head, and listens.', actors: [{ id: 'fhunt', name: 'The Pale Huntress', look: HUNTRESS, dy: 40, spirit: true }], fx: [{ kind: 'frost', dy: -40 }], dur: 4.6 },
    { at: 'hero', night: 0, speaker: 'Lyra', portrait: '❄️', text: '“Observatory. So Nessa is on the Summit. But first, you and I are going to have words.”', dur: 3.8 }],
  'lyra-lantern-siege': [
    { at: '$ward', dy: -40, night: .5, text: 'Night on Blackwater Pool. The lantern Lyra built burns on the shore, the only warm light for a mile.', fx: [{ kind: 'kindle', dy: -40 }], dur: 4 },
    { dx: -400, text: 'Out on the water, the mist gathers into the shape of a rider, and the rider points at the lantern.', actors: [{ id: 'lhunt', name: '???', look: HUNTRESS, dx: -400, dy: 20, spirit: true }], fx: [{ kind: 'frost', dx: -400 }], dur: 4.4 },
    { text: 'Shadewolves slip out of the reeds. Cold lights drift behind them.', fx: [{ kind: 'wolves', n: 3, dx: -250 }, { kind: 'wisps', n: 2, dx: -150, delay: .6 }], dur: 4 },
    { at: 'hero', night: .3, speaker: 'Lyra', portrait: '❄️', text: '“That light is for Nessa. Nobody puts it out.”', dur: 3.4 }],
  'lyra-huntress': [
    { at: 'woods:bell', dy: -80, text: 'The Ancient Bell rings out, and the winter mist tears apart like wet paper.', fx: [{ kind: 'light', dy: -80 }, { kind: 'ring', dy: -80, delay: .4 }], dur: 3.8 },
    { at: 'woods:bell', dy: 30, text: 'The Pale Huntress kneels in the melting frost. Her hood slips back.', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], dur: 4 },
    { text: 'Under it is Lyra’s own face: older, colder, and with no one standing beside it.', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], fx: [{ kind: 'frost', dx: 40 }], dur: 4.2 },
    { speaker: 'The Pale Huntress', portrait: '👻', text: '“You froze her once. I only finished what you started. Stay alone, frost-daughter. It is safer for everyone.”', actors: [{ id: 'hhunt', name: 'The Pale Huntress', look: HUNTRESS, dx: 40, dy: 40, spirit: true, face: -1 }], dur: 5 },
    { text: 'Then she is mist, and the mist is gone.', fx: [{ kind: 'wither', dx: 40 }], dur: 3 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“That’s what I’d become if I stopped looking for her. …I won’t.”', dur: 4 }],
  'chapter-woods@lyra': [
    { at: 'obj:woods:barrier', text: 'Frost races through the thorn wall at the Eastern Gate, until every stem and every thorn is white glass…', actors: [{ id: 'cnut', name: 'Nutkin', look: NUTKIN.look, dx: -160, dy: 40 }], fx: [{ kind: 'frost', delay: .3 }], dur: 4 },
    { text: '…and Nutkin taps it once with his post-horn. The whole wall shatters into glittering dust.', actors: [{ id: 'cnut', name: 'Nutkin', look: NUTKIN.look, dx: -160, dy: 40 }], fx: [{ kind: 'shatter' }], dur: 3.8 },
    { at: 'summit:observatory', cut: true, dy: -60, night: .5, text: 'High on the Silver Heights, in the Old Observatory, a white-haired girl sits in a cage of ice, singing half a song.', actors: [{ id: 'cnessa', name: 'Nessa', look: LOOKS.nessa, dy: 40 }], fx: [{ kind: 'frost', dy: -20 }], dur: 5 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'Above her, in the Star Cradle, a queen of ice listens to every note.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'shadow', dy: -80, delay: .5 }], dur: 4.4 },
    { title: 'Chapter III', sub: 'The Hollow Star', dur: 3.4 }],
  // ─────────────── Chapter III
  'lyra-glasshouse': [
    { at: 'hero', text: '(The wind through the gate smells of pine, snow and woodsmoke. Of home.)', fx: [{ kind: 'frost' }], dur: 3.8 },
    { at: 'summit:hamlet', cut: true, dy: -60, night: .3, text: 'Long ago, in Gran’s glasshouse above Frostpine, a girl of twelve tried to sing the Rime Song alone.', actors: [{ id: 'glyra', name: 'Lyra', look: LITTLE_LYRA, dx: -50, dy: 40 }, { id: 'gnessa0', name: 'Nessa', look: LITTLE_NESSA, dx: 50, dy: 40, face: -1 }], fx: [{ kind: 'memory' }], dur: 4.8 },
    { text: 'Her little sister sat among the winter roses, clapping along. Nessa’s hair was brown then.', actors: [{ id: 'glyra', name: 'Lyra', look: LITTLE_LYRA, dx: -50, dy: 40 }, { id: 'gnessa0', name: 'Nessa', look: LITTLE_NESSA, dx: 50, dy: 40, face: -1 }], dur: 4 },
    { text: 'The song went wrong. The cold got loose. Frost raced over every pane at once, with Nessa inside.', actors: [{ id: 'glyra', name: 'Lyra', look: LITTLE_LYRA, dx: -50, dy: 40 }, { id: 'gnessa0', name: 'Nessa', look: LITTLE_NESSA, dx: 50, dy: 40, face: -1 }], fx: [{ kind: 'frost', n: 3 }, { kind: 'shatter', delay: 1.2 }], dur: 4.6 },
    { text: 'When Gran broke the door down, Nessa was laughing and shivering, and her hair had turned white as snow.', actors: [{ id: 'gnessa1', name: 'Nessa', look: LOOKS.nessa, dx: 50, dy: 40, face: -1 }], dur: 4.6 },
    { at: 'hero', cut: true, night: 0, speaker: 'Lyra', portrait: '❄️', text: '“I kept away so it could never happen again. …And they took her anyway.”', dur: 4.2 }],
  'lyra-reunion': [
    { at: 'npc:summit:aune', night: .4, text: 'That night, by Aune’s fire, the Rimeward sisters sit side by side for the first time in three winters.', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], fx: [{ kind: 'embers', dy: 30 }], dur: 4.6 },
    { speaker: 'Nessa', portrait: '👧', text: '“You can hug me, you know. I won’t break. I’m not glass.”', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], dur: 3.6 },
    { text: 'Lyra’s arms are cold. Nessa doesn’t let go anyway.', actors: [{ id: 'rnessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 50 }], fx: [{ kind: 'frost', dx: -30, dy: 40 }], dur: 3.6 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'High above, in the Star Cradle, a crown of ice turns toward the hamlet… and the wind begins to rise.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'shadow', dy: -60, delay: .5 }], dur: 4.6 }],
  'lyra-blizzard': [
    { at: 'summit:hamlet', night: .6, text: 'The wind howls down from the Cradle, and snow buries Frostpine Hamlet to the windowsills.', fx: [{ kind: 'frost', n: 3 }, { kind: 'snuff', dx: -150, delay: .6 }, { kind: 'snuff', dx: 150, delay: 1 }], dur: 4.4 },
    { text: 'In the storm, a voice like cracking ice: “Come home, daughters. Come home and sing for me.”', fx: [{ kind: 'shadow', delay: .3 }], dur: 4.4 },
    { speaker: 'Nessa', portrait: '👧', text: '“That’s her. The Queen. …I’ve got a flint. You do the ice, I’ll do the fire. Like Gran used to say.”', dur: 4.2 }],
  'lyra-rime-book': [
    { at: 'npc:summit:corvin', text: 'Abbot Corvin lays the Rime-book on the table. Its pages look blank, until Lyra breathes on them.', dur: 3.8 },
    { text: 'Frost-script blooms across the paper, silver on white, in Gran’s crooked hand. Nessa gasps.', fx: [{ kind: 'frost' }, { kind: 'memory', delay: .6 }], dur: 4 },
    { at: 'summit:cradle', cut: true, dy: -60, night: .5, text: 'The words become a picture: the Star Cradle, long ago. Two sisters in white stand beneath the star, singing.', actors: [{ id: 'rime1', name: 'Rimeward', look: RIME_COLD, dx: -60, dy: 60, spirit: true }, { id: 'rime2', name: 'Rimeward', look: RIME_WARM, dx: 40, dy: 60, face: -1, spirit: true }], fx: [{ kind: 'frost', dy: -60 }], dur: 5 },
    { text: 'One voice cold, one voice warm. A crown of frost rises around the star and keeps its light bright.', actors: [{ id: 'rime1', name: 'Rimeward', look: RIME_COLD, dx: -60, dy: 60, spirit: true }, { id: 'rime2', name: 'Rimeward', look: RIME_WARM, dx: 40, dy: 60, face: -1, spirit: true }], fx: [{ kind: 'ring', dy: -90 }, { kind: 'light', dy: -90, delay: .6 }], dur: 4.6 },
    { text: 'Then the star falls, and its frost falls with it. Out of the dark, a shadow sets that frost on the throne like a queen.', fx: [{ kind: 'starfall', dy: -90 }, { kind: 'shadow', dy: -60, delay: 1 }], dur: 4.8 },
    { at: 'summit:tarn', cut: true, night: 0, text: 'Then three lights: one deep under Mirrorsky Tarn,', fx: [{ kind: 'ring' }], dur: 2.8 },
    { at: 'summit:frostfang', cut: true, text: 'one on Frostfang Crag,', fx: [{ kind: 'ring' }], dur: 2.4 },
    { at: 'summit:rift', cut: true, text: 'and one in the Void Rift, where the Queen’s heralds gather: the shards of the fallen star.', fx: [{ kind: 'ring' }, { kind: 'wisps', n: 2, delay: .4 }], dur: 3.8 },
    { at: 'hero', speaker: 'Nessa', portrait: '👧', text: '“Three shards. I can count. Let’s go and get them.”', dur: 3.2 }],
  'lyra-herald-voice': [
    { at: '$thief', text: 'The crowned herald cracks in Lyra’s grip like lake ice in spring.', fx: [{ kind: 'frost' }, { kind: 'shatter', delay: .5 }], dur: 3.6 },
    { speaker: 'The Crowned Herald', portrait: '👑', text: '(Out of its broken mouth comes another voice, cold and very close.) “Daughter. You sing so like your grandmother.”', dur: 4.8 },
    { speaker: 'The Crowned Herald', portrait: '👑', text: '“Stop fighting your frost. Come home to the Cradle with your sister, and neither of you will ever be cold alone again.”', dur: 5 },
    { dy: -200, text: 'Then the herald is snow on the wind, streaming away south toward the Void Rift.', fx: [{ kind: 'wisps', n: 2 }, { kind: 'lantern', to: { dx: -200, dy: 1800 } }], dur: 4 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“She sounds like Gran. …She isn’t Gran.”', dur: 3.4 }],
  'lyra-two-voices': [
    { at: 'summit:altar', night: .4, text: 'Nessa sings, and Lyra sings with her: one voice cold, one voice warm, for the first time since the glasshouse.', actors: [{ id: 'snessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 60 }], fx: [{ kind: 'ring' }, { kind: 'frost', delay: .6 }], dur: 5 },
    { text: 'Snow begins to fall around the altar, soft and slow. It doesn’t bite. Underneath it, the grass is green.', actors: [{ id: 'snessa', name: 'Nessa', look: LOOKS.nessa, dx: -60, dy: 60 }], fx: [{ kind: 'light', delay: .4 }], dur: 4.6 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'In the Star Cradle, Queen Hoarfrost rises from her throne of ice, and the black star shivers behind her.', fx: [{ kind: 'frost', dy: -80 }, { kind: 'quake', delay: .4 }], dur: 4.6 },
    { speaker: 'Queen Hoarfrost', portrait: '👑', text: '“Two voices. At last. Come to me, daughters, and sing the mountain to sleep.”', dur: 4.4 }],
  'star-rises@lyra': [
    { at: 'summit:cradle', dy: -100, text: 'Queen Hoarfrost’s crown cracks, and all her frost comes loose at once, a hundred years of winter falling like snow.', fx: [{ kind: 'shatter', dy: -60 }, { kind: 'frost', dy: -60, delay: .4 }], dur: 4.6 },
    { text: 'The star drinks the shards and rises, whole again. Its crown of frost settles round it, soft and bright, the way the Rimewardens sang it.', fx: [{ kind: 'light', dy: -100 }], dur: 4.6 },
    { text: 'But a thread of black smoke tears loose from where the Queen stood…', fx: [{ kind: 'smoke', dy: -100, to: { dx: 1600, dy: 900 } }], dur: 3.6 },
    { at: 'obj:summit:barrier', cut: true, text: '…and flees east. Behind it, black ice creeps over the Eastern Gate: cold without a spark of warmth in it.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .3 }], dur: 4.6 },
    { at: 'hero', text: 'Lyra touches the frost on her sleeve. It is warm. Far below, a small figure in a blue scarf is already running for the Eastern Gate.', dur: 4.4 }],
  'lyra-black-ice': [
    { at: 'obj:summit:barrier', night: .3, text: 'The Eastern Gate is sealed in black ice: frost with no warmth anywhere in it. It doesn’t shine. It drinks the light.', fx: [{ kind: 'shadow' }], dur: 4.4 },
    { at: 'npc:summit:lyra-nessa-gate', text: 'Nessa climbs onto the old song-stone by the gate, takes a deep breath, and begins the warm half of Gran’s song.', fx: [{ kind: 'ring' }], dur: 4.4 },
    { at: 'obj:summit:barrier', text: 'The black ice shivers… and the last of the Queen’s wraiths tear themselves out of it, screaming.', fx: [{ kind: 'wisps', n: 3 }, { kind: 'frost', delay: .4 }, { kind: 'quake', delay: .6 }], dur: 4.4 },
    { at: 'hero', night: .2, speaker: 'Lyra', portrait: '❄️', text: '“Keep singing, Nessa. Don’t stop for anything. I’ve got you.”', dur: 3.6 }],
  'chapter-summit@lyra': [
    { at: 'obj:summit:barrier', text: 'The sisters sing, one voice cold and one voice warm, and frost that remembers warmth creeps over the black ice.', actors: [{ id: 'gnessa', name: 'Nessa', look: LOOKS.nessa, dx: -170, dy: 40 }], fx: [{ kind: 'frost', delay: .4 }, { kind: 'light', delay: 1.2 }], dur: 4.8 },
    { text: 'The black ice cracks from end to end, and shatters into snow.', actors: [{ id: 'gnessa', name: 'Nessa', look: LOOKS.nessa, dx: -170, dy: 40 }], fx: [{ kind: 'shatter' }], dur: 3.4 },
    { at: 'ember:forge', cut: true, dy: -60, text: 'Beyond lie the Ember Wastes, where the Dawn Forge has gone cold… and a serpent of fire lies coiled around it, hating everything that is cold.', fx: [{ kind: 'fire', n: 2, t: 60 }, { kind: 'quake', delay: .4 }], dur: 5 },
    { title: 'Chapter IV', sub: 'The Dawn Forge', dur: 3.4 }],
  // ─────────────── Chapter IV
  'lyra-hot-wind': [
    { at: 'hero', text: 'Hot wind blows through the broken ice, and the snow on Lyra’s cloak turns to steam.', fx: [{ kind: 'smoke' }], dur: 3.8 },
    { at: 'ember:camp', cut: true, dy: -40, text: 'Ahead, Emberwatch Outpost is burning. Ember imps hang in the smoke above its walls, lobbing fire.', fx: [{ kind: 'imps', n: 3, dy: -80 }, { kind: 'fire', n: 2, t: 80, delay: .5 }], dur: 4.4 },
    { speaker: 'Captain Ashka', portrait: '💂‍♀️', text: '“Buckets! More buckets! …Who is THAT, walking out of the west in a snow cloak?”', dur: 3.8 },
    { at: 'hero', cut: true, speaker: 'Lyra', portrait: '❄️', text: '“A land of fire. Everyone says I’ll be useless here. …Let’s find out.”', fx: [{ kind: 'frost' }], dur: 4 }],
  'lyra-caravan': [
    { at: '$ward', dy: -30, text: 'The Salt Caravan Camp. Oona’s water barrels stand in a ring in the sun, and every one of them is boiling.', fx: [{ kind: 'smoke' }, { kind: 'embers', delay: .4 }], dur: 4.2 },
    { text: 'In the middle of the ring, half buried in the sand, an ember core glows white-hot. The imps are coming back for it.', fx: [{ kind: 'fire', n: 1, t: 30 }, { kind: 'imps', n: 3, dx: 300, dy: -120, delay: .6 }], dur: 4.4 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“Water for every town in the wastes, and they’re boiling it away. Not while I’m standing here.”', fx: [{ kind: 'frost' }], dur: 4 }],
  'lyra-first-snow': [
    { at: 'ember:green', text: 'The Last Green: a handful of thirsty trees, their leaves curled brown at the edges.', dur: 3.6 },
    { at: 'hero', text: 'Lyra lifts her hands. For once she doesn’t hold the cold back. She lets it go.', fx: [{ kind: 'frost' }], dur: 3.8 },
    { at: 'ember:green', text: 'Snow falls on the Ember Wastes for the first time in a thousand years. It melts where it lands, and the roots drink.', fx: [{ kind: 'frost', n: 3 }, { kind: 'douse', delay: .6 }], dur: 5 },
    { text: 'By the time the last flake has melted, every leaf in the grove is green.', fx: [{ kind: 'light', delay: .3 }], dur: 3.8 },
    { at: 'hero', speaker: 'Lyra', portrait: '❄️', text: '“Three winters I was afraid of my own hands. …Look what they can do.”', dur: 4.6 }],
  'lyra-wyrm-wakes': [
    { at: 'ember:forge', dy: -60, text: 'The last frost rune bites into the slag shell around the Dawn Forge. Hot stone meets sudden cold, and cracks run through it like lightning.', fx: [{ kind: 'frost', dy: -40 }, { kind: 'shatter', dy: -40, delay: .6 }], dur: 4.6 },
    { text: 'The shell splits… and a serpent of living fire pours out of it, coil after coil.', fx: [{ kind: 'quake' }, { kind: 'fire', n: 3, t: 40, delay: .4 }], dur: 4.4 },
    { text: 'The Cinderwyrm tastes the frost in the air, and screams.', fx: [{ kind: 'embers' }, { kind: 'shadow', delay: .3 }], dur: 3.6 },
    { at: 'hero', speaker: 'Nessa', portrait: '👧', text: '(Nessa skids up the forge steps behind you, out of breath.) “I’m here! Did I miss it? I’m singing!”', actors: [{ id: 'wnessa', name: 'Nessa', look: LOOKS.nessa, dx: -80, dy: 30 }], dur: 4.4 }],
  'chapter-ember@lyra': [
    { at: 'ember:forge', dy: -60, text: 'The Dawn Forge burns white and gold, and a new dawn spills across the wastes, with a little snow in it.', fx: [{ kind: 'light', dy: -60 }, { kind: 'frost', delay: .8 }], dur: 4.4 },
    { at: 'hero', text: 'Nessa sits down beside you on the forge steps to watch it come up. One sister cold, one warm. Neither lets go.', actors: [{ id: 'enessa2', name: 'Nessa', look: LOOKS.nessa, dx: -50, dy: 20 }], dur: 5 },
    { at: 'summit:cradle', cut: true, dy: -90, text: 'On the Summit, the Star shines in its crown of frost.', fx: [{ kind: 'light', dy: -90 }], dur: 3.4 },
    { at: 'woods:bell', cut: true, dy: -60, text: 'In Whisperroot, the Bell rings for the dawn, and no mist answers.', fx: [{ kind: 'light', dy: -60 }], dur: 3.4 },
    { at: 'meadow:rise', cut: true, dy: -80, text: 'And in the meadow, the Beacon blazes over Mirror Lake, where a courier once threw her satchel into the water.', fx: [{ kind: 'light', dy: -80 }], dur: 4.4 },
    { title: 'Every light is shining', sub: 'The post always gets through', dur: 4 }],
};

export const LYRA: HeroStory = {
  hero: 'lyra',
  chains: {
    meadow: ['lyra0', 'lyra1', 'lyra2', 'lyra6', 'lyra12', 'lyra13', 'lyra48', 'lyra49', 'lyra9', 'lyra50', 'lyra11', 'lyra51', 'm10', 'lyra52'],
    woods: ['lyra53', 'lyra3', 'lyra14', 'lyra15', 'lyra19', 'lyra7', 'lyra55', 'lyra57', 'lyra58', 'lyra17', 'lyra18', 'lyra21', 'm15', 'lyra60'],
    summit: ['lyra61', 'lyra22', 'lyra62', 'lyra4', 'lyra26', 'lyra23', 'lyra24', 'lyra63', 'lyra28', 'lyra29', 'lyra65', 'lyra66', 'lyra27', 'm19', 'lyra68'],
    ember: ['lyra70', 'lyra30', 'lyra37', 'lyra5', 'lyra31', 'lyra72', 'lyra73', 'lyra38', 'lyra36', 'lyra35', 'lyra75', 'lyra74', 'm12', 'm13'],
  },
  quests: {
    // ═════════════ Chapter I · the lost post, the lake and the serpent
    meadow: [
    q({ id: 'lyra0', title: 'The Lake Remembers', giver: 'lou', kind: 'activate', count: 3, near: 'mirror', switches: 'rune', order: ['Frost rune', 'Road rune', 'Heart rune'], auto: true, cine: { done: 'lyra-lake-memory' }, summary: 'Wake three old frost runes on the shore of Mirror Lake, and let the lake show what Fisher Lou only heard.', reward: { xp: 170, mana: 10 },
      text: { offer: ['You came down the lake road at dawn, trailing frost. The reeds are still white where you walked.', 'A courier girl, you say? Aye… a little one ran past my boat after midnight, satchel bouncing. Something pale was after her.', 'Then the fog came down thick as porridge, and I heard a splash like the whole lake falling over. That’s all I know.', 'See those old carved stones round the shore? They’ve been humming since you turned up. My gran said the frost-folk cut them. Maybe they’ll talk to you.'],
        progress: ['Wake the three frost runes on the shore stones of Mirror Lake.'], complete: ['(The last rune rings like a bell, and the whole lake goes still as a mirror.)'], after: ['Frost on the water, in summer. Hmph. The fish don’t like it either.'] } }),
    q({ id: 'lyra1', title: 'Nessa’s Letters', giver: 'fox', kind: 'trail', count: 4, near: 'mirror', place: 'millbrook', auto: true, cine: { start: 'lyra-frost-trail' }, summary: 'Let your frost find the letters the wind stole from Nessa, and follow them west from Mirror Lake to Millbrook Farm.', reward: { xp: 140, mana: 10 },
      clues: ['A single blue mitten in the grass. Nessa’s. I knitted it for her, badly, the winter she turned nine.', 'Frost on the clover, in the middle of summer. Is that hers… or mine? I never can tell where my cold ends.', 'Letters, blown into the ditch. Every one addressed in her round, careful hand. Some of them have been torn open.', 'Small bare footprints by the farm gate, going from letter to letter. Someone has been picking up what the wind dropped.'],
      text: { offer: ['The satchel went into the lake. But not all of her post did. The wind took a flurry of letters west, toward Millbrook Farm.', 'If she dropped anything on that road, the frost will find it. It always finds her.'], progress: ['Follow the glittering frost west from Mirror Lake toward Millbrook Farm.'],
        complete: ['Someone has been collecting her post. And that farmer over there looks like he knows who.'], after: [] } }),
    q({ id: 'lyra2', title: 'The Letter Thief', giver: 'bram', kind: 'chase', count: 1, place: 'millbrook', who: person('Wick the Magpie-boy', '🧒', { robe: '#5a4a3a', hat: 'cap', hatColor: '#2e2420', small: true }), summary: 'Catch the boy selling Nessa’s letters around Millbrook Farm.', reward: { xp: 130, gold: 40 },
      text: { offer: ['There’s a lad around my farm selling letters. Sealed ones, courier’s post. Says he found them in a ditch.', 'One had frost on the seal, if you can believe it. In summer. That mean anything to you, miss? …You’ve gone pale. Paler.'], progress: ['Wick hangs around Millbrook Farm. He’s quick, but he runs out of breath.'],
        deliver: ['Ow! Alright! I only sold the boring ones, I swear!', 'They came blowing up the lake road the morning after the star fell, like a flock of paper birds. Finders keepers, I thought.', 'The ones nobody would buy, I chucked in Gloom Hollow. The gloomlings like them. They sit on them like eggs.'],
        complete: ['Gloom Hollow, south of here. Of course he did.', 'Don’t look at the lad like that, miss. He’s gone blue round the ears. …Oh. That’s you doing that, isn’t it?'], after: ['Wick’s mending my fences now. Honest work, and he hates it.'] } }),
    q({ id: 'lyra6', title: 'Letters in the Gloom', giver: 'bram', kind: 'collect', count: 4, near: 'hollow', item: 'Nessa’s letter', icon: 'letter', turnIn: 'wren', cine: { done: 'lyra-unsent-letters' }, summary: 'Gather the rest of Nessa’s letters in Gloom Hollow and bring them to Postmistress Wynne in Sunpetal.', reward: { xp: 170, gold: 45 },
      text: { offer: ['Gloom Hollow is south of the farm. The gloomlings sit on those letters like eggs, Wick says.', 'Every one is somebody’s news, and your sister carried them. Fetch them back and take them to Postmistress Wynne in Sunpetal, north of here. She’ll know what’s what.'], progress: ['Four of Nessa’s letters in Gloom Hollow, south of the farm. Then take them to Wynne in Sunpetal.'],
        complete: ['Nessa’s letters! And hardly chewed. You’re the sister from the mountain, aren’t you? She talks about you. Snow in summer, she says.', 'Everything bound for the Silver Heights is missing, though. That was all in her own satchel.', 'Wait there, love. There’s something you ought to see.'], after: ['Lou’s at the lake with his scale. Go and calm him down, would you?'] } }),
    q({ id: 'lyra12', title: 'Scales Like Dinner Plates', giver: 'lou', kind: 'collect', count: 4, near: 'mirror', item: 'Serpent scale', icon: 'gem', summary: 'Gather the great scales washed up around Mirror Lake for Fisher Lou.', reward: { xp: 130, gold: 30 },
      text: { offer: ['Back again? And you’ve got that look. Wynne told you about my scale, then.', 'Something big, swallowing the satchel? I’ve said for thirty years there’s a big one in this lake. Thirty years!', 'Since the star fell, scales have been washing up on the shore. Big as dinner plates. Fetch me four, and I’ll finally have proof.'], progress: ['Four scales along the shores of Mirror Lake.'],
        complete: ['Look at the size of them. Green as pondweed and cold as your hands. I knew it. I KNEW it.', 'Mind you, the lake’s been dead quiet since that night. Whatever it is, it’s gone somewhere.', 'Scholar Ilse in Goldenhearth knows all the old lake tales. She’ll know its name.'], after: ['Shh. The big one is… well, gone, for now. I still whisper out of habit.'] } }),
    q({ id: 'lyra13', title: 'The Serpent in the Books', giver: 'lou', kind: 'talk', count: 1, to: 'ilse', summary: 'Ask Scholar Ilse in Goldenhearth about the beast of Mirror Lake.', reward: { xp: 120 },
      text: { offer: ['Goldenhearth is the big city north-east of the lake. Ilse will be in her books, same as always.', 'Show her the scales. And tell her Lou was right.'], progress: ['Goldenhearth lies north-east of Mirror Lake.'], complete: [], after: ['Lou was right. Say it slowly.'],
        deliver: ['Lou was right? Oh, he will be unbearable.', 'These are Gloamgill’s scales. The old serpent of Mirror Lake. It sleeps for a hundred years at a time, down in the black water, dreaming of anything that glows.', 'When the Beacon died, the shadow woke it. It followed the dark down the underground streams to the Beacon Rise, and coiled itself around the cold Beacon like a lake around a stone.', 'If it swallowed your sister’s satchel, the satchel is down there with it. And it won’t come up for anything… except the light of the Beacon’s three sun-crystals.', 'They were flung across the valley the night the Beacon died. Captain Brannoc was in here this morning, asking about a parcel that glowed. His courier Tansy never came back from the east road. Go and see him, dear.'] } }),
    q({ id: 'lyra48', title: 'Tansy’s Cart', giver: 'brannoc', kind: 'defend', count: 3, place: 'rot', waves: [3, 4, 5], foes: ['bristleboar', 'gloomling', 'bristleboar'], ward: 'Tansy’s cart', auto: true, cine: { start: 'lyra-cart' }, summary: 'Hold Courier Tansy’s overturned cart at Rotwood Den against three waves of boars and gloom.', reward: { xp: 190, hearts: 1 },
      text: { offer: ['Tansy rode the east road the night the star fell, the same night your sister ran the lake road. Her pigeon came in yesterday. One word on it: BOARS.', 'Her cart is over on its side at Rotwood Den, far to the east, and she’s sitting on top of it. Get her down.', 'And if you can keep that cold of yours pointed at the boars and not at my courier, even better.'], progress: ['Stand by Tansy’s cart at Rotwood Den and break every wave before it reaches her.'],
        complete: ['(The last boar bolts into the trees with frost on its tusks. Tansy slides down off the cart, shaking.)', '“You’re the frost-sister! Nessa said you’d come. She said it like it was the weather.”'], after: [] } }),
    q({ id: 'lyra49', title: 'Post Marked ‘Warm’', giver: 'fox', kind: 'key', count: 1, keys: [0], place: 'rot', turnIn: 'brannoc', summary: 'Find the sun-crystal Nessa posted, spilled from Tansy’s cart around Rotwood Den, and bring it to Captain Brannoc.', reward: { xp: 170, hearts: 1 },
      text: { offer: ['(Tansy is turning out her spilled mailbags on the grass.) “The parcel! Your sister’s parcel! It burst when we went over. It GLOWED, and it rolled off into the brambles.”', '“She found a warm stone in the road that night, shining like a coal, and posted it: ‘Keeper of the Beacon. WARM. Do not drop.’ Of course she did.”', 'Frost never settles on a sun-crystal. If I cover these brambles in rime, the one bare patch is where it is.'],
        progress: ['Look for the bare, warm patch in the frost around Rotwood Den. Then take the crystal to Captain Brannoc in Goldenhearth.'],
        complete: ['A sun-crystal, posted by a courier girl with the address written on it. I’ve seen everything now.', 'Tansy says Nessa raced east with her in the cart, then jumped out at the Gloomwater Bridge and ran on alone. The bridge came down behind her. Pale riders were waiting on the far bank.', 'And Tansy found something else under her cart seat. Something from your sister’s round.'], after: ['The east road is watched again.'] } }),
    q({ id: 'lyra9', title: 'The Post Must Go Through', giver: 'brannoc', kind: 'deliver', count: 1, to: 'odo', item: 'Nessa’s last letter for the Hill', summary: 'Finish Nessa’s round: carry her last letter to Old Shepherd Odo on Shepherd’s Hill.', reward: { xp: 120, gold: 40 },
      text: { offer: ['One letter from your sister’s round, still sealed. For Old Shepherd Odo, on Shepherd’s Hill.', 'Couriers have a saying: the post always gets through. Your sister would want it delivered. Shepherd’s Hill is far to the north-east.'], progress: ['Shepherd’s Hill is far to the north-east of Goldenhearth.'], complete: [], after: ['The post always gets through.'],
        deliver: ['A letter? For me? Nobody has written to me since my Hettie moved to Willowmere.', '…It’s from Hettie. She’s coming for the harvest. With the grandchildren. All seven of them.', 'You finished your sister’s round for her. That’s a kind thing, frost or no frost.', 'Now, while you’re up here… there’s a light among my sheep that hums all night. I think it’s been waiting for you.'] } }),
    q({ id: 'lyra50', title: 'The Lamb with a Lantern in It', giver: 'odo', kind: 'key', count: 1, keys: [1], place: 'shepherd', summary: 'Find the sun-crystal the sheep sleep around on Shepherd’s Hill.', reward: { xp: 160, gold: 30 },
      text: { offer: ['It came rolling up my hill the night the Beacon died, glowing like a lamb with a lantern in it.', 'My flock sleeps round it like it was a stove. Go gently. They’re wary of cold hands, though I can’t think why.'], progress: ['The crystal is somewhere on Shepherd’s Hill, among the sleeping sheep.'],
        complete: ['Two crystals. Look how they shine together. Even your frost glows gold in that light.', 'Ilse’s serpent, is it? Then mind the water. Down by the Faerie Ring, the springs have been knocking all week, like something big is swimming underneath.'], after: ['Go carefully. And wave to Hettie, if you see her.'] } }),
    q({ id: 'lyra11', title: 'Freeze the Serpent’s Road', giver: 'fox', kind: 'activate', count: 3, near: 'faerie', switches: 'rune', order: ['West spring', 'Moss spring', 'East spring'], auto: true, cine: { done: 'lyra-springs-frozen' }, summary: 'Freeze the three springs around the Faerie Ring, so Gloamgill can’t flee back into the deep.', reward: { xp: 140, mana: 12 },
      text: { offer: ['Ilse said Gloamgill swims the underground streams. The springs that feed them rise around the Faerie Ring, south-east of the lake.', 'If I freeze them shut, it can’t slip back into the deep when the light draws it up. It will have to face me.', 'Frost that locks a door. That, at least, I know how to do.'], progress: ['Three springs around the Faerie Ring. Freeze them shut.'],
        complete: [], after: [] } }),
    q({ id: 'lyra51', title: 'Gold in the Ice', giver: 'fox', kind: 'key', count: 1, keys: [2], place: 'faerie', auto: true, summary: 'Break the last sun-crystal out of the frozen spring at the Faerie Ring.', reward: { xp: 170 },
      text: { offer: ['(The last frozen spring glows from inside, gold as a sunrise.)', 'The deep pushed it up to me. The third crystal, frozen into the ice like a fly in amber.'], progress: ['The third sun-crystal glows in the ice around the Faerie Ring.'],
        complete: ['(Lyra breaks the crystal free. It is warm in her cold hands, and it doesn’t mind her at all.)', 'Three. Now the Beacon Rise, far to the east. And the thing that ate my sister’s letter.'], after: [] } }),
    q({ id: 'lyra52', title: 'A Bridge of Frost', giver: 'holt', kind: 'build', count: 5, near: 'shrine', item: 'Old bridge timber', icon: 'bundle', place: 'gateE', site: 'bridge', siteName: 'The Frost Bridge', summary: 'Pull five old bridge timbers out of the river by the Sun Shrine, then freeze them into a bridge across the Gloomwater at the Eastern Gate.', reward: { xp: 300, hearts: 1 },
      text: { offer: ['That was you, lighting the Beacon? Then you’re the one to help me with this mess.', 'The Gloomwater Bridge came down the night the star fell. A courier girl ran over it just before. I saw her from my window. She never looked back.', 'The river’s too wild to bridge in a hurry. But the old timbers washed up by the Sun Shrine, north of here. Fetch me five, and then… well. I hear you can freeze a river.'],
        progress: ['Five old bridge timbers along the river by the Sun Shrine, then build at the Eastern Gate.'],
        complete: ['(Lyra lays her hands on the water. Ice races out across the Gloomwater, thick and blue, and locks round every timber like a fist.)', 'Well, I’ll be. Timber and frost, and she doesn’t even wobble. Best bridge I never built.', 'The road east is open. Your courier girl went that way, into Whisperroot. Go and bring her home.'], after: ['Mind the third plank. It’s a bit slippy.'] } }),
    ],
    // ═════════════ Chapter II · the wraiths' trail and the Pale Huntress
    woods: [
    q({ id: 'lyra53', title: 'Mist That Bites', giver: 'fox', kind: 'visit', count: 1, place: 'camp', auto: true, cine: { ready: 'lyra-mist-parts' }, summary: 'Walk through the winter mist of Whisperroot to the Mosskeeper’s Camp.', reward: { xp: 150, mana: 10 },
      text: { offer: ['(Beyond the frost bridge, white mist curls between the trees. Summer mist doesn’t bite like that.)', 'Nessa ran this road. There’s a camp inside the woods. Someone there must have seen her.'], progress: ['The Mosskeeper’s Camp lies south-east of the Western Gate.'], complete: [], after: [] } }),
    q({ id: 'lyra3', title: 'The Courier’s Word', giver: 'guide', kind: 'talk', count: 1, to: 'nutkin', summary: 'Ask Courier Nutkin at the camp about Nessa.', reward: { xp: 120 },
      text: { offer: ['You walked out of the mist and it didn’t touch you. It shrank from you, almost.', 'It rolls off the Old Bell every night now, cold enough to kill the moss. There’s a rider in it, they say. A pale woman.', 'A courier girl with frost in her hair? Nutkin would know. The couriers look after each other.'], progress: ['Nutkin is here at the camp.'], complete: [], after: [],
        deliver: ['Nessa? She carried the post with me for two whole summers! Fastest feet in the valley, after mine.', 'She came through here a week ago, soaked and shivering, with pale riders in the mist behind her. I hid her in the mailbags till they passed.', 'Then she ran south for Bellhollow, to Nana Bristle. Everyone runs to Nana. She kept saying your name. “Lyra will come.”'] } }),
    q({ id: 'lyra14', title: 'Soup at Nana Bristle’s', giver: 'nutkin', kind: 'talk', count: 1, to: 'nana', summary: 'Visit Nana Bristle in Bellhollow, where Nessa hid.', reward: { xp: 120 },
      text: { offer: ['Bellhollow is south-east of the camp. Follow your nose. Nana’s soup reaches further than the road does.', 'And… Lyra? Nessa said you’d be scary. You’re not that scary. Only a bit.'], progress: ['Bellhollow lies south-east of the camp.'], complete: [], after: ['Nana’s soup mends everything. Mostly.'],
        deliver: ['You’re the sister. Sit. Eat. You’re too thin for a hero and too cold for anything.', 'Nessa slept by my stove for two nights. She talked about you the whole time, until my ears were warm.', 'She told me about a glasshouse, dear. About the winter you froze it with her inside, and cried for a week, and never hugged her again.', 'She wasn’t angry. She just missed her sister. Then one morning she went down to the stream, the mist came, and she was gone.'] },
      choice: {
        a: { label: 'Tell her about the glasshouse', lines: ['(You tell her: Gran’s frost-song sung wrong, the cold getting away from you, Nessa’s hair turning white.)', 'Oh, my dear. You were twelve. A child with a winter inside her.', 'And you’ve carried that glasshouse on your back ever since. Put it down. It’s far too heavy for climbing mountains.'], reward: { regen: .4 } },
        b: { label: 'Change the subject', lines: ['Hmph. Keep your secrets, dear, if they keep you warm. But they don’t, do they?', 'When you find her, hug her. That’s all. It isn’t complicated.'], reward: { mana: 12 } },
      } }),
    q({ id: 'lyra15', title: 'Hoofprints of Frost', giver: 'nana', kind: 'trail', count: 4, near: 'bellhollow', place: 'pool', turnIn: 'maeve', summary: 'Follow the frozen trail from Bellhollow to Blackwater Pool, then ask Fisher Maeve what she saw.', reward: { xp: 170 },
      clues: ['Hoofprints in the moss, rimmed with frost. No horse made these. They’re too light, and they don’t sink.', 'Nessa’s courier badge, trodden into the mud. She dropped it on purpose. She always drops things on purpose.', 'The ferns here are frozen stiff and black at the tips. Cold with nothing living in it. Not like mine. …Is it?', 'The shore of Blackwater Pool, iced over in one long bridge. They rode straight across the water with her.'],
      text: { offer: ['The frost those riders leave behind doesn’t melt, dear. Follow it east from the stream.', 'Fisher Maeve at Blackwater Pool sees everything that crosses her water. Ask her.', 'And if you see the Old Bellkeeper out there, send him home. He went up to ring the mist away three days ago, the old fool, and never came back.'], progress: ['Follow the frozen hoofprints east from Bellhollow toward Blackwater Pool.'],
        complete: ['The pale ones? I saw them. Rode right across my pool on a bridge of ice, with a little white-haired girl slung over a saddle.', 'She was kicking. Good for her.', 'One of them didn’t go on with the rest. It rides round and round the Trapper’s Lodge at night, like it’s waiting for someone.'], after: ['Pale riders. Pale fish too, since. Coincidence? I think not.'] } }),
    q({ id: 'lyra19', title: 'A Light on the Water', giver: 'maeve', kind: 'build', count: 4, near: 'pool', item: 'Driftwood', icon: 'bundle', place: 'pool', site: 'lantern', siteName: 'Nessa’s Lantern', summary: 'Gather driftwood around Blackwater Pool and build a lantern post on the shore where Nessa was taken.', reward: { xp: 170, gold: 40 },
      text: { offer: ['Before you go chasing ghosts: couriers use this shore road, and nobody should cross it in the dark again.', 'Bring me four good pieces of driftwood from around the pool, and we’ll build a lantern post right here. So the next one who runs this way can see where she’s going.'], progress: ['Four pieces of driftwood around Blackwater Pool, then build the lantern on the shore.'],
        complete: ['There. A light on the water. Your sister will see it when she comes home this way.', 'You built that with your own cold hands, and it burns warm as anything. Funny, that.', 'Now go and have words with that rider. The Trapper’s Lodge is east of here. Ysolde’s been sleeping with an axe.'], after: ['The lantern burns all night. The fish are delighted.'] } }),
    q({ id: 'lyra7', title: 'The Pale Rider', giver: 'maeve', kind: 'chase', count: 1, place: 'lodge', escapes: true, turnIn: 'ysolde', who: person('The Pale Rider', '👻', { robe: '#dff6ff', hat: 'hood', hatColor: '#bfe8ff', skin: '#e8f4ff', hair: '#ffffff' }), cine: { caught: 'rider-flees' }, summary: 'Catch the frost wraith haunting the Trapper’s Lodge, then tell Trapper Ysolde what it said.', reward: { xp: 220, mana: 12 },
      text: { offer: ['(Maeve points east with her fishing rod.) The rider circles the Trapper’s Lodge every night. It was with the ones that took her.', 'Catch it and make it talk. If those things can talk.'], progress: ['The pale rider haunts the Trapper’s Lodge, east of Blackwater Pool.'],
        deliver: ['(The wraith hisses a single word, cold as the Summit wind: “…Observatory.”)', '(Then, lower, almost like laughter: “The Huntress is waiting for you, frost-daughter.”)'],
        complete: ['That thing has circled my lodge for a week, and you just grabbed it by the mist. Brave or daft, I can’t tell.', 'It flew north-east, to the Old Bell. The mist is thickest there. That’s where its mistress sits, the one they call the Huntress.', 'Observatory, it said? There’s an old one high on the Summit. So that’s where they’ve taken your girl.'], after: ['Quiet feet catch more than loud ones. Cold hands catch pale riders, apparently.'] } }),
    q({ id: 'lyra55', title: 'The Bellkeeper in the Ice', giver: 'ysolde', kind: 'rescue', count: 1, place: 'glade', guards: 5, escort: true, captive: BELLKEEPER, turnIn: 'nana', summary: 'Free the Old Bellkeeper from the wraiths’ cage of ice at the Moonlit Glade and walk him home to Nana Bristle in Bellhollow.', reward: { xp: 240, hearts: 1 },
      text: { offer: ['One more thing, before you go chasing bells. Those riders didn’t only carry off your sister.', 'The Old Bellkeeper climbed up to ring the mist away. The wraiths froze him in a cage of ice and left him at the Moonlit Glade, far to the west, like bait on a hook.', 'Nana Bristle hasn’t slept since. Bring him home to her. And mind the bait doesn’t catch you.'],
        progress: ['The Moonlit Glade lies far to the west. Break the wraiths, open the ice cage, and walk the Bellkeeper home to Nana in Bellhollow.'],
        deliver: ['Cold… cold hands. But not hers. Yours are a kind cold. Like snow on a windowsill.', 'I saw her, frostweaver. Up on the Bell, under the hood. I’ll tell you all of it, once I’ve had some of Nana’s soup.'],
        arrive: ['Bellhollow! I can smell the soup from here. I may cry. Don’t look.'],
        complete: ['Home! You silly old man, climbing bells at your age. Sit. Eat.', '(Between spoonfuls, the Bellkeeper talks.) “Her face under the hood was young, and sad. Like yours, frostweaver. Very like yours.”', '“Roots have grown round the Bell since. Wake the three root runes, and they will let it go.”', 'Oh, and Maeve’s lad came running while you were out. The mist is rolling across Blackwater Pool, dear. Straight for your lantern.'], after: ['Two stubborn old things by one stove. Stars help me.'] } }),
    q({ id: 'lyra57', title: 'A Light Nobody Puts Out', giver: 'maeve', kind: 'defend', count: 3, place: 'pool', waves: [4, 5, 6], foes: ['shadewolf', 'wisp', 'shadewolf'], ward: 'The shore lantern', cine: { start: 'lyra-lantern-siege' }, summary: 'Hold the lantern you built at Blackwater Pool against three waves of the Huntress’s mist-creatures.', reward: { xp: 300, hearts: 1 },
      text: { offer: ['You came! She’s sending the mist for your lantern. She can’t stand a light that burns for somebody.', 'Wolves in the reeds, cold lights on the water. Hold the shore, frostweaver. I’ll hold my rod. Threateningly.'], progress: ['Stand by the shore lantern and break every wave before it reaches it.'],
        complete: ['Still burning! Not even a flicker. Your sister will see it from the next valley.', 'The Old Bellkeeper sent word while you were busy. He knows where the first root rune sleeps, and he wants to tell you himself. Bellhollow, west of here.'], after: ['Not a flicker. The wolves won’t come near it now.'] } }),
    q({ id: 'lyra58', title: 'Where the Roots Began', giver: 'bellkeeper', kind: 'key', count: 1, keys: [0], place: 'ruins', turnIn: 'forester', summary: 'Wake the first root rune deep in the Root Ruins, then tell Forester Birch at Glowcap Farm.', reward: { xp: 180 },
      text: { offer: ['The oldest root in Whisperroot starts in the Root Ruins, far to the north. The first rune sleeps there, where the roots began.', 'Forester Birch works the timber at Glowcap Farm, just west of the ruins. He has watched the Huntress ride past his fields. Ask him where she goes.'], progress: ['The Root Ruins lie far to the north. Glowcap Farm is south-west of them.'],
        complete: ['A root rune, humming like a beehive! Welcome, frostweaver. Mind the mushrooms, they sulk in the cold.', 'The Huntress? Aye. She rides past every night, east toward the Thornling Nest. The second rune is there, and the thornlings love her mist.'], after: ['Timber and runes, what a week.'] } }),
    q({ id: 'lyra17', title: 'Thorns in the Mist', giver: 'forester', kind: 'key', count: 1, keys: [1], turnIn: 'ivo', summary: 'Wake the root rune in the Thornling Nest, then report to Scout Ivo at the Owl Watchtower.', reward: { xp: 160 },
      text: { offer: ['The Thornling Nest lies north of Lanternmarket, a long walk east of here. Thornlings spit. Blink through the gaps.', 'Scout Ivo keeps watch from the Owl Watchtower, south-east of the nest. He’ll want to know you made it out.'], progress: ['The nest is north of the city. The watchtower is south-east of it.'],
        complete: ['You came out of the nest with a rune AND all your fingers. The owls are hooting like mad.', 'I watch the Bell from up here. Every night she sits on it, the Huntress, and every night she looks this way. As if she’s waiting for someone.'], after: ['All clear, for now.'] } }),
    q({ id: 'lyra18', title: 'Owl-light', giver: 'ivo', kind: 'key', count: 1, keys: [2], summary: 'Wake the last root rune around the Owl Watchtower.', reward: { xp: 150 },
      text: { offer: ['The last rune sleeps somewhere round the foot of my tower. It glows green when it’s dreaming.', 'Wake it, and the roots around the Bell will start to let go.'], progress: ['Look around the Owl Watchtower.'],
        complete: ['All three runes are singing! Listen to the owls. Proud as anything.', 'But the Huntress heard them too. The mist is thicker tonight, and full of little cold lights.'], after: ['The owls are proud.'] } }),
    q({ id: 'lyra21', title: 'Cold Lights', giver: 'ivo', kind: 'slay', count: 6, enemy: 'wisp', summary: 'Snuff six wisps drifting in the Huntress’s mist.', reward: { xp: 170, mana: 12 },
      text: { offer: ['Those lights in the mist are wisps. She sees through them, the way a spider feels its web.', 'Snuff six, and she’ll be blind when you come for her. Then she’ll have to come down off that Bell and face you.'], progress: ['Wisps are small violet lights. They dart side to side.'],
        complete: ['Six! The mist is thinning. I can see the Bell from here, and her on it, sitting very still.', 'The Bellkeeper told me what he saw under her hood. Whatever she is, Lyra, she isn’t you.'], after: ['Go carefully.'] } }),
    q({ id: 'lyra60', title: 'The Post Goes East', giver: 'lyra-nutkin-city', kind: 'escort', count: 1, who: NUTKIN, from: 'city', place: 'gateE', ambush: ['thornling', 'shadewolf', 'thornling'], auto: true, summary: 'Walk Courier Nutkin and the Summit post from Lanternmarket to the thorn wall at the Eastern Gate, and freeze the thorns to glass.', reward: { xp: 320 },
      text: { offer: ['You rang the Bell! The whole market heard it. I ran all the way from camp. Well, most of the way.', 'I’ve a bag of post for the Summit, and there’s a thorn wall across the Eastern Gate as thick as a haystack. Nobody’s got through since the mist came.', 'Couriers say frost kills a bramble quicker than any axe. Walk me there, and we’ll see. The post always gets through.'],
        progress: ['Lead Nutkin east to the Eastern Gate and keep the thornlings off him.'],
        arrive: ['There it is. Thorns as long as my arm. Go on, Lyra. Do the cold thing.'],
        complete: ['(Lyra lays both hands on the wall. Frost races through every stem and every thorn, until the whole wall is white and still as glass…)'], after: [] } }),
    ],
    // ═════════════ Chapter III · home, Nessa and the Rimewardens' secret
    summit: [
    q({ id: 'lyra61', title: 'Home, and Not Home', giver: 'fox', kind: 'trail', count: 4, near: 'gateW', place: 'lookout', auto: true, cine: { start: 'lyra-glasshouse' }, summary: 'Follow the wraiths’ frozen trail from the Western Gate to the Warden’s Lookout, through the snows where Lyra grew up.', reward: { xp: 140, mana: 10 },
      clues: ['A frost-mark cut into a pine: a snowflake inside a heart. Gran’s mark. She put one on every tree between here and home.', 'Wraith hoofprints, and beside them two little boot heels dragging deep grooves in the snow. Kicking all the way. That’s my Nessa.', 'A snowman by the road, with a very rude face and pebbles for teeth. She made it while they rested. For me to find.', 'The Warden’s Lookout. Someone has swept the snow off the bench by the fire, as if they’ve been expecting company.'],
      text: { offer: ['(An icy wind comes through the gate, and it smells of home: pine, snow and woodsmoke.)', 'The Silver Heights. I kept to the high snows for three winters, where my cold couldn’t reach anyone. Nessa is up here somewhere. So I’m going looking.'], progress: ['Follow the frozen trail from the Western Gate to the Warden’s Lookout.'],
        complete: ['(Up at the lookout, a courier with frosty ears is waving both paws.)'], after: [] } }),
    q({ id: 'lyra22', title: 'Bramble’s Report', giver: 'guide', kind: 'talk', count: 1, to: 'bramble', summary: 'Hear what Courier Bramble saw on the road to Frostpine Hamlet.', reward: { xp: 100 },
      text: { offer: ['A frostweaver, walking up out of the woods? You’re a Rimeward, or I’m a goat. You have the look.', 'Frost wraiths came down from the Cradle a week ago with a girl slung over a saddle. White hair, loud voice. She bit one of them.', 'Bramble is here at the lookout, pretending she isn’t freezing. She followed them as far as she dared. Talk to her.'], progress: ['Bramble is at the lookout.'], complete: [], after: [],
        deliver: ['You’re Lyra? THE Lyra? Nutkin sent word up the courier line: “Frost-sister coming. Be nice to her.” I’m being nice!', 'The riders took Nessa past Frostpine Hamlet, south-west, to the Old Observatory. Poor old Vale has locked himself in the top of it with his telescope.', 'Healer Aune in the hamlet patched up the ones who tried to follow. But the road to her is thick with wisps. Mind yourself.'] } }),
    q({ id: 'lyra62', title: 'Post for Frostpine', giver: 'bramble', kind: 'deliver', count: 1, to: 'aune', item: 'Frostpine’s post-bag', summary: 'Carry the hamlet’s week-old post past the wisps to Healer Aune in Frostpine Hamlet.', reward: { xp: 130, gold: 40 },
      text: { offer: ['And, um. Would you take the hamlet’s post? It’s been sitting in my bag a whole week.', 'The wisps sit on the road south-east like it’s theirs, and I’m only small. You’re not small. You’re sort of… wintry.', 'Give it to Healer Aune. She shares it out. And she’ll know you. Everyone in Frostpine knew your gran.'], progress: ['Frostpine Hamlet lies south-east of the lookout. Mind the wisps on the road.'], complete: [], after: ['Post always gets through. Even through wisps. Especially through wisps.'],
        deliver: ['Post! Real post! Nobody has got through for a week.', 'And you’re… Lyra Rimeward. You have your gran’s scowl exactly.', 'I know why you’ve come. The wraiths dragged your sister past my door, south-west to the Old Observatory.'] } }),
    q({ id: 'lyra4', title: 'Nessa', giver: 'aune', kind: 'rescue', count: 1, place: 'observatory', guards: 5, escort: true, captive: NESSA, cine: { done: 'lyra-reunion' }, summary: 'Free Nessa from the frost wraiths at the Old Observatory and bring her to Healer Aune.', reward: { xp: 260, hearts: 1 },
      text: { offer: ['The Old Observatory lies south-west of the hamlet. Five wraiths stand guard, and Vale has barricaded himself in the dome.', 'Bring her back here to me. She’ll be half frozen, and you’ll be no better.'], progress: ['The Old Observatory lies south-west of the hamlet. Break the wraiths, open the cage, and bring her back to Aune.'],
        deliver: ['Lyra?! LYRA! I knew it, I told them you’d come! I told them every single day!', 'They wanted Gran’s song. The Rime Song. They kept saying their queen needs two voices. I wouldn’t sing. Not without you.'], arrive: ['Is that Aune? Is there soup? Lyra, is there soup?'],
        complete: ['Sit down, both of you. Your sister is frozen to the bone and stubborn as a goat. Must run in the family.', 'She stays by my fire tonight. And so do you, Lyra Rimeward. No arguments.'], after: ['Two frost-girls in one hamlet. Stars help us.'] } }),
    q({ id: 'lyra26', title: 'The Queen’s Blizzard', giver: 'aune', kind: 'activate', count: 4, near: 'hamlet', switches: 'brazier', order: ['Well brazier', 'Mill brazier', 'Chapel brazier', 'Gate brazier'], cine: { start: 'lyra-blizzard' }, summary: 'Clear the ice from Frostpine Hamlet’s four hearth-braziers so Nessa can relight them before the blizzard buries the hamlet.', reward: { xp: 160, regen: .4 },
      text: { offer: ['Listen to that wind. That isn’t weather. Something up at the Cradle is angry that you took her back.', 'The blizzard has put out every hearth-brazier in the hamlet. If they stay dark till morning, Frostpine freezes in its beds.', 'Nessa has a flint and more nerve than sense. You clear the ice off the braziers, and she’ll strike the fire. Four of them, round the hamlet.'], progress: ['Four hearth-braziers around Frostpine Hamlet. Clear the ice so Nessa can light them.'],
        complete: ['Four fires, burning right through a blizzard. Frost to clear the way and a spark to follow. Your gran would have liked that.', 'Nessa’s asking for you. She’s sitting by the well, and she’s gone very quiet. That’s never a good sign with Nessa.'], after: ['The hamlet sleeps warm tonight.'] } }),
    q({ id: 'lyra23', title: 'Frost in Her Hair', giver: 'aune', kind: 'talk', count: 1, to: 'nessa', summary: 'Sit with Nessa by the well in Frostpine Hamlet.', reward: { xp: 120 },
      text: { offer: ['Go on. She’s by the well. Whatever it is, you two can sort it out without me listening. I’ll only listen a little.'], progress: ['Nessa is in Frostpine Hamlet.'], complete: [], after: [],
        deliver: ['Lyra. Can I ask you something, and you won’t go all icy and walk off up a mountain?', 'Is it the glasshouse? Is that why you never came down? Because my hair went white?', 'Because I LIKE my hair. Everyone at the post house thinks I’m very dramatic.'] },
      choice: {
        a: { label: '“I was afraid I’d hurt you again.”', lines: ['So you stayed away, so your frost couldn’t reach me? Lyra, the cold reached me anyway. It was the lonely kind.', 'You didn’t hurt me. You just left.', 'Right. That’s decided. No more leaving. Now: the Queen called us daughters, and I want to know why.'], reward: { regen: .4 } },
        b: { label: '“It isn’t your hair. It’s the frost in it.”', lines: ['The frost in it? …You mean that’s YOURS? Still in me? From that day?', 'Huh. So when I’m cold, that’s you, looking after me. That’s nicer than I thought.', 'Now: the Queen called us daughters, and I want to know why.'], reward: { mana: 12 } },
      } }),
    q({ id: 'lyra24', title: 'The Skyhold Road', giver: 'nessa', kind: 'escort', count: 1, who: NESSA, from: 'hamlet', place: 'city', ambush: ['frostwraith', 'wisp', 'frostwraith'], turnIn: 'corvin', cine: { done: 'lyra-rime-book' }, summary: 'Walk Nessa from Frostpine Hamlet to Abbot Corvin in Skyhold, keep the wraiths off her, and read Gran’s Rime-book.', reward: { xp: 200 },
      text: { offer: ['Gran kept a chronicle, the Rime-book. When she died, it went to Abbot Corvin in Skyhold, east of here, over the ridge.', 'Walk me there? My legs are still half ice, and the Queen’s wraiths will want me back.', 'And you have to talk on the way. Three winters of talking. I’ll start. Once, at the post house…'], progress: ['Lead Nessa east to Skyhold and keep the wraiths off her.'],
        arrive: ['Skyhold! Look at the towers, Lyra! I delivered a parcel here once. It was a goat.'],
        complete: ['The Rimeward sisters, together, at my door. I did not think I would live to see that.', 'Your grandmother sat where you are standing, many winters ago, and wrote in this book. The pages look blank to me. They never were, I think. Not to a Rimeward.'], after: ['The Rime-book is yours to read, whenever you wish.'] } }),
    q({ id: 'lyra63', title: 'Under Mirrorsky Ice', giver: 'corvin', kind: 'key', count: 1, keys: [0], place: 'tarn', turnIn: 'lyra-nessa-sky', summary: 'Freeze a path out over Mirrorsky Tarn to the first star shard, then bring it to Nessa in Skyhold.', reward: { xp: 160 },
      text: { offer: ['So that is the Queen. Your family’s own frost, fallen with the star and crowned by the dark.', 'She cannot sing the Rime Song herself. She needs two Rimeward voices to seal the mountain in ice forever. That is why she took your sister. That is why she wants you.', 'Crack her crown, then. The first shard lies in Mirrorsky Tarn, north-west of here. Water that deep never freezes. Unless someone asks it to.'],
        progress: ['Mirrorsky Tarn lies north-west of Skyhold, above the hamlet. Freeze your way out to the shard, then take it to Nessa in Skyhold.'],
        complete: ['A star shard! It’s warm. Why is it warm? It’s a bit of the sky! Shouldn’t it be cold?', 'Corvin and I read more of the Rime-book while you were out. Well, he read. I guessed.'], after: ['Two more shards. I’m counting.'] } }),
    q({ id: 'lyra28', title: 'Frostfang Crag', giver: 'lyra-nessa-sky', kind: 'key', count: 1, keys: [1], turnIn: 'dov', summary: 'Take the star shard from Frostfang Crag, then find Quartermaster Dov at Silver Pass Camp.', reward: { xp: 150 },
      text: { offer: ['The next shard is on Frostfang Crag, north-east of the city. Golems AND wraiths. I’d come, but you’d only make that face.', 'Afterwards, go and see Quartermaster Dov at Silver Pass Camp, north-west of the crag. Corvin says his guards have seen the Queen’s heralds gathering.', 'And Lyra? Come back. That’s an order from your little sister, which is the highest kind.'], progress: ['Frostfang Crag is north-east of Skyhold. Silver Pass Camp is north-west of the crag.'],
        complete: ['A Rimeward, on my crag road, with a star shard in her pocket. Well, well. The Abbot sent word you might come.', 'The Queen’s heralds are gathering on the ridge. Frost wraiths with crowns of ice. They’re looking for shards, and for you.'], after: ['Halt! Oh, it’s you.'] } }),
    q({ id: 'lyra29', title: 'The Queen’s Heralds', giver: 'dov', kind: 'slay', count: 5, enemy: 'frostwraith', summary: 'Break five frost wraiths gathering on the heights around Silver Pass.', reward: { xp: 150 },
      text: { offer: ['Her heralds prowl round my camp. They freeze my guards solid and then just… stand there, admiring them.', 'You’re as cold as they are, frostweaver. Colder, maybe. Break five of them.'], progress: ['Wraiths blink close and throw ice. Keep moving.'],
        complete: ['Five heralds, shattered. And you know, when you fight, the snow falls AWAY from my lads. As if it’s keeping them out of it.', 'That’s not their kind of cold. That’s yours.', 'One of them got away, though. The one with the tallest crown. It went up to the Broken Spire, and it’s been calling my lads by name. In a girl’s voice.'], after: ['The wall holds.'] } }),
    q({ id: 'lyra65', title: 'The Crowned Herald', giver: 'dov', kind: 'chase', count: 1, place: 'spire', escapes: true, turnIn: 'dov', who: HERALD, cine: { caught: 'lyra-herald-voice' }, summary: 'Run down the crowned herald singing in Nessa’s voice at the Broken Spire, then report to Dov.', reward: { xp: 200, mana: 12 },
      text: { offer: ['That crowned one isn’t like the rest. It stands on the Broken Spire, east of here, and sings. In your sister’s voice, Rimeward.', 'My lads keep walking out into the snow after it. Catch it. Shut it up. I don’t much care how.'], progress: ['The crowned herald lurks at the Broken Spire, east of Silver Pass.'],
        deliver: ['(The herald hisses in Nessa’s voice, then in another: cracking ice, very far away and very close.)'],
        complete: ['Gone south in a puff of snow? Toward the Void Rift, then. That’s where her heralds gather.', 'And look what it dropped when you grabbed it: a map of the Heights, scratched in frost. There’s a light marked in the Rift. Your third shard, I’d bet my boots.'], after: ['Nobody on my wall answers to a song any more.'] } }),
    q({ id: 'lyra66', title: 'A Shard in the Rift', giver: 'dov', kind: 'key', count: 1, keys: [2], place: 'rift', turnIn: 'lyra-nessa-sky', summary: 'Take the last star shard from the Void Rift, then bring it to Nessa in Skyhold.', reward: { xp: 170 },
      text: { offer: ['The Void Rift is far to the south, below Skyhold. Wisps and wraiths in heaps. She’ll have put that shard there on purpose.', 'Take it, then take it to your sister in Skyhold. I hear she has plans. Loud ones.'], progress: ['The Void Rift lies far to the south. Then back to Nessa in Skyhold.'],
        complete: ['All three shards! And Lyra, I finished the Rime-book. The ice-script is just Gran’s handwriting, backwards.', 'The Rime Song only works with both voices. Cold alone seals things forever. Warm alone melts everything. Together, frost keeps things safe. Like snow on seeds.', 'That’s why Gran taught us both halves. You got the cold. I got the warm. We have to sing it together at the Star Altar before we face her.'], after: ['I’m nervous. Are you nervous? You look nervous. For you.'] } }),
    q({ id: 'lyra27', title: 'The Rime Song', giver: 'lyra-nessa-sky', kind: 'activate', count: 4, near: 'altar', switches: 'rune', order: ['Cold voice', 'Warm voice', 'Cold voice', 'Warm voice'], ordered: true, auto: true, cine: { done: 'lyra-two-voices' }, summary: 'Wake the four song-stones around the Star Altar in turn, cold then warm, while Nessa sings.', reward: { xp: 180, mana: 14 },
      text: { offer: ['Four song-stones stand around the Star Altar, east of the city. Gran’s book says you wake them in turn: cold, then warm, then cold, then warm.', 'You do the frost. I’ll sing. Loudly. If I get the words wrong, sing louder so nobody notices.'], progress: ['Four song-stones around the Star Altar. Cold, then warm, in turn.'],
        complete: ['(The last song-stone rings. For the first time since the glasshouse, Lyra’s frost doesn’t feel like a door closing. It feels like a blanket.)', 'Now we go and knock that crown off her head. Together.'], after: [] } }),
    q({ id: 'lyra68', title: 'Sing the Ice Apart', giver: 'lyra-nessa-gate', kind: 'defend', count: 3, place: 'gateE', waves: [4, 5, 6], foes: ['frostwraith', 'wisp', 'frostwraith'], ward: 'Nessa’s song-stone', auto: true, cine: { start: 'lyra-black-ice' }, summary: 'Hold the Eastern Gate against the Queen’s last wraiths while Nessa sings the black ice apart.', reward: { xp: 330, hearts: 1 },
      text: { offer: ['You did it! I felt it, all the way down in Skyhold. Like a door opening. So I ran. All the way. Don’t tell Aune.', 'Umbra fled east and sealed the pass behind it with black ice. Corvin says only the Rime Song can break frost with no warmth in it.', 'So I sing, right here on this old song-stone. And you keep her last wraiths off me. We break it together, or not at all.'],
        progress: ['Hold the Eastern Gate while Nessa sings. Break every wave before it reaches her.'],
        complete: ['(Nessa sings the last warm note. Lyra takes her hand, and sings the cold one.)'], after: [] } }),
    ],
    // ═════════════ Chapter IV · frost in a land of fire
    ember: [
    q({ id: 'lyra70', title: 'A Snowball in a Kiln', giver: 'fox', kind: 'slay', count: 5, enemy: 'emberImp', auto: true, cine: { start: 'lyra-hot-wind' }, summary: 'Emberwatch Outpost is burning. Freeze five ember imps out of the smoky sky.', reward: { xp: 200, hearts: 1 },
      text: { offer: ['Umbra fled into the Ember Wastes. Nessa has run on ahead with the post, of course. Nobody catches her twice.', 'And the outpost is burning. Ember imps hover out of reach and lob fire. So close in fast, and freeze them where they float.'], progress: ['Ember imps hover out of reach and lob fire. Close in fast.'],
        complete: ['(The last imp drops out of the smoke with a hiss, like a coal in a snowdrift. Behind you, the outpost’s fires sputter out under a skin of frost.)'], after: [] } }),
    q({ id: 'lyra30', title: 'Soot’s Letters', giver: 'guide', kind: 'talk', count: 1, to: 'soot', summary: 'Collect your post from Courier Soot at the outpost.', reward: { xp: 110 },
      text: { offer: ['A frostweaver? In the Wastes? An hour ago I’d have laughed. I’d have said you’d be a puddle by noon.', 'Something black fell out of the west wind two nights ago. Since then the imps have gone mad, and the Dawn Forge sits cold, with a fire-serpent wrapped round it.', 'Soot’s our courier, the one that doesn’t burn. She’s been hopping about waiting for you all day.'], progress: ['Soot is here at the outpost.'], complete: [], after: [],
        deliver: ['Lyra Rimeward! Pip, Nutkin, Bramble and me: the whole courier line has been passing your news along like a hot potato.', 'Letter for you. From Nessa. It says: “Arrived in Brasshaven. It is VERY hot. Also I miss snow.”', 'And Kiln-mother Hessa wants to meet you. She says a frostweaver in the Wastes is either a miracle or a joke, and she’d like to know which.'] } }),
    q({ id: 'lyra37', title: 'Sand Brave Enough', giver: 'soot', kind: 'talk', count: 1, to: 'hessa', summary: 'Meet Kiln-mother Hessa in Kilnhollow.', reward: { xp: 120 },
      text: { offer: ['Kilnhollow is south-east of the outpost, where the glass-kilns never go out. Don’t touch the glass. Well, you can. You’re probably the only one who can.'], progress: ['Kilnhollow lies south-east of the outpost.'], complete: [], after: ['Glass is only sand that was brave enough to walk through fire.'],
        deliver: ['So you’re the frost-girl. Hm. Smaller than I expected. Colder, too.', 'The Dawn Forge lit the sunrise over these wastes for a thousand years. Its keeper, Pyrrhus, fell in love with the fire and wanted all of it for himself.', 'He bred a serpent out of the slag, the Cinderwyrm, to keep anyone from sharing the forge’s light. It swallowed the three ember cores and spat them across the wastes.', 'Now it lies coiled round the cold forge, and it hates frost more than anything. So tell me, frost-girl. Why are you really here?'] },
      choice: {
        a: { label: '“Because my sister is here.”', lines: ['Ha! Family. The only thing hotter than a kiln.', 'Good answer. Frost that stays for someone is worth more than fire that burns for itself.', 'Go on to Brasshaven, east of here. Forgemaster Tovan has a problem only cold can fix, and he’s too proud to say so.'], reward: { regen: .5 } },
        b: { label: '“Because everyone says I’ll be useless here.”', lines: ['Ha! Stubborn. I like stubborn. Sand is stubborn, and look what it becomes.', 'Useless? Girl, half this desert is dying of heat. You may be the most useful thing that ever walked into it.', 'Go on to Brasshaven, east of here. Forgemaster Tovan has a problem only cold can fix, and he’s too proud to say so.'], reward: { mana: 14 } },
      } }),
    q({ id: 'lyra5', title: 'Winter in the Forge', giver: 'tovan', kind: 'activate', count: 3, near: 'city', switches: 'vent', order: ['West vent', 'North vent', 'East vent'], turnIn: 'tovan', summary: 'Freeze Brasshaven’s three overheating forge vents before they burst.', reward: { xp: 260, mana: 14 },
      text: { offer: ['You’re the frost-girl your sister won’t stop talking about? Good. Three of my forge vents are glowing white.', 'Since the serpent coiled round the Dawn Forge, the heat under the city has nowhere to go. If the vents burst, half of Brasshaven burns.', 'Freeze them. Just… not my beard.'], progress: ['Three vents around Brasshaven. Freeze them.'],
        complete: ['Ice! In Brasshaven! My apprentices are having snowball fights in the forge.', 'Forty years I’ve fought fire with fire. Never once thought to fight it with snow.', 'I was wrong about you, frost-girl. So listen: I know where the serpent spat the cores.'], after: ['Cool as a mountain morning.'] } }),
    q({ id: 'lyra31', title: 'A Core Held in Frost', giver: 'tovan', kind: 'key', count: 1, keys: [0], summary: 'Recover the first ember core from the Obsidian Maze. Only frost can hold it.', reward: { xp: 160 },
      text: { offer: ['The first core glows in the Obsidian Maze, far to the north-west. It burns through any glove, any salt, any hand. My best smiths have tried.', 'But frost… wrap it in your cold, and it might just let you carry it. Bring it back here.'], progress: ['The Obsidian Maze lies far to the north-west.'],
        complete: ['You carried it all that way bare-handed? It’s hissing in your ice like a kettle, but it’s whole!', 'Hessa always says the forge was made by two kinds of hands: hot ones to light it and cold ones to temper it. I thought it was a kiln-saying.', 'Now, trouble. Oona’s caravan sent a runner. The second core fell among her water barrels at the Salt Caravan Camp, the water is boiling, and the imps are swarming it.'], after: ['One of three.'] } }),
    q({ id: 'lyra72', title: 'Ice in the Water Barrels', giver: 'tovan', kind: 'defend', count: 3, place: 'caravan', waves: [4, 5, 6], foes: ['emberImp', 'ashScorpion', 'emberImp'], ward: 'Oona’s water barrels', auto: true, cine: { start: 'lyra-caravan' }, summary: 'Keep Oona’s water barrels frozen and hold the Salt Caravan Camp against three waves of imps and scorpions.', reward: { xp: 320, hearts: 1 },
      text: { offer: ['Oona’s caravan carries water to every town in the wastes. It’s stuck at the Salt Caravan Camp, south-east of the city, with an ember core boiling it dry.', 'The imps want that core back, and they’ll burn the camp to get it. Get down there. Freeze the barrels, and hold the camp.'], progress: ['Hold the Salt Caravan Camp. Break every wave before it reaches the barrels.'],
        complete: ['(The last scorpion scuttles off into the dunes. Every barrel in the ring is frosted white, and the water inside is cold and safe.)'], after: [] } }),
    q({ id: 'lyra73', title: 'A Core Among the Barrels', giver: 'fox', kind: 'key', count: 1, keys: [1], place: 'caravan', turnIn: 'tovan', summary: 'Wrap the second ember core in frost at the Salt Caravan Camp and carry it back to Tovan.', reward: { xp: 200 },
      text: { offer: ['(In the middle of the frozen barrels, the ember core still glows white, hissing at the frost.)', 'Wrap it in cold, like the first one. Then carry it back to Tovan in Brasshaven.'], progress: ['The ember core lies among the barrels at the Salt Caravan Camp. Then back to Tovan in Brasshaven.'],
        complete: ['Two cores! The first one sings when the second comes near. The forge is remembering.', 'Oona sent word. Her water is thawing slowly all the way home, cold and sweet. Every thirsty town in the wastes owes you a drink.', 'And your sister came by. She has a letter for Ashfall Watch, and she says the imps won’t stop her. I told her to wait for you. She is waiting. Very loudly.'], after: ['Two of three.'] } }),
    q({ id: 'lyra38', title: 'The Last Post Run', giver: 'nessa', kind: 'escort', count: 1, who: NESSA, from: 'city', place: 'watch', ambush: ['emberImp', 'ashScorpion', 'emberImp'], turnIn: 'seer', summary: 'Walk Nessa and her letter north to Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 200 },
      text: { offer: ['Ember-seer Ilyana at Ashfall Watch hasn’t had post in weeks. I’ve got a letter for her from Abbot Corvin, and it says URGENT on it in red.', 'Tovan says the dunes are full of imps. So walk with me. Couriers look after each other, and sisters look after each other twice.'], progress: ['Lead Nessa north to Ashfall Watch and keep the imps off her.'],
        arrive: ['Ashfall Watch! Special delivery! …She’s already waving. Seers. You can’t surprise them.'],
        complete: ['A letter from the Summit, carried by a Rimeward and guarded by a Rimeward. I saw it in the flames, and still I hardly believed it.', 'The Abbot writes that the dark that fled his mountain is cold without any warmth: an endless winter night. It wants the dawn never to come again.', 'Only the Dawn Forge can stop it. But first, the wastes have something to ask of you, frost-daughter.'], after: ['The flames speak of two sisters.'] } }),
    q({ id: 'lyra36', title: 'Snow on the Last Green', giver: 'seer', kind: 'visit', count: 1, place: 'green', turnIn: 'seer', cine: { ready: 'lyra-first-snow' }, summary: 'Bring the first snow in a thousand years to the Last Green, then return to Ilyana.', reward: { xp: 170, mana: 12 },
      text: { offer: ['East of here grows the Last Green, the only grove left in the wastes. It is dying of thirst. No rain has fallen on it in a lifetime.', 'The flames showed me snow on its leaves. I did not understand it. Then you walked up my hill.', 'Go there. Let your cold fall on it. Then come back and tell me what you saw.'], progress: ['The Last Green lies east of Ashfall Watch.'],
        complete: ['You made it snow. In the Ember Wastes. The flames are laughing. I have never heard them laugh.', 'Frost that gives water. Frost that keeps a seed safe until spring. That is what your family’s magic was always for, child.', 'Now, the last core. It sank into the Molten Mere, where the serpent drinks. No hand could ever reach it. Perhaps a cold one can.'], after: ['Green and white, green and white.'] } }),
    q({ id: 'lyra35', title: 'Frost Runes on the Molten Mere', giver: 'seer', kind: 'activate', count: 3, near: 'mere', switches: 'rune', order: ['Rime rune', 'Hearth rune', 'Dawn rune'], auto: true, summary: 'Carve three frost runes around the Molten Mere to freeze the slag channels that feed the Cinderwyrm.', reward: { xp: 200, mana: 14 },
      text: { offer: ['Three slag channels run from the Molten Mere, south-west of here, deep under the sand to the Dawn Forge. The serpent drinks fire through them, and the last core lies at the bottom of that fire.', 'The couriers say you froze a lake’s springs once, to trap a serpent in the meadow. Do it again. Freeze the channels, and the mere will cool enough to give up its core.'], progress: ['Three frost runes around the Molten Mere.'],
        complete: ['(The last rune bites into the slag, and a long hiss runs away under the sand toward the Dawn Forge. Far off, something enormous stirs, hungry and furious.)', '(Out on the cooling mere, a crust of black stone splits, and something glows white underneath.)'], after: [] } }),
    q({ id: 'lyra75', title: 'The Core in the Cooling Slag', giver: 'fox', kind: 'key', count: 1, keys: [2], place: 'mere', auto: true, summary: 'Walk out over the cooling crust of the Molten Mere and lift the last ember core in frost.', reward: { xp: 200 },
      text: { offer: ['Mirror Lake at the start, and a lake of fire at the end. Nessa would call that poetic.', 'The last core is out there on the cooling slag. Walk softly. Frost first, then feet.'], progress: ['The last ember core glows on the cooling crust of the Molten Mere.'],
        complete: ['(Lyra lifts the last core in both hands. It hisses at her frost, then settles, like a cat on a warm lap.)', 'Three. Now the Dawn Forge, far to the north-east. And whatever is coiled around it.'], after: [] } }),
    q({ id: 'lyra74', title: 'Frost on the Slag Shell', giver: 'fox', kind: 'activate', count: 3, near: 'forge', switches: 'rune', order: ['West seam', 'North seam', 'East seam'], auto: true, cine: { done: 'lyra-wyrm-wakes' }, summary: 'Freeze the three seams of the slag shell around the Dawn Forge until it cracks, and wake what sleeps inside.', reward: { xp: 300 },
      text: { offer: ['The Cinderwyrm sleeps in a shell of cooling stone round the Dawn Forge. Hessa says hot stone hates a sudden cold.', 'Three seams in the shell. Freeze them all, and it cracks like a jar left out in the snow.', 'And then it comes out. Good. I’m tired of it hiding.'], progress: ['Freeze the three seams of the slag shell around the Dawn Forge.'], complete: [], after: [] } }),
    ],
  },
  // Only the guardians and Umbra are the valley's own quests; Lyra tells them in her words.
  reuse: {
    meadow: {
      m10: { title: 'Gloamgill', giver: 'fox', cine: { done: 'lyra-last-letter' }, summary: 'Draw Gloamgill up from under the Beacon Rise with the sun-crystals, defeat it, and relight the Meadow Beacon.', reward: { xp: 320, hearts: 1 },
        text: { offer: ['The springs are frozen. Gloamgill has only one way out of the dark now: up, toward the light.', 'It has slept down there a hundred years. It will spit ice, whirl and charge, and the ground will burst wherever it swims. Keep moving.', 'Then I lay the crystals in the Beacon, far to the south-east. And I get my sister’s letter back.'],
          progress: ['The Beacon Rise lies far to the south-east.'], complete: [], after: ['The Beacon shines!'] } },
    },
    woods: {
      m15: { title: 'The Pale Huntress', giver: 'ivo', cine: { done: 'lyra-huntress' }, summary: 'Defeat the Pale Huntress and ring the Ancient Root Bell.', reward: { xp: 360, hearts: 1 },
        text: { offer: ['The Old Bell stands in the far north-east. She throws ice in fans, blinks from mist to mist, and calls down the blizzard.', 'Break her, then ring the Bell. Its voice should drive the mist out of Whisperroot for good.'],
          progress: ['The Old Bell stands in the far north-east.'], complete: [], after: ['The Bell rings!'] } },
    },
    summit: {
      m19: { title: 'Queen Hoarfrost', giver: 'lyra-nessa-sky', summary: 'Defeat Queen Hoarfrost at the Star Cradle and return the shards to the star.', reward: { xp: 420, hearts: 1 },
        text: { offer: ['The Star Cradle is at the top of the world, north-east of the Spire. She rains blizzards, slams the ice, spins frost in spirals and steps through the cold like a door.', 'She’s made of the same frost as you, Lyra, so she knows your tricks. But she doesn’t know mine. I’ll be singing the whole time. You won’t hear me. You’ll feel it.', 'Crack her crown, then lay the three shards in the Cradle.'],
          progress: ['The Star Cradle is in the far north-east.'], complete: [], after: ['The star is home. Now the gate!'] } },
    },
    ember: {
      m12: { title: 'Cinderwyrm', giver: 'fox', summary: 'Defeat the Cinderwyrm, the Serpent in the Slag, at the Dawn Forge.', reward: { xp: 480, hearts: 1 },
        text: { offer: ['(The Cinderwyrm rears over the Dawn Forge, and the air shimmers with heat.)', 'It rains lava, spins fire in spirals and charges like a landslide, and wherever it has been, the ground burns. Never stand still.', 'It hates frost. Good. Let it hate me. Nessa is singing, and I’m not afraid of my cold any more.'],
          progress: ['The Dawn Forge is in the far north-east.'], complete: [], after: ['Be brave.'] } },
      m13: { title: 'The Endless Winter Night', giver: 'fox', summary: 'Defeat Umbra, the Endless Winter Night, and light the Dawn Forge.', reward: { xp: 900, hearts: 2 },
        text: { offer: ['(The Cinderwyrm crumbles into cooling slag, and for one breath the forge is quiet. Then every ember in the wastes goes out at once.)', '(Far to the west, dark light rises from the Beacon Rise, the Old Bell and the Star Cradle. The shadows of the serpent, the Huntress and the Queen gather into one.)', '(Black frost creeps over the Dawn Forge: a winter with no warmth anywhere in it. Nessa takes your hand. Umbra is here.)'],
          progress: ['Defeat Umbra at the Dawn Forge.'], complete: [], after: [] } },
    },
  },
  npcs: {
    meadow: [
      { id: 'lyra-wick', name: 'Wick', portrait: '🧒', at: 'millbrook', dx: -140, dy: 90, activity: 'wander', after: 'lyra2', look: look('#5a4a3a', 'cap', { hatColor: '#2e2420', small: true }), lines: ['I’m mending fences. For free. Bram says it builds character. I had loads of character before.', 'Your sister gave me a biscuit once, you know. I should’ve given her letters back.'], barks: ['Honest work, ugh.', 'Sorry about the letters!'] },
      { id: 'lyra-tansy', name: 'Courier Tansy', portrait: '🧑', at: 'city', dx: -60, dy: 300, activity: 'wander', after: 'lyra49', look: COURIER, lines: ['Nessa and I raced the whole east road in my cart. She steers like a mad goat. Best courier I ever rode with.', 'The post always gets through. Say it with me.'], barks: ['Post’s moving again!', 'Mind the boars!'] },
    ],
    woods: [
      { id: 'lyra-nutkin-city', name: 'Courier Nutkin', portrait: '🐿️', at: 'city', dx: 240, dy: 260, activity: 'wander', after: 'm15', look: NUTKIN.look, lines: ['Summit post, all sorted! Well, mostly sorted.', 'Nessa and I raced once, camp to Bellhollow. She cheated. She says I cheated. We both cheated.'], barks: ['Post for the Summit!', 'Ready when you are!'] },
    ],
    summit: [
      { id: 'nessa', name: 'Nessa', portrait: '👧', at: 'hamlet', dx: 60, dy: -120, activity: 'play', after: 'lyra4', until: 'lyra24', look: NESSA.look, lines: ['Aune says I have to stay warm. I’m warm! I’m SO warm.', 'You came all this way for me. You’re the best big sister in the whole valley. Don’t let it go to your head.'], barks: ['Lyra!', 'Snowball!'] },
      { id: 'lyra-nessa-sky', name: 'Nessa', portrait: '👧', at: 'city', dx: -260, dy: 200, activity: 'play', after: 'lyra24', until: 'lyra68', look: NESSA.look, lines: ['Corvin lets me read the Rime-book if I don’t lick my fingers to turn the pages. I lick them a little.', 'Gran’s handwriting is terrible. It’s like ice-script. It might actually BE ice-script.'], barks: ['Lyra! Over here!', 'I’m practising my half!'] },
      { id: 'lyra-nessa-gate', name: 'Nessa', portrait: '👧', at: 'gateE', dx: -170, dy: 40, activity: 'idle', after: 'm19', until: 'ember:lyra70', look: NESSA.look, lines: ['The ice is humming. It knows the song. It doesn’t like it.', 'Ready when you are. Well, I’m ready now. I was born ready.'], barks: ['La-laaa!', 'Warming up!'] },
    ],
    ember: [
      { id: 'nessa', name: 'Nessa', portrait: '👧', at: 'city', dx: -60, dy: 300, activity: 'play', after: 'summit:lyra68', until: 'lyra38', look: NESSA.look, lines: ['I carried Tovan’s letters all the way here! Nobody catches me twice.', 'Well. A soot-sprite nearly did, on the road. That doesn’t count. It was a sprite.'], barks: ['Special delivery!', 'It’s SO hot!'] },
      { id: 'lyra-nessa-watch', name: 'Nessa', portrait: '👧', at: 'watch', dx: 70, dy: -80, activity: 'play', after: 'lyra38', look: NESSA.look, lines: ['Ilyana says the flames like my singing. I think the flames are being polite.', 'When this is over, we’re going home together. Both of us. You promised. Well, I promised for you.'], barks: ['I’m warming up my voice!', 'La-laaa!'] },
    ],
  },
  // Orrin and Sable are Mira's story; Lyra only hears of them. Their places at the Summit stay empty for her.
  // The Old Bellkeeper is in the wraiths' ice cage until Lyra brings him home.
  npcFor: {
    'summit:orrin': { hidden: true }, 'summit:orrin2': { hidden: true },
    'summit:sable': { hidden: true }, 'summit:sable2': { hidden: true }, 'summit:sable3': { hidden: true },
    'woods:bellkeeper': { after: 'woods:lyra55' },
  },
  script: {
    meadow: {
      pickupKey: 'Sun-crystal found! {n}/3',
      sealed: 'Gloamgill lies coiled deep in the black water under the Rise. Only the light of three sun-crystals will draw it up.',
      tip: 'When the ground bubbles where Gloamgill swims, move! Frostbolt slows even a serpent. Spend gold at the smith in Goldenhearth to grow stronger.',
      guide: { done: ['The meadow is bright again. Your sister would be proud of you.'] },
      finale: { locked: ['The Beacon is dark, and the water under the Rise lies still. Three sun-crystals are needed to draw up what sleeps below.'], guarded: ['Gloamgill is coiled around the Beacon. Defeat the serpent to relight it.'],
        done: ['The crystals blaze in the Beacon, and gold light pours down the Rise into the dark water below.', 'Gloamgill shudders, spits a soaked courier’s satchel onto the stones, and sinks back into the deep to sleep another hundred years.', 'Inside, wrapped in oilcloth and perfectly dry, is a letter in Nessa’s round hand: “For Lyra. Silver Heights. Please deliver.”'] },
      victory: { title: 'The Beacon shines again.', text: 'Nessa’s letter is found and the meadow is safe. But she ran east over the Gloomwater Bridge into Whisperroot Woods, and pale riders were waiting on the other side.' },
    },
    woods: {
      pickupKey: 'Root rune awakened. {n}/3',
      sealed: 'The Pale Huntress is wrapped in sleeping roots and mist. Wake the three root runes first.',
      tip: 'The Huntress blinks from mist to mist and throws ice in fans. When she vanishes, keep moving, and step out of the blizzard’s circles.',
      guide: { done: ['The woods are warm again. Who would have thought a frostweaver would bring the warmth back?'] },
      finale: { locked: ['Three root runes are needed to loosen the roots around the Bell.'], guarded: ['The Pale Huntress is wound around the Bell.'],
        done: ['You ring the Ancient Bell. Its voice rolls through every root, and the winter mist drifts out of Whisperroot like breath on a cold morning.', 'Where the Huntress sat, a scrap of blue wool is caught on the Bell’s rim: the other mitten.', 'Nessa was here. The riders carried her on, east and up, toward the Summit.'] },
      victory: { title: 'The Bell rings through the valley.', text: 'The winter mist is gone from Whisperroot, and the Huntress with it, for now. Nessa is on the Summit, in the Old Observatory, and Lyra is going home.' },
    },
    summit: {
      pickupKey: 'Star shard gathered. {n}/3',
      sealed: 'Queen Hoarfrost is sealed behind a crown of black frost. Gather the three star shards first.',
      tip: 'When the Queen’s blizzard falls, blink out of its circles. When she steps out of the cold beside you, she slams the ice. Never stand still.',
      guide: { done: ['The Heights are yours again, Rimeward. Come home more often.'] },
      finale: { locked: ['The Cradle is cold, and the frost on it is black. Three star shards are needed.'], guarded: ['Queen Hoarfrost sits on the Cradle in her crown of ice. Defeat her!'],
        done: ['You lay the three shards in the Cradle. The star remembers its light and rises, whole, with a soft crown of frost around it.', 'Far below, a small voice is still singing the warm half of an old song. You can feel it in your hands.', 'But a thread of black smoke has torn loose from the Queen’s broken crown and fled east, toward the Ember Wastes. Umbra is not finished.'] },
      victory: { title: 'The star rises home.', text: 'Nessa is free, the Rimeward sisters sing together again, and the star is whole. But Umbra fled east into the Ember Wastes, where frost has never been welcome.' },
    },
    ember: {
      pickupKey: 'Ember core held in frost. {n}/3',
      sealed: 'The Cinderwyrm sleeps curled in the slag, wrapped in a shell of cooling stone. Recover the three ember cores first.',
      tip: 'The Cinderwyrm leaves fire wherever it charges: never follow its trail. Its lava falls in circles you can blink out of.',
      guide: { done: ['The wastes are cooling. Who’d have guessed it would take a frostweaver?'] },
      finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['The Cinderwyrm is coiled around the forge. Defeat it!'],
        done: ['You set the three ember cores in the Dawn Forge. Nessa sings the warm voice, you sing the cold one, and the fire takes, tempered and steady.', 'Its flame roars up white and gold, and a new dawn spills across the wastes, with a little snow in it.', 'Far to the west, the Star, the Bell and the Beacon shine back. The endless winter night is over.'] },
      victory: { title: 'The dawn returns.', text: 'Umbra is gone for good. The Dawn Forge burns again, and the Rimeward sisters, frost and warmth together, have become the valley’s newest legend.' },
    },
  },
  cines,
};
