import { LOOKS, type Shot } from '../cutscenes';
import { look, own, person, type HeroStory } from './kit';

// Riven, the Shadow. A foundling with a shadow that moves on its own and hurts, sold as a child to the Hushed, a guild
// of thieves. The night the star fell the Hushed stole the Beacon's sun-crystals for a buyer who paid in black feathers,
// and Riven, who had cased the job, walked out and left the pay on the table.
//
// I · The Broken Beacon: a thief catches thieves. Riven steals the crystals back out of the Hushed's three drops before
//     Corvane, the Feathered Shade (Umbra in the shape of the buyer Riven always feared), comes to collect them.
// II · The Bell Beneath the Roots: the Hushed smuggle through Silkmother Vesh's tunnels and pay her toll in foundlings.
//     Riven finds the Lantern House he grew up in, the matron who sold him, and Sable's childhood runes in the web.
// III · The Hollow Star: Nullface wears Riven's face, then Sable's. Orrin stays at the edge; Riven is the one who
//     reaches Sable, as an equal, because they carry the same shadow.
// IV · The Dawn Forge: the Ashen Broker's network in Kilnhollow and Brasshaven, and Umbra, which claims to be the shadow
//     Riven and Sable were born with. The shadow was never the enemy. The choosing is.
const q = own('riven');

const L = {
  wick: person('Wick', '🧒', { robe: '#4a4058', hat: 'cap', hatColor: '#2e2a36', hair: '#2e2420', small: true }),
  needle: person('Needle', '🥷', { robe: '#3a3048', hat: 'hood', hatColor: '#2a2438' }),
  loom: person('Matron Loom', '👵', { robe: '#5a4a3a', hat: 'bonnet', hatColor: '#3a2e24', hair: '#8a8a8a' }),
  tib: person('Tib', '🧒', { robe: '#3a3458', hair: '#1a1a24', small: true }),
  ada: person('Little Ada', '👧', { robe: '#4a4468', hair: '#2e2420', small: true }),
  double: person('Riven?', '🗡️', { robe: '#3a3048', hat: 'hood', hatColor: '#2a2438', hair: '#1a1a24', skin: '#c8bcd8' }),
  aled: person('Brother Aled', '🧘', { robe: '#a8844a', hair: '#8a6a4a' }),
  sable: person('Sable', '🌑', { robe: '#2a2438', hat: 'hood', hatColor: '#1a1428', hair: '#1a1a24' }),
  broker: person('The Ashen Broker', '🎭', { robe: '#4a3a3a', hat: 'hood', hatColor: '#2a1e1a', skin: '#b0a090' }),
};
const corvane = look('#1e1a26', 'hood', { hatColor: '#120e18', skin: '#2a2438', hair: '#120e18' });
const loomLook = look('#5a4a3a', 'bonnet', { hatColor: '#3a2e24', hair: '#8a8a8a' });
const kid = (robe: string, hair = '#2e2420') => look(robe, 'none', { hair, small: true });
const hushed = look('#3a3048', 'hood', { hatColor: '#2a2438', hair: '#1a1a24' });

// ═════════════════════════════ cutscenes
const cines: Record<string, Shot[]> = {
  // ─────────────── Chapter I
  'riven-hushed-scatter': [
    { at: 'meadow:shepherd', night: .5, text: 'Moth, crow, owl. The oldest signal the Hushed have: the guard is coming. Scatter.', fx: [{ kind: 'kindle', dx: -120 }, { kind: 'kindle', delay: .6 }, { kind: 'kindle', dx: 120, delay: 1.2 }], dur: 4.2 },
    { text: 'Hooded figures burst out of the heather and bolt downhill in every direction.', actors: [{ id: 'h1', name: 'Hushed', look: hushed, dx: -40, dy: 20, walk: { dx: -520, dy: 260 } }, { id: 'h2', name: 'Hushed', look: hushed, dx: 30, dy: 40, walk: { dx: 480, dy: 320 } }, { id: 'h3', name: 'Hushed', look: hushed, dx: 0, dy: -20, walk: { dx: 60, dy: 560 } }], fx: [{ kind: 'smoke', delay: .3 }], dur: 4.4 },
    { text: 'Behind them, on the hilltop, something is left glowing in the dirt. So is a great deal of scattered, furious sheep.', dur: 4.2 },
    { at: 'hero', night: 0, speaker: 'Riven', portrait: '🗡️', text: '“I taught half of them that signal. Nice to know somebody listened.”', dur: 3.8 }],
  'riven-corvane': [
    { at: 'meadow:rise', cut: true, dy: -80, night: .65, text: 'The dark of the moon. Above the cold Beacon, a masked shade unfolds a cloak of black feathers.', actors: [{ id: 'corvane', name: 'Corvane', look: corvane, dy: 40, spirit: true }], fx: [{ kind: 'feathers', dy: -20 }, { kind: 'shadow', delay: .8 }], dur: 4.8 },
    { speaker: 'Corvane', portrait: '🎭', text: '“Three crystals, little shadow. I paid for them. Everything I pay for comes to me in the end.”', dur: 4.4 },
    { speaker: 'Corvane', portrait: '🎭', text: '“You took my job once, little shadow. Take my feathers again. Everyone has a price.”', dur: 4.4 },
    { at: 'hero', cut: true, night: 0, speaker: 'Riven', portrait: '🗡️', text: '“Keep your feathers. I left them on the table.”', dur: 3.6 }],
  'beacon-lit@riven': [
    { at: 'meadow:rise', dy: -90, text: 'The Beacon roars back to life. Corvane’s feathers blow away across the meadow, and every one turns to smoke.', fx: [{ kind: 'light', dy: -90 }, { kind: 'feathers', dy: -60, delay: .4 }], dur: 4.4 },
    { at: 'obj:meadow:barrier', cut: true, text: 'Its light reaches all the way to the Eastern Gate, where the old Gloomwater Bridge lies broken in the river.', fx: [{ kind: 'collapse' }], dur: 4.6 },
    { at: 'npc:meadow:holt', text: 'Bridgewright Holt is already there, scratching his head at the wreck.', dur: 3.6 }],
  'chapter-meadow@riven': [
    { at: 'obj:meadow:barrier', text: 'Plank by plank, the Gloomwater Bridge stands again.', fx: [{ kind: 'build' }], dur: 3.6 },
    { at: 'obj:meadow:barrier', dx: 900, text: 'Beyond it the road dives under ancient trees: Whisperroot Woods. Somewhere under those roots, the Hushed’s tunnels run east.', dur: 4.6 },
    { at: 'woods:web', cut: true, night: .4, text: 'In Silkshadow Hollow, something with far too many legs is spinning.', fx: [{ kind: 'shadow' }], dur: 4 },
    { at: 'woods:bell', cut: true, dy: -60, text: 'And around the Ancient Bell hangs a web of runes. Riven knows those shapes. He drew them himself, once, in chalk.', fx: [{ kind: 'shadow', dy: -60 }], dur: 4.8 },
    { title: 'Chapter II', sub: 'The Bell Beneath the Roots', dur: 3.4 }],
  // ─────────────── Chapter II
  'glade-memory@riven': [
    { at: 'woods:glade', text: 'The last lantern catches. Silver light fills the glade…', fx: [{ kind: 'memory' }], dur: 3.4 },
    { night: .45, text: '…and it shows two small children from the Lantern House, holding lanterns almost as big as they are.', actors: [{ id: 'gsable', name: 'Little Sable', look: LOOKS.littleSable, dx: -50, dy: 50 }, { id: 'griven', name: 'Little Riven', look: LOOKS.littleRiven, dx: 40, dy: 55, face: -1 }], fx: [{ kind: 'lantern', dx: -50, dy: 20 }], dur: 5 },
    { speaker: 'Little Sable', portrait: '👧', text: '“If you touch moon, then eye, then door, the shadows have to let you through. It’s the rule.”', dur: 4.4 },
    { speaker: 'Little Riven', portrait: '🧒', text: '“You made that rule up.”', dur: 2.8 },
    { speaker: 'Little Sable', portrait: '👧', text: '“So? Somebody has to make them. Might as well be us.”', dur: 3.8 },
    { night: 0, text: 'The light fades. The glade is empty again.', fx: [{ kind: 'memory' }], dur: 3 }],
  'riven-lamp': [
    { at: 'npc:woods:juna', dy: -40, night: .5, text: 'The Lantern House lamp catches, and warm light spills out of a window that has been dark for twenty years.', fx: [{ kind: 'light', dy: -40 }], dur: 4.4 },
    { text: 'Up at the sill, a small boy presses his nose to the glass. His shadow sits beside him, quiet for once.', actors: [{ id: 'ltib', name: 'Tib', look: kid('#3a3458', '#1a1a24'), dx: 50, dy: 20, face: -1 }], dur: 4.4 },
    { at: 'hero', night: 0, speaker: 'Riven', portrait: '🗡️', text: '“Somebody should have done that for us.”', dur: 3.2 }],
  'bell-rung@riven': [
    { at: 'woods:bell', dy: -80, text: 'The Ancient Bell rings out, and its voice rolls through every root in Whisperroot.', fx: [{ kind: 'light', dy: -80 }, { kind: 'ring', dy: -80, delay: .3 }], dur: 4 },
    { text: 'Sable’s rune-web shivers, and comes apart like frost in the sun.', fx: [{ kind: 'wither', dy: -40 }], dur: 3.6 },
    { dy: 40, text: 'Out of the falling silk step the missing children: blinking, holding hands, their shadows all a-twitch.', actors: [{ id: 'bada', name: 'Little Ada', look: kid('#4a4468'), dx: -60, dy: 40, walk: { dx: 60, dy: 30 } }, { id: 'bk1', look: kid('#5a4a3a', '#6b3f2a'), dx: -20, dy: 70, walk: { dx: 50, dy: 30 } }, { id: 'bk2', look: kid('#3a4a5a', '#1a1a24'), dx: 20, dy: 60, walk: { dx: 40, dy: 30 } }], dur: 4.8 },
    { speaker: 'Little Ada', portrait: '👧', text: '“Are you the one Tib talks about? The one with a shadow like ours?”', dur: 3.8 },
    { at: 'woods:city', cut: true, dx: 520, dy: -320, text: 'Deep in the woods, something answers with a howl. The shadow wants its children back.', fx: [{ kind: 'wolves', n: 5 }, { kind: 'shadow', delay: .4 }], dur: 4.4 }],
  'chapter-woods@riven': [
    { at: 'obj:woods:barrier', text: 'The Bell-lanterns blaze, and the Bell’s last echo rolls down the road…', fx: [{ kind: 'light' }], dur: 3.4 },
    { text: '…and the wall of thorns at the Eastern Gate withers into dust.', fx: [{ kind: 'wither' }], dur: 3.4 },
    { at: 'summit:spire', cut: true, night: .4, text: 'High on Starfall Summit, a girl in a black cloak sits alone at the Broken Spire, scratching a chalk moth on the stones.', actors: [{ id: 'wsable', name: 'Sable', look: LOOKS.sable, dx: -40, dy: 60 }], dur: 5 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'Above her, the fallen star glows black in its Cradle. Inside it, something without a face is trying faces on.', fx: [{ kind: 'shadow', dy: -80 }], dur: 4.8 },
    { title: 'Chapter III', sub: 'The Hollow Star', dur: 3.4 }],
  // ─────────────── Chapter III
  'riven-double': [
    { at: '$thief', text: 'You catch the thief by the hood. It turns around, and it is wearing your face.', actors: [{ id: 'dbl', name: 'Riven?', look: LOOKS.riven, spirit: true, face: -1 }], dur: 4 },
    { speaker: 'Riven?', portrait: '🗡️', text: '“Riven. You look so tired of being you. Let me wear it for a while.”', dur: 4 },
    { text: 'Its face runs like wet paint, and it bursts into black smoke that streams away up the mountain.', fx: [{ kind: 'shadow' }, { kind: 'smoke', to: { dx: 1400, dy: -1200 }, delay: .3 }], dur: 4.2 }],
  'tarn-vision@riven': [
    { at: 'summit:tarn', text: 'You look into Mirrorsky Tarn. Your own face looks back…', fx: [{ kind: 'memory' }], dur: 3.2 },
    { text: '…and ripples, and becomes Sable’s. The same eyes. The same shadow, standing up behind her.', actors: [{ id: 'tsable', name: 'Sable', look: LOOKS.sable, dy: 40, spirit: true }], dur: 4.6 },
    { at: 'summit:crystal', cut: true, text: 'Then the water shows a light in Crystal Hollow,', fx: [{ kind: 'ring' }], dur: 2.8 },
    { at: 'summit:frostfang', cut: true, text: 'a dark hollow on Frostfang Crag, where the shard you carry used to lie,', fx: [{ kind: 'ring' }], dur: 3.2 },
    { at: 'summit:spire', cut: true, text: 'and a third light at the Broken Spire, right beside a girl in black.', fx: [{ kind: 'ring' }], dur: 3.6 }],
  'riven-orrin': [
    { at: 'npc:summit:orrin', night: .5, text: '(Orrin closes his eyes, and an old memory rises like frost on glass.)', fx: [{ kind: 'memory' }], dur: 3.6 },
    { text: 'The Lantern House, long ago. A young wizard counts gold into Matron Loom’s hand, and a small girl in a black cloak is led out to him.', actors: [{ id: 'oorrin', name: 'Orrin', look: LOOKS.youngOrrin, dx: -80, dy: 40 }, { id: 'oloom', name: 'Matron Loom', look: loomLook, dx: 10, dy: 30, face: -1 }, { id: 'osable', name: 'Little Sable', look: LOOKS.littleSable, dx: 40, dy: 60, walk: { dx: -90, dy: 0 }, face: -1 }], dur: 5.4 },
    { text: 'Behind the door, a boy with the very same shadow watches her go.', actors: [{ id: 'oriven', name: 'Little Riven', look: LOOKS.littleRiven, dx: 120, dy: 20, face: -1 }], dur: 4 },
    { speaker: 'Master Orrin', portrait: '🧙‍♂️', text: '“I never even saw you, Riven. I am sorry for that too.”', dur: 3.8 },
    { at: 'hero', night: 0, text: 'Riven says nothing for a long time.', dur: 3 }],
  'riven-two-shadows': [
    { at: 'summit:spire', text: 'Door, eye, moon. The runes around the Spire flare one by one…', fx: [{ kind: 'ring' }, { kind: 'memory', delay: .6 }], dur: 3.8 },
    { dy: 50, text: '…and two shadows stretch out across the snow, born the same, and touch.', actors: [{ id: 'ssable', name: 'Sable', look: LOOKS.sable, dx: -50, dy: 60 }, { id: 'sriven', name: 'Riven', look: LOOKS.riven, dx: 50, dy: 60, face: -1 }], fx: [{ kind: 'shadow', dy: 80, delay: .5 }], dur: 4.6 },
    { speaker: 'Sable', portrait: '🌑', text: '“Oh. It doesn’t hurt. Why doesn’t it hurt?”', dur: 3.4 },
    { speaker: 'Riven', portrait: '🗡️', text: '“Because nobody’s pulling on it. It’s just us.”', dur: 3.6 },
    { at: 'summit:cradle', cut: true, dy: -80, text: 'Far above, inside the hollow star, something without a face turns toward them, and begins to put one on.', fx: [{ kind: 'shadow', dy: -80 }], dur: 4.6 }],
  'star-rises@riven': [
    { at: 'summit:cradle', dy: -100, text: 'The star rises from its Cradle, whole again, and the whole Summit shines.', fx: [{ kind: 'light', dy: -100 }], dur: 4 },
    { text: 'Where Nullface fell there is only an empty mask, and a thread of black smoke tearing loose from it…', fx: [{ kind: 'smoke', dy: -100, to: { dx: 1600, dy: 900 } }], dur: 4 },
    { at: 'obj:summit:barrier', cut: true, text: '…that flees east, and seals the Eastern Gate behind it with black ice.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .3 }], dur: 4.2 },
    { at: 'summit:cradle', cut: true, text: 'Sable’s shadow is still there beside her. It just isn’t hurting her any more.', actors: [{ id: 'rsable', name: 'Sable', look: LOOKS.sable, dx: -40, dy: 70 }, { id: 'rriven', name: 'Riven', look: LOOKS.riven, dx: 40, dy: 70, face: -1 }], dur: 4.4 },
    { speaker: 'Sable', portrait: '🌑', text: '“I’m going down to Skyhold. To him. Before I lose my nerve. Come and find me there?”', dur: 4.2 },
    { speaker: 'Riven', portrait: '🗡️', text: '“I always do.”', dur: 2.6 }],
  'chapter-summit@riven': [
    { at: 'obj:summit:barrier', text: 'Riven and Sable lay their hands on the black ice. Two shadows, born the same, reach into it together.', actors: [{ id: 'criven', name: 'Riven', look: LOOKS.riven, dx: -170, dy: 60 }, { id: 'csable', name: 'Sable', look: LOOKS.sable, dx: -170, dy: -60 }], fx: [{ kind: 'shadow', delay: .6 }], dur: 4.6 },
    { speaker: 'Sable', portrait: '🌑', text: '“Moon, eye, door?”', dur: 2.4 },
    { speaker: 'Riven', portrait: '🗡️', text: '“Just the door.”', dur: 2.4 },
    { text: 'The black ice cracks from end to end, and shatters. Behind them, an old wizard leans on his staff and, for once, lets someone else do the magic.', actors: [{ id: 'corrin', name: 'Orrin', look: LOOKS.orrin, dx: -300, dy: 40, walk: { dx: 60, dy: 0 } }], fx: [{ kind: 'shatter' }], dur: 5 },
    { at: 'ember:forge', cut: true, dy: -60, text: 'Beyond lie the Ember Wastes, where the Dawn Forge has gone cold… and a broker in an ash mask is buying up its fire.', fx: [{ kind: 'quake' }, { kind: 'feathers', delay: .6 }], dur: 5 },
    { title: 'Chapter IV', sub: 'The Dawn Forge', dur: 3.4 }],
  // ─────────────── Chapter IV
  'riven-broker': [
    { at: '$thief', text: 'You catch the broker by the sleeve. The sleeve is full of ash.', dur: 3.4 },
    { speaker: 'The Ashen Broker', portrait: '🎭', text: '“The Hushed trained you well, little shadow. But Umbra trained me.”', dur: 4 },
    { text: 'The mask cracks. There is nothing behind it but ash, and the ash blows away north-east, toward Brasshaven.', fx: [{ kind: 'smoke', to: { dx: 1300, dy: -600 } }, { kind: 'feathers', delay: .4 }], dur: 4.4 }],
  'pyrrhus-wakes@riven': [
    { at: 'ember:forge', dy: -60, text: 'The great bellows heave. For the first time in weeks, the Dawn Forge breathes.', fx: [{ kind: 'build' }], dur: 3.8 },
    { text: 'The ash around the anvil rises into a towering shape: the old armour of Pyrrhus, the forge’s fallen keeper…', fx: [{ kind: 'quake' }, { kind: 'embers', delay: .3 }, { kind: 'smoke', delay: .6 }], dur: 4.6 },
    { text: '…with a cracked grey mask where his face used to be.', fx: [{ kind: 'shadow', delay: .2 }], dur: 3.4 },
    { speaker: 'The Ashen Broker', portrait: '🎭', text: '“Three cores, carried right to my door. And two little shadows, for the price of none.”', dur: 4.4 },
    { at: 'hero', speaker: 'Riven', portrait: '🗡️', text: '“We’re not for sale.”', dur: 2.8 }],
  'chapter-ember@riven': [
    { at: 'ember:forge', dy: -60, text: 'The Dawn Forge burns white and gold, and a new dawn spills across the wastes.', fx: [{ kind: 'light', dy: -60 }], dur: 4.2 },
    { dy: 40, text: 'Two friends sit on the forge steps. Their shadows lie beside them in the sunrise, perfectly still.', actors: [{ id: 'eriven', name: 'Riven', look: LOOKS.riven, dx: 30, dy: 50, face: -1 }, { id: 'esable', name: 'Sable', look: LOOKS.sable, dx: -30, dy: 50 }], dur: 4.6 },
    { speaker: 'Sable', portrait: '🌑', text: '“It’s not hurting.”', dur: 2.6 },
    { speaker: 'Riven', portrait: '🗡️', text: '“No. It’s just ours.”', dur: 2.8 },
    { at: 'woods:city', cut: true, text: 'In Lanternmarket, the lamp in the Lantern House window has not gone out once.', fx: [{ kind: 'light' }], dur: 3.8 },
    { at: 'meadow:city', cut: true, text: 'In Goldenhearth, a boy called Wick sweeps the bakery step, and saves a honey bun for a thief.', dur: 4.2 },
    { at: 'meadow:rise', cut: true, dy: -80, text: 'And the Beacon, the Bell and the Star shine back across a valley that nobody owns.', fx: [{ kind: 'light', dy: -80 }], dur: 4.2 },
    { title: 'Every light is shining', sub: 'Riven chose, and the valley is whole', dur: 4 }],
};

export const RIVEN: HeroStory = {
  hero: 'riven',
  chains: {
    meadow: ['m1', 'riven1', 'riven6', 'riven2', 'm2', 'riven0', 'riven9', 'riven11', 'm5', 'm7', 'm6', 'riven10', 'm11', 'm9', 'm10', 'm12'],
    woods: ['m1', 'm7', 'riven16', 'm2', 'riven7', 'riven14', 'riven15', 'm9', 'riven3', 'm6', 'riven18', 'riven19', 'm12', 'm15', 'riven17', 'm16', 'm17'],
    summit: ['m1', 'riven21', 'riven22', 'riven23', 'm10', 'riven24', 'm12', 'm5', 'm6', 'm14', 'm15', 'riven26', 'riven4', 'riven25', 'm19', 'm20'],
    ember: ['m1', 'm2', 'riven5', 'riven29', 'riven30', 'riven35', 'm8', 'm7', 'm6', 'riven32', 'riven31', 'm10', 'riven34', 'm15', 'm12', 'm13'],
  },
  quests: {
    // ═════════════════════════════ Chapter I · a thief catches thieves
    meadow: [
    q({ id: 'riven1', title: 'An Old Debt', giver: 'fox', kind: 'talk', count: 1, to: 'magpie', summary: 'Find Magpie, the guildmistress of the Hushed, at her hat stall in Goldenhearth.', reward: { xp: 90 },
      text: { offer: ['Brannoc wants the crystals. Magpie knows where they are. Magpie always knows where everything is.', 'She’ll be at her hat stall, pretending she didn’t rob anybody last night.'], progress: ['Magpie keeps a hat stall on the south-west side of Goldenhearth.'], complete: [], after: ['Hats! Fine hats!'],
        deliver: ['Riven. You walked out on the Hushed. People don’t do that. And you left your pay on the table, which is just rude.', 'The crystals? Gone to the drops. Three hiding places, for the buyer to collect at the dark of the moon.', 'He calls himself Corvane. A mask, all feathers. His pay turned to smoke by morning. Every last feather.', 'A girl in a black cloak brought us his job. I think she was one of yours, from the foundling house. She walked east, and she dropped feathers like breadcrumbs.', 'I won’t tell you where the drops are. Not yet. I’m more scared of him than I am of you.'] } }),
    q({ id: 'riven6', title: 'Follow the Feathers', giver: 'fox', kind: 'trail', count: 4, near: 'city', place: 'willow', auto: true, cine: { done: 'feather-trail' }, summary: 'Follow the trail of black feathers from Goldenhearth to Willowmere.', reward: { xp: 150, regen: .4 },
      clues: ['A black feather caught in the city gate. It crumbles to smoke when I touch it.', 'Another, on a milestone. Whoever paid the Hushed walked this road on foot, alone.', 'Scuff marks where someone sat and cried. Then stood up and kept walking.', 'Feathers all along the Willowmere jetty, as if someone waited here a long, long time.'],
      text: { offer: ['Magpie won’t give up the drops. But the girl in black left a trail, and feathers leave a trail if you know how to look.', 'East, out of the city, toward Willowmere. Let’s see where you went.'], progress: ['Follow the black feathers east from Goldenhearth.'], complete: [], after: [] } }),
    q({ id: 'riven2', title: 'Needle Runs', giver: 'ottilie', kind: 'chase', count: 1, place: 'willow', who: L.needle, summary: 'Catch the hooded sneak skulking around Willowmere for Mayor Ottilie.', reward: { xp: 150, gold: 50 },
      text: { offer: ['You there! Hooded person! Are you with the other hooded person?', 'A little sneak has been skulking round my jetty since dawn, and my weathervane has gone missing.', 'Catch him, please. And wipe your boots afterwards.'], progress: ['The sneak is darting around Willowmere. Run him down.'],
        deliver: ['Riven?! You’re supposed to be gone!', 'Fine, take it! Take the weathervane too, it was heavy anyway. And this letter. Magpie said carry it to the jetty and never read it. It’s sealed with a black sun.'],
        complete: ['My weathervane! And a letter? I read all the post in Willowmere. It’s a mayor’s privilege.', '“The lights must go out, one by one. When they are all dark, I will stop hurting.” And underneath, in a nasty scratchy hand:', '“Crystals to the three drops. Corvane collects at the dark of the moon. The gloom covers Sunpetal tonight.” Tonight! Go on, then!'], after: ['Boots. Wiped. Thank you.'] } }),
    q({ id: 'riven0', title: 'Light Fingers', giver: 'maren', kind: 'collect', count: 4, near: 'sunpetal', item: 'Stolen purse', icon: 'bundle', turnIn: 'maren', summary: 'Find the purses the Hushed lifted in Sunpetal during the attack and give them back.', reward: { xp: 120, gold: 30 },
      text: { offer: ['While everyone was at the barricade, someone went through every house on the lane. Purses, rings, my good scissors.', 'You move like one of them, dear. No offence. Maybe you know where a thief would stash things?'], progress: ['Four stolen purses are hidden around Sunpetal.'],
        complete: ['Under the well cover? In the rain barrel? You do know how they think.', 'And look: one purse has a scrap of map in it. The Old Stone Garden, with a little chalk moth drawn on the third stone. Does that mean anything to you?', 'Thank you, Riven. You didn’t have to do this. That’s the point, isn’t it?'], after: ['Honest hands. Who’d have thought.'] } }),
    q({ id: 'riven9', title: 'The Moth Under the Stone', giver: 'fox', kind: 'key', count: 1, keys: [0], auto: true, summary: 'Open the Hushed’s first drop in the Old Stone Garden and take back a sun-crystal.', reward: { xp: 140, mana: 8 },
      text: { offer: ['A chalk moth on a stone. That’s a Hushed drop. We used to leave each other things under moths.', 'The Old Stone Garden is north-east of Sunpetal. Let’s see what the buyer left there.'], progress: ['Find the drop under the moth stone in the Old Stone Garden, north-east of Sunpetal.'],
        complete: ['(Under the stone: a sun-crystal, wrapped in black cloth. On top of it lies a single black feather.)', 'One crystal back. This feather should have turned to smoke by now. It hasn’t. Like it’s waiting for its buyer.'], after: [] } }),
    q({ id: 'riven11', title: 'Smoke and Feathers', giver: 'fox', kind: 'deliver', count: 1, to: 'ilse', item: 'Corvane’s feather', summary: 'Show the feather from the drop to Scholar Ilse in Goldenhearth.', reward: { xp: 110 },
      text: { offer: ['Scholar Ilse in Goldenhearth knows every old story in the valley. Maybe one of them has feathers that won’t melt.'], progress: ['Scholar Ilse is in Goldenhearth, on the west side of the square.'], complete: [], after: ['Books remember what people forget.'],
        deliver: ['Oh my. Don’t hold it so close to your face, dear.', 'Corvane, the Feathered Shade. In the oldest tales he buys lights: lamps, hearths, beacons. He pays in feathers that fade the moment he has what he paid for.', 'They say Umbra’s shadow takes the shape of whatever frightens you most. For a thief, what’s worse than a buyer you can never say no to?', 'This one hasn’t faded, so he hasn’t collected. And whoever took his pay will have written it down. Thieves do love their books.'] } }),
    q({ id: 'riven10', title: 'The Scatter Signal', giver: 'fox', kind: 'activate', count: 3, near: 'shepherd', switches: 'lantern', order: ['Moth lamp', 'Crow lamp', 'Owl lamp'], ordered: true, auto: true, cine: { done: 'riven-hushed-scatter' }, summary: 'Light the Hushed’s warning lamps on Shepherd’s Hill, in the old order, to scatter the crew.', reward: { xp: 150, gold: 40 },
      text: { offer: ['The crew is up on Shepherd’s Hill, far to the north-east. A dozen scared thieves sitting on one crystal.', 'The Hushed have a signal for “the guard is coming, scatter”: moth lamp, crow lamp, owl lamp, in that order. I taught it to half of them.', 'Light the three lamps around the hill and they’ll run. They’ll leave the crystal behind. Thieves always do.'], progress: ['Light the lamps around Shepherd’s Hill: Moth, then Crow, then Owl.'],
        complete: ['(Down the hill, hooded figures bolt in every direction. So, unfortunately, does a great number of sheep.)', '(…You hadn’t thought about the sheep.)'], after: [] } }),
    ],
    // ═════════════════════════════ Chapter II · the Lantern House
    woods: [
    q({ id: 'riven16', title: 'Needle Again', giver: 'forester', kind: 'chase', count: 1, place: 'shroomfarm', who: L.needle, summary: 'Catch the runner popping out of the tunnels under Glowcap Farm.', reward: { xp: 170, gold: 60 },
      text: { offer: ['There! Popping out of my glowcaps like a mole! Hood, sack, very fast little legs.', 'Catch him before he gets back underground. I’d help, but I’m holding an axe and I don’t trust myself.'], progress: ['The runner is darting around Glowcap Farm. Catch him.'],
        deliver: ['No. No, no, no. Riven AGAIN? I walked all the way to a different forest!', 'Fine! Here’s the map! Every Hushed tunnel under Whisperroot. They all run east, into the spider queen’s hollow.', 'Vesh, she’s called. The Silkmother. She lets the Hushed pass, for a toll. Not gold.', 'Ask the herbalist in Lanternmarket why her children keep going missing. I only carry barrels. I don’t carry kids. I swear I don’t.'],
        complete: ['A map of tunnels under my own farm. I’ll be filling those in with manure, thank you very much.', 'Lanternmarket is east, past the Moonlit Glade. Mind the wolves on the road.'], after: ['Your little friend hauls mushrooms for me now. He giggles less.'] } }),
    q({ id: 'riven7', title: 'The Foundling', giver: 'juna', kind: 'rescue', count: 1, place: 'nest', guards: 5, escort: true, turnIn: 'juna', cine: { done: 'foundling-memory' }, summary: 'Rescue Tib, a foundling taken from the Lantern House, from the Thornling Nest and bring him to Juna.',
      captive: L.tib, reward: { xp: 200, regen: .5 },
      text: { offer: ['A boy went missing from the Lantern House last night. Tib. He has… a shadow that hurts. You wouldn’t understand.', '…Oh. You would. Your shadow just moved on its own.', 'Something dragged him north, to the Thornling Nest. Please. Nobody else goes looking for children like him.'], progress: ['Break the guards at the Thornling Nest, north of the market, free Tib, and walk him back to Juna.'], arrive: ['Is this where Juna lives? Is there a bed? A real one?'],
        deliver: ['You’re… like me. Your shadow moves too.', 'The lady in black said I’d stop hurting if I came with her. I didn’t want to go. Then the spiders came instead.'],
        complete: ['Tib, oh, Tib. He hasn’t let go of your sleeve once, Riven.', 'He says a woman with a ring of keys took the other children. South, toward the water.'], after: ['Tib says he wants to be a thief like you. I told him you’re a hero. He says what’s the difference.'] } }),
    q({ id: 'riven14', title: 'Little Footprints', giver: 'juna', kind: 'trail', count: 4, near: 'city', place: 'pool', turnIn: 'maeve', summary: 'Follow the missing children’s tracks south from Lanternmarket to Blackwater Pool, then talk to Fisher Maeve.', reward: { xp: 160, mana: 10 },
      clues: ['Small boot prints in the soft ground. Three pairs, walking in a line, very close together.', 'A rag doll face down in the ferns. Someone was in too much of a hurry to go back for it.', 'A ring of keys scratched into the bark. The mark of the Lantern House. The old one.', 'The prints end at the water’s edge, where a tunnel mouth yawns under the reeds.'],
      text: { offer: ['A woman with a ring of keys. …No. It can’t be.', 'Follow the children’s tracks south from the market to Blackwater Pool. Fisher Maeve is always there. She sees everything and says nothing.'], progress: ['Follow the small footprints south to Blackwater Pool, then talk to Fisher Maeve.'],
        complete: ['Tunnel? Aye, under the reeds. Lanterns go in at night, and come out without the little ones.', 'The woman with the keys? Nana Bristle in Bellhollow knew her once. Knew her well. Ask Nana.'], after: ['Shh. The fish are listening.'] } }),
    q({ id: 'riven15', title: 'Nana Remembers', giver: 'maeve', kind: 'talk', count: 1, to: 'nana', summary: 'Ask Nana Bristle in Bellhollow about the woman with the ring of keys.', reward: { xp: 110 },
      text: { offer: ['Bellhollow is west of here, up the stream. Nana Bristle makes a stew that could wake the Bell by itself.', 'Tell her Maeve sent you. And bring a spoon.'], progress: ['Nana Bristle lives in Bellhollow, west of the pool.'], complete: [], after: ['Mind the spoon.'],
        deliver: ['Let me look at you. Dark hair, quick hands, a shadow that won’t sit still… Little Riven. You used to hide in my flour sacks.', 'I cooked at the Lantern House when you were small. Matron Loom ran it. A ring of keys, and a heart like a coin purse.', 'She found homes for the children with the hurting shadows, she said. For a price. The Hushed paid for you. An old star-wizard paid for Sable.', 'Now nobody buys children, so she sells them to the spider instead. Oh, my little flour-sack boy. I’m so sorry.'] } }),
    q({ id: 'riven3', title: 'Moon, Eye, Door', giver: 'fox', kind: 'activate', count: 3, near: 'ruins', switches: 'rune', order: ['Moon', 'Eye', 'Door'], ordered: true, auto: true, cine: { done: 'sable-echo' }, summary: 'Touch Sable’s shadow-runes in the Root Ruins in the order of your old game.', reward: { xp: 190, regen: .6 },
      text: { offer: ['Moon, eye, door. Sable carved our game into the Root Ruins when she ran from Orrin, far to the north.', 'If I touch the runes in the old order, maybe they will answer.'], progress: ['Find Sable’s runes in the Root Ruins, north of the glade. Moon, then Eye, then Door.'], complete: [], after: [] } }),
    q({ id: 'riven18', title: 'A Lamp in the Window', giver: 'juna', kind: 'build', count: 4, near: 'shroomfarm', item: 'Glowcap', icon: 'mushroom', place: 'city', site: 'lantern', siteName: 'Lantern House lamp', turnIn: 'juna', cine: { done: 'riven-lamp' }, summary: 'Gather glowcaps at Glowcap Farm and light the old lamp in the Lantern House window.', reward: { xp: 170, gold: 50 },
      text: { offer: ['Before you go after them, help me with one thing. The Lantern House always kept a lamp in the window, so lost children could find their way home.', 'Loom let it go out, years ago. Bring me four glowcaps from Glowcap Farm, in the north-west. They burn all night.', 'Then we light it together, here in the market.'], progress: ['Gather four glowcaps around Glowcap Farm, then build the lamp at the Lantern House in Lanternmarket.'],
        complete: ['There. The first light in that window in twenty years.', 'Tib drew you something. A chalk moth, with a lamp. It’s for “the lady in black, so she knows the lamp is lit.” Keep it safe.'], after: ['The lamp stays lit. Always.'] } }),
    q({ id: 'riven19', title: 'Under the Nest', giver: 'juna', kind: 'key', count: 1, keys: [1], turnIn: 'ivo', summary: 'Wake the knot-rune in the tunnel under the Thornling Nest, then report to Scout Ivo.', reward: { xp: 150 },
      text: { offer: ['Needle’s map shows a tunnel right under the Thornling Nest, north of the market. A knot-rune glows down there.', 'Scout Ivo watches the nest from the Owl Watchtower, east of it. Tell him when you’re out.'], progress: ['Wake the rune at the Thornling Nest, north of the city, then report to Scout Ivo at the Owl Watchtower.'],
        complete: ['Out of the nest in one piece! The owls bet against you. Owls are terrible gamblers.', 'Two knots cut, you say? Then the third is the one humming under my tower. Has been for days.'], after: ['All clear, for now.'] } }),
    q({ id: 'riven17', title: 'The Way Home', giver: 'fox', kind: 'escort', count: 1, who: L.ada, from: 'bell', place: 'city', ambush: ['shadewolf', 'webspinner', 'shadewolf'], auto: true, summary: 'Walk Ada and the freed foundlings from the Old Bell to the Lantern House in Lanternmarket.', reward: { xp: 200, item: 'healthPotion' },
      text: { offer: ['(The children huddle behind Ada, the oldest. Six of them, and every shadow twitching.)', 'Lanternmarket is south-west of here. There’s a lamp in the window, waiting. Stay close to me.'], progress: ['Walk Ada and the children to Lanternmarket, south-west of the Bell. Keep the wolves off them.'], arrive: ['Is that the lamp? Tib said there’d be a lamp.'],
        complete: ['(The children run for the Lantern House door. Juna is already there, arms wide open, and Tib is shouting everybody’s name.)'], after: [] } }),
    ],
    // ═════════════════════════════ Chapter III · two shadows
    summit: [
    q({ id: 'riven21', title: 'Someone With My Face', giver: 'aune', kind: 'chase', count: 1, place: 'hamlet', who: L.double, escapes: true, turnIn: 'aune', cine: { caught: 'riven-double' }, summary: 'Catch the thief in Frostpine Hamlet who looks exactly like you.', reward: { xp: 160, gold: 40 },
      text: { offer: ['You! You have some nerve, walking back in here after emptying my whole cupboard of tonics!', '…Wait. Your shadow is on the left. The thief’s shadow fell the wrong way.', 'Then there are two of you, and the other one is still in the hamlet. Catch it!'], progress: ['Your double is lurking around Frostpine Hamlet. Catch it.'],
        deliver: ['(Only a smear of black smoke is left, drifting up toward the Summit.)'],
        complete: ['It melted? Into smoke? Stars keep us.', 'The mirror-shades come down from the hollow star. If one wears your face, something up there knows you.', 'And Brother Aled from Skyhold went up the mountain two days ago. He met himself up there, and he won’t come down.'], after: ['Real Riven. Shadow on the correct side. Good.'] } }),
    q({ id: 'riven22', title: 'The Monk Who Met Himself', giver: 'aune', kind: 'escort', count: 1, who: L.aled, from: 'bloom', place: 'city', ambush: ['wisp', 'frostwraith', 'wisp'], turnIn: 'orla', summary: 'Walk Brother Aled down from the Starbloom Grove to Tinker Orla in Skyhold.', reward: { xp: 170, mana: 10 },
      text: { offer: ['Brother Aled went to pray in the Starbloom Grove, far to the north. He sat down beside a man with his own face, and he hasn’t moved since.', 'Walk him to Skyhold, south-east of the tarn. Tinker Orla has been studying these mirror-shades. She’ll want to see him.'], progress: ['Find Brother Aled at the Starbloom Grove and walk him to Tinker Orla in Skyhold.'], arrive: ['Skyhold. Real towers. Real bells. And that’s really me, isn’t it? Yes. I think that’s me.'],
        complete: ['Brother Aled! Sit down, sit down. Don’t look at the shiny bits.', 'So it’s true. The shades wear your face and walk off with your way home. And you say one wore yours, Riven?'], after: ['Tink tink. Don’t mind me.'] } }),
    q({ id: 'riven23', title: 'A Light That Shows Faces', giver: 'orla', kind: 'build', count: 4, near: 'observatory', item: 'Old lens', icon: 'gem', place: 'altar', site: 'lantern', siteName: 'True-light lantern', turnIn: 'orla', summary: 'Gather old lenses at the Old Observatory and build a true-light lantern on the Star Altar.', reward: { xp: 190, gold: 60 },
      text: { offer: ['Here’s my idea. A mirror-shade can wear any face but its own, because it hasn’t got one.', 'Give me a lantern that only shows true faces, and the shades will have to show nothing. And nothing is very easy to hit.', 'Old Vale’s observatory, far to the south-west, has a heap of cracked lenses. Bring me four, then build the lantern on the Star Altar, east of the city.'], progress: ['Gather four old lenses around the Old Observatory, then build the lantern at the Star Altar, east of Skyhold.'],
        complete: ['It works! I saw it from here: a great white beam, straight down into the Void Rift.', 'And down in the Rift, among all the stolen faces, one real one. An old man with a beard, in chains.'], after: ['Best thing I ever built. Don’t tell the monks, they think it was a prayer.'] } }),
    q({ id: 'riven24', title: 'What Orrin Paid', giver: 'orla', kind: 'talk', count: 1, to: 'orrin', cine: { done: 'riven-orrin' }, summary: 'Hear Master Orrin out in Skyhold.', reward: { xp: 120 },
      text: { offer: ['Go and see him. He looks like a man who’s been carrying a stone up a mountain for twenty years.'], progress: ['Master Orrin rests on the west side of Skyhold.'], complete: [], after: [],
        deliver: ['The Lantern House. Matron Loom. Yes. I paid her for Sable. I thought paying was the same as caring.', 'Her shadow hurt her. I called the star down to burn it out of her, and I tore the sky. Umbra slid in through the tear.', 'Now it wears faces in the hollow star, and whispers to her that the dark will make the hurting stop. It will not. It only wants out.'] },
      choice: {
        a: { label: 'You bought her, like they bought me', lines: ['Yes. And I have been paying for it ever since.', 'I cannot ask you to forgive me. Only to reach her. She will not listen to me. She might listen to you.'], reward: { mana: 12 } },
        b: { label: 'You tried. So did the Hushed, in their way', lines: ['…That is kinder than I deserve.', 'She will not listen to me. She might listen to you. You carry the same shadow. You know what it costs.'], reward: { regen: .5 } },
      } }),
    q({ id: 'riven26', title: 'Tag, You’re It', giver: 'fox', kind: 'chase', count: 1, place: 'spire', who: L.sable, auto: true, summary: 'Catch Sable at the Broken Spire, the way you always did.', reward: { xp: 180 },
      text: { offer: ['Sable. Right there on the broken stones. And she’s running.', 'She always ran. I always caught her. Let’s see if that’s still true.'], progress: ['Catch Sable around the Broken Spire.'],
        deliver: ['You still cheat. You shadowstep on the corners.', '…Hello, Riven.'], complete: [], after: [] } }),
    q({ id: 'riven4', title: 'Sable’s Question', giver: 'sable', kind: 'talk', count: 1, to: 'sable', summary: 'Answer Sable’s question.', reward: { xp: 200 },
      text: { offer: ['I knew it was you the moment I saw you fight. You still move like a shadow that’s late for something.', 'You cut my web. Of course you did. I wrote your name into it so nobody else could.', 'Before Umbra calls me back to the star, I need to ask you one thing. Only you would know.'], progress: ['Sable is waiting at the Broken Spire.'], complete: [], after: [],
        deliver: ['The shadow we were born with. Did it ever stop hurting? For you?'] },
      choice: {
        a: { label: 'It never stopped. It just stopped choosing for me', lines: ['It doesn’t choose for you. You choose.', '…Then maybe it doesn’t get to choose for me either. I’d forgotten that was allowed.'], reward: { regen: .6 } },
        b: { label: 'It got quieter when I found people', lines: ['People worth standing in front of. A boy with a lamp. A thief who said no. That grumpy captain.', 'Yes, I watched. I always watched. I think… I would like some of those, Riven.'], reward: { mana: 12 } },
      } }),
    q({ id: 'riven25', title: 'Door, Eye, Moon', giver: 'sable', kind: 'activate', count: 3, near: 'spire', switches: 'rune', order: ['Door', 'Eye', 'Moon'], ordered: true, auto: true, cine: { done: 'riven-two-shadows' }, summary: 'Touch the runes around the Broken Spire in the old game’s order, backwards.', reward: { xp: 200, gold: 50 },
      text: { offer: ['Nullface wears my face in the star. It wore yours too, didn’t it? It wants both of us.', 'There’s a way into the star that Umbra doesn’t know. Our game, backwards: door, eye, moon. Forwards, it lets the shadows in. Backwards, it lets us out.', 'I carved the stones around the Spire years ago, just in case. Touch them for me. My hands are shaking.'], progress: ['Touch the runes around the Broken Spire: Door, then Eye, then Moon.'],
        complete: ['(The last rune flares. Behind you, Sable lets out a breath she seems to have been holding for years.)'], after: [] } }),
    ],
    // ═════════════════════════════ Chapter IV · the broker's network
    ember: [
    q({ id: 'riven5', title: 'The Ashen Broker', giver: 'hessa', kind: 'chase', count: 1, place: 'kiln', escapes: true, turnIn: 'hessa', who: L.broker, cine: { caught: 'riven-broker' }, summary: 'Catch the ash-masked broker buying up the kiln-fire in Kilnhollow.', reward: { xp: 240, gold: 90 },
      text: { offer: ['You’re the one Ashka sent? Good. A masked stranger has been buying up my kiln-fire, and paying in black feathers.', 'Black feathers, Riven. You know what those mean better than I do. He’s in the hollow right now. Catch him!'], progress: ['The broker lurks around Kilnhollow. Run him down.'],
        deliver: ['“Run home, little shadow. I will be waiting at the forge.”'],
        complete: ['A mask full of ash? Then Umbra has hands in every town.', 'The ash blew north-east, toward Brasshaven. That’s where the buying and selling is done.'], after: ['No more feathers in Kilnhollow.'] } }),
    q({ id: 'riven29', title: 'Where the Ash Blows', giver: 'hessa', kind: 'trail', count: 4, near: 'kiln', place: 'city', turnIn: 'riven-magpie', summary: 'Follow the broker’s ash from Kilnhollow to Brasshaven.', reward: { xp: 170, regen: .5 },
      clues: ['A smudge of grey ash on a kiln stone, in the shape of a hand.', 'Ash prints on the road, and a black feather that hasn’t crumbled yet.', 'A brass token dropped in the dust: “Orsolo, weigher. Brasshaven market.”', 'Ash all over a stall by the Brasshaven gate. A very familiar stall. It sells scarves.'],
      text: { offer: ['Follow the ash, Riven. A thing made of ash always leaves some behind.'], progress: ['Follow the trail of ash north-east from Kilnhollow to Brasshaven.'],
        complete: ['Don’t look at me like that. Somebody had to come east and keep you out of trouble.', 'Also I heard there were no hats in the Wastes. A market is a market.', 'That ash? The Broker. He’s bought half of Brasshaven with feathers, and his weigher is Orsolo, by the brass scales.'], after: ['Scarves! Fine scarves!'] } }),
    q({ id: 'riven30', title: 'The Weigher’s Scales', giver: 'riven-magpie', kind: 'talk', count: 1, to: 'riven-orsolo', summary: 'Get the truth out of Orsolo the weigher in the Brasshaven market.', reward: { xp: 120 },
      text: { offer: ['Orsolo weighs the Broker’s feathers like coin and hands them out to anyone who’ll sell fire.', 'He’s a coward, not a villain. Cowards talk. Go and make him.'], progress: ['Orsolo keeps his brass scales in the Brasshaven market.'], complete: [], after: [],
        deliver: ['Put that dagger away! Please! I only weigh things!', 'The Broker brings feathers, I weigh them, and people sell him fire. Lamp oil, kiln-coal… ember cores.', 'He hid the cores where nobody honest goes: the Scorpion Burrows, the Obsidian Maze, the Old Foundry. When he holds all three, he goes to the Dawn Forge.'] },
      choice: {
        a: { label: 'Scare him straight', lines: ['Yes! Straight! Very straight! I will never weigh another feather as long as I live!', '…Your friend with the scarves said you were nicer than this.'], reward: { gold: 50 } },
        b: { label: 'Offer him a way out', lines: ['A way out? For me? …I didn’t know that was allowed.', 'Then I’ll tell Captain Rusk everything. He’ll be cross. He is always cross.'], reward: { regen: .4 } },
      } }),
    q({ id: 'riven35', title: 'Smoke for Pay', giver: 'rusk', kind: 'collect', count: 5, near: 'city', item: 'Feather-coin', icon: 'feather', turnIn: 'rusk', summary: 'Collect the Broker’s feather-coins around Brasshaven and show Captain Rusk what they are worth.', reward: { xp: 140, gold: 40 },
      text: { offer: ['Orsolo’s been talking. About feathers, and a Broker, and a thief from the west who scares weighers.', 'Half my market has been paid in black feathers, and nobody believes me that they’re worthless.', 'Collect five of them from around the market and bring them here. In front of everyone. Let’s see what they’re worth.'], progress: ['Collect five feather-coins around the Brasshaven market, then bring them to Captain Rusk.'],
        complete: ['(The feathers crumble to smoke in Rusk’s hand, in front of half the market.)', 'There. Worth exactly nothing. Nobody sells that Broker so much as a candle from today.', 'Now: the cores. The Scorpion Burrows are south-west of the city. Start there.'], after: ['Nobody takes feathers in my city.'] } }),
    q({ id: 'riven32', title: 'A Chalk Moth for Sable', giver: 'fox', kind: 'deliver', count: 1, to: 'riven-sable', item: 'Tib’s chalk moth', summary: 'Bring Tib’s drawing to Sable at Ashfall Watch.', reward: { xp: 110, mana: 10 },
      text: { offer: ['Sable is up at Ashfall Watch, north of the city, reading the smoke with the seer.', 'I’ve carried Tib’s chalk moth since Whisperroot. I kept waiting for the right moment. There is never a right moment.'], progress: ['Bring Tib’s drawing to Sable at Ashfall Watch, north of Brasshaven.'], complete: [], after: [],
        deliver: ['A chalk moth. With a lamp. “For the lady in black, so she knows the lamp is lit.”', 'I put out every light I could reach, Riven. And a little boy I scared half to death lit one for me.', '…I’m keeping this. Forever. Don’t look at me. It’s the smoke.'] } }),
    q({ id: 'riven31', title: 'Clear the Smoke', giver: 'riven-sable', kind: 'activate', count: 3, near: 'foundry', switches: 'vent', order: ['Ash vent', 'Cinder vent', 'Smoke vent'], auto: true, summary: 'Open the three old vents around the Old Foundry to let the Broker’s smoke out.', reward: { xp: 180, gold: 60 },
      text: { offer: ['The Broker filled the Old Foundry with his smoke, so nothing honest can breathe in there.', 'Three old vents stand around it. Open them, and the smoke has somewhere to go. The foundry is south-east of here.'], progress: ['Open the three vents around the Old Foundry, south-east of the watch.'],
        complete: ['(The vents roar. Black smoke pours out of the foundry and blows away over the dunes, and the last core glows inside.)'], after: [] } }),
    q({ id: 'riven34', title: 'Walk With Me', giver: 'riven-sable', kind: 'escort', count: 1, who: L.sable, from: 'watch', place: 'forge', ambush: ['emberImp', 'ashScorpion', 'emberImp'], auto: true, summary: 'Walk with Sable to the Dawn Forge and keep the imps off her.', reward: { xp: 220, hearts: 1 },
      text: { offer: ['I’m coming with you to the forge. Don’t argue. You’ll lose.', 'Umbra wants to catch one of us alone. So it doesn’t get to.'], progress: ['Walk with Sable to the Dawn Forge in the far north-east. Keep the imps off her.'], arrive: ['There it is. Cold as a grave. Let’s give it a heartbeat.'],
        complete: ['(Sable sits down on the forge steps to catch her breath. She doesn’t let go of the chalk moth.)'], after: [] } }),
    ],
  },
  reuse: {
    // ═════════════════════════════ Chapter I
    meadow: {
      m1: { title: 'Crumbs and Rumours', giver: 'tom', to: 'brannoc', summary: 'Go and see Captain Brannoc in Goldenhearth before he comes to see you.',
        text: { offer: ['You look like someone who slept on my step. Because you did. Here, a honey bun. No charge.', 'Have you heard? Somebody robbed the Beacon last night. Pried the sun-crystals right out of it.', 'Captain Brannoc has been stopping every hood in the city since dawn. You’re wearing a hood. Just saying.'],
        progress: ['Captain Brannoc is by the barracks, on the north side of the city.'], after: ['Honey buns! Still warm!'], complete: [],
        deliver: ['A hood. Today, everyone in a hood is either a thief or cold. Which are you?', 'Somebody pried the three sun-crystals out of the Beacon at midnight. Clean work. Hushed work.', 'And you walked right up to me. So either you’re innocent, or you’ve come to deal.', 'Here’s the deal. Bring me the crystals and I’ll forget your face. Cross me, and I won’t.'] } },
      m2: { title: 'Cover of Gloom', giver: 'fox', turnIn: 'rowan', summary: 'Hold Sunpetal’s barricade against the gloom sent to cover the Hushed.', reward: { xp: 130, hearts: 1 },
        text: { offer: ['“The gloom covers Sunpetal tonight.” It isn’t an accident. It’s cover. While a village fights, the Hushed rob it.', 'Sunpetal is far to the west, north-west of the city. If I run, I’ll make the barricade by dusk.'], progress: ['Stay by Sunpetal’s barricade and stop the gloom before it reaches it.'],
          complete: ['A stranger in a hood, holding our barricade. I didn’t expect that.', 'But while we fought, someone went through the houses. Healer Maren is in a terrible state. Would you see her?'], after: ['You’re welcome in Sunpetal, stranger.'] } },
      m5: { title: 'The Drowned Ledger', giver: 'magpie', item: 'Ledger page', icon: 'letter', summary: 'Fish the Hushed’s ledger pages out of the reeds at Mirror Lake.',
        text: { offer: ['Ilse told you about books, did she? Fine. Yes. I kept the ledger.', 'The night Corvane paid, I threw it in Mirror Lake. It wouldn’t burn. The pages wouldn’t catch.', 'They’ll have washed into the reeds by now. Four pages. The drops are all written down. Go, before I change my mind.'], progress: ['Mirror Lake lies south-west of the city. Look for ledger pages along the shore.'],
          complete: ['The Stone Garden, you’ve done. Gloom Hollow is the second. “The Hollow. Wick carries.”', 'Wick. He’s the youngest. Twelve. He wanted out, like you did.', 'The last page is torn off. Whoever has the third drop didn’t want me to know. Go and find Wick first. Please.'], after: ['Hats! Fine hats! Er, hello.'] } },
      m7: { title: 'Down the Drop', giver: 'magpie', turnIn: 'bram', summary: 'Take the sun-crystal from the drop in Gloom Hollow, then see Farmer Bram.',
        text: { offer: ['Gloom Hollow, south-west, past Farmer Bram’s fields. It’s thick with gloom. That’s why we used it.', 'Bram’s the nearest honest man. If Wick went past, Bram saw him.'], progress: ['Gloom Hollow lies south of Millbrook Farm. Then see Farmer Bram.'],
          complete: ['Out of the Hollow, with a glowing rock? You’re either brave or daft.', 'Listen. Last night the gloom dragged a lad east past my fence. He was shouting “I won’t! I won’t carry it!” Took him toward Rotwood Den.'], after: ['Mind my turnips on the way out.'] } },
      m6: { title: 'The Boy Who Said No', giver: 'bram', turnIn: 'brannoc', captive: L.wick, summary: 'Free Wick from Rotwood Den and walk him to Captain Brannoc in Goldenhearth.', reward: { xp: 150, hearts: 1 },
        text: { offer: ['Rotwood Den is far to the east of the city. Nasty place. Boars, and worse.', 'If that lad’s still alive, he’s in a cage there. Somebody ought to bring him home. …Looks like it’s you.'], progress: ['Rotwood Den lies far to the east. Break the guards, open the cage, and bring Wick to Captain Brannoc in Goldenhearth.'], arrive: ['Is that the guard captain? Riven. Riven, he’s going to lock me up.'],
          deliver: ['Riven? You came back for me? Nobody comes back.', 'Corvane wanted me to carry the Hollow crystal to him. I said no. So he sent the gloom.', 'The rest of the crew are up on Shepherd’s Hill with the last one, waiting for the dark of the moon. They’re scared stiff.'],
          complete: ['A Hushed kid, walked in by a Hushed… something. Right to my barracks.', 'He’s twelve, he’s shaking, and he says he told that shade no. To its face. If it has one.', 'He’s your catch, thief. What do I do with him?'], after: ['The walls hold. So, it turns out, do some thieves.'] },
        choice: {
          a: { label: 'Vouch for him', lines: ['Your word. The word of a thief.', '…Fine. He sweeps the barracks until he’s taller than me. And you owe me, Riven. Now go and get my last crystal.'], reward: { mana: 10 } },
          b: { label: 'Send him to Baker Tom', lines: ['Tom? The baker? …Actually, Tom would love that. He’s always saying he needs quick hands.', 'Go on, lad. Honey buns don’t knead themselves. And you, thief: my last crystal.'], reward: { gold: 40, item: 'healthPotion' } },
        } },
      m11: { title: 'Wool Over Their Eyes', summary: 'Drive five of Odo’s panicked sheep back into their pen.',
        text: { offer: ['Was that you? The lamps? My whole flock went down the hill like a woolly avalanche!', 'Before you go poking about for whatever those hooded folk left behind, you’ll help me pen them. Five sheep.', 'Walk up behind one and it trots away from you. Gently. They’re very upset.'], progress: ['Walk behind a sheep to drive it into the pen. Slowly does it.'],
          complete: ['Five home, and not one of them grateful.', 'Now. Those hooded folk dug a hole by my signal stones before they ran. I’d look there.'], after: ['Baa. Sorry. Habit.'] } },
      m9: { title: 'The Last Drop', cine: { done: 'riven-corvane' }, summary: 'Find the last sun-crystal the Hushed buried on Shepherd’s Hill.',
        text: { offer: ['The hole is up by my signal stones, on top of the hill. I didn’t touch it. It hums.', 'And lad… the moon goes dark tonight. Something has been circling the Beacon Rise since dusk, with far too many feathers.'], progress: ['Search the hilltop for the last sun-crystal.'],
          complete: ['All three! I’m an old shepherd, but even I know what a thief does next. He runs.', '…You’re not running, are you? No. You’re going to the Rise.'], after: ['Mind the feathers.'] } },
      m10: { title: 'The Feathered Shade', giver: 'fox', summary: 'Defeat Corvane at the Beacon Rise and put the sun-crystals back in the Beacon.', cine: { done: 'beacon-lit' },
        text: { offer: ['(The moon goes dark. Far to the south-east, on the Beacon Rise, a masked shade spreads its feathered cloak and waits.)', 'Corvane came to collect. He blinks, he strikes from the dark, he throws shadow. So do I.', 'Umbra takes the shape of what you fear. I always feared the buyer. Let’s see what a buyer does when nobody sells.'], progress: ['The Beacon Rise lies far to the south-east.'], complete: [], after: ['The Beacon shines, and nobody owns it.'] } },
      m12: { title: 'A Bridge for a Thief', summary: 'Gather bridge timber around Willowmere, then rebuild the Gloomwater Bridge with Holt.',
        text: { offer: ['You lit the Beacon? The one they said was robbed? Funny old week.', 'The Gloomwater Bridge fell into the river the night the star fell. Nobody gets east to Whisperroot without her.', 'Five good timbers from around Willowmere, north-west of here, and we build her at the gate. Honest work. You’ll hate it.'], progress: ['Bring five bridge timbers from around Willowmere, then build at the Eastern Gate.'],
          complete: ['There. Straight and true, and I only swore twice.', 'A hat-seller sent word for you, by the way. Said the Hushed run their goods east under Whisperroot, through the spiders’ tunnels.'], after: ['Mind the third plank. It squeaks.'] } },
    },
    // ═════════════════════════════ Chapter II
    woods: {
      m1: { title: 'Under Whisperroot', summary: 'Go through the Eastern Gate and find Mosskeeper Oda.',
        text: { offer: ['(The road east dives under trees so old they seem to be listening.)', 'The Hushed run their goods through tunnels under these woods. Whoever keeps the camp in there will know where the ground is hollow.'], progress: ['Follow the road into the woods, to the Mosskeeper’s Camp.'], complete: [], after: [],
          deliver: ['A stranger from the meadow, with the Beacon lit behind him. The roots felt it.', 'Hollow ground? Forester Birch at Glowcap Farm swears he hears barrels rolling under his mushrooms at night.', 'And worse. Children are going missing from Lanternmarket. The Bell has gone silent, and something spins webs across the roads.'] } },
      m7: { title: 'Barrels Under the Glowcaps', giver: 'guide', summary: 'Wake the root rune at the tunnel mouth under Glowcap Farm, then find Forester Birch.',
        text: { offer: ['Glowcap Farm lies north of here. If there’s a tunnel, it’ll open near the old root rune that glows at the farm’s edge.', 'Tell Birch I sent you. He’ll grumble. He always grumbles.'], progress: ['Glowcap Farm is north of the camp. Wake the root rune there, then find Forester Birch.'],
          complete: ['A root rune, glowing like that, under my farm? Well, that explains the humming.', 'And the barrels? There’s a runner down there right now. I heard him giggling. Nobody giggles in a tunnel unless they’re up to something.'], after: ['Timber, mushrooms and thieves. What a week.'] } },
      m2: { title: 'Wolves on the Lantern Road', giver: 'forester', turnIn: 'juna', summary: 'Clear shadewolves off the road to Lanternmarket, then find Herbalist Juna there.',
        text: { offer: ['The road to Lanternmarket is crawling with shadewolves since the Bell went quiet.', 'Clear six of them on your way, and give Juna in the market my regards. She patched my thumb once.'], progress: ['Shadewolves circle before they lunge. Keep moving, and head east to Lanternmarket.'],
          complete: ['Birch sent you? And you came through the wolves for a stranger’s thumb? Sit down, sit down.', 'I’m Juna. I keep the old Lantern House. It was a foundling house, once. Now it’s just me, and whatever children the woods leave on my step.'], after: ['Mind the lanterns. Mind the children.'] } },
      m9: { title: 'The Moon-Night Lanterns', giver: 'nana', cine: { ready: 'glade-memory' }, summary: 'Light the four old lanterns of the Moonlit Glade, then tell Nana Bristle what you saw.',
        text: { offer: ['Before you go charging after Loom: the Moonlit Glade, north-east of here. Loom took you all there on moon-nights to light the old lanterns.', 'Light them again. The glade remembers faces. It might remember yours.'], progress: ['Light the four lanterns around the Moonlit Glade, north-east of Bellhollow, then come back to Nana.'],
          complete: ['Two little ones with lanterns, making up rules. That was you and Sable. Always the two of you.', 'She carved her runes on every stone she passed. When she ran from Orrin, she carved them all over the Root Ruins, north of the glade. Go and read them. She’d want you to.'], after: ['Eat something, dear. You’re all shadow.'] } },
      m6: { title: 'The Matron’s Cage', giver: 'fox', turnIn: 'thessaly', captive: L.loom, summary: 'Free Matron Loom from the spiders in the Root Ruins and bring her to Warden Thessaly in Lanternmarket.', reward: { xp: 150, hearts: 1 },
        text: { offer: ['(Somewhere deeper in the ruins, spiders click. And someone is calling for help, in a voice you haven’t heard since you were small.)', 'Matron Loom. Caught by her own spiders.', '…I could leave her. Nobody would blame me. Everybody would blame me. I would blame me.'], progress: ['Break the spiders guarding Loom’s cage in the Root Ruins, then walk her to Warden Thessaly in Lanternmarket.'], arrive: ['The watch? You’re taking me to the watch?'],
          deliver: ['Riven. Look at you, all grown up. Worth every coin the Hushed paid.', 'The Silkmother wanted more children. I had none left to give. So she took me instead.', 'Get me out of here, and I’ll tell you where they are. Every one of them.'],
          complete: ['Matron Loom. The watch has wanted her for years.', 'She says the Silkmother keeps the children in the web around the Old Bell, and the web is knotted to three root runes. Cut the knots and the whole thing comes loose.', 'She says you’ve already cut one, at Glowcap Farm. But you caught her, Riven. So you choose what happens to her.'], after: ['The watch owes you, thief.'] },
        choice: {
          a: { label: 'Let the watch judge her', lines: ['Then she’ll answer for every child, in front of the whole market.', 'That isn’t revenge. That’s the right thing. It rarely feels like much, does it?'], reward: { regen: .4 } },
          b: { label: 'Let her walk away', lines: ['Soft, for a thief. But it’s your debt, not mine. Go, Loom, and never come back.', '(Loom stares at you as if nobody has ever let her off anything. Then she goes.)'], reward: { mana: 10 } },
        } },
      m12: { title: 'The Last Knot', summary: 'Wake the root rune humming under the Owl Watchtower.',
        text: { offer: ['It hums under the tower. Every night a bit louder.', 'Find it and wake it. I’d do it myself, but I’m scared of the dark. Don’t tell the owls.'], progress: ['Search around the Owl Watchtower for the last root rune.'],
          complete: ['All three! Listen. The whole web is trembling, all the way to the Bell.', 'And something over there is waking up. Something with eight legs, and a crown.'], after: ['The owls owe me money.'] } },
      m15: { title: 'Silkmother Vesh', giver: 'ivo', summary: 'Defeat Silkmother Vesh and ring the Ancient Root Bell.', cine: { done: 'bell-rung' },
        text: { offer: ['The Old Bell hangs in the far north-east, wrapped in silk and runes.', 'They say the Silkmother spits webs and sends roots racing through the ground. Keep moving, and cut yourself free.', 'And Riven… the children are in that web. Aim carefully.'], progress: ['The Old Bell stands in the far north-east.'], complete: [], after: ['The Bell rings, and the owls finally shut up.'] } },
      m16: { title: 'The Lantern House Holds', ward: 'The Lantern House gate', summary: 'Hold Lanternmarket’s gate, and the Lantern House behind it, against the shadow.',
        text: { offer: ['You brought them home, and the shadow followed you. Every wolf and spinner in the woods is coming for the market.', 'My watch holds the walls. You hold the gate. The Lantern House is right behind it.'], progress: ['Stand at the gate and stop them before they reach it.'],
          complete: ['The gate holds. The lamp is still lit. Not one child taken.', 'But the Silkmother’s poison lingers: a wall of black thorns has grown across the Eastern Gate. Light the three Bell-lanterns beside it.'], after: ['Every lantern lit, and one in a window.'] } },
      m17: { title: 'Through the Thorns', summary: 'Light the three Bell-lanterns at the Eastern Gate to wither the thorn wall.',
        text: { offer: ['Take this flame. It was lit from the Lantern House lamp.', 'Light the three Bell-lanterns by the Eastern Gate, and the thorns will remember they were only ever roots.'], progress: ['Light the three Bell-lanterns by the Eastern Gate.'],
          complete: ['(The thorn wall shivers and crumbles. Far behind you, the Bell rings once more, and a lamp burns in a window.)'], after: [] } },
    },
    // ═════════════════════════════ Chapter III
    summit: {
      m1: { title: 'Faces on the Mountain', summary: 'Go through the Eastern Gate and find Sky-warden Ilsa.',
        text: { offer: ['(An icy wind howls through the Eastern Gate. Somewhere up there, a star has gone black.)', 'Sable ran up the mountain, and her runes still say my name. I’m done waiting for her to come down.'], progress: ['Take the road east through the gate, to Warden’s Lookout.'], complete: [], after: [],
          deliver: ['Another climber. You’d better not be one with two faces.', 'Since the star fell hollow, travellers meet themselves on the high roads. A face just like theirs, smiling wrong. Then they’re lost.', 'And a girl in a black cloak sits at the Broken Spire, far to the east. Nobody dares go near her. Healer Aune in Frostpine Hamlet has had a thief, if you’re looking for trouble.'] } },
      m10: { title: 'The Only Real Face', giver: 'orla', summary: 'Free the old man in the Void Rift and bring him to Tinker Orla in Skyhold.',
        text: { offer: ['The Void Rift is south-east of the altar. Whoever that old man is, the shades are keeping him for something.', 'Bring him out, Riven. Follow the lantern’s beam.'], progress: ['The Void Rift lies south-east. Break the guards, open the cage, and bring him to Skyhold.'], arrive: ['Skyhold. I built my first telescope on those walls. I was so sure of everything, then.'],
          deliver: ['You… are not Sable. But you have her shadow. The very same shadow.', 'I am Orrin. I did a terrible thing to someone you love. Get me to Skyhold, and I will tell you all of it. My legs are slow.'],
          complete: ['Master Orrin? THE Master Orrin? The one who pulled down the star?', 'He’s resting on the west side of the city. He keeps asking for “the boy with Sable’s shadow”.'], after: ['I’m going to need a bigger lantern.'] } },
      m12: { title: 'Fire on the Crag', summary: 'Take the star shard from Frostfang Crag.',
        text: { offer: ['Three shards fell when the star broke. One lies on Frostfang Crag, north-east of the city, among the golems.', 'Bring it here. With all three, the hollow shell can be cracked, and Nullface with it.'], progress: ['Frostfang Crag is north-east of Skyhold.'],
          complete: ['One shard. Warm as a heartbeat.', 'I cannot see where the other two fell. The Tarn can. Mirrorsky Tarn, north-west of the city.'], after: ['Thank you, Riven. For all of it.'] } },
      m5: { title: 'True Water', giver: 'orrin', turnIn: 'guide', cine: { ready: 'tarn-vision' }, summary: 'Look into Mirrorsky Tarn, then tell Sky-warden Ilsa what you saw.',
        text: { offer: ['The Tarn reflects what the sky remembers, and it cannot wear a false face.', 'Look into it for me. Then tell Ilsa what you see; her lookout is on your way.'], progress: ['Mirrorsky Tarn lies north-west of Skyhold. Then Ilsa at Warden’s Lookout, further west.'],
          complete: ['Your face, then hers? That’s more than most people get from that water.', 'And the lights: one in Crystal Hollow, north of my lookout. The last at the Broken Spire, where your girl in black sits.'], after: ['The sky is a map, if you’re brave enough to read it.'] } },
      m6: { title: 'Cold Light in the Hollow', giver: 'guide', turnIn: 'dov', summary: 'Take the star shard from Crystal Hollow, then find Quartermaster Dov at Silver Pass.',
        text: { offer: ['Crystal Hollow is north of my lookout. The shard hums. You’ll hear it before you see it.', 'Then go east to Quartermaster Dov at Silver Pass. The road to the Spire is his.'], progress: ['Crystal Hollow is north of the lookout. Then Silver Pass Camp, far to the east.'],
          complete: ['A shard, and the one who carries it wants the Spire road? Everybody wants the Spire road tonight.', 'The void has been throwing itself at my barricade since dusk. With faces. My own soldiers’ faces.'], after: ['Halt! Oh. It’s the real you.'] } },
      m14: { title: 'The Pass at Night', summary: 'Hold the Silver Pass barricade against three waves from the void.',
        text: { offer: ['Here they come again. Wisps, wraiths, and things wearing my soldiers’ faces.', 'Hold the barricade with us. Three waves, and the Spire road is yours.'], progress: ['Stand by the barricade and break every wave.'],
          complete: ['The pass holds! And every face that came over that ridge was a fake. Good riddance.', 'The Spire is east of here. She’s still up there. She hasn’t moved in three days.'], after: ['The pass holds.'] } },
      m15: { title: 'The Last Shard', auto: true, summary: 'Take the last star shard from the Broken Spire.',
        text: { offer: ['The last shard is at the Broken Spire, east of the pass.', 'And so is she. Go carefully. They say she moves like smoke.'], progress: ['The Broken Spire lies east of the pass.'],
          complete: ['(The third shard is warm in your hand. Behind you, someone laughs: a laugh you haven’t heard since you were ten.)'], after: [] } },
      m19: { title: 'Nullface', giver: 'sable', summary: 'Defeat Nullface and return the shards to the Star Cradle.', cine: { done: 'star-rises' },
        text: { offer: ['The Star Cradle is north-east of here, at the top of the world. Nullface waits inside the hollow star.', 'It has no face of its own. It will wear yours first, then mine. It blinks, it strikes from behind, it rains the sky down. Don’t stop, whatever it looks like.', 'I’ll be right behind you. I promised once, remember? I always find you.'], progress: ['The Star Cradle is in the far north-east.'], complete: [], after: ['The star is home. So are we, nearly.'] } },
      m20: { title: 'Two Shadows, One Door', who: L.sable, summary: 'Walk Sable from Skyhold to the Eastern Gate, where the black ice seal waits.',
        text: { offer: ['She came to me, Riven. She let me say I was sorry. I did not deserve that.', 'Umbra sealed the eastern pass with black ice. It knows my starlight. It does not know two shadows that have stopped being afraid.', 'Walk her to the Eastern Gate. The wraiths will try to stop you. I will follow, when my old legs let me.'], progress: ['Walk Sable to the Eastern Gate and keep the wraiths off her.'], arrive: ['There’s the ice. It’s humming my name. Let it hum.'],
          complete: ['(Sable takes your hand. Two shadows stretch across the black ice.)'], after: [] } },
    },
    // ═════════════════════════════ Chapter IV
    ember: {
      m1: { title: 'Ash on the East Wind', summary: 'Follow Umbra’s smoke through the Eastern Gate and find Captain Ashka.',
        text: { offer: ['(A thread of black smoke crawls east over the last ridge. Sable walks beside you, very quiet.)', 'Umbra ran into the Ember Wastes. Captain Ashka keeps the outpost there. Let’s see what she’s seen.'], progress: ['Take the road east through the gate, to Emberwatch Outpost.'], complete: [], after: [],
          deliver: ['Two of you, in black, out of the smoke? You’ll forgive me if I keep hold of my spear.', 'Something black fell out of the east wind. Since then: imps every night, the Dawn Forge cold, and a masked buyer paying for fire with feathers.', 'Your friend can go up to Ashfall Watch. The seer will want to meet her. You, stranger, can help me hold this gate.'] } },
      m2: { title: 'Sparks at the Gate', summary: 'Hold the gate of Emberwatch Outpost against three waves of imps.',
        text: { offer: ['Here they come. Imps, out of the smoke, same as every night. They hover out of reach and lob fire.', 'Help us hold the outpost gate!'], progress: ['Stand by the outpost gate. Imps keep their distance, so close in fast.'],
          complete: ['The outpost stands. You fight like someone who’s done it in the dark.', 'Kiln-mother Hessa in Kilnhollow, south-east of here, has been asking about feathers. Go and see her.'], after: ['Watch the sky for sparks.'] } },
      m8: { title: 'The Burrow Drop', giver: 'rusk', summary: 'Take the first of the Broker’s hidden ember cores from the Scorpion Burrows.',
        text: { offer: ['The Burrows are south-west of the city, and the scorpions don’t take bribes. Not even feathers.', 'When the sand bulges, move. Bring me that core.'], progress: ['The Scorpion Burrows lie south-west of Brasshaven.'],
          complete: ['A core! Hot enough to cook on. Don’t cook on it.', 'Bad news, too. Zara’s hunters found a hooded boy caged at the Salt Caravan Camp, south-east. He keeps saying “Riven”.'], after: ['One core down. I’m bad at counting when I’m cross.'] } },
      m7: { title: 'Needle Says No', giver: 'rusk', turnIn: 'riven-magpie', captive: L.needle, summary: 'Free Needle at the Salt Caravan Camp and bring him to Magpie in Brasshaven.',
        text: { offer: ['The Salt Caravan Camp is south-east of the city. Scorpions and imps are thick around it.', 'Get the boy out. And if he’s another one of your thieves, I don’t want to know.'], progress: ['Break the guards at the Salt Caravan Camp, free the hooded boy, and bring him to Magpie in Brasshaven.'], arrive: ['Magpie? Magpie! Don’t be cross. Be a little bit cross.'],
          deliver: ['Riven! You came for me? I ran away from you twice!', 'The Broker wanted me to carry a core to the Foundry. I said no. First time I ever said no to a job.', 'I got that from you, you know. Walking out. It’s catching.'],
          complete: ['Needle said no? Our Needle?', 'You’ve ruined the whole guild, Riven. Every last one of them saying no to jobs. I’ve never been prouder.', 'Now, the Obsidian Maze, north-west of the outpost. The Broker’s second core is in there.'], after: ['Needle is selling scarves now. Badly.'] } },
      m6: { title: 'Glass Knives', giver: 'riven-magpie', turnIn: 'tovan', summary: 'Take the ember core from the Obsidian Maze, then bring it to Forgemaster Tovan.',
        text: { offer: ['The Obsidian Maze, far to the north-west. Walls like knives. You’ll love it.', 'Take the core to Forgemaster Tovan after. He’s the one who can put it back where it belongs.'], progress: ['The Obsidian Maze lies far to the north-west. Then Forgemaster Tovan in Brasshaven.'],
          complete: ['Two cores, carried in by a thief. The forge won’t mind. Fire doesn’t care whose hands.', 'Pyrrhus kept the Dawn Forge once, until the shadow got into him. The Broker wears his ash now, like a coat.', 'The last core is in the Old Foundry, north-east. But the foundry’s choked with smoke. Ilyana at Ashfall Watch might know why. So might your friend in black.'], after: ['The anvils are ringing again.'] } },
      m10: { title: 'Out of the Smoke', giver: 'fox', summary: 'Take the last ember core from the Old Foundry, then find Ember-seer Ilyana at Ashfall Watch.',
        text: { offer: ['The smoke is gone. The last core is somewhere in the Old Foundry.', 'Then back to Ashfall Watch. Ilyana will know what comes next. So will Sable.'], progress: ['Search the Old Foundry for the last ember core. Then Ashfall Watch, north of the city.'],
          complete: ['Three cores. The flames have been saying your name for days, thief. It is very distracting.', 'The Broker waits at the Dawn Forge, in the far north-east. It won’t take the cores from you. It wants to take you.'], after: ['The flames speak of you.'] } },
      m15: { title: 'A Breath for the Forge', giver: 'fox', cine: { done: 'pyrrhus-wakes' }, summary: 'Gather brass gears at the Old Foundry, then rebuild the Great Bellows at the Dawn Forge.',
        text: { offer: ['Three cores aren’t enough. A forge has to breathe, and its Great Bellows are smashed.', 'The Old Foundry is full of brass gears. Four of them, and I can rebuild the bellows here.', 'When the forge breathes, the Broker will come. Good. I’m tired of chasing it.'], progress: ['Gather four brass gears at the Old Foundry, then rebuild the Great Bellows at the Dawn Forge.'], complete: [], after: [] } },
      m12: { title: 'The Ashen Broker', summary: 'Defeat the Ashen Broker, Umbra’s hand in the Wastes, at the Dawn Forge.',
        text: { offer: ['(The ash rises into Pyrrhus’s old armour, with the Broker’s cracked mask where his face should be.)', 'It throws fire, rains lava and strikes from the shadows. Like me, with worse manners.', 'Umbra had a buyer in every land. This is the last one.'], progress: ['Defeat the Ashen Broker at the Dawn Forge.'], complete: [], after: ['No more buyers.'] } },
      m13: { title: 'The Shadow That Chose', summary: 'Defeat Umbra and light the Dawn Forge.',
        text: { offer: ['(The Broker falls into ash, and the ash turns black and begins to crawl. Out of the Beacon, the Bell and the Star, every guardian’s shadow gathers into one.)', '(“I am the shadow you were born with, both of you,” Umbra says, with Sable’s voice and yours. “I chose you. You are mine.”)', 'It’s wrong. The shadow was never the enemy. The choosing is. And I choose.'], progress: ['Defeat Umbra at the Dawn Forge.'], complete: [], after: [] } },
    },
  },
  npcs: {
    meadow: [
      { id: 'magpie', name: 'Magpie', portrait: '🐦‍⬛', at: 'city', dx: -420, dy: 220, activity: 'idle', until: 'ember:m1', look: look('#2e2a36', 'hood', { hatColor: '#1e1a26', hair: '#2e2420' }), lines: ['Hats! Fine hats! Nobody looks twice at someone selling hats.', 'You were the quietest little thing I ever took on. Still are. It’s unnerving.'], barks: ['Hats!', 'Psst, Riven.'] },
      { id: 'riven-wick', name: 'Wick', portrait: '🧒', at: 'city', dx: 130, dy: 300, activity: 'sweep', after: 'm6', look: look('#4a4058', 'cap', { hatColor: '#2e2a36', hair: '#2e2420', small: true }), lines: ['Barracks in the mornings, Tom’s ovens in the afternoons. Everybody wants me now, Riven. Imagine.', 'I said no to a shade. Nobody can make me do anything any more. Except Tom. Tom is terrifying.'], barks: ['Honey buns!', 'Riven!'] },
    ],
    woods: [
      { id: 'riven-tib', name: 'Tib', portrait: '🧒', at: 'city', dx: 230, dy: 200, activity: 'play', after: 'riven7', look: look('#3a3458', 'none', { hair: '#1a1a24', small: true }), lines: ['I’m practising being quiet. Like you. Did you hear me? No? Good.', 'My shadow does a dance when I’m happy. Juna says that’s allowed.'], barks: ['Riven!', 'Shh, I’m hiding.'] },
      { id: 'riven-needle', name: 'Needle', portrait: '🥷', at: 'shroomfarm', dx: -150, dy: 90, activity: 'wander', after: 'riven16', look: look('#3a3048', 'hood', { hatColor: '#2a2438', hair: '#1a1a24' }), lines: ['Mushrooms don’t run away. That’s the best thing about mushrooms.', 'If Magpie asks, I’m retired. From running. And from thieving. Mostly from you.'], barks: ['Not you again.', 'Hauling!'] },
    ],
    summit: [
      { id: 'riven-aled', name: 'Brother Aled', portrait: '🧘', at: 'city', dx: 300, dy: 250, activity: 'idle', after: 'riven22', look: look('#a8844a', 'none', { hair: '#8a6a4a' }), lines: ['I have taken a vow never to look in a puddle again.', 'The other me was very rude. I hope I am not like that.'], barks: ['Is that you? Good.'] },
    ],
    ember: [
      { id: 'riven-magpie', name: 'Magpie', portrait: '🐦‍⬛', at: 'city', dx: -380, dy: 240, activity: 'idle', after: 'summit:m20', look: look('#2e2a36', 'scarf', { hatColor: '#8a3b2f', hair: '#2e2420' }), lines: ['Scarves! Fine scarves! Keeps the ash out of your nose.', 'I came east because you’d get yourself killed without someone to disapprove of you.'], barks: ['Scarves!', 'Psst, Riven.'] },
      { id: 'riven-orsolo', name: 'Weigher Orsolo', portrait: '⚖️', at: 'city', dx: 60, dy: 280, activity: 'idle', after: 'summit:m20', look: look('#8a6a3a', 'cap', { hatColor: '#c9a24c', beard: true }), lines: ['I weigh things. Honest things, from now on. Mostly nuts.'], barks: ['Fair weight!', 'Oh no, it’s you.'] },
      { id: 'riven-needle2', name: 'Needle', portrait: '🥷', at: 'city', dx: -300, dy: 300, activity: 'wander', after: 'm7', look: look('#3a3048', 'hood', { hatColor: '#2a2438', hair: '#1a1a24' }), lines: ['Magpie says I’m bad at selling scarves. I say scarves are bad at being sold.', 'I said no to the Broker. I’m going to say no to everything now. It’s wonderful.'], barks: ['Scarves?', 'No!'] },
      { id: 'riven-sable', name: 'Sable', portrait: '🌑', at: 'watch', dx: 90, dy: 80, activity: 'idle', after: 'summit:m20', until: 'riven34', look: look('#2a2438', 'hood', { hatColor: '#1a1428', hair: '#1a1a24' }), lines: ['Ilyana reads the fire. I read the smoke. Between us we’re almost a lantern.', 'It still pulls at me here, Riven. Umbra. It thinks I’ll come back if it asks nicely.'], barks: ['The smoke is moving wrong.', 'Riven.'] },
    ],
  },
  npcFor: {
    // Sable meets Riven at the Spire only once he has caught her, and walks east with him instead of staying at the gate.
    'summit:sable': { after: 'summit:riven26', lines: ['We used to race up the Lantern House stairs. You always cheated.', 'It’s quieter, with you here. The shadow, I mean.'], barks: ['…Riven.'] },
    'summit:sable2': { hidden: true },
    'summit:sable3': { hidden: true },
    'summit:orrin': { lines: ['I paid for her, Riven. I thought paying was the same as caring.', 'I have much to make right. Most of it is not mine to make.'], barks: ['I have much to make right.'] },
    'summit:orrin2': { lines: ['Go on, both of you. The Wastes are waiting, and so is the last light.', 'I will hold this gate. Nothing follows you through it.'], barks: ['Go, and look after each other.'] },
  },
  script: {
    meadow: {
      sealed: 'Corvane hides in a cloak of smoke-feathers. Take back the three sun-crystals first.',
      pickupKey: 'Sun-crystal stolen back! {n}/3',
      tip: 'Corvane blinks and strikes from the dark. Keep moving, and shadowstep behind it when it lands. Smith Hilda in Goldenhearth can sharpen your daggers.',
      guide: { done: ['The Beacon is back, and they say a thief put it there.'] },
      finale: { locked: ['The Beacon is cold. Its three sun-crystals are still in the Hushed’s drops.'], guarded: ['Corvane perches on the Beacon, waiting to collect. Break the buyer to restore the light.'],
        done: ['You set the three sun-crystals back where the Hushed pried them out. Gold light roars up and sweeps across the valley.', 'Corvane’s mask cracks, and its cloak comes apart into a thousand black feathers. Every one of them turns to smoke.', 'Far to the east, over the dark trees of Whisperroot, the light glints on something silver. A web.'] },
      victory: { title: 'The Beacon shines again.', text: 'The crystals are home and the buyer is smoke. But the Hushed’s tunnels run east under Whisperroot, and Sable walked that way.' },
    },
    woods: {
      sealed: 'Silkmother Vesh sleeps in a cocoon of rune-silk. Wake the three root runes to cut its knots.',
      pickupKey: 'Knot-rune cut. {n}/3',
      tip: 'Silkmother Vesh spits webs that slow you and sends roots through the ground. Shadowstep out of the silk, and never fight her from inside it.',
      guide: { done: ['The woods breathe easy, and there’s a lamp in the Lantern House window.'] },
      finale: { locked: ['The Bell hangs silent in its web. Three root runes still hold the knots.'], guarded: ['Silkmother Vesh crouches over the Bell. Cut her down to free it.'],
        done: ['You ring the Ancient Bell. Its voice rolls through every root, and the rune-web falls away like frost.', 'In the falling silk you see Sable’s runes: moon, eye, door… and one more you know. Your own name.', 'She wrote you into the web. She knew you would be the one to cut it.'] },
      victory: { title: 'The Bell rings, and the children come home.', text: 'Whisperroot breathes again and the Lantern House lamp is lit. Sable has fled up to Starfall Summit, and her runes still say your name.' },
    },
    summit: {
      sealed: 'Nullface hides behind the hollow star’s void shell. Gather the three star shards first.',
      pickupKey: 'Star shard found. {n}/3',
      tip: 'Nullface blinks and strikes from behind, just like you. Watch where its shadow lands, and use Smoke Veil to make it lose you.',
      guide: { done: ['The star is home. Mind your face on the high roads, all the same.'] },
      finale: { locked: ['The Cradle is cold. Three star shards are needed.'], guarded: ['Nullface drifts over the Cradle, wearing your face. Break the mask!'],
        done: ['You lay the three shards into the Cradle. The star remembers its light and rises, whole, into the sky.', 'Nullface tries on your face one last time, then Sable’s. Neither fits. The mask splits down the middle.', 'But a thread of black smoke tears loose from the empty shell and streaks east, toward the Ember Wastes. Umbra is not finished.'] },
      victory: { title: 'The star rises home.', text: 'Nullface is broken and Sable is choosing for herself. Umbra fled east into the Ember Wastes, and this time Sable is coming with you.' },
    },
    ember: {
      sealed: 'The Ashen Broker hides in a shell of cooling ash. Recover the three ember cores first.',
      pickupKey: 'Ember core recovered. {n}/3',
      tip: 'The Broker strikes out of the shadows and rains fire. Keep moving, and use Smoke Veil to make it lose you. Ash scorpions burrow: watch for moving sand.',
      guide: { done: ['The wastes are cooling, thief. Er, hero. Which is it?'] },
      finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['A shadow broods over the forge. Defeat it!'],
        done: ['You set the three ember cores into the Dawn Forge. Its fire roars up, white and gold, and a new dawn spills across the wastes.', 'Umbra’s last shadow does not burn away. It shrinks, and settles at your feet and at Sable’s: just a shadow, the shape of a person, doing nothing at all.', 'Every land, every light. And nobody owns any of them.'] },
      victory: { title: 'The dawn returns.', text: 'Umbra is gone, and the shadow it claimed is only a shadow again. Riven took no pay for any of it, and chose every step.' },
    },
  },
  cines,
};
