import { look, own, person, type HeroStory } from './kit';

// Wren, "The Pack". A hunter raised by Hunter Garrick and by a wolf pack. The night the star fell, the shadow took the
// pack and ran them east; only young Fenn stayed. Moonfang, the pack's mother, pulled the worst of the shadow into
// herself and ran ahead of it, so it would follow her and not her pups.
//
// Umbra's shadow wears the shape of what each hero fears most, and Wren fears the wild turning on her, and the people
// turning on the wild. Meadow: the villages blame the wolves for what Gorehide, the Boar King, does. Woods: Shadowmane,
// the shadow itself in a wolf's coat, leads the pack, and Wren finds Moonfang's hidden pup. Summit: Skyhorn, the stag who
// guards the Cradle, herds every wild thing to the Rift because the shadow took his fawn. Ember: Moonfang's trail through
// the wastes, the Duneworm that hunts her, and Umbra, the Moon-Eater. Across the four lands, people learn the wolves
// were never the dark, and Wren learns to stand between both.

const q = own('wren');

const BURR = person('Burr the Poacher', '🪤', { robe: '#5a5a3a', hat: 'cap', hatColor: '#3a3a24', beard: true });
const BURR_LOOK = look('#5a5a3a', 'cap', { hatColor: '#3a3a24', beard: true });
const wolf = (name: string, fur: string) => person(name, '🐺', { robe: fur, hair: fur });
const FAWN = person('Frostling', '🦌', { robe: '#f4efe6', hat: 'ears', hatColor: '#e8e2d0', skin: '#e8dcc8', hair: '#e8e2d0', small: true });

export const WREN: HeroStory = {
  hero: 'wren',
  chains: {
    meadow: ['m1', 'wren7', 'm3', 'wren8', 'wren1', 'm6', 'wren2', 'wren9', 'm4', 'wren10', 'm7', 'wren11', 'm11', 'm9', 'wren12', 'm10', 'm12'],
    woods: ['m1', 'wren3', 'wren4', 'wren13', 'm3', 'm7', 'm6', 'wren14', 'm9', 'm10', 'm12', 'wren16', 'm11', 'wren19', 'm4', 'm15', 'wren18', 'm17'],
    summit: ['m1', 'm6', 'wren5', 'wren20', 'wren21', 'm10', 'wren25', 'm12', 'wren24', 'wren22', 'm15', 'wren23', 'm19', 'm20'],
    ember: ['m1', 'm2', 'm6', 'm3', 'm4', 'm14', 'wren33', 'm8', 'wren28', 'm7', 'wren29', 'm10', 'wren6', 'wren30', 'wren32', 'm15', 'm12', 'm13'],
  },
  quests: {
    // ═════════════════════════════ Chapter I · snares, the Boar King, and a valley afraid of wolves
    meadow: [
    q({ id: 'wren7', title: 'Snares in the Stones', giver: 'fox', kind: 'collect', count: 4, near: 'stones', item: 'Poacher’s snare', icon: 'bundle', auto: true, summary: 'Pull up the snares hidden around the Old Stone Garden before a wolf steps in one.', reward: { xp: 90 },
      text: { offer: ['Snares at the Old Stone Garden. Right where the pack’s tracks are.', '(Fenn’s ears go flat.) Not while I’m breathing. Back north-east to the stones, boy. We pull up every one.'],
        progress: ['Four snares hidden in the grass around the Old Stone Garden, north-east of Sunpetal.'],
        complete: ['Four. And look at the size of these loops. You could catch a cart-horse in one.', 'These weren’t set for wolves, Fenn. They were set for something much bigger.'], after: [] } }),
    q({ id: 'wren8', title: 'The Poacher', giver: 'fox', kind: 'chase', count: 1, place: 'stones', auto: true, who: BURR, summary: 'Catch the poacher who set the snares in the Old Stone Garden.', reward: { xp: 130, gold: 40 },
      text: { offer: ['(A man in a patched cap creeps out from behind a standing stone, counting his snares. He counts them twice.)', 'That’s him. Fenn, with me!'],
        progress: ['Burr is quick, but he tires. Catch him before he reaches the road.'],
        deliver: ['Alright, alright! Call off the wolf! I’ve never skinned a wolf in my life, I swear it!', 'Those snares weren’t for your pack. They were for Gorehide. The Boar King. Size of a haycart, tusks like scythes.', 'And your wolves? A black wolf ran at the front of them, with eyes like holes. The white one ran at the back, like she was being driven.'],
        complete: ['(Burr scrambles off toward the road, leaving his sack of wire behind.)', 'A black wolf at the front? Moonfang has led that pack for nine winters. Nobody drives Moonfang. Nobody.'], after: [] } }),
    q({ id: 'wren1', title: 'The Howl in the South-east', giver: 'fox', kind: 'talk', count: 1, to: 'garrick', summary: 'Ask Hunter Garrick at the Hunter’s Camp about the howl.', reward: { xp: 80 },
      text: { offer: ['(Far away to the south-east, a howl rolls over the meadow. Fenn stops dead, ears up.)', 'That was Thistle. She’s the fastest of the pack, and she only howls like that when she’s stuck.', 'Garrick will know where she is. The Hunter’s Camp is far to the south-east, past Goldenhearth.'],
        progress: ['The Hunter’s Camp lies in the south-east of the meadow, beyond Goldenhearth.'], complete: [], after: [],
        deliver: ['Wren! And Fenn. Good lad. I thought I’d lost the lot of you that night.', 'I heard the pack go by. Black as ink, all of them, and a big black brute at the front I’ve never seen in my life.', 'Thistle didn’t make it east. She’s caught in a box-trap in Rotwood Den, north-east of here, and the boars are all round her.'] } }),
    q({ id: 'wren2', title: 'The Hunter’s Totems', giver: 'garrick', kind: 'activate', count: 3, near: 'rot', switches: 'totem', order: ['Bear totem', 'Stag totem', 'Wolf totem'], auto: true, summary: 'Wake the three old hunter’s totems around Rotwood Den to pull the gloom out of Thistle.', reward: { xp: 160, mana: 10 },
      text: { offer: ['The old hunters raised three totems around Rotwood Den, to keep the gloom out of the beasts’ hearts. Bear, stag and wolf.', 'They went dark with the Beacon. Wake them, and maybe the gloom lets go of Thistle.'],
        progress: ['Three hunter’s totems stand around Rotwood Den, north-east of the camp.'],
        complete: ['(All three totems glow green. Back at the camp, Thistle lifts her head and howls, clear and bright. Her eyes are brown again.)', 'If the gloom can let go of one wolf, it can let go of all of them. Even Moonfang.'], after: [] } }),
    q({ id: 'wren9', title: 'Wolves at the Camp', giver: 'garrick', kind: 'defend', count: 3, place: 'camp', waves: [3, 3, 4], foes: ['shadewolf', 'gloomling', 'shadewolf'], ward: 'the Hunter’s Camp', cine: { start: 'pack-attack', done: 'wren-shadowmane' }, summary: 'Hold the Hunter’s Camp when the shadow-bound pack comes back for Thistle.', reward: { xp: 200, hearts: 1 },
      text: { offer: ['Thistle’s free, and whatever holds the rest of them will want her back. It’ll come tonight.', 'Stand with me at the fire. Drive them off. Go easy on them if you can, girl. They’re ours.'],
        progress: ['Stay by the Hunter’s Camp. Drive off every wave before it reaches the tents.'],
        complete: ['They broke and ran. And that black one on the ridge never came down. It just watched, and called them off.', 'Something is leading your pack, and it isn’t Moonfang.'], after: ['Quiet night. Thistle slept on my boots.'] } }),
    q({ id: 'wren10', title: 'Not a Wolf’s Bite', giver: 'brannoc', kind: 'trail', count: 4, near: 'millbrook', place: 'hollow', turnIn: 'bram', summary: 'Follow the fence-breaker’s tracks from Millbrook Farm, then tell Farmer Bram what you found.', reward: { xp: 130 },
      clues: ['A fence post at Millbrook, snapped clean through. Wolves don’t break fences. They jump them.', 'Hoofprints in the mud, split and deep, each one as wide as a dinner plate.', 'Bristles caught on a thornbush, thick as broom straw and black with gloom.', 'A wallow at the edge of Gloom Hollow, churned to soup. Whatever sleeps here is enormous.'],
      text: { offer: ['Start at Millbrook Farm, far to the west. Farmer Bram lost his fence and six hens two nights ago.', 'Follow whatever did it. If it was wolves, I want to know. If it wasn’t, I want to know that too.'],
        progress: ['Follow the tracks from Millbrook Farm south toward Gloom Hollow, then tell Farmer Bram.'],
        complete: ['Hoofprints like dinner plates? Bristles like broom straw? That’s no wolf, lass. That’s a boar.', 'And there’s only one boar that size in the valley. Gorehide. My granddad called him the Boar King.'], after: ['I’ve been blaming wolves for a boar. Shame on me.'] } }),
    q({ id: 'wren11', title: 'Proof for the Captain', giver: 'bram', kind: 'deliver', count: 1, to: 'brannoc', item: 'Gorehide’s bristle', summary: 'Bring Gorehide’s bristle to Captain Brannoc in Goldenhearth.', reward: { xp: 110, gold: 50 },
      text: { offer: ['Take that bristle to Captain Brannoc in Goldenhearth, east of here. Let him argue with that.'],
        progress: ['Captain Brannoc is in Goldenhearth, east of Millbrook Farm.'], complete: [], after: ['Tell Brannoc Bram sent you. He owes me for a pig.'],
        deliver: ['…That’s a bristle? It’s a broom handle.', 'Gorehide. My grandfather hunted him when I was a boy, and he was old then. The gloom must have fed him fat.', 'Fine. The wolf bounty comes down today, and I’ll send criers to every village. A bounty on the boar goes up instead.', 'Old Odo on Shepherd’s Hill, far to the north-east, has the last sun-crystal. He hates wolves worse than anyone. Good luck.'] } }),
    q({ id: 'wren12', title: 'Bait for a King', giver: 'wren-burr', kind: 'collect', count: 4, near: 'faerie', item: 'Stinkhorn truffle', icon: 'mushroom', turnIn: 'wren-burr', summary: 'Gather stinkhorn truffles around the Faerie Ring for Burr’s boar bait.', reward: { xp: 100 },
      text: { offer: ['You again. And the wolf. Look, I’m not here to set snares. I’m here to help. Probably.', 'Three winters I’ve chased Gorehide. He never comes when he’s called, but he comes for stinkhorn truffles. He can smell them a mile off.', 'They grow round the Faerie Ring, west of here. Bring me four, and we lay them on the Rise.'],
        progress: ['Stinkhorn truffles grow around the Faerie Ring, west of the Hunter’s Camp. You’ll smell them before you see them.'],
        complete: ['Phew. That’s the stuff. Gorehide will smell those from his wallow.', 'I set those snares for him, you know. Not for your pack. Nobody believed a boar could get that big.'], after: ['I still smell like truffles. It won’t wash off.'] } }),
    ],
    // ═════════════════════════════ Chapter II · tracking the pack, Snowpaw, and the thing that wears a wolf
    woods: [
    q({ id: 'wren3', title: 'Moonfang’s Tracks', giver: 'fox', kind: 'trail', count: 4, near: 'bellhollow', place: 'pool', auto: true, summary: 'Follow the great white wolf’s tracks east from Bellhollow to Blackwater Pool.', reward: { xp: 150 },
      clues: ['Pawprints as wide as my hand. Moonfang’s. The shadow hasn’t shrunk her.', 'A tuft of fur on a bramble, half white and half black, as if it can’t decide.', 'A shadow-bound deer, left untouched. The other wolves would have eaten it. She stopped them.', 'By the water: a den dug under the roots. And inside, a tiny pale pup, glowing like moonlight.'],
      text: { offer: ['(Fenn’s hackles rise. He has found her scent, strong and fresh, running east out of Bellhollow.)', 'Moonfang. Easy, boy. Quietly. Let’s see where she went.'],
        progress: ['Follow the pawprints east from Bellhollow toward Blackwater Pool.'],
        complete: ['A pup. Moonfang left a pup here, and the shadow never touched her. Fenn, that’s your little sister.', 'Moonfang couldn’t stay. Something was chasing her. But she hid this one first.'], after: [] } }),
    q({ id: 'wren4', title: 'Snowpaw', giver: 'fox', kind: 'escort', count: 1, from: 'pool', place: 'bellhollow', auto: true, beast: 'wolf', who: wolf('Snowpaw', '#dff6ff'), ambush: ['shadewolf', 'shadewolf', 'webspinner'], summary: 'Bring Moonfang’s pup safely to Nana Bristle in Bellhollow.', reward: { xp: 180, hearts: 1 },
      text: { offer: ['She won’t come near the shadewolves. If they find us, she’ll freeze. Keep them off her.', 'Oda says Nana Bristle in Bellhollow feeds every stray in the woods. She’ll keep the pup safe.'],
        progress: ['Lead Snowpaw west to Bellhollow. Chase off anything that threatens her.'],
        arrive: ['(Snowpaw bounds into Bellhollow and straight into Nana Bristle’s apron.)'],
        complete: ['(Nana Bristle scoops up the pup.) “Oh, you little snowball! Of course you can stay. There’s always room at my table.”', '(Snowpaw sneezes on her. Nana decides this means yes.)'], after: [] } }),
    q({ id: 'wren13', title: 'Nana Bristle’s Door', giver: 'nana', kind: 'defend', count: 3, place: 'bellhollow', waves: [3, 4, 5], foes: ['shadewolf', 'shadewolf', 'wisp'], ward: 'Nana Bristle’s door', cine: { start: 'wren-bellhollow' }, summary: 'Stand at Nana Bristle’s door in Bellhollow when the shadewolves come for Snowpaw.', reward: { xp: 200 },
      text: { offer: ['Hear that, dearie? Howling, all round the village. They’ve smelled the little one.', 'I’ve got a rolling pin and a very loud voice. You’ve got a bow. Stand at my door with me tonight.'],
        progress: ['Stand by Nana Bristle’s door and drive off the shadewolves before they reach it.'],
        complete: ['Not one of them got past my step! And you never once aimed for their hearts, did you? I saw.', 'Snowpaw slept through the whole thing. Now, the Old Bellkeeper across the lane knows what that black brute is.'], after: ['Soup’s on. For you, the wolf, and the littler wolf.'] } }),
    q({ id: 'wren14', title: 'Two Fenns and a Runaway', giver: 'fenn', kind: 'chase', count: 1, place: 'glade', who: person('Little Wick', '👦', { robe: '#c9a24c', small: true, hair: '#8a6a30' }), summary: 'Catch Lamplighter Fenn’s runaway boy Wick in the Moonlit Glade.', reward: { xp: 140 },
      text: { offer: ['You’re the girl with the wolf called Fenn? My name is Fenn. I had it first.', '(Fenn the wolf sniffs Fenn the lamplighter. Neither is impressed.)', 'My boy Wick heard a wolf-girl was in town and ran off to the Moonlit Glade, west of here, to see real wolves. Please catch him before they do!'],
        progress: ['Wick is somewhere in the Moonlit Glade, west of Lanternmarket. He’s quick, but he runs out of puff.'],
        deliver: ['Aww! You caught me! Is that your wolf? Can I pat him? He’s smaller than the black one.', 'I saw it! The big black wolf, right here in the glade! It walked through a tree, like the tree wasn’t even there!'],
        complete: ['Through a tree, he says. That boy. …Though he’s never been one for fibbing.', 'Thank you for bringing him home. And since you were in that glade, there’s something there you ought to see.'], after: ['Wick wants a wolf now. I said we’ll see.'] } }),
    q({ id: 'wren16', title: 'The Trapper’s Lodge', giver: 'ivo', kind: 'talk', count: 1, to: 'ysolde', summary: 'Find Trapper Ysolde at the Trapper’s Lodge and ask her about Shadowmane.', reward: { xp: 90 },
      text: { offer: ['Ysolde has trapped these woods for thirty years. If anyone can tell you what Shadowmane is, it’s her.', 'Her lodge is far to the south of the tower.'],
        progress: ['The Trapper’s Lodge lies far to the south of the Owl Watchtower.'], complete: [], after: [],
        deliver: ['The wolf-girl. My little brother wrote to me about you. Yes, Burr. He’s round the back, chopping my wood to say sorry for something.', 'Shadowmane. My hounds won’t follow it. There’s nothing to follow. It leaves no scent, and it walks through brambles without a thorn catching.', 'But I found where its trail starts. I’ll show you where it sleeps.'] } }),
    q({ id: 'wren19', title: 'Burr’s Moon Runes', giver: 'wren-burr-w', kind: 'activate', count: 3, near: 'spring', switches: 'rune', order: ['Moon rune of the east', 'Moon rune of the south', 'Moon rune of the west'], auto: true, summary: 'Wake the three moon runes around the Moss Shrine.', reward: { xp: 160, mana: 12 },
      text: { offer: ['Oi. Wolf-girl. I owe you one for Gorehide, so here it is. Don’t tell my sister I was listening.', 'Our granny said shadow can’t hold its shape under a full moon. The old trappers carved moon runes round the Moss Shrine, far north of here, for hunting nights.', 'Wake all three. Then when you face that thing at the Bell, the moon will be on your side.'],
        progress: ['Three moon runes around the Moss Shrine, far to the north of the lodge.'],
        complete: ['(The third rune glows silver. High above the trees, the moon comes out from behind the clouds, and stays out.)', 'Thank you, Burr. Now we need arrows that can hit something made of shadow. Herbalist Juna in Lanternmarket might know how.'], after: [] } }),
    q({ id: 'wren18', title: 'Old Grizzle Walks In', giver: 'fox', kind: 'escort', count: 1, from: 'bell', place: 'city', turnIn: 'thessaly', beast: 'wolf', who: wolf('Old Grizzle', '#8a8a8a'), ambush: ['webspinner', 'wisp', 'thornling'], summary: 'Walk Old Grizzle from the Old Bell to Lanternmarket, to show the city a freed wolf.', reward: { xp: 240, hearts: 1 },
      text: { offer: ['(An old grey wolf with a torn ear limps out of the trees and sits down in front of Wren.)', 'Grizzle. The oldest of the pack. It was you who kept Briony safe in the ruins, wasn’t it, you old softie.', 'Come on. Lanternmarket needs to see a wolf walk in through the lantern gate. South-west, boy.'],
        progress: ['Walk Old Grizzle south-west to Lanternmarket. Keep the last shadow-creatures off him.'],
        arrive: ['(Old Grizzle pads into Lanternmarket. Nobody screams. Little Wick holds out a sausage.)'],
        complete: ['That’s the wolf that kept Briony alive? …He’s very grey, isn’t he.', 'The torches go back in the shed. For good. Your pack can drink at our wells whenever they like.', 'Now. There’s a wall of black thorns across the Eastern Gate, and I think your white wolf is on the other side of it.'], after: ['Grizzle sleeps by the fountain now. The children feed him far too much.'] } }),
    ],
    // ═════════════════════════════ Chapter III · the herds, the wild things of the heights, and the white stag
    summit: [
    q({ id: 'wren5', title: 'Goats and a Wolf', giver: 'kiri', kind: 'herd', count: 5, animal: 'goat', near: 'hamlet', place: 'hamlet', turnIn: 'kiri', summary: 'Herd Little Kiri’s runaway goats back into their pen.', reward: { xp: 160, mana: 12 },
      text: { offer: ['YOUR WOLF SCARED MY GOATS! They ran EVERYWHERE!', 'You have to put them back. All five. In the pen. Walk behind them and they go the other way. Everybody knows that.'],
        progress: ['Walk behind a goat to push it toward the pen in Frostpine Hamlet.'],
        complete: ['Five goats! Okay. Okay, you’re forgiven. Can I pat the wolf?', '(Fenn allows it, with enormous dignity.)', 'Goatherd Brun says wolves are eating his goats on the terrace, south-east of here. Are they your wolves? Go and tell him they’re not!'], after: ['The goats still don’t like Fenn.'] } }),
    q({ id: 'wren20', title: 'Wolves at the Fold', giver: 'brun', kind: 'defend', count: 3, place: 'terrace', waves: [4, 4, 5], foes: ['shadewolf', 'frostwraith', 'shadewolf'], ward: 'Brun’s goat fold', summary: 'Stand at Brun’s goat fold on the terrace when the wolves come in the night.', reward: { xp: 200 },
      text: { offer: ['Kiri sent you? The wolf-girl. Hah. Then whose side are you on, when they come for my goats tonight?', 'Because they will. Every night this week. Stand at my fold, or get off my terrace.'],
        progress: ['Stand by Brun’s goat fold and drive off every wave before it reaches the goats.'],
        complete: ['They ran! And the wraiths ran with them. Behind them, mind. Wraiths at the back, wolves in front, like dogs driving a herd.', 'And not one wolf bit you. Not once. Why not?'], after: ['The fold’s quiet. Too quiet. I miss complaining.'] },
      choice: {
        a: { label: 'Because I’m on their side too', lines: ['On their side. And on mine, at my fold, all night long. Hmph.', 'Well. If you can stand on both sides, maybe an old goatherd can try standing on neither.'], reward: { mana: 10 } },
        b: { label: 'Because they’re starving, not wicked', lines: ['Starving. Aye… there’s not been a hare on the heights since the star fell. Nothing left to hunt but goats.', 'I’ll leave the old nanny’s scraps on the far ridge for them. Don’t tell my wife.'], reward: { gold: 60 } },
      } }),
    q({ id: 'wren21', title: 'Where the Wild Things Go', giver: 'fox', kind: 'trail', count: 4, near: 'terrace', place: 'rift', auto: true, summary: 'Follow the wild things’ tracks east from the terrace to the Void Rift.', reward: { xp: 170 },
      clues: ['Wolf prints in the snow, running east. Beside them, the light prints of hares, and the neat little prints of foxes.', 'Every wild thing on the heights went this way. Not running from something. Called by something.', 'Hoofprints, huge and cloven, walking behind all of them like a shepherd behind his flock.', 'The Void Rift. Every track ends at its edge. And in the dark below, something small and white is crying.'],
      text: { offer: ['(The wolves’ tracks run east from the terrace. Fenn puts his nose down and goes stiff all over.)', 'Not just wolves. Everything went this way. Come on, boy.'],
        progress: ['Follow the tracks east from the Goatherd’s Terrace toward the Void Rift.'],
        complete: ['A fawn. A white fawn, in a cage of shadow at the bottom of the Rift, and wolves circling it like guards.', 'Skyhorn’s fawn. That’s why the stag left his ridge.'], after: [] } }),
    q({ id: 'wren25', title: 'A Black Antler for the Abbot', giver: 'wren-eska', kind: 'deliver', count: 1, to: 'corvin', item: 'Skyhorn’s blackened antler-tip', summary: 'Bring Skyhorn’s blackened antler-tip to Abbot Corvin in Skyhold.', reward: { xp: 150 },
      text: { offer: ['The monks of Skyhold worship Skyhorn. They will not believe he is sick. They mean to drive the wolves off the Frostfang cliffs at dawn instead.', 'Skyhorn shed this at the Rift: the tip of an antler, black as pitch. Take it to Abbot Corvin in Skyhold, west of here. Make him look at it.'],
        progress: ['Abbot Corvin is in Skyhold, west of the Star Altar.'], complete: [], after: ['Skyhold has a lot to answer for. So do I.'],
        deliver: ['A wolf in my city, and a girl who speaks for wolves. Eska sent you, I suppose. What is that?', '…Black. Skyhorn’s antler, gone black. Stars forgive me, I have blamed the wolves for what the dark did to our own stag.', 'My brothers are already on the road to Frostfang Crag with torches. What would you have me do?'] },
      choice: {
        a: { label: 'Call the brothers back', lines: ['Then I will ring the recall bell. The wolves may keep their crag, and my brothers their breakfast.', 'But go up to Frostfang yourself. The second star shard lies there, and a wolf den under the rocks.'], reward: { mana: 12 } },
        b: { label: 'Send them to help the wolves', lines: ['Help them? …Monks carrying hay up a mountain to feed wolves. The pilgrims will sing about it for a hundred years. Very well.', 'Go up ahead of them. The second star shard lies on Frostfang Crag, and a wolf den under the rocks.'], reward: { regen: .5 } },
      } }),
    q({ id: 'wren24', title: 'Stones on the Den', giver: 'fox', kind: 'slay', count: 4, enemy: 'cragGolem', auto: true, summary: 'Break the crag golems stamping on the wolf den under Frostfang Crag.', reward: { xp: 150 },
      text: { offer: ['Golems, all round the den. They’re trying to stamp it flat.', 'Four of them. Break them, Fenn, and then we dig her out.'],
        progress: ['Crag golems raise their fists before they strike. Dodge, then shoot.'],
        complete: ['(The last golem crumbles. Wren and Fenn dig until her hands and his paws are raw.)', '(Out of the rubble crawls a thin grey she-wolf with a white blaze on her chest. She looks at Wren, and doesn’t run.)'], after: [] } }),
    q({ id: 'wren22', title: 'A Wolf for the Goatherd', giver: 'fox', kind: 'escort', count: 1, from: 'frostfang', place: 'terrace', turnIn: 'brun', beast: 'wolf', who: wolf('Hazel', '#9a9a9a'), ambush: ['frostwraith', 'wisp', 'cragGolem'], summary: 'Walk the lame wolf Hazel from Frostfang Crag to Goatherd Brun’s terrace.', reward: { xp: 220 },
      text: { offer: ['She can’t hunt on that leg. She’ll starve up here, or the wraiths will drive her back to the Rift.', 'I know somebody with a fold full of goats and a soft heart he pretends he hasn’t got. Come on, Hazel. South-west, to the terrace.'],
        progress: ['Walk Hazel from Frostfang Crag south-west to the Goatherd’s Terrace. Keep the wraiths off her.'],
        arrive: ['(Hazel limps onto the terrace. Every goat freezes. Brun drops his bucket.)'],
        complete: ['You’ve brought a wolf. To my goats. To my GOATS.', '…She’s all bones. Hazel, is it? Well, Hazel, you’ll eat what the dogs eat and sleep in the old byre, and if one kid goes missing—', '(Hazel lies down on Brun’s boots with a sigh. Brun’s face does something complicated.) …She can stay.'],
        after: ['Hazel keeps the wraiths off the fold now. Best dog I ever had. Don’t tell her I said dog.'] } }),
    q({ id: 'wren23', title: 'Calling the Stag', giver: 'wren-eska', kind: 'activate', count: 3, near: 'altar', switches: 'rune', order: ['Horn-stone of the Dawn', 'Horn-stone of the Moon', 'Horn-stone of the Star'], ordered: true, summary: 'Wake the three horn-stones around the Star Altar, in order: dawn, moon, star.', reward: { xp: 180, mana: 10 },
      text: { offer: ['You saw him. Then you know he is still in there, fighting it.', 'When Skyhorn was a fawn, the old wardens called him down with three horn-stones around this altar: dawn, then moon, then star.', 'Wake them in that order. He will come to the Cradle to answer, and there you must break the dark out of his antlers. I cannot ask anyone else.'],
        progress: ['Wake the three horn-stones around the Star Altar in order: dawn, moon, then star.'],
        complete: ['Hear that? A horn-call, from the Cradle. He is answering.', 'Go, child. Break the black light and lay the shards in the Cradle. And please… do not hurt him more than you must.'], after: ['Frostling is waiting for her father.'] } }),
    ],
    // ═════════════════════════════ Chapter IV · Moonfang's trail through the wastes, and the worm that hunts her
    ember: [
    q({ id: 'wren33', title: 'The Screaming Vents', giver: 'fox', kind: 'activate', count: 3, near: 'nest', switches: 'vent', order: ['Screaming vent', 'Hissing vent', 'Roaring vent'], auto: true, summary: 'Open the three steam vents around the Scorpion Burrows to scare the Duneworm off.', reward: { xp: 140 },
      text: { offer: ['Cinderfinch said the vents round the Scorpion Burrows scare the worm away. Let’s open them, Fenn, before we go down its tunnel.'],
        progress: ['Open the three steam vents around the Scorpion Burrows, east of Saltglass Farm.'],
        complete: ['(The third vent shrieks like a kettle the size of a house. Deep under the sand, something huge turns and slithers away.)', 'It’s gone. For now. The core, quick.'], after: [] } }),
    q({ id: 'wren28', title: 'Hunter Zara', giver: 'fox', kind: 'talk', count: 1, to: 'zara', summary: 'Find the hunter at the Salt Caravan Camp and ask after Moonfang.', reward: { xp: 90 },
      text: { offer: ['(Far east of the Burrows, the smoke of a camp. And the smell of a hunter on the wind: leather and arrow-oil, like Garrick’s tent.)', 'Somebody over there hunts for a living. Maybe she’s seen Moonfang.'],
        progress: ['The Salt Caravan Camp lies far to the east of the Scorpion Burrows.'], complete: [], after: [],
        deliver: ['Stop right there. …A wolf-girl. I heard about you from a trapper who came in with the caravan. Burr, he said.', 'Your white wolf came past two nights ago with the Duneworm right behind her. I put three arrows in its hide. It didn’t notice.', 'Then the scorpions hit the camp. They’ve got Burr caged at the far end. Help me get him out.'] } }),
    q({ id: 'wren29', title: 'A Tower Against the Sand', giver: 'zara', kind: 'build', count: 4, near: 'caravan', item: 'Bleached plank', icon: 'bundle', place: 'caravan', site: 'tower', siteName: 'Zara’s worm-watch', summary: 'Gather planks around the caravan camp and build Zara’s worm-watch tower.', reward: { xp: 180 },
      text: { offer: ['Out here the worm comes up under you before you hear it. We need eyes up high.', 'Bring four good planks from the wrecked carts round the camp, and we’ll put up a watch-tower right here.'],
        progress: ['Four bleached planks from the wrecked carts around the caravan camp, then build the tower.'],
        complete: ['Up you go. Look north. See those ripples in the sand? That’s the worm, heading for the Old Foundry.', 'And that white speck, far to the north, past the foundry? That’s your wolf. The worm is between you and her.', 'The last core is at the foundry. Get it before the worm comes back for it.'], after: ['Best view in the wastes. Mostly sand.'] } }),
    q({ id: 'wren6', title: 'The Last Green', giver: 'fox', kind: 'trail', count: 4, near: 'watch', place: 'green', auto: true, cine: { done: 'wren-moonfang' }, summary: 'Follow Moonfang’s tracks east from Ashfall Watch to the Last Green.', reward: { xp: 240, hearts: 1 },
      clues: ['Big pawprints in the ash, and between them, spots of blood. She’s hurt.', 'A burnt patch where something tried to hold her down. She broke free.', 'White fur on a black rock. The shadow is falling off her like old snow.', 'The first grass in a hundred miles. And under the last green tree, Moonfang.'],
      text: { offer: ['(Fenn freezes on the step of Ashfall Watch, nose up. Moonfang’s scent, fresh, running east.)', 'The last green tree. Come on, Fenn. Run.'],
        progress: ['Follow the pawprints east from Ashfall Watch to the Last Green.'],
        complete: ['She knows us, Fenn. She knows us.', 'The Phoenix Spring, far to the south, heals anything, Ilyana said. We’re taking her there.'], after: [] } }),
    q({ id: 'wren30', title: 'The Long Walk to the Spring', giver: 'fox', kind: 'escort', count: 1, from: 'green', place: 'spring', auto: true, beast: 'wolf', who: wolf('Moonfang', '#f4f4f4'), ambush: ['shadewolf', 'emberImp', 'ashScorpion'], cine: { done: 'wren-spring' }, summary: 'Walk Moonfang from the Last Green to the Phoenix Spring.', reward: { xp: 240 },
      text: { offer: ['She can walk. Slowly. The Phoenix Spring is far to the south, past the Old Foundry.', 'The worm will smell her the moment she leaves the green. Stay close, Moonfang. We’ve got you now.'],
        progress: ['Walk Moonfang south from the Last Green to the Phoenix Spring. Keep everything off her.'],
        arrive: ['(Moonfang wades into the Phoenix Spring and drinks, and drinks, and drinks.)'],
        complete: ['(When she lifts her head, her fur is white as the moon all the way through. Not one hair of shadow left.)', 'Moonfang. Oh, Moonfang.'], after: [] } }),
    q({ id: 'wren32', title: 'Stand at the Spring', giver: 'fox', kind: 'defend', count: 3, place: 'spring', waves: [4, 5, 6], foes: ['ashScorpion', 'emberImp', 'shadewolf'], ward: 'Moonfang’s spring', auto: true, cine: { start: 'wren-spring-siege' }, summary: 'Hold the Phoenix Spring while Moonfang heals.', reward: { xp: 260 },
      text: { offer: ['(The ground trembles. Out in the sand, a hundred small things are digging toward the spring.)', 'It’s sending everything it has. Fenn, we hold here. Nothing touches her.'],
        progress: ['Stand by the Phoenix Spring and break every wave before it reaches Moonfang.'],
        complete: ['(The last scorpion burrows away. Moonfang steps out of the spring and stands beside Fenn, shoulder to shoulder.)', 'The worm sleeps under the Dawn Forge. Let’s go and wake it.'], after: [] } }),
    ],
  },
  reuse: {
    meadow: {
      m1: { title: 'Where the Pack Ran', giver: 'fox', summary: 'Follow the pack’s tracks to Sunpetal Village and find Elder Rowan.',
        text: { offer: ['(The pack’s tracks cross the Old Stone Garden and run south-west, toward the smoke of a village.)', 'Sunpetal. Garrick always says Elder Rowan sees everything that happens in the meadow. Come on, Fenn. Stay close.'],
          progress: ['The tracks lead south-west to Sunpetal Village.'], complete: [], after: ['Rowan saw them. He must have.'],
          deliver: ['Garrick’s girl. The one the wolves raised. Keep that animal close, child. My people are frightened.', 'Your pack ran through our lanes at midnight with eyes like pitch. Mothers barred their doors.', 'And now hunters from the city are setting wolf snares out by the Old Stone Garden, where your pack’s tracks are.'] } },
      m3: { title: 'What Fenn Dug Up', giver: 'fox', auto: true, summary: 'Take the sun-crystal Fenn found among the stones of the Old Stone Garden.', reward: { xp: 120 },
        text: { offer: ['(Fenn is digging furiously at the foot of the tallest stone. Something golden glows in the hole.)', 'Garrick told me about these. Sun-crystals. The Beacon’s fire lived in them.'],
          progress: ['Look for the golden light among the stones, where Fenn was digging.'],
          complete: ['(The crystal is warm in Wren’s hand. Fenn stops growling for the first time since the star fell.)', 'You feel it too? The gloom doesn’t like this light. Maybe the shadow in the pack won’t either.'], after: ['Two more crystals, somewhere in the meadow.'] } },
      m6: { title: 'Thistle in the Trap', giver: 'garrick', turnIn: 'garrick', beast: 'wolf', captive: wolf('Thistle', '#8a8a8a'), summary: 'Free Thistle from the box-trap in Rotwood Den and bring her back to Garrick.', reward: { xp: 150, hearts: 1 },
        text: { offer: ['Rotwood Den is a boar wallow. Bristleboars and gloomlings sleep in the rot, and five of them lie round that trap.', 'She’ll still have the shadow in her, girl. She may snap at you. Bring her back to my fire anyway.'],
          progress: ['Rotwood Den lies north-east of the Hunter’s Camp. Drive off the guards, open the trap and bring Thistle back to Garrick.'],
          arrive: ['(Thistle limps into the Hunter’s Camp and flops down by Garrick’s fire, growling at nobody in particular.)'],
          deliver: ['(Thistle snarls, black-eyed, and backs into the corner of the trap.)', '(Then Fenn pushes his nose through the bars. Thistle sniffs him… and her tail gives one slow wag.)'],
          complete: ['That’s our Thistle. Still half shadow, look at her eyes. But she followed you home.', 'The old hunters knew a trick for beasts gone dark. Let me think on it.'], after: ['She growls at me. She always did.'] } },
      m4: { title: 'A Price on Every Pelt', giver: 'garrick', to: 'brannoc', summary: 'Ask Captain Brannoc in Goldenhearth to take down the bounty on wolves.', reward: { xp: 90 },
        text: { offer: ['After last night, the whole meadow will say wolves attacked the Hunter’s Camp. And Goldenhearth already pays silver for wolf pelts.', 'Captain Brannoc set that bounty. Go and talk sense into him, before every hunter in the valley goes out with a bow.'],
          progress: ['Goldenhearth is north-west of the Hunter’s Camp. Captain Brannoc keeps the city guard.'], complete: [], after: ['Brannoc’s not a bad man. Just a frightened one.'],
          deliver: ['The wolf-girl. I’ve heard of you. Wolves ran through my farms the night the star fell, and something has smashed Bram’s fences every night since.', 'Bring me proof it isn’t your wolves, and I’ll take the bounty down. Until then, it stands.'] } },
      m7: { title: 'The Boar King’s Wallow', giver: 'bram', summary: 'Take the sun-crystal from Gloom Hollow, where Gorehide wallows, then tell Farmer Bram.', reward: { xp: 140 },
        text: { offer: ['Gloom Hollow is where Gorehide wallows, just south of here. Folk say a sun-crystal glows down there too, under the muck.', 'If you’re going in, lass, go quick. And come back out.'],
          progress: ['Gloom Hollow lies south of Millbrook Farm. Find the crystal in the gloom.'],
          complete: ['You came back out! With a crystal! And… what is that, stuck to it?', 'A bristle as long as my arm. No wolf ever grew one of those. That’s your proof, lass.'], after: ['The hens are laying again. Mostly.'] } },
      m11: { title: 'Fenn the Sheepdog', summary: 'Steer five of Odo’s scattered sheep back into their pen, with Fenn’s help.', reward: { xp: 130 },
        text: { offer: ['A WOLF! On my hill! Get it off before it eats the — wait. Is it… rounding up my sheep?', '(Fenn trots in a wide circle, and three lost sheep drift toward the pen.)', 'Hmph. The boars scattered my whole flock. If that wolf wants to be useful, walk behind five sheep and steer them into the pen.'],
          progress: ['Walk behind a sheep to push it toward Odo’s pen. Fenn will help. Mostly.'],
          complete: ['Five sheep home, and not one of them bitten. Forty years I’ve shouted wolves off this hill.', 'Maybe I’ve been shouting at the wrong beasts.'], after: ['That wolf of yours can come back for the lambing.'] } },
      m9: { title: 'Odo’s Crystal', summary: 'Find the last sun-crystal among the stones of Shepherd’s Hill.', reward: { xp: 150 },
        text: { offer: ['The last sun-crystal sits among the stones up here. It hums at night, and every night the hum gets angrier.', 'Take it. And mind: something huge gores the Beacon Rise every night, digging at the Beacon’s roots like it wants the light dead.'],
          progress: ['The crystal is somewhere among the stones of Shepherd’s Hill.'],
          complete: ['All three crystals. Hear that? Away in the south-east, the Rise is rumbling.', 'That’s him. Gorehide. That poacher Burr was up here asking after him, too. He’s gone to wait at the Hunter’s Camp.'], after: ['Mind the boar. Mind the wolves. Well, mind the boar.'] } },
      m10: { title: 'Gorehide', giver: 'wren-burr', summary: 'Bring down Gorehide, the Boar King, at the Beacon Rise and relight the Meadow Beacon.',
        text: { offer: ['Lay the truffles on the Beacon Rise, south-east of here, and stand back. Way back.', 'Gorehide charges in straight lines and flings up rocks and roots. Get out of his way, and keep shooting.', 'Beat him and lay the crystals in the Beacon. The light should burn the gloom out of every beast in the meadow.'],
          progress: ['The Beacon Rise lies south-east of the Hunter’s Camp.'], complete: [], after: ['Did you see him go down? I’ll be telling that one for years.'] } },
      m12: { title: 'Over the Gloomwater', summary: 'Gather bridge timbers around Willowmere and rebuild the Gloomwater Bridge at the Eastern Gate.',
        text: { offer: ['You lit the Beacon? With a wolf? Well, I’ve seen stranger. No. No, I haven’t.', 'The Gloomwater Bridge came down the night the star fell. Your pack swam the river, I’d bet. You’d drown.', 'Five good timbers from around Willowmere, north-west of here, and we build her together, right here at the gate.'],
          progress: ['Five bridge timbers from around Willowmere, then build at the Eastern Gate.'],
          complete: ['There she stands! Straight, strong, and only a little bit wobbly.', 'Whisperroot Woods is over the river. Your pack went that way. Go on, girl. Bring them home.'], after: ['Tell your wolves to walk, not swim. Third plank squeaks.'] } },
    },
    woods: {
      m1: { title: 'Pawprints Under the Trees', summary: 'Follow the pack into Whisperroot and find Mosskeeper Oda.',
        text: { offer: ['(Over the bridge, the pack’s pawprints run straight in under the dark trees. Fenn sniffs, and sneezes.)', 'Shadow-smell. Lots of it. There’s a camp just ahead. Somebody there must have heard them.'],
          progress: ['Take the road east through the gate to Mosskeeper’s Camp.'], complete: [], after: [],
          deliver: ['You came over the river with a wolf at your heel? Brave, or mad. The woods have had enough of wolves.', 'Shadewolves came through three nights ago, led by a black alpha. The woodsfolk call it Shadowmane.', 'But one ran alone, well ahead of them: a great white wolf, limping. She went south-east, toward Bellhollow.'] } },
      m3: { title: 'The Bell and the Pack', giver: 'nana', to: 'bellkeeper', summary: 'Ask the Old Bellkeeper in Bellhollow about the black wolf.',
        text: { offer: ['The Old Bellkeeper lives just across the lane. He rang the Ancient Bell every dawn for sixty years.', 'Ask him about the black wolf. He goes quiet when I do.'],
          progress: ['The Old Bellkeeper is here in Bellhollow.'], complete: [], after: [],
          deliver: ['The black wolf. Shadowmane. It came the night the star fell, and lay down round the Old Bell like a dog on a doorstep.', 'While the Bell is silent, every wolf in Whisperroot answers one howl. Its howl. Your pack too, child.', 'Three root runes can wake the Bell. The first glows under Glowcap Farm, far to the north.'] } },
      m7: { title: 'The Glowcap Rune', giver: 'bellkeeper', summary: 'Wake the root rune at Glowcap Farm and ask Forester Birch about the pack.',
        text: { offer: ['Glowcap Farm is far to the north, where the mushrooms grow taller than you. Touch the rune and it will wake.', 'Forester Birch works the timber there. He has seen your wolves, I think.'],
          progress: ['Glowcap Farm lies far to the north of Bellhollow.'],
          complete: ['A root rune! It hums like a hive. The trees round here will sleep sounder.', 'Your wolves? They den in the Root Ruins by day, north-east of here. And they dragged one of the city’s scouts in there two days ago.'], after: ['Timber, runes and wolves. What a week.'] } },
      m6: { title: 'The Scout and the Grey Wolf', giver: 'forester', turnIn: 'thessaly', captive: person('Scout Briony', '💂‍♀️', { robe: '#6a7a8a', hat: 'helm', hatColor: '#8a8f9a', hair: '#b8743c' }), summary: 'Free Scout Briony from the Root Ruins and bring her to Warden Thessaly in Lanternmarket.', reward: { xp: 130, gold: 50 },
        text: { offer: ['Scout Briony, from the Lanternmarket watch. The shadewolves put her in an old cage in the Root Ruins, and six of them guard it.', 'Warden Thessaly will be half mad by now. Bring the lass back to her in Lanternmarket.'],
          progress: ['The Root Ruins are north-east of Glowcap Farm. Drive off the guards, open the cage, and bring Briony to Warden Thessaly in Lanternmarket.'],
          arrive: ['Lanternmarket! Warden! Put the torches down, I’m fine, I’m fine!'],
          deliver: ['You’re the wolf-girl? Then listen. There was an old grey wolf with a torn ear. He lay across the cage door all night.', 'The others wanted in. He wouldn’t let them. He could have eaten me. He brought me a rabbit instead.'],
          complete: ['Briony! Thank the lanterns. I had the torches ready to burn the woods’ edge and drive every wolf into the river.', 'A grey wolf kept her alive? …Then I’ll hold the torches. For now. Show me the wolves aren’t the danger, and I’ll put them away.'], after: ['The torches stay in the shed. For now.'] } },
      m9: { title: 'What the Glade Remembers', summary: 'Light the four old lanterns of the Moonlit Glade, then return to Lamplighter Fenn.',
        text: { offer: ['Four old lanterns stand round the Moonlit Glade. Nobody has lit them since I was a boy.', 'My grandmother said the glade remembers every lost thing that ever slept in it. Light them, and see what it shows you.'],
          progress: ['Four lanterns around the Moonlit Glade, west of the city.'],
          complete: ['A white wolf curled round a baby in the snow, keeping her warm? …That baby was you, wasn’t it.', 'Then the wolves never stole a child. They saved one. Thessaly should hear that.', 'The second rune is in the Thornling Nest, north-east of the glade. Scout Ivo watches it from the Owl Watchtower.'], after: ['Every lantern remembers something.'] } },
      m10: { title: 'Thorns Round the Second Rune', summary: 'Wake the rune in the Thornling Nest, then ask Scout Ivo about the black wolf.',
        text: { offer: ['The Thornling Nest is north of the city. Thornlings spit thorns. Duck.', 'Scout Ivo at the Owl Watchtower, east of the nest, sees everything that moves in these woods. Ask him about your black wolf.'],
          progress: ['The Thornling Nest is north of Lanternmarket. The watchtower is east of it.'],
          complete: ['Two runes! The owls are hooting like mad.', 'Your black wolf? I’ve watched it from up here every night. In the moonlight it casts no shadow. Not a scrap.'], after: ['All clear. For now.'] } },
      m12: { title: 'The Rune Under the Owls', summary: 'Wake the last root rune at the foot of the Owl Watchtower.',
        text: { offer: ['The last rune sleeps somewhere round the foot of this tower. It glows green when it’s awake.', 'Wake it, and the Bell has all three of its runes.'],
          progress: ['Look around the foot of the Owl Watchtower.'],
          complete: ['All three runes are singing! Hear the Bell? Not ringing yet. Humming. Waiting.', 'But before you go near that black wolf, go and hear what Trapper Ysolde has found.'], after: ['The owls are proud of you.'] } },
      m11: { title: 'No Scent, No Shadow', giver: 'ysolde', summary: 'Follow Shadowmane’s fading trail from the Owl Watchtower to Silkshadow Hollow, then tell Ysolde what you found.', reward: { xp: 150 },
        clues: ['Pawprints in the mud, huge, but they fade even as you look at them. Fenn sniffs, and backs away.', 'A birch the black wolf brushed past. Its bark has gone grey and cold, as if winter touched only this one tree.', 'A hollow in the moss where it lay down. No warmth, no hair, no smell. Only cold.', 'Silkshadow Hollow: a pool of shadow in the shape of a wolf, with nothing inside it. Like a coat hung up for the night.'],
        text: { offer: ['Its trail starts under the Owl Watchtower, north of here, and runs south-east to Silkshadow Hollow, where it rests by day.', 'Follow it. Look hard. Then come back here and tell me what you think it is.'],
          progress: ['Follow the fading pawprints from the Owl Watchtower to Silkshadow Hollow, then return to Ysolde.'],
          complete: ['A wolf-shaped hole with nothing in it. That’s what I thought.', 'It isn’t a wolf, girl. It’s the shadow itself, wearing a wolf like a coat. The old ones say it takes the shape of what you fear most.', 'You fear your own pack turning on you. So it made itself their alpha. Beat the coat off it, and they’ll come loose.'], after: ['Quiet feet. And keep your wolf close.'] } },
      m4: { title: 'Moonpetal Arrowheads', giver: 'juna', summary: 'Pick moonpetals in the Moonlit Glade so Herbalist Juna can coat your arrows.', reward: { xp: 110 },
        text: { offer: ['Arrows for a shadow? Now there’s an order. Moonpetal sap eats shadow like fire eats straw.', 'Pick five moonpetals in the Moonlit Glade, west of here, and I’ll dip every arrowhead you own.'],
          progress: ['The Moonlit Glade lies west of Lanternmarket.'],
          complete: ['Five moonpetals, fresh as dew. Hold still… there. Your arrows glow like the moon.', 'Shadowmane lies at the Old Bell, far to the north-east. The whole city is watching you, wolf-girl. Even Thessaly.'], after: ['Don’t lick the arrowheads.'] } },
      m15: { title: 'Shadowmane', giver: 'fox', summary: 'Defeat Shadowmane at the Old Bell and ring the Ancient Root Bell.',
        text: { offer: ['(From the far north-east, from the Old Bell, a howl rolls through the trees. Every hair on Fenn’s back stands up.)', 'It knows we’re coming. It charges, it howls up shadewolves, and it throws shadow. Keep moving, keep shooting.', 'Break the coat, Fenn. Then we ring the Bell and bring the pack home.'],
          progress: ['The Old Bell stands in the far north-east of the woods.'], complete: [], after: ['The Bell rings! And the pack sings with it.'] } },
      m17: { title: 'Through the Thorn Gate', summary: 'Light the three Bell-lanterns at the Eastern Gate and follow Moonfang’s tracks.',
        text: { offer: ['Take this flame. It was lit from the Bell’s own candle.', 'Light the three Bell-lanterns by the Eastern Gate, and the thorns will wither. Then go after your white wolf. The woods owe her that.'],
          progress: ['Three Bell-lanterns by the Eastern Gate, far to the east.'],
          complete: ['(The thorn wall shivers. Far behind you the Bell rings once more, and the whole pack howls with it.)'], after: [] } },
    },
    summit: {
      m1: { title: 'Pawprints in the Snow', summary: 'Follow Moonfang’s pawprints up to Warden’s Lookout and find Sky-warden Ilsa.',
        text: { offer: ['(Beyond the gate the road climbs into snow. Moonfang’s pawprints climb with it, and so does a smell of cold and shadow.)', 'There’s a lookout ahead. Somebody up there has seen her. Come on, Fenn.'],
          progress: ['Take the road east through the gate to Warden’s Lookout.'], complete: [], after: [],
          deliver: ['A girl and a wolf, climbing my mountain. Have you any idea how many wolves I’ve had up here this week?', 'The Summit’s own wolves, half-starved, with shadow in their fur, raiding the goat terraces. And a great white wolf went north, to Crystal Hollow.', 'And Skyhorn, the white stag who guards the Cradle, has left his ridge. He has never done that. Not in my lifetime.'] } },
      m6: { title: 'White Fur in the Crystals', summary: 'Find the star shard in Crystal Hollow, and Moonfang’s trail, then tell Ilsa.', reward: { xp: 110 },
        text: { offer: ['Crystal Hollow is north of here. A shard of the fallen star came down there, and your white wolf went the same way.', 'If you find either one, come back and tell me.'],
          progress: ['Crystal Hollow lies north of Warden’s Lookout.'],
          complete: ['A star shard, and white fur on the crystals? She slept there, then, curled round the shard to keep warm.', 'And hoofprints over her pawprints? Skyhorn. Following her. Or herding her.', 'Frostpine Hamlet is south-east of here. They’ve lost goats to the wolves, so go gently with that one of yours.'], after: ['Rest a moment. The wind bites.'] } },
      m10: { title: 'The Fawn in the Rift', giver: 'fox', turnIn: 'wren-eska', captive: FAWN, summary: 'Free Skyhorn’s fawn from the Void Rift and bring her to the Horn-warden at the Star Altar.', reward: { xp: 160, hearts: 1 },
        text: { offer: ['The fawn is caged at the bottom of the Void Rift. The shadow is using her as bait, and the wolves as her guards.', 'Pilgrims say an old monk at the Star Altar, north of the Rift, tends the white stag. We take the fawn to her.'],
          progress: ['The Void Rift lies in the far south-east. Drive off the guards, open the cage, and bring the fawn north to the Star Altar.'],
          arrive: ['(At the Star Altar an old woman in white drops her broom and runs to meet the fawn.)'],
          deliver: ['(The fawn stumbles out of the cage on legs like twigs, and presses her nose into Fenn’s neck. Fenn looks very worried about this.)'],
          complete: ['Little Frostling! Oh, you foolish, brave child. You brought her back.', 'I am Eska, the Horn-warden. I have tended Skyhorn for forty winters. The night the star fell, the shadow in it sank into his antlers.', 'Then it took his fawn, so he would do anything it asked. Herd every wild thing on the heights to the Rift, to feed the dark.'], after: ['Frostling sleeps. Skyhorn does not.'] } },
      m12: { title: 'The Shard on the Crag', giver: 'corvin', auto: true, summary: 'Take the star shard from Frostfang Crag, north-east of Skyhold.', reward: { xp: 130 },
        text: { offer: ['Frostfang Crag is north-east of the city. Crag golems have woken all over it, drawn by the shard’s heat.', 'Take the shard before they crush it. And the den, child. See to the den.'],
          progress: ['Frostfang Crag lies north-east of Skyhold.'],
          complete: ['(The shard is warm as a stone left in the sun. Below the crag, from under a heap of broken rock, something whimpers.)', 'A wolf, pinned under the rubble. And golems stamping all round her.'], after: ['The crag is loud with golems.'] } },
      m15: { title: 'The White Stag at the Spire', giver: 'fox', auto: true, cine: { done: 'wren-skyhorn' }, summary: 'Take the last star shard from the Broken Spire.', reward: { xp: 150 },
        text: { offer: ['(Far to the north-east, on the Broken Spire, something white moves against the sky. Fenn whines.)', 'Skyhorn. And the last shard is up there with him. Let’s go and see him, Fenn. Carefully.'],
          progress: ['The Broken Spire lies in the far north-east of the Summit.'],
          complete: ['He stood right there, close enough to touch. His eyes were like Moonfang’s, the night the star fell. Fighting it.', 'Eska will know what to do. Back to the Star Altar.'], after: ['Three shards.'] } },
      m19: { title: 'Skyhorn', giver: 'wren-eska', summary: 'Free Skyhorn from the star’s shadow at the Star Cradle and lay the three shards in it.',
        text: { offer: ['The Star Cradle is at the top of the world, north-east of the Spire. Skyhorn waits for you there.', 'He charges, he calls down falling stars, and he blinks across the snow like moonlight. Keep moving.', 'Break the black light out of his antlers, then lay the three shards in the Cradle.'],
          progress: ['The Star Cradle is in the far north-east.'], complete: [], after: ['The star is home. And so is he.'] } },
      m20: { title: 'Frostling Goes Home', giver: 'corvin', who: FAWN, summary: 'Walk Frostling from Skyhold to the Eastern Gate, where Skyhorn waits by the black ice.',
        text: { offer: ['Eska brought the fawn down to Skyhold to rest, and Skyhorn has come down off the Cradle. He waits at the Eastern Gate, by the black ice.', 'Walk Frostling to him, child. The wraiths still want her. And, well… my brothers would like to watch.'],
          progress: ['Lead Frostling from Skyhold to the Eastern Gate. Keep the wraiths off her.'],
          arrive: ['(Frostling sees her father and bolts the last few steps. The great stag bends his head, and the fawn disappears under his chin.)'],
          complete: ['(Skyhorn looks at the black ice sealing the gate. Then he looks at Wren. Then he lowers his antlers.)'], after: [] } },
    },
    ember: {
      m1: { title: 'Pawprints in the Ash', summary: 'Follow Moonfang’s bloody pawprints to Emberwatch Outpost and find Captain Ashka.',
        text: { offer: ['(Past the broken ice the snow turns to ash. White pawprints run through it, and between them, spots of blood.)', 'She’s hurt, Fenn. There’s an outpost ahead. Hurry.'],
          progress: ['Take the road east through the gate to Emberwatch Outpost.'], complete: [], after: [],
          deliver: ['A girl and a wolf, out of the Summit? After what came through here last week, I nearly shot you both.', 'A great white wolf, bleeding, and behind her something moving under the sand, as long as the outpost wall. The Duneworm.', 'The imps have gone mad since. They’ll be at the gate again tonight.'] } },
      m2: { title: 'Sparks at Emberwatch', summary: 'Hold the gate of Emberwatch Outpost against three waves of imps.', reward: { xp: 100 },
        text: { offer: ['Ember imps hover out of reach and lob fire. They’ve hit us every night since the worm went by.', 'And here they come. Help us hold the outpost gate, and I’ll tell you everything I know about your wolf.'],
          progress: ['Stand by the outpost gate. Imps keep their distance, so close in fast.'],
          complete: ['The gate stands. And your wolf bit an imp. I’ve never seen an imp look so surprised.', 'The white wolf went north first, into the Obsidian Maze. The worm followed her in, and came out without her.'], after: ['Watch the sky for sparks. And the sand for ripples.'] } },
      m6: { title: 'The Worm’s Glass Skin', giver: 'guide', summary: 'Search the Obsidian Maze, north of the outpost, for Moonfang’s trail and the ember core.',
        text: { offer: ['The Obsidian Maze is north of here. The old folk say it isn’t rock at all: it’s the Duneworm’s shed skin, gone to glass in the heat.', 'An ember core glows in there, too. Bring back whatever you find.'],
          progress: ['The Obsidian Maze lies north of Emberwatch Outpost.'],
          complete: ['An ember core, from the forge itself! And white fur on the glass. She hid in the maze, where the worm couldn’t turn.', 'Kiln-mother Hessa in Kilnhollow has lived in these wastes eighty years. She’ll know what that worm wants.'], after: ['One core. The forge has three hearts.'] } },
      m3: { title: 'The Kiln-mother’s Guest', summary: 'Ask Kiln-mother Hessa in Kilnhollow about the white wolf and the worm.',
        text: { offer: ['Kilnhollow lies south-east of the outpost, where the glass-kilns never go out. Hessa will talk your ear off. Let her.'],
          progress: ['Kilnhollow is south-east of the outpost.'], complete: [], after: [],
          deliver: ['A white wolf? She lay by my kiln one night, all blood and ash. I gave her water. She let me. Wolves don’t, usually.', 'The Duneworm hunts her. Pyrrhus, the old keeper of the Dawn Forge, fed it embers until it grew too big to stop. When he fell, it went hungry.', 'It swallowed the forge’s three ember cores, and spits them out where its tunnels end. And now it wants your wolf. It likes things that shine.'] } },
      m4: { title: 'Salt Against the Worm', turnIn: 'fenwick', item: 'Salt crystal', summary: 'Gather salt crystals around Saltglass Farm, the one thing the Duneworm fears.',
        text: { offer: ['The worm hates salt. It burns its hide the way fire burns ours. That’s why it never comes near Saltglass Farm.', 'Gather five clean salt crystals round the farm, south-west of here, and pack them in your quiver. Show them to Fenwick, too. He’ll want to know why you’re digging up his pans.'],
          progress: ['Saltglass Farm lies south-west of Kilnhollow.'],
          complete: ['Salt for arrows? Take all you like, lass. The worm never comes past my salt pans.', 'But something small does. Every night something steals my salt, and I swear it rides that worm.'], after: ['Salt and fire, fire and salt.'] } },
      m14: { title: 'The Worm’s Tick-bird', giver: 'fenwick', summary: 'Catch the soot-sprite who rides the Duneworm, near Saltglass Farm.', reward: { xp: 150 },
        text: { offer: ['There! The sooty little thief! It rides that worm’s back like a tick-bird on a buffalo.', 'Catch it, and make it tell you where the worm sleeps. It’s fast, but it tires.'],
          progress: ['Cinderfinch hides near Saltglass Farm. Run it down: it has to stop for breath.'],
          deliver: ['Oof! Alright! Don’t let the wolf eat me! I only take the salt to rub on the worm’s sores!', 'It sleeps under the Dawn Forge, far to the north-east. Its tunnels come up in the Scorpion Burrows and the Old Foundry.', 'The screaming vents round the Burrows scare it off. But it’s hunting the white wolf. It never stops hunting her.'],
          complete: ['Salt for the worm’s sores? The little rascal was being kind. Hm. It can have a bag a week.', 'The Scorpion Burrows are east of here. Mind the ground: the scorpions swim through the sand.'], after: ['Cinderfinch visits on Sundays now. It brings me pebbles.'] } },
      m8: { title: 'Down the Worm’s Tunnel', giver: 'fox', auto: true, summary: 'Take the second ember core from the Scorpion Burrows.',
        text: { offer: ['The Scorpion Burrows are the ends of the worm’s tunnels. It spat the second core out somewhere down here.', 'The scorpions come up right under your feet, Fenn. When the sand bulges, move.'],
          progress: ['The Scorpion Burrows lie east of Saltglass Farm.'],
          complete: ['Two cores. Hot as coals, even through the salt.', '(Fenn has a scent. Not Moonfang: people, and smoke, far to the east.)'], after: ['Two of three.'] } },
      m7: { title: 'Burr in a Cage', giver: 'zara', turnIn: 'zara', captive: BURR, summary: 'Free Burr from the salt cage at the caravan camp and bring him to Zara.', reward: { xp: 160, hearts: 1 },
        text: { offer: ['Six of them, scorpions and imps, round the old salt cage. The fool tried to stop them taking the caravan’s water.', 'Get him out, and walk him back to my fire.'],
          progress: ['The cage is at the far end of the Salt Caravan Camp. Defeat the guards, open the cage, and bring Burr to Zara.'],
          arrive: ['(Burr sits down by Zara’s fire, very hard, and drinks an entire waterskin.)'],
          deliver: ['Wolf-girl! Of all the cages in all the wastes. Took your time.', 'I came east to find your white wolf. Thought I owed her one, after the snares. Got as far as the caravan’s water and no further.'],
          complete: ['Your trapper’s braver than he looks. Not much braver. Some.', 'He’s been leaving meat on the white wolf’s trail since the Summit. That’s how she lived this long.', 'If we’re going after that worm, I want to see it coming. Help me put up a watch-tower.'], after: ['Burr’s snoring by the fire. Loudly.'] } },
      m10: { title: 'Where Pyrrhus Fed the Worm', giver: 'zara', summary: 'Take the last ember core from the Old Foundry, then find Ember-seer Ilyana at Ashfall Watch.', reward: { xp: 150 },
        text: { offer: ['The Old Foundry is north of here. That’s where old Pyrrhus fed his worm, back when he still kept the forge.', 'Take the core, then climb on to Ashfall Watch. The Ember-seer lives up there, and she sees everything that moves in the wastes.'],
          progress: ['The Old Foundry is north of the caravan camp. Ashfall Watch is north-west of the foundry.'],
          complete: ['Three cores, all together. The forge will listen now.', 'The flames showed me your white wolf. She lies under the last green tree in the wastes, east of here, and she is fading.', 'And they showed me the moon going black. The Moon-Eater is coming, child. Umbra, in the shape your wolves fear most.'], after: ['The flames speak of you. And of her.'] } },
      m15: { title: 'Wake the Forge, Wake the Worm', giver: 'fox', summary: 'Gather brass gears at the Old Foundry, then rebuild the Great Bellows at the Dawn Forge.', reward: { xp: 220 },
        text: { offer: ['A forge must breathe, Ilyana said, and its Great Bellows were smashed when Pyrrhus fell. The Old Foundry is full of brass gears.', 'Four gears to the Dawn Forge, far to the north-east, and we rebuild the bellows. When the forge breathes, the worm under it wakes.', 'Good. I’m done with it hunting her.'],
          progress: ['Four brass gears from the Old Foundry, then build at the Dawn Forge.'], complete: [], after: [] } },
      m12: { title: 'The Duneworm', summary: 'Defeat the Duneworm, Devourer Under the Wastes, at the Dawn Forge.',
        text: { offer: ['(The Duneworm towers over the Dawn Forge, sand pouring off it like water. Moonfang’s hackles rise beside Fenn’s.)', 'It bursts up out of the ground, and it spits fire and lava. Never stand still. Salt arrows, Fenn. Every one.', 'And when it falls, the shadow that has been riding it will have nowhere left to hide.'],
          progress: ['The Dawn Forge is in the far north-east.'], complete: [], after: ['Be brave, Fenn.'] } },
      m13: { title: 'Umbra, the Moon-Eater', summary: 'Defeat Umbra, the Moon-Eater, and light the Dawn Forge.',
        text: { offer: ['(The worm crumbles into sand. Overhead the moon rises… and something black begins to eat it, bite by bite.)', '(From the Beacon Rise, the Old Bell and the Star Cradle, dark light streams east and gathers into one great shape.)', 'The Moon-Eater. The thing that took the moon out of our song. Moonfang, Fenn: sing. We finish it here.'],
          progress: ['Defeat Umbra at the Dawn Forge.'], complete: [], after: [] } },
    },
  },
  npcs: {
    meadow: [
      { id: 'wren-burr', name: 'Burr the Poacher', portrait: '🪤', at: 'camp', dx: -140, dy: 40, activity: 'idle', after: 'm9', until: 'woods:m1', look: BURR_LOOK,
        lines: ['I’m not a poacher. I’m a… freelance hunter of very large boars.', 'Garrick and I go way back. He still hasn’t forgiven me for the badger.'], barks: ['Truffles…', 'Not a poacher!'] },
    ],
    woods: [
      { id: 'wren-burr-w', name: 'Burr the Poacher', portrait: '🪤', at: 'lodge', dx: -150, dy: 50, activity: 'idle', until: 'summit:m1', look: BURR_LOOK,
        lines: ['My sister makes me chop wood whenever I do something stupid. There’s a lot of wood.', 'Ysolde says I have to say sorry to every wolf in the woods. One at a time.'], barks: ['Chop, chop.', 'Sorry, wolves.'] },
      { id: 'wren-briony', name: 'Scout Briony', portrait: '💂‍♀️', at: 'city', dx: -60, dy: 250, activity: 'patrol', after: 'm6', look: look('#6a7a8a', 'helm', { hatColor: '#8a8f9a', hair: '#b8743c' }),
        lines: ['The grey wolf brought me a rabbit. Raw. It’s the thought that counts.', 'I tell everyone at the watch: the wolves aren’t the dark. Most of them believe me now.'], barks: ['Eyes on the trees.', 'Hello, wolf!'] },
    ],
    summit: [
      { id: 'wren-eska', name: 'Horn-warden Eska', portrait: '👵', at: 'altar', dx: -120, dy: 80, activity: 'sweep', look: look('#e8e2d0', 'hood', { hatColor: '#c9c2e0', hair: '#e8e2d0' }),
        lines: ['Forty winters I have swept this altar for Skyhorn. He always comes back.', 'The old wardens said the shadow wears the shape of what you fear most. Mine wore his.'], barks: ['Peace, little one.', 'He will come back.'] },
    ],
    ember: [
      { id: 'wren-burr-e', name: 'Burr the Poacher', portrait: '🪤', at: 'caravan', dx: -160, dy: 50, activity: 'idle', after: 'm7', look: BURR_LOOK,
        lines: ['I’ve given up poaching. I feed wolves now. The pay is terrible.', 'Tell Garrick I did one good thing. He won’t believe you, but tell him anyway.'], barks: ['Meat for the white wolf…', 'No more cages. Ever.'] },
    ],
  },
  npcFor: {
    'meadow:guide': { barks: ['Over here, wolf-girl!', 'The Beacon needs lighting.'] },
    'woods:guide': { barks: ['Mind the fog, wolf-girl.', 'The Bell, child. The Bell.'] },
    // Wren's Summit is the stag's story: Orrin and Sable keep to themselves.
    'summit:orrin': { hidden: true },
    'summit:sable': { hidden: true },
    'summit:sable2': { hidden: true },
    'summit:orrin2': { hidden: true },
    'summit:sable3': { hidden: true },
  },
  script: {
    meadow: {
      sealed: 'Gorehide sleeps under a crust of gloom-stone on the Rise. Find the three sun-crystals first.',
      tip: 'Gorehide charges in a straight line: tumble aside, then loose arrows into his flank. Spend gold at the smith in Goldenhearth to grow stronger.',
      finale: { locked: ['The Beacon is cold, and deep under the Rise something enormous is snoring. Three sun-crystals are needed.'], guarded: ['Gorehide paws the earth in front of the Beacon. Bring down the Boar King to relight it.'],
        done: ['The crystals blaze in the Beacon, and gold light rolls across the meadow.', 'All over the valley, bristleboars stop, blink, and wander off to root for acorns as if nothing had happened.', 'Far to the east, over the dark trees of Whisperroot, a wolf howls. Fenn answers.'] },
      victory: { title: 'The Beacon shines again.', text: 'The Boar King is beaten, the wolf bounty is torn down, and the meadow’s beasts are free of the gloom. But the pack ran east into Whisperroot Woods, with a black wolf at its head.' },
      guide: { done: ['The meadow’s safe again. Even for wolves, I hear.'] },
    },
    woods: {
      sealed: 'Shadowmane lies curled round the Bell inside a knot of sleeping roots. Wake the three root runes first.',
      tip: 'Shadowmane howls up shadewolves: thin them out, then turn your arrows on the alpha. Tumble through its charges.',
      finale: { locked: ['Three root runes are needed to wake the Bell, and whatever sleeps beside it.'], guarded: ['Shadowmane stands over the Bell, the pack’s howl in its throat. Break it!'],
        done: ['You ring the Ancient Bell. Its voice rolls through every root, and the shadow that wore a wolf’s shape tears apart like mist.', 'All over Whisperroot, wolves shake themselves as if they had come up out of cold water.', 'But the biggest pawprints of all lead out of the woods, east, toward the Summit.'] },
      victory: { title: 'The Bell rings through the valley.', text: 'Shadowmane is broken and the pack is free. But Moonfang was never with them: she carried the worst of the shadow away on her own back, east into the snows of Starfall Summit.' },
      guide: { done: ['The woods breathe easy. And the wolves drink at the brook again.'] },
    },
    summit: {
      sealed: 'Skyhorn is wrapped in a shell of black starlight. Gather the three star shards first.',
      tip: 'Skyhorn blinks across the snow and calls down falling stars: dash out of the circles, and shoot while he lands.',
      finale: { locked: ['The Cradle is cold. Three star shards are needed.'], guarded: ['Skyhorn stands over the Cradle, black light twisting in his antlers. Free him!'],
        done: ['You lay the three shards in the Cradle. The star remembers its light and rises, whole, into the sky.', 'Skyhorn stands, shakes the snow off his back, and bows his great head to you, just once.', 'But a thread of black smoke has torn loose from the star and fled east, toward the Ember Wastes. Moonfang went that way too.'] },
      victory: { title: 'The star rises home.', text: 'Skyhorn is free, and the Summit’s wolves and goatherds share the heights. But the shadow fled east into the Ember Wastes, and so did Moonfang.' },
      guide: { done: ['The sky is whole. The heights are quiet. Even the wolves.'] },
    },
    ember: {
      sealed: 'The Duneworm lies coiled under the forge in a shell of cooling stone. Recover the three ember cores first.',
      tip: 'Watch the sand: a moving mound means something is coming up under you. Magma hulks crack the ground around them, so step out of the glowing circles.',
      finale: { locked: ['The Dawn Forge is cold. Three ember cores are needed to wake it.'], guarded: ['A shadow broods over the forge, and the moon above it is going dark. Defeat it!'],
        done: ['You set the three ember cores in the Dawn Forge. Its fire roars up, white and gold, and the moon comes out of the dark, round and silver.', 'Moonfang sings to it. Across the whole valley, from the Summit to the meadow, the wolves sing back.', 'Every land, every light, every wolf. The pack is home.'] },
      victory: { title: 'The moon sings again.', text: 'Umbra is gone for good. Moonfang is free, the pack is home, and the valley has learned what Wren always knew: the wolves were never the dark.' },
      guide: { done: ['The wastes are cooling. And I haven’t seen a ripple in the sand since.'] },
    },
  },
  cines: {
    // ─────────────── Chapter I
    'wren-shadowmane': [
      { at: 'meadow:camp', dx: 380, dy: -260, night: .55, text: 'On the ridge above the camp stands a wolf blacker than the night around it. Its eyes burn violet.', fx: [{ kind: 'shadow' }], dur: 4.4 },
      { text: 'It lifts its head and howls, and every wolf of the pack turns and runs to it.', fx: [{ kind: 'howl' }, { kind: 'wolves', n: 4, delay: .6 }], dur: 4.2 },
      { speaker: 'Hunter Garrick', portrait: '🏹', text: '“That one hasn’t got a whiff of pack on it. Whatever it is, it’s leading them east.”', dur: 4.2 },
      { at: 'hero', night: 0, text: 'Thistle stays by the fire. Fenn does not stop growling until dawn.', dur: 3.8 }],
    'beacon-lit@wren': [
      { at: 'meadow:rise', dy: -90, text: 'The Beacon roars back to life, and gold light spills across the meadow.', fx: [{ kind: 'light', dy: -90 }], dur: 4 },
      { at: 'meadow:rise', dx: 160, dy: 40, text: 'Where Gorehide fell lies only a very old boar, blinking in the light. He snorts once, and trots off into the long grass.', fx: [{ kind: 'smoke' }], dur: 4.6 },
      { at: 'obj:meadow:barrier', cut: true, text: 'The light reaches all the way to the Eastern Gate, where the Gloomwater Bridge lies broken in the river.', fx: [{ kind: 'collapse' }], dur: 4.6 },
      { at: 'npc:meadow:holt', text: 'Bridgewright Holt is already there, scratching his head at the wreck.', dur: 3.6 }],
    'chapter-meadow@wren': [
      { at: 'obj:meadow:barrier', text: 'Plank by plank, the Gloomwater Bridge stands again.', fx: [{ kind: 'build' }], dur: 3.6 },
      { at: 'obj:meadow:barrier', dx: 900, text: 'On the far bank, pawprints lead in under the dark trees of Whisperroot Woods.', dur: 3.8 },
      { at: 'woods:bell', cut: true, dy: -60, text: 'Deep in the woods, beside the silent Bell, something black lies curled like a sleeping wolf.', fx: [{ kind: 'shadow', dy: -60 }, { kind: 'howl', delay: 1 }], dur: 4.6 },
      { title: 'Chapter II', sub: 'The Bell Beneath the Roots', dur: 3.4 }],
    // ─────────────── Chapter II
    'wren-bellhollow': [
      { at: '$ward', dy: -40, night: .5, text: 'Dusk in Bellhollow. Out in the trees, eyes begin to glow.', fx: [{ kind: 'wolves', n: 4, dx: 380, dy: 120 }], dur: 4 },
      { speaker: 'Nana Bristle', portrait: '👵', text: '“Not in my village, you don’t! Shoo! SHOO!”', dur: 3.2 }],
    'glade-memory@wren': [
      { at: 'woods:glade', night: .4, text: 'The last lantern catches. The glade fills with silver light…', fx: [{ kind: 'memory' }], dur: 3.6 },
      { text: '…and remembers a winter night long ago. Snow on the moss, and a basket with a crying baby in it, left all alone.', fx: [{ kind: 'frost', delay: .4 }], dur: 5 },
      { text: 'A great white wolf pads out of the trees, sniffs the basket, and curls herself round it until the crying stops.', actors: [{ id: 'mmoon', beast: true, spirit: true, dx: 30, dy: 50, face: -1 }], dur: 5.2 },
      { text: 'At dawn a young hunter finds them: Garrick, before his beard went grey. The white wolf does not run.', actors: [{ id: 'mgarrick', name: 'Young Garrick', look: look('#556b3a', 'hood', { hatColor: '#3f4f2a' }), dx: -160, dy: 60, walk: { dx: 100, dy: 0 } }], dur: 5 },
      { at: 'hero', night: 0, text: 'The light fades. Wren stands very still, and Fenn leans against her legs.', dur: 3.6 }],
    'bell-rung@wren': [
      { at: 'woods:bell', dy: -80, text: 'The Ancient Bell rings out, and its voice rolls through every root in Whisperroot.', fx: [{ kind: 'light', dy: -80 }], dur: 4 },
      { at: 'woods:bell', dx: -300, dy: 120, text: 'All through the woods, shadewolves stop in their tracks. The black drains from their eyes like ink from wet paper.', fx: [{ kind: 'wolves', n: 4 }, { kind: 'light', delay: .8 }], dur: 5 },
      { text: 'Wren’s pack, free and blinking, lift their heads and sing.', fx: [{ kind: 'howl' }], dur: 3.6 },
      { at: 'hero', text: 'But one voice is missing. Moonfang is not among them. Only her tracks, running east toward the Summit.', dur: 4.4 }],
    'chapter-woods@wren': [
      { at: 'obj:woods:barrier', text: 'The Bell-lanterns blaze, and the wall of thorns withers into dust.', fx: [{ kind: 'light' }, { kind: 'wither', delay: .8 }], dur: 4 },
      { at: 'obj:woods:barrier', dx: 300, text: 'In the frost beyond the gate: big white pawprints, climbing toward the Summit.', dur: 3.8 },
      { at: 'summit:cradle', cut: true, dy: -80, text: 'High on Starfall Summit, a great white stag stands over the fallen star. His antlers are full of black light.', fx: [{ kind: 'shadow', dy: -80 }], dur: 5 },
      { title: 'Chapter III', sub: 'The Hollow Star', dur: 3.4 }],
    // ─────────────── Chapter III
    'wren-skyhorn': [
      { at: 'summit:spire', dy: -40, text: 'On the Broken Spire stands a white stag as tall as a house. Starlight hangs in his antlers like frost.', fx: [{ kind: 'light', dy: -80 }], dur: 4.6 },
      { text: 'But in the heart of the antlers, black light twists and pulls, like a hook in a fish.', fx: [{ kind: 'shadow', dy: -80 }], dur: 4.2 },
      { text: 'Skyhorn looks at Wren for one long heartbeat. Then he shakes his great head, and bolts for the Cradle.', fx: [{ kind: 'smoke', dy: -40, to: { dx: 1000, dy: 600 } }], dur: 4.4 },
      { at: 'hero', text: 'Fenn does not growl. He only whines, the way he did the night the pack went dark.', dur: 3.8 }],
    'star-rises@wren': [
      { at: 'summit:cradle', dy: -100, text: 'The shards blaze in the Cradle, and the fallen star rises into the sky, whole again.', fx: [{ kind: 'light', dy: -100 }], dur: 4.2 },
      { at: 'summit:cradle', dx: 120, dy: 40, text: 'In the snow lies Skyhorn, pure white again, breathing slow. The black light is gone from his antlers.', dur: 4.4 },
      { text: 'But it has not gone far. A thread of black smoke tears loose and streaks east, over the last ridge…', fx: [{ kind: 'smoke', dy: -60, to: { dx: 1400, dy: 900 } }], dur: 4.2 },
      { at: 'obj:summit:barrier', cut: true, text: '…and black ice creeps over the Eastern Gate behind it. Beyond the ice, one set of white pawprints goes on into the Ember Wastes.', fx: [{ kind: 'quake' }, { kind: 'shadow', delay: .3 }], dur: 5 }],
    'chapter-summit@wren': [
      { at: 'obj:summit:barrier', text: 'Skyhorn lowers his great antlers to the black ice. Starlight gathers in them, bright as the star itself.', fx: [{ kind: 'light', delay: .4 }], dur: 4.6 },
      { text: 'Fenn throws back his head and howls, and from the terraces and the crags every wolf on the Summit howls with him.', fx: [{ kind: 'howl', delay: .3 }, { kind: 'wolves', n: 3, dx: -300, dy: 120, delay: .8 }], dur: 4.8 },
      { text: 'The black ice cracks from end to end, and shatters.', fx: [{ kind: 'shatter' }], dur: 3.4 },
      { at: 'ember:kiln', dx: 300, cut: true, text: 'Far beyond, in the Ember Wastes, a great white wolf limps on through the ash. Behind her, the sand ripples.', actors: [{ id: 'cmoon', beast: true, spirit: true, dx: -60, dy: 40, walk: { dx: 160, dy: -20 } }], fx: [{ kind: 'quake', delay: 1.2 }], dur: 5 },
      { title: 'Chapter IV', sub: 'The Dawn Forge', dur: 3.4 }],
    // ─────────────── Chapter IV
    'wren-moonfang': [
      { at: 'ember:green', text: 'Under the last green tree lies a great white wolf. The shadow is sliding off her fur like old snow.', actors: [{ id: 'moonfang', beast: true, spirit: true, dx: 50, dy: 40, face: -1 }], fx: [{ kind: 'memory' }], dur: 4.8 },
      { text: 'She carried it for them. When the shadow took the pack, Moonfang pulled the worst of it into herself and ran, so it would chase her and not her pups.', fx: [{ kind: 'shadow', dx: 50, dy: 20 }], dur: 5.4 },
      { text: 'Fenn creeps close. She lifts her head and licks his ear once, the way she did when he was small.', dur: 4.6 },
      { text: 'Then she looks at Wren the way she once looked at a crying baby in the snow.', dur: 4 }],
    'wren-spring': [
      { at: 'ember:spring', dy: -40, text: 'Moonfang stands in the Phoenix Spring, white from nose to tail, and throws back her head.', actors: [{ id: 'smoon', beast: true, spirit: true, dx: 20, dy: 30, face: -1 }], fx: [{ kind: 'light', dy: -40 }], dur: 4.2 },
      { text: 'She howls, and far away to the west, across three lands, her pack howls back.', fx: [{ kind: 'howl' }], dur: 4.4 },
      { at: 'ember:forge', cut: true, dy: -60, night: .5, text: 'At the Dawn Forge, the sand heaves. Something enormous has heard her too.', fx: [{ kind: 'quake' }, { kind: 'fire', n: 2, t: 30, delay: .4 }], dur: 4.4 },
      { at: 'hero', night: 0, speaker: 'Wren', portrait: '🏹', text: '“It’s coming for her? Then it comes through me.”', dur: 3.8 }],
    'wren-spring-siege': [
      { at: '$ward', dy: -40, night: .45, text: 'The sand round the Phoenix Spring begins to boil. Scorpions and imps pour out of it, driven ahead of the worm.', fx: [{ kind: 'imps', n: 4, dx: 380, dy: -120 }, { kind: 'quake', delay: .5 }], dur: 4.4 },
      { speaker: 'Wren', portrait: '🏹', text: '“Stay in the water, Moonfang. Fenn, with me!”', dur: 3.2 }],
    'pyrrhus-wakes@wren': [
      { at: 'ember:forge', dy: -60, text: 'The Great Bellows heave. For the first time in years, the Dawn Forge breathes.', fx: [{ kind: 'build' }], dur: 3.8 },
      { text: 'The sand round the anvil sinks, and swirls, and opens like a mouth…', fx: [{ kind: 'quake' }, { kind: 'smoke', delay: .4 }], dur: 3.8 },
      { text: '…and the Duneworm rises out of the ground: Pyrrhus’s last pet, fat on embers, its hide stuck full of Zara’s arrows.', fx: [{ kind: 'fire', n: 3, t: 40, delay: .3 }, { kind: 'shadow', delay: .6 }], dur: 5 }],
    'chapter-ember@wren': [
      { at: 'ember:forge', dy: -60, text: 'The Dawn Forge burns white and gold, and the moon slips free of the dark, whole and silver.', fx: [{ kind: 'light', dy: -60 }], dur: 4.6 },
      { at: 'ember:forge', dx: 120, dy: 60, text: 'Moonfang lifts her head and sings to it, and Fenn sings with her.', actors: [{ id: 'emoon', beast: true, spirit: true, face: -1 }], fx: [{ kind: 'howl' }], dur: 4.4 },
      { at: 'woods:bellhollow', cut: true, text: 'In Bellhollow, Snowpaw tumbles out of Nana Bristle’s door to answer. In Lanternmarket, Old Grizzle sits up by the fountain.', fx: [{ kind: 'howl' }], dur: 4.8 },
      { at: 'meadow:camp', cut: true, night: .4, text: 'And at the Hunter’s Camp, where it all began, Garrick puts down his pipe and listens to the whole valley howl.', fx: [{ kind: 'howl' }, { kind: 'light', delay: .6 }], dur: 4.8 },
      { at: 'meadow:rise', cut: true, dy: -80, night: 0, text: 'Every light is burning. Every wolf is home. And the people of the valley leave their doors open at night.', fx: [{ kind: 'light', dy: -80 }], dur: 4.6 },
      { title: 'The pack is home', sub: 'Every light is shining', dur: 4 }],
  },
};
